src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ANG_PCI_compliance_expiry_date__c</fullName>
        <description>PCI compliance expiry date</description>
        <label>PCI compliance expiry date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_PCI_compliant__c</fullName>
        <description>Determines if an agency is PCI Compliant</description>
        <label>Is PCI compliant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Nil CC</fullName>
                </value>
                <value>
                    <fullName>Corporate Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>Map the objects AGT from AIMS. This is a value equal to category.</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>China &amp; North Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East &amp; North Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Russia &amp; CIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_to_External_System__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent to External System</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IATA_Agency</fullName>
        <active>true</active>
        <description>The new record type for ALL Agencies with NEW data model - Use this for all Agencies</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Available_Services__c</fullName>
        <description>This field contains the names of the portal services available to the current contact. This should be updated through a trigger</description>
        <label>Available Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AIRS / CAIRS Online Bulletin</fullName>
                </value>
                <value>
                    <fullName>ASD</fullName>
                </value>
                <value>
                    <fullName>Biller Direct</fullName>
                </value>
                <value>
                    <fullName>BSP / CASS Change of Bank details</fullName>
                </value>
                <value>
                    <fullName>BSP / CASS Change Request</fullName>
                </value>
                <value>
                    <fullName>BSPLink</fullName>
                </value>
                <value>
                    <fullName>CassLink</fullName>
                </value>
                <value>
                    <fullName>CASSLink Export</fullName>
                </value>
                <value>
                    <fullName>CASSLink Import</fullName>
                </value>
                <value>
                    <fullName>CASSLink Route Analyzer</fullName>
                </value>
                <value>
                    <fullName>CNS CASSLink</fullName>
                </value>
                <value>
                    <fullName>CNS Endorsement &amp; Changes</fullName>
                </value>
                <value>
                    <fullName>Currency Center</fullName>
                </value>
                <value>
                    <fullName>GSA Appointments</fullName>
                </value>
                <value>
                    <fullName>IATA Accreditation &amp; Changes</fullName>
                </value>
                <value>
                    <fullName>IATA EasyPay</fullName>
                </value>
                <value>
                    <fullName>ICCS</fullName>
                </value>
                <value>
                    <fullName>ICE – IATA Customer E-Statement</fullName>
                </value>
                <value>
                    <fullName>IFAP</fullName>
                </value>
                <value>
                    <fullName>IFG Production</fullName>
                </value>
                <value>
                    <fullName>IFG Sandbox</fullName>
                </value>
                <value>
                    <fullName>Join BSP / CASS</fullName>
                </value>
                <value>
                    <fullName>Management Information Report</fullName>
                </value>
                <value>
                    <fullName>MITA Agreements</fullName>
                </value>
                <value>
                    <fullName>MSO Management</fullName>
                </value>
                <value>
                    <fullName>Payment Link</fullName>
                </value>
                <value>
                    <fullName>Paypal</fullName>
                </value>
                <value>
                    <fullName>Resource Center</fullName>
                </value>
                <value>
                    <fullName>Risk Profile and RHC</fullName>
                </value>
                <value>
                    <fullName>Simplified Interline Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BSP_CASS_Payment_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BSP/CASS Payment contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Portal_Status__c</fullName>
        <label>User Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved User</fullName>
                </value>
                <value>
                    <fullName>Approved Admin</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Regional Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Africa &amp; Middle East</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Asia &amp; Pacific</fullName>
                </value>
                <value>
                    <fullName>China &amp; North Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Mgmt_Report_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mgmt Report Team</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Update_Contact_Available_Services_Test.cls
@isTest
private class Update_Contact_Available_Services_Test {
	
	@testSetup static void setup() {
		DateTime dt = system.now()+90;
		Date d = date.newinstance(dt.year(), dt.month(), dt.day());

		List<IATA_ISO_Country__c> countrylist = new List<IATA_ISO_Country__c>();
		IATA_ISO_Country__c isoc1 = new IATA_ISO_Country__c(Name = 'Test1', ISO_Code__c = 'TS', Region__c = 'Americas');
		countrylist.add(isoc1);
		insert countrylist;
		
		List<Account> agencylist = new List<Account>();
		Id agencyRT = RecordTypeSingleton.getInstance().getRecordTypeID('Account','IATA_Agency');
		Account a1 = new Account(Name='Test1 Agency', RecordtypeId=agencyRT,
			IATA_ISO_Country__c = isoc1.id, Sent_to_external_system__c = true, 
			IATACode__c = '12345678', Location_Class__c = 'P', Status__c = AMS_Utils.ACC_S9_APPROVED, 
			Is_PCI_compliant__c = 'No', ANG_PCI_compliance_expiry_date__c = d);
		agencylist.add(a1);
		insert agencylist;

		Contact co1 = new Contact(AccountId = a1.id, Firstname = 'teste1', Lastname='test1', Phone = '911111111', MobilePhone = '911111111', Email = 'test@test.com', BSP_CASS_Payment_contact__c = true, User_Portal_Status__c = 'Approved Admin', Available_Services__c = null);
		Contact co2 = new Contact(AccountId = a1.id, Firstname = 'teste2', Lastname='test2', Phone = '911111112', MobilePhone = '911111112', Email = 'test2@test.com', BSP_CASS_Payment_contact__c = false, User_Portal_Status__c = 'Approved Admin',Available_Services__c = null);
		Contact co3 = new Contact(AccountId = a1.id, Firstname = 'teste3', Lastname='test3', Phone = '911111113', MobilePhone = '911111113', Email = 'test3@test.com', BSP_CASS_Payment_contact__c = false, User_Portal_Status__c = 'Approved', Available_Services__c = null);
		
		List<Contact> cos = new List<Contact>{co1,co2,co3}; 
		insert cos;

		Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal'];

        User testeUser1 = new User (
                Alias = 'newUser1',
                Email='newuser1@testorg.com',
                EmailEncodingKey='UTF-8',
                LastName='Testing1',
                LanguageLocaleKey='en_US',
                ContactId = co1.id,
                LocaleSidKey='en_US',
                ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles',
                UserName='newuser1@testorg.com',
                Mgmt_Report_Team__c = true
            );

        User testeUser2 = new User (
                Alias = 'newUser2',
                Email='newuser2@testorg.com',
                EmailEncodingKey='UTF-8',
                LastName='Testing1',
                LanguageLocaleKey='en_US',
                ContactId = co2.id,
                LocaleSidKey='en_US',
                ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles',
                UserName='newuser2@testorg.com',
                Mgmt_Report_Team__c = true
            );

        User testeUser3 = new User (
                Alias = 'newUser3',
                Email='newuser3@testorg.com',
                EmailEncodingKey='UTF-8',
                LastName='Testing1',
                LanguageLocaleKey='en_US',
                ContactId = co3.id,
                LocaleSidKey='en_US',
                ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles',
                UserName='newuser3@testorg.com',
                Mgmt_Report_Team__c = true
            );

        List<User> us = new List<User>{testeUser1,testeUser2,testeUser3}; 
		insert us;
	}

	@isTest static void test_method_one() {
		Test.startTest();
		Update_Contact_Available_Services_Batch batch = new Update_Contact_Available_Services_Batch();
        Database.executeBatch(batch, 10);
		Test.stopTest();
	}
	
	
	
}