src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EF_Allow_Billing_Agreements__c</fullName>
        <description>Field allowed to be updated only by E&amp;F Business Development Manager. This field controls whether E&amp;F Billing Agreements are allowed (occasionally with management&apos;s approval) for the Account or not.</description>
        <inlineHelpText>Controls whether the creation of Billing Agreements on this Account is allowed or not. With &quot;Allowed with Approval&quot; selection, the E&amp;F management must approval creation of Billing Agreements before they are activated.</inlineHelpText>
        <label>E&amp;F Allow Billing Agreements</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EF_Allow_Billing_Agreements</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>EF_Allow_Billing_Agreements__c</fullName>
        <label>E&amp;F Allow Billing Agreements</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EF_Allow_Billing_Agreements</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EF_Approval__c.object
<CustomObject>
    <description>Object used to temporarily store values of records being modified on Contract or E&amp;F Airline Billing Agreement, and that need an approval.</description>
    <fields>
        <fullName>Airline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airline</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>EF_Approval_Temp_Storages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>EF_Approval_Temp_Storages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EF_Billing_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airline Billing Agreement</label>
        <referenceTo>EF_Billing_Agreement__c</referenceTo>
        <relationshipName>EF_Approval_Temp_Storages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <globalPicklist>EF_Payment_Method</globalPicklist>
        <label>Payment Method</label>
        <type>Picklist</type>
    </fields>
    <label>E&amp;F Approval Storage</label>
    <nameField>
        <displayFormat>EFA-{0000000}</displayFormat>
        <label>E&amp;F Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E&amp;F Approval Storages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EF_Billing_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Airline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airline</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>EF_Relationships_Airline</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>EF_Relationships_Client</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>EF_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EF_Location_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>E&amp;F Location ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EF_Related_Records__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EF_Related_Records__c</referenceTo>
        <relationshipName>EF_LocationRelationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <globalPicklist>EF_Payment_Method</globalPicklist>
        <label>Payment Method</label>
        <type>Picklist</type>
    </fields>
    <label>E&amp;F Airline Billing Agreement</label>
    <nameField>
        <displayFormat>E&amp;F ABA-{0000}{MM}{YY}</displayFormat>
        <label>E&amp;F Airline Billing Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E&amp;F Airline Billing Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EF_Related_Records__c.object
<CustomObject>
    <description>E&amp;F CRM Project needs to store simple information, therefore this &quot;Dummy&quot; object is created to store that information under different record types to fulfill different needs.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Relationship</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Related Contacts or Cases</relationshipLabel>
        <relationshipName>EF_Related_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EF_Billing_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airline Billing Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Relationship</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EF_Billing_Agreement__c</referenceTo>
        <relationshipLabel>Related Contacts or Cases</relationshipLabel>
        <relationshipName>EF_Related_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>E&amp;F Related Records</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E&amp;F Related Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/EF_Allow_Billing_Agreements.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Allowed</fullName>
    </customValue>
    <customValue>
        <fullName>Allowed with Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Not Allowed</fullName>
    </customValue>
    <masterLabel>E&amp;F Allow Billing Agreements</masterLabel>
</GlobalValueSet>

src/classes/EF_BaContractApprovalHelperTest.cls
@isTest
private class EF_BaContractApprovalHelperTest
{
	@isTest static void testBillingAgreementCreation_StartsApprovalProcess()
	{
		EF_TestDataFactory.createBaseData();
		Contract contract = [select Id, AccountId, Account.Name from Contract where Account.Name = 'Test Account Client'];
		Account customer = [select Id, Name, EF_Allow_Billing_Agreements__c from Account where Name = 'Test Account customer'];
		Account client = [select Id, Name, EF_Allow_Billing_Agreements__c from Account where Name = 'Test Account client'];
		
		customer.EF_Allow_Billing_Agreements__c = 'Allowed with Approval';
		client.EF_Allow_Billing_Agreements__c = 'Allowed with Approval';
		update customer;
		update client;

		List<ProcessInstanceWorkItem> pwiList = [SELECT Id, ActorId, ProcessInstance.TargetObjectId	FROM ProcessInstanceWorkitem];
		System.assertEquals(0, pwiList.size());

		// Create a billing agreement 
		EF_Billing_Agreement__c ba = new EF_Billing_Agreement__c();
		ba.Client__c = client.Id;
		ba.Airline__c = customer.Id;
		ba.Contract__c = contract.Id;
		ba.EF_Location_ID__c =  [select Id, Name from EF_Related_Records__c where Name='Main' limit 1].Id;
		insert ba;

		pwiList = [SELECT Id, ActorId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem];
		System.assertEquals(1, pwiList.size());
		System.assertEquals(ba.Id, pwiList.get(0).ProcessInstance.TargetObjectId);
	}

	@isTest static void testBillingAgreementUpdateKeyField_StartsApprovalProcessCreateEFapprovalRecord()
	{
		EF_TestDataFactory.createBaseData();
		Contract contract = [select Id, AccountId, Account.Name from Contract where Account.Name = 'Test Account Client'];
		Account customer = [select Id, Name, EF_Allow_Billing_Agreements__c from Account where Name = 'Test Account customer'];
		Account client = [select Id, Name, EF_Allow_Billing_Agreements__c from Account where Name = 'Test Account client'];
		
		List<ProcessInstanceWorkItem> pwiList = [SELECT Id, ActorId, ProcessInstance.TargetObjectId	FROM ProcessInstanceWorkitem];
		System.assertEquals(0, pwiList.size());
		List<EF_Approval__c> approvalList = [select id from EF_Approval__c];
		System.assertEquals(0, approvalList.size());

		// Create a billing agreement 
		EF_Billing_Agreement__c ba = new EF_Billing_Agreement__c();
		ba.Client__c = client.Id;
		ba.Airline__c = customer.Id;
		ba.Contract__c = contract.Id;
		ba.Payment_Method__c = 'Credit Card';
		ba.EF_Location_ID__c =  [select Id, Name from EF_Related_Records__c where Name='Main' limit 1].Id;
		insert ba;

		customer.EF_Allow_Billing_Agreements__c = 'Allowed with Approval';
		client.EF_Allow_Billing_Agreements__c = 'Allowed with Approval';
		update customer;
		update client;

		ba.Payment_Method__c = 'Bank Transfer';
		update ba;

		pwiList = [SELECT Id, ActorId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem];
		System.assertEquals(1, pwiList.size());
		System.assertEquals(ba.Id, pwiList.get(0).ProcessInstance.TargetObjectId);
		approvalList = [SELECT Id, EF_Billing_Agreement__c FROM EF_Approval__c];
		System.assertEquals(1, approvalList.size());
		System.assertEquals(ba.Id, approvalList.get(0).EF_Billing_Agreement__c);
	}

	@isTest static void testBillingAgreementChangeApproval_updateBaDeleteRecord()
	{
		EF_TestDataFactory.createBaseData();
		Contract contract = [select Id, AccountId, Account.Name from Contract where Account.Name = 'Test Account Client'];
		Account customer = [select Id, Name, EF_Allow_Billing_Agreements__c from Account where Name = 'Test Account customer'];
		Account client = [select Id, Name, EF_Allow_Billing_Agreements__c from Account where Name = 'Test Account client'];
		
		List<ProcessInstanceWorkItem> pwiList = [SELECT Id, ActorId, ProcessInstance.TargetObjectId	FROM ProcessInstanceWorkitem];
		System.assertEquals(0, pwiList.size());
		List<EF_Approval__c> approvalList = [select id from EF_Approval__c];
		System.assertEquals(0, approvalList.size());

		// Create a billing agreement 
		EF_Billing_Agreement__c ba = new EF_Billing_Agreement__c();
		ba.Client__c = client.Id;
		ba.Airline__c = customer.Id;
		ba.Contract__c = contract.Id;
		ba.Payment_Method__c = 'Credit Card';
		ba.EF_Location_ID__c =  [select Id, Name from EF_Related_Records__c where Name='Main' limit 1].Id;
		insert ba;

		customer.EF_Allow_Billing_Agreements__c = 'Allowed with Approval';
		client.EF_Allow_Billing_Agreements__c = 'Allowed with Approval';
		update customer;
		update client;

		ba.Payment_Method__c = 'Bank Transfer';
		update ba;
		List<EF_Billing_Agreement__c> baList = [select id, Payment_Method__c from EF_Billing_Agreement__c];
		System.assertEquals('Credit Card', baList.get(0).Payment_Method__c);

		Test.startTest();
			pwiList = [SELECT Id, ActorId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem];
			System.assertEquals(1, pwiList.size());
			System.assertEquals(ba.Id, pwiList.get(0).ProcessInstance.TargetObjectId);

			Approval.ProcessWorkitemRequest pwir = new Approval.ProcessWorkitemRequest();
			pwir.setAction('Approve');
			pwir.setWorkItemId(pwiList.get(0).Id);
			Approval.process(pwir);

			approvalList = [SELECT Id, EF_Billing_Agreement__c FROM EF_Approval__c];
			System.assertEquals(0, approvalList.size());
			baList = [select id, Payment_Method__c from EF_Billing_Agreement__c];
			System.assertEquals('Bank Transfer', baList.get(0).Payment_Method__c);
			

		Test.stopTest();		
	}

	@isTest static void testBillingAgreementChangeRejection_rollbackBA()
	{
		EF_TestDataFactory.createBaseData();
		Contract contract = [select Id, AccountId, Account.Name from Contract where Account.Name = 'Test Account Client'];
		Account customer = [select Id, Name, EF_Allow_Billing_Agreements__c from Account where Name = 'Test Account customer'];
		Account client = [select Id, Name, EF_Allow_Billing_Agreements__c from Account where Name = 'Test Account client'];
		
		List<ProcessInstanceWorkItem> pwiList = [SELECT Id, ActorId, ProcessInstance.TargetObjectId	FROM ProcessInstanceWorkitem];
		System.assertEquals(0, pwiList.size());
		List<EF_Approval__c> approvalList = [select id from EF_Approval__c];
		System.assertEquals(0, approvalList.size());

		// Create a billing agreement 
		EF_Billing_Agreement__c ba = new EF_Billing_Agreement__c();
		ba.Client__c = client.Id;
		ba.Airline__c = customer.Id;
		ba.Contract__c = contract.Id;
		ba.Payment_Method__c = 'Credit Card';
		ba.EF_Location_ID__c =  [select Id, Name from EF_Related_Records__c where Name='Main' limit 1].Id;
		insert ba;

		customer.EF_Allow_Billing_Agreements__c = 'Allowed with Approval';
		client.EF_Allow_Billing_Agreements__c = 'Allowed with Approval';
		update customer;
		update client;

		ba.Payment_Method__c = 'Bank Transfer';
		update ba;
		List<EF_Billing_Agreement__c> baList = [select id, Payment_Method__c from EF_Billing_Agreement__c];
		System.assertEquals('Credit Card', baList.get(0).Payment_Method__c);

		Test.startTest();
			pwiList = [SELECT Id, ActorId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem];
			System.assertEquals(1, pwiList.size());
			System.assertEquals(ba.Id, pwiList.get(0).ProcessInstance.TargetObjectId);

			Approval.ProcessWorkitemRequest pwir = new Approval.ProcessWorkitemRequest();
			pwir.setAction('Reject');
			pwir.setWorkItemId(pwiList.get(0).Id);
			Approval.process(pwir);

			approvalList = [SELECT Id, EF_Billing_Agreement__c FROM EF_Approval__c];
			System.assertEquals(0, approvalList.size());
			baList = [select id, Payment_Method__c from EF_Billing_Agreement__c];
			System.assertEquals('Credit Card', baList.get(0).Payment_Method__c);
			

		Test.stopTest();		
	}
}