src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Top Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BSP_CASS_Payment_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BSP/CASS Payment contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Assessment_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tell if the contact is define as Financial Assessment Contact.
IFAP Application.</description>
        <label>Financial Assessment Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Portal_Status__c</fullName>
        <label>User Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved User</fullName>
                </value>
                <value>
                    <fullName>Approved Admin</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Regional Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AMS_GetAccountContact.cls
global class AMS_GetAccountContact {
	
	@InvocableMethod(label = 'Get Contacts')
	public static List<Contact> getContactId(List<Id> accountIds) {
		Id accountIdBR = accountIds[0];
		List<Contact> contactsBR = getContacts(accountIdBR);

		Map<String, List<Contact>> mapContacts = new Map<String, List<Contact>>();
		List<Contact> appLst = new List<Contact>();
		List<Contact> finLst = new List<Contact>();
		List<Contact> bspLst = new List<Contact>();
		mapContacts.put('Approved Admin', appLst);
		mapContacts.put('Financial contact', finLst);
		mapContacts.put('BSP Cass contact', bspLst);
		Boolean needsHOContacts = populateMapContacts(contactsBR, mapContacts);

		if(needsHOContacts) {
			Account accountBR = [SELECT Id, Top_Parent__c, Location_Type__c FROM Account WHERE Id = :accountIdBR];
			if(accountBR.Location_Type__c != 'HO' && accountBR.Location_Type__c != 'AO') {
				List<Contact> contactsHO = getContacts(accountBR.Top_Parent__c);
				populateMapContacts(contactsHO, mapContacts);
			}
		}
		
		if(!appLst.isEmpty()) {
			return new List<Contact> {new Contact(Id= appLst[0].Id)};
		} else if(!finLst.isEmpty()) {
			return new List<Contact> {new Contact(Id= finLst[0].Id)};
		} else if(!bspLst.isEmpty()) {
			return new List<Contact> {new Contact(Id= bspLst[0].Id)};
		} else {
			return null;
		}
	}

	private static List<Contact> getContacts(Id accountId) {
		return [SELECT Id, Email, AccountId, Preferred_Language__c, User_Portal_Status__c, BSP_CASS_Payment_contact__c, Financial_Assessment_Contact__c
			  	FROM Contact
			  	WHERE AccountId = :accountId AND IsEmailBounced = false AND 
			  	(BSP_CASS_Payment_contact__c = true OR Financial_Assessment_Contact__c = true OR User_Portal_Status__c = 'Approved Admin')];
	}

	//Returns true if all the map lists are empty
	private static Boolean populateMapContacts(List<Contact> contacts, Map<String, List<Contact>> mapContacts) {
		List<Contact> appLst = mapContacts.get('Approved Admin');
		List<Contact> finLst = mapContacts.get('Financial contact');
		List<Contact> bspLst = mapContacts.get('BSP Cass contact');
		for(Contact c : contacts) {
			if(c.User_Portal_Status__c == 'Approved Admin') {
				appLst.add(c);
			}

			if(c.Financial_Assessment_Contact__c) {
				finLst.add(c);
			}

			if(c.BSP_CASS_Payment_contact__c) {
				bspLst.add(c);
			}
		}
		return appLst.isEmpty() && finLst.isEmpty() && bspLst.isEmpty();
	}

}