src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Type__c</fullName>
        <inlineHelpText>A - Association
C - Corporation
E - Government Owned Enterprise
L - Limited Company
O - Other
P - Partnership
R - Limited Partnership
S - Sole Proprietorship
T - Trust Company
V - Co-operative</inlineHelpText>
        <label>Company Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IATA_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IATA Member Airline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_AIMS_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is AIMS Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Modified_by_Source__c</fullName>
        <description>Date this record was last updated with master data from the source. Workflow updates this field.</description>
        <inlineHelpText>Date this record was last updated with master data from the source.</inlineHelpText>
        <label>Last Modified by Source</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>Map the objects AGT from AIMS. This is a value equal to category.</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_for_creation__c</fullName>
        <description>Reason for creating a standard account</description>
        <inlineHelpText>Select the reason for creating this standard account</inlineHelpText>
        <label>Reason for creation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account is missing</fullName>
                </value>
                <value>
                    <fullName>Airline Headquarter applying for a code</fullName>
                </value>
                <value>
                    <fullName>Branch is missing</fullName>
                </value>
                <value>
                    <fullName>Created By Analyst From Wizard</fullName>
                </value>
                <value>
                    <fullName>Created by customer</fullName>
                </value>
                <value>
                    <fullName>Headquarter is missing</fullName>
                </value>
                <value>
                    <fullName>New agent</fullName>
                </value>
                <value>
                    <fullName>New airline joining BSP</fullName>
                </value>
                <value>
                    <fullName>New Airline joining CASS</fullName>
                </value>
                <value>
                    <fullName>New for E&amp;F</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remittance_frequency__c</fullName>
        <label>Remittance frequency</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>M</fullName>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Fortnightly</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>Every 10 days</label>
                </value>
                <value>
                    <fullName>W</fullName>
                    <label>4 times per month</label>
                </value>
                <value>
                    <fullName>V</fullName>
                    <label>Weekly</label>
                </value>
                <value>
                    <fullName>S</fullName>
                    <label>Every 5 days</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Twice a week</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>Every 3 days</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Daily</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accommodation</fullName>
                </value>
                <value>
                    <fullName>Airline</fullName>
                </value>
                <value>
                    <fullName>Airline Supplier</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Equipment Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Cargo Agent</fullName>
                    <label>Freight Forwarder</label>
                </value>
                <value>
                    <fullName>General Public</fullName>
                </value>
                <value>
                    <fullName>General Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Governmental Institution</fullName>
                </value>
                <value>
                    <fullName>Holding Company</fullName>
                </value>
                <value>
                    <fullName>IATA</fullName>
                </value>
                <value>
                    <fullName>Infrastructure Partner</fullName>
                </value>
                <value>
                    <fullName>Internal Use</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Non-Airline Transportation</fullName>
                </value>
                <value>
                    <fullName>Recreational</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Used for records imported from external sources. Specifies the name of the Source System</description>
        <label>Source System</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>IATA_Agency</fullName>
        <active>true</active>
        <description>The new record type for ALL Agencies with NEW data model - Use this for all Agencies</description>
        <label>Agency</label>
    </recordTypes>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard_Account</fullName>
        <active>true</active>
        <description>Use for all other accounts.</description>
        <label>Standard Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ANG_Enable_NewGen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To enable the agency’s country to use the new accreditations model used in NewGen and Risk Event</description>
        <label>New Accr. Model &amp; Risk Events enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IATA_ISO_State__c.object
<CustomObject>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>IATA ISO States</relationshipLabel>
        <relationshipName>IATA_ISO_States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <externalId>true</externalId>
        <label>ISO Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IATA ISO State</label>
    <nameField>
        <label>ISO State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>License_Cost_Center__c</fullName>
        <inlineHelpText>The IATA cost center that is paying for your Salesforce.com license.</inlineHelpText>
        <label>License Cost Center</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/WorkflowHelperTest.cls
@isTest
private class WorkflowHelperTest {

    @testSetup static void setup(){
        
    }

    @isTest static void  AccountUpdateIndustryTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        Id accountRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);
        fieldsOfObject.put('Type','IATA Passenger Sales Agent');

        Account acct = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgencyNoType');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);

        Account acct2 = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);
        
        insert new List<Account>{acct,acct2};

        Test.stopTest();

        acct = [Select Id, Industry, Type from Account where name = 'NewGenAgency'];

        System.assertEquals('Travel Agent',acct.Industry);

        acct = [Select Id, Industry, Type from Account where name = 'NewGenAgencyNoType'];

        System.assertEquals(null,acct.Industry);
    }

    @isTest static void  updateAirlineMembershipTestPositive(){
        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        Id accountRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgencyHE');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);
        fieldsOfObject.put('Type','IATA Passenger Sales Agent');
        fieldsOfObject.put('IATA_Member__c',true);

        Account acct = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);

        insert acct;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgencyAE');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);
        fieldsOfObject.put('Type','IATA Passenger Sales Agent');
        fieldsOfObject.put('ParentId',acct.Id);

        Account acctAE = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);

        insert acctAE;

        Test.stopTest();
    
        acctAE = [Select Id, IATA_Member__c from Account where name = 'NewGenAgencyAE'];

        System.assertEquals(true,acctAE.IATA_Member__c);

        acct.IATA_Member__c = false;
        update acct;

        update acctAE;

        acctAE = [Select Id, IATA_Member__c from Account where name = 'NewGenAgencyAE'];

        System.assertEquals(false,acctAE.IATA_Member__c);

    }

    @isTest static void  updateAirlineMembershipTest(){
        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        Id accountRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgencyHE');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);
        fieldsOfObject.put('Type','IATA Passenger Sales Agent');
        fieldsOfObject.put('IATA_Member__c',true);

        Account acct = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);

        insert acct;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgencyAE');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);
        fieldsOfObject.put('Type','IATA Passenger Sales Agent');
        fieldsOfObject.put('ParentId',acct.Id);

        Account acctAE = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);

        insert acctAE;

        Test.stopTest();
    
        acctAE = [Select Id, IATA_Member__c from Account where name = 'NewGenAgencyAE'];

        System.assertEquals(true,acctAE.IATA_Member__c);

        acct.IATA_Member__c = false;
        update acct;

        update acctAE;

        acctAE = [Select Id, IATA_Member__c from Account where name = 'NewGenAgencyAE'];

        System.assertEquals(false,acctAE.IATA_Member__c);

    }

    @isTest static void  updateLastModifiedDateByIntegrationsTest(){
        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        Id accountRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);
        fieldsOfObject.put('Type','IATA Passenger Sales Agent');

        Account acct = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);

        insert acct;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency2');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);

        Account acct2 = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);
        

        // Create a unique UserName
          String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';

        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(
            Alias = 'standt',
            Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8',
            FirstName = 'System',
            LastName='Integrations',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName=uniqueUserName,
            License_Cost_Center__c ='IDS005CH01'
            );

        System.runAs(u) {
            insert acct2;
        }


        Test.stopTest();
    
        acct =  [Select Id, Last_Modified_by_Source__c from Account where name = 'NewGenAgency'];
        acct2 = [Select Id, Last_Modified_by_Source__c from Account where name = 'NewGenAgency2'];

        System.assertEquals(null,acct.Last_Modified_by_Source__c);

        Date date1 = date.newinstance(System.today().year(), System.today().month(), System.today().day());
        Date date2 = date.newinstance(acct2.Last_Modified_by_Source__c.year(), acct2.Last_Modified_by_Source__c.month(), acct2.Last_Modified_by_Source__c.day());

        System.assertEquals(date1,date2);

        System.runAs(u) {
            update acct;
        }

        acct =  [Select Id, Last_Modified_by_Source__c from Account where name = 'NewGenAgency'];
        
        date1 = date.newinstance(System.today().year(), System.today().month(), System.today().day());
        date2 = date.newinstance(acct.Last_Modified_by_Source__c.year(), acct.Last_Modified_by_Source__c.month(), acct.Last_Modified_by_Source__c.day());

        System.assertEquals(date1,date2);

    }

    @isTest static void  updateWebstarAccountCategoryTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        Id accountRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);
        fieldsOfObject.put('Source_System__c','webstar');

        Account acct = ANG_EntityCreator.createAccount(accountRT, ctry.Id, fieldsOfObject);

        insert acct;

        Test.stopTest();

        acct =  [Select Id, sector__c, Category__c from Account where name = 'NewGenAgency'];

        System.assertEquals('Travel Agent',acct.sector__c);
        System.assertEquals('IATAN Passenger Agent',acct.Category__c);
        
    }

    @isTest static void  updateAIMSAccountRecordtypeTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        Id standardRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'Standard_Account');

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Is_AIMS_Account__c',true);
        fieldsOfObject.put('Source_System__c','webstar');

        Account acct = ANG_EntityCreator.createAccount(standardRT, ctry.Id, fieldsOfObject);

        insert acct;

        Test.stopTest();

        acct =  [Select Id, recordTypeId from Account where name = 'NewGenAgency'];

        Id accountRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');

        System.assertEquals(accountRT,acct.recordTypeId);
        
    }    

    @isTest static void  resetAccountIdCardDiscountTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        Id standardRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('ID_Card_Key_Account_Discount__c',50);
        fieldsOfObject.put('IDCard_Key_Account__c',true);

        Account acct = ANG_EntityCreator.createAccount(standardRT, ctry.Id, fieldsOfObject);

        insert acct;

        Test.stopTest();

        acct.IDCard_Key_Account__c = false;
        update acct;

        acct =  [Select Id, ID_Card_Key_Account_Discount__c from Account where name = 'NewGenAgency'];

        System.assertEquals(0,acct.ID_Card_Key_Account_Discount__c);
        
    }    
    
    @isTest static void resetAccountTypeTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        ID airLineRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline') ;

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Sector__c','Airline');
        fieldsOfObject.put('ACLI_Status__c','Active Company');
        fieldsOfObject.put('Account_Type__c','Not Applicable');

        Account acct = ANG_EntityCreator.createAccount(airLineRT, ctry.Id, fieldsOfObject);

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency2');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Sector__c','Airline');
        fieldsOfObject.put('ACLI_Status__c','Active Company');
        fieldsOfObject.put('Account_Type__c','Not Applicable');
        fieldsOfObject.put('Membership_status__c','IATA member');

        Account acct2 = ANG_EntityCreator.createAccount(airLineRT, ctry.Id, fieldsOfObject);

        insert new List<Account>{acct,acct2};

        Test.stopTest();

        acct =  [Select Id, Account_Type__c from Account where name = 'NewGenAgency'];

        System.assertEquals(null,acct.Account_Type__c);

        acct2 =  [Select Id, Account_Type__c from Account where name = 'NewGenAgency2'];

        System.assertEquals('Not Applicable',acct2.Account_Type__c);

    }


    @isTest static void restoreAccountTypeTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        ID airLineRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline') ;

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Sector__c','Airline');
        fieldsOfObject.put('ACLI_Status__c','Active Company');
        fieldsOfObject.put('Membership_status__c','IATA member');

        Account acct = ANG_EntityCreator.createAccount(airLineRT, ctry.Id, fieldsOfObject);

        insert new List<Account>{acct};

        Test.stopTest();

        acct =  [Select Id,Sector__c,Membership_status__c,ACLI_Status__c,Account_Type__c from Account where name = 'NewGenAgency'];

        system.debug('dudu account is:'+acct);

        System.assertEquals('Not Applicable',acct.Account_Type__c);


    }

    @isTest static void setAccountSiteTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        Id standardRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'Standard_Account');
        ID airLineRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline') ;

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Created by customer');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Industry','Travel Agent');
        fieldsOfObject.put('Site','Site');
        fieldsOfObject.put('Sector__c','Travel Agent');
        
        Account acct = ANG_EntityCreator.createAccount(airLineRT, ctry.Id, fieldsOfObject);

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency2');
        fieldsOfObject.put('Short_Name__c','NewGenAgency2');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Created by customer');
        fieldsOfObject.put('Airline_designator__c','1234');
        fieldsOfObject.put('IATACode__c','1234567');
        fieldsOfObject.put('Industry','Travel Agent');
        fieldsOfObject.put('Site','Site');
        fieldsOfObject.put('Sector__c','Airline');

        Account acct2 = ANG_EntityCreator.createAccount(standardRT, ctry.Id, fieldsOfObject);
            
        insert new List<Account>{acct,acct2};

        Test.stopTest();

        acct =   [Select Id,Industry,Site,Airline_designator__c,IATACode__c, IATA_ISO_Country__r.ISO_Code__c from Account where name = 'NewGenAgency'];
        acct2 =  [Select Id,Industry,Site,Airline_designator__c,IATACode__c, IATA_ISO_Country__r.ISO_Code__c from Account where name = 'NewGenAgency2'];

        System.assertEquals('Site',acct.site);
        System.assertEquals('1234 1234567 PT',acct2.site);

    }

    @isTest static void setDataQualityHistoryTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        ID airLineRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline') ;

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Created by customer');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Industry','Travel Agent');

        Account acct = ANG_EntityCreator.createAccount(airLineRT, ctry.Id, fieldsOfObject);

        insert new List<Account>{acct};

        Test.stopTest();

        acct =   [Select Id,Data_quality_history__c from Account where name = 'NewGenAgency'];

        System.assertEquals(null, acct.Data_quality_history__c);

        acct.Comment_data_quality_feedback__c = 'XPTO';
        update acct;

        acct =   [Select Id,Data_quality_history__c from Account where name = 'NewGenAgency'];

        String formattedDate = System.now().format('YYYY-MM-dd');

        System.assertEquals(formattedDate+': XPTO', acct.Data_quality_history__c);
    }

    @isTest static void  updateAirlineTradeNameParentTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        ID airLineRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline') ;

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgencyHE');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Type','IATA Passenger Sales Agent');
        fieldsOfObject.put('IATA_Member__c',true);
        fieldsOfObject.put('TradeName__c','tradenameParent');

        Account acct = ANG_EntityCreator.createAccount(airLineRT, ctry.Id, fieldsOfObject);

        insert acct;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgencyAE');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','AE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Account is missing');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Type','IATA Passenger Sales Agent');
        fieldsOfObject.put('ParentId',acct.Id);
        fieldsOfObject.put('TradeName__c','AE Trade Name');

        Account acctAE = ANG_EntityCreator.createAccount(AMS_Utils.RECTYPE_AIRLINE_BR, ctry.Id, fieldsOfObject);

        insert acctAE;

        Test.stopTest();
    
        acctAE = [Select Id, TradeName__c, name from Account where location_type__c = 'AE'];

        System.assertEquals('tradenameParent',acctAE.TradeName__c);
        System.assertEquals('tradenameParent',acctAE.name);

        acct.TradeName__c = 'NewTradeNameParent';        
        acctAE.TradeName__c = 'XPTO';


        Profile p = [SELECT Id FROM Profile WHERE Name='Account management team'];
        
        User u = [Select id from User where ProfileId = :p.Id LIMIT 1];

        System.runAs(u) {
            
            update new List<Account>{acct,acctAE};
        }

        acctAE = [Select Id, TradeName__c, name from Account where location_type__c = 'AE'];

        System.assertEquals('NewTradeNameParent',acctAE.name);

    }


    @isTest static void setAccountDDSUpdateDateTest(){

        Test.startTest();

        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        ID airLineRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline') ;

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Created by customer');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Industry','Travel Agent');
        fieldsOfObject.put('DDS_Status__c','No Reply');

        Account acct = ANG_EntityCreator.createAccount(airLineRT, ctry.Id, fieldsOfObject);

        insert new List<Account>{acct};

        Test.stopTest();

        acct =   [Select Id,DDS_Last_Update_Date__c from Account where name = 'NewGenAgency'];

        System.assertEquals(null,acct.DDS_Last_Update_Date__c);

        acct.DDS_Status__c = 'multinational';
        update acct;

        acct =   [Select Id,DDS_Last_Update_Date__c from Account where name = 'NewGenAgency'];
        
        Date date1 = date.newinstance(System.today().year(), System.today().month(), System.today().day());
        Date date2 = date.newinstance(acct.DDS_Last_Update_Date__c.year(), acct.DDS_Last_Update_Date__c.month(), acct.DDS_Last_Update_Date__c.day());

        System.assertEquals(date1,date2);

    }

    @isTest static void setACLIAccountNameTest(){

        // Create a unique UserName
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        User u = new User(
            Alias = 'standt',
            Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8',
            FirstName = 'System',
            LastName='Integrations',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName=uniqueUserName,
            License_Cost_Center__c ='IDS005CH01'
            );
        
        insert u;

        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Airline_HQ_ACLI'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        
        Test.startTest();

        System.runAs(u) {
            
        IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='Portugal',ISO_Code__c='PT', ANG_Enable_NewGen__c = true)  ;
        insert ctry ;

        IATA_ISO_State__c stt = new IATA_ISO_State__c(Name= 'PORTUGAL', ISO_Code__c = 'PT', IATA_ISO_Country__c = ctry.Id);
        insert stt;

        ID airLineRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline') ;

        Map<String,Object> fieldsOfObject;

        fieldsOfObject = new Map<String,Object>();
        fieldsOfObject.put('Name','NewGenAgency');
        fieldsOfObject.put('Short_Name__c','NewGenAgency');
        fieldsOfObject.put('Location_Class__c','P');
        fieldsOfObject.put('Location_Type__c','HE');
        fieldsOfObject.put('Remittance_frequency__c','M');
        fieldsOfObject.put('Reason_for_creation__c','Created by customer');
        fieldsOfObject.put('Company_Type__c','A');
        fieldsOfObject.put('Name_on_AOC__c','NEWNAME');

        Account acct = ANG_EntityCreator.createAccount(airLineRT, ctry.Id, fieldsOfObject);

        insert new List<Account>{acct};

        Test.stopTest();

        acct =   [Select Id,Name from Account];

        System.assertEquals('NEWNAME', acct.Name);

        acct.Name_on_AOC__c = null;
        acct.Legal_name__c  = 'OLDNAME';


        update acct;
            
        acct =   [Select Id,Name from Account];

        System.assertEquals('OLDNAME', acct.Name);
        
        }


    }
}