src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Top_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Top Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Notification_Template__c</fullName>
        <label>Notification Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Portal_Status__c</fullName>
        <label>User Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved User</fullName>
                </value>
                <value>
                    <fullName>Approved Admin</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Regional Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Alert_Contact_By_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alert Contact By Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Critical_notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Critical notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiry_date__c</fullName>
        <label>Expiry date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notificatin_color__c</fullName>
        <label>Notificatin color</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>#007FFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>#FF5E4D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notification_Campagne_Name__c</fullName>
        <label>Notification Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Notification_template__c.object
<CustomObject>
    <fields>
        <fullName>Admins_Users__c</fullName>
        <label>Administrators/User</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrators</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Alert_Contact_By_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alert Contact By Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Alert_Contact_By_Push_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Alert contacts with a push notification on NewGen mobile app</description>
        <label>Alert Contact By Push Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CriticalNotification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>wf : to check send email box.
notifications with this box checked will be first in the list of notification on the dashboard</description>
        <label>Critical notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expire_in_days__c</fullName>
        <label>Expire in (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Chinese (Simplified)</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazilian)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Notification_template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Notification template</label>
        <referenceTo>Notification_template__c</referenceTo>
        <relationshipLabel>Notification templates</relationshipLabel>
        <relationshipName>Notification_templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notification_color__c</fullName>
        <label>Notification color</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>#007FFF</fullName>
                </value>
                <value>
                    <fullName>#FF5E4D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification template</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notification template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Notification_Template__c</fullName>
        <label>Notification Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ISSP_CreateNotification.cls
/*
    Class that create a notification to Portal Users
    Used in Portal and NewGen APP (mobile)
*/
public with sharing class ISSP_CreateNotification {

    public static Boolean privetTrigger = false;

    public static map<Schema.sObjectType,string> objTypecontactIdMap = new map<Schema.sObjectType,string>{Case.getSObjectType()=>'ContactId',Contact.getSObjectType()=>'Id',Portal_Application_Right__c.getSObjectType()=>'Contact__c'};
    
    public static void CreateNotificationForSobjectList(list<sObject> sObjList){
        list<string> tList = new  list<string>();
        string contactField = objTypecontactIdMap.get(sObjList[0].Id.getSObjectType());
        set<string> contactsIdSet = new set<string>();
        set<string> templatesNameSet = new set<string>();
        for(sObject obj : sObjList){
            contactsIdSet.add(string.valueOf(obj.get(contactField)));
             if(String.isNotEmpty((String)obj.get('Notification_template__c')))
                for(string str:string.valueOf(obj.get('Notification_template__c')).split(';')){
                    if(str != ''){
                        templatesNameSet.add(str);
                    }
                }
        }
        if(templatesNameSet.size()==0) return;

        map<string,set<string>> ContactsAdminsSetMap = getAllContactsAdmins(contactsIdSet);
        map<string,boolean> isAdminsNotificationMap = new map<string,boolean>();

        for(Notification_template__c nt : [select Id,Admins_Users__c,Name from Notification_template__c where Name in:templatesNameSet]){+
            System.debug(loggingLevel.FINE, '____ [cls ISSP_CreateNotification - CreateNotificationForSobjectList] nt - ' + nt);
            isAdminsNotificationMap.put(nt.Name,false);
            if(nt.Admins_Users__c == 'Administrators'){
                isAdminsNotificationMap.put(nt.Name,true);
            }
        }
        
        System.debug(loggingLevel.FINE, '____ [cls ISSP_CreateNotification - CreateNotificationForSobjectList] isAdminsNotificationMap - ' + isAdminsNotificationMap);
        System.debug(loggingLevel.FINE, '____ [cls ISSP_CreateNotification - CreateNotificationForSobjectList] ContactsAdminsSetMap - ' + ContactsAdminsSetMap);

        for(sObject obj :sObjList){
            if(obj.get('Notification_template__c') != null && obj.get('Notification_template__c') != '')
                for(string str:string.valueOf(obj.get('Notification_template__c')).split(';')){
                    if(str != ''){
                        tList.add(obj.get(contactField)+':'+str);
                        if(isAdminsNotificationMap.containsKey(str) && isAdminsNotificationMap.get(str) && ContactsAdminsSetMap.containsKey(string.valueOf(obj.get(contactField)))){
                            for(string conId : ContactsAdminsSetMap.get(string.valueOf(obj.get(contactField)))){
                                tList.add(conId+':'+str);
                            }
                        }
                    }
                }
          obj.put('Notification_template__c','');
        }
        if(tList.size()>0)
            createNotification(tList);  
    }
    
    public static void createNotification(List<String> tList) {
        createNotification(tList, true);
    }

    public static List<Notification__c> createNotification(list<string> tList, Boolean insertNotifications){
        try{
            map<string,set<string>> tMap = createSetMapFromList(tList,0,1);
            set<string> notificationNameSet = getNotificationNameSet(tMap);
            
            map<string,string> languageMap = getLanguagesMap();
            map<string,string> contactLanguageMap = new map<string,string>();
            for(User user : [Select u.LanguageLocaleKey, u.ContactId From User u where ContactId in:tMap.keySet()]){
                contactLanguageMap.put(user.ContactId,languageMap.get(user.LanguageLocaleKey));
            }
            
            map<string,Notification_template__c> notificationTemplateMap = new map<string,Notification_template__c>();
            map<string,map<string,Notification_template__c>> notificationTemplateTranslateMap = new  map<string,map<string,Notification_template__c>>();
            
            list<Notification__c> newNotificationList = new list<Notification__c>();
            
            list <Notification_template__c> NotificationTemplateList = 
                [Select n.Subject__c, n.Name, n.Message__c, n.Language__c,Type__c,Notification_color__c,Alert_Contact_By_Email__c,
                    Expire_in_days__c, CriticalNotification__c,Alert_Contact_By_Push_Notification__c, 
                    (Select Subject__c, Name, Message__c, Language__c,Type__c,Notification_color__c,Alert_Contact_By_Email__c,
                    Expire_in_days__c, CriticalNotification__c, Alert_Contact_By_Push_Notification__c From Notification_templates__r)
                     From Notification_template__c n  where  Name in:notificationNameSet ];
            for(Notification_template__c nt: NotificationTemplateList){
                notificationTemplateMap.put(nt.Name,nt);
                notificationTemplateTranslateMap.put(nt.Name,new map<string,Notification_template__c>());
                for(Notification_template__c ntTranslate:nt.Notification_templates__r){
                    notificationTemplateTranslateMap.get(nt.Name).put(ntTranslate.Language__c,ntTranslate);
                }
            }
            
            for(string parentId : tMap.keySet()){
                for(string rempId : tMap.get(parentId)){
                    Notification_template__c nt = notificationTemplateMap.get(rempId);
                    if(notificationTemplateTranslateMap.get(rempId).get(contactLanguageMap.get(parentId)) != null) nt = notificationTemplateTranslateMap.get(rempId).get(contactLanguageMap.get(parentId));

                    Notification__c notification = new Notification__c(
                        Contact__c = parentId,
                        Message__c = nt.Message__c,
                        Alert_Contact_By_Email__c = nt.Alert_Contact_By_Email__c,
                        Alert_Contact_By_Push_Notification__c = nt.Alert_Contact_By_Push_Notification__c,
                        Subject__c = nt.Subject__c
                        ,Type__c = nt.Type__c
                        ,Notificatin_color__c = nt.Notification_color__c 
                        ,Notification_Campagne_Name__c = ISSP_CampaignNotificationBatch.notificationCampagneName
                        ,Critical_notification__c = nt.CriticalNotification__c
                        ,Expiry_date__c = (nt.Expire_in_days__c != null ? system.Now() + nt.Expire_in_days__c : null)
                    );
                    newNotificationList.add(notification);
                }
            }
            
            if(insertNotifications) insert newNotificationList;

            return newNotificationList;
           
        }catch(Exception e){
            system.debug('\n\n\n\n Exception : '+e.getMessage()+'\n\n\n\n');
            return new List<Notification__c>();
        }
        
   }
   
   private static map<string,set<string>> createSetMapFromList(list<string> tList,integer key,integer value){
        map<string,set<string>> tMap = new  map<string,set<string>>();
        for(string str:tList){
           if(tMap.get(str.split(':')[key])==null) tMap.put(str.split(':')[key],new set<string>());
           tMap.get(str.split(':')[key]).add(str.split(':')[value]);
        }
        return tMap;
   }
   
   
   private static  set<string> getNotificationNameSet(map<string,set<string>> tMap){
        set<string> roleNameSet = new set<string>();
        for(string str:tMap.keySet()){
           roleNameSet.addAll(tMap.get(str));
        }
        return roleNameSet;
   }
   
   private static  map<string,set<string>> getAllContactsAdmins(set<string> contactsSet){
       map<Id,Id> topAccountContact = new  map<Id,Id>();
       map<string,set<string>> contactAdminMap = new map<string,set<string>>();
       
       for(Contact con: [select Id,AccountId,Account.Top_Parent__c from Contact where Id in :contactsSet]){
            if(con.Account.Top_Parent__c!=null && con.AccountId!=null){
                //commenting lines below cause they will never occur
                //if(con.Account.Top_Parent__c==null) topAccountContact.put(con.AccountId,con.Id);
                //else 
                topAccountContact.put(con.Account.Top_Parent__c,con.Id);
             }
            contactAdminMap.put(con.Id,new set<string>());
       }
       for(Contact con: [select Id,AccountId,Account.Top_Parent__c from Contact where Account.Top_Parent__c in :topAccountContact.keySet() 
                                                                                   and User_Portal_Status__c='Approved Admin']){
            string topAccId = con.Account.Top_Parent__c;
            if(topAccId == null) topAccId = con.AccountId;
            
            contactAdminMap.get(topAccountContact.get(topAccId)).add(con.Id);
       }
       return contactAdminMap;
   }
   
   
    
    public static map<string,string> getLanguagesMap()
    {
      Schema.DescribeFieldResult fieldResult = User.LanguageLocaleKey.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      map<string,string> languageMap = new map<string,string>();
      
      for( Schema.PicklistEntry f : ple)
      {
          languageMap.put( f.getValue(),f.getLabel());
      }       
       return languageMap;
    }
   
    /*not used anywhere
    public static void debug(string str,string mes){
        system.debug('n\n\n\n'+str+' : '+ mes +'\n\n\n\n');
    }
    public static void debug(string str,map<string,string> mes){
        system.debug('n\n\n\n'+str+' : '+ mes +'\n\n\n\n');
    }
    public static void debug(string str,set<Id> mes){
        system.debug('n\n\n\n'+str+' : '+ mes +'\n\n\n\n');
    }
    public static void debug(string str,map<Id,Id> mes){
        system.debug('n\n\n\n'+str+' : '+ mes +'\n\n\n\n');
    }*/



    //INC253595 - Start

    public static void SendEmailToPortalAdminNewContact(list<Contact> newPortalContactList) {
        
        system.debug('SendEmailToPortalAdminNewContact starting...' + newPortalContactList);
        ID templateId = PortalServiceAccessTriggerHandler.getEmailTemplateIdByName(ENV.EmailTemplateData.NotifyAdminNewContact);
        System.debug('templateId==>'+templateId);
        if(String.isBlank(templateId)) {
            system.debug(LoggingLevel.ERROR, 'Email template ' + ENV.EmailTemplateData.NotifyAdminNewContact + ' not found');   
        }
        Set<ID> accountIDs = new Set<ID>();
        for(Contact con : newPortalContactList) {
                accountIDs.add(con.AccountId);
        }
        
        System.debug('zZzZ accountIDs==>'+accountIDs);
        map<ID, Set<ID>> accIdToUserIdMap = new map<ID, Set<ID>>();
        for(AccountTeamMember member : PortalServiceAccessTriggerHandler.getPortalAdmins(accountIDs)) {
            Set<ID> userIDs = accIdToUserIdMap.get(member.AccountId);
            if(null == userIDs)
                userIDs = new Set<ID>();
            
            userIDs.add(member.UserId);
            accIdToUserIdMap.put(member.AccountId, userIDs);
        }
        
        ID standartReplyUserID = PortalServiceAccessTriggerHandler.getStandartReplyUserID(ENV.Reply_Email);
        System.debug('zZzZ standartReplyUserID==>'+standartReplyUserID);    
        
        List<Messaging.SingleEmailMessage> msgList = new List<Messaging.SingleEmailMessage>();
        for(Contact con : newPortalContactList) {
            System.debug('con==>'+con + 'accountMap ' + accIdToUserIdMap);
                     
            Set<ID> portalAdminUserIDs = accIdToUserIdMap.get(con.AccountId);
            if(null == portalAdminUserIDs) continue;
            
            if(String.isNotBlank(templateId)) {
                for(ID userId : portalAdminUserIDs) {
                    Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage(); 
                    emailMsg.setTemplateId(templateId);
                    emailMsg.setTargetObjectId(userId);
                    emailMsg.saveAsActivity = false;
                    
                    if(null != standartReplyUserID)
                        emailMsg.setOrgWideEmailAddressId(standartReplyUserID);
                    else {
                        emailMsg.setReplyTo(ENV.Reply_Email);
                        emailMsg.setSenderDisplayName(ENV.AccessToApplicationServiceRequested_Email_Subject);
                    }
                    emailMsg.setWhatId(con.id); 
                    msgList.add(emailMsg);
                }
            }

            // NewGen Mobile APP Start
            Set <String> portalAdminUserIDsAsString = (Set<String>)JSON.deserialize(JSON.serialize(portalAdminUserIDs), Set<String>.class);
            NewGen_Account_Statement_Helper.sendPushNotification(portalAdminUserIDsAsString, Label.NewGenApp_PortalUserRequested, 
                null, NewGen_Account_Statement_Helper.NAVIGATE_TO_USER_REQUEST_ADMIN);
            // NewGen Mobile APP End
        }
        System.debug('zZzZ msgList==>'+msgList);
        if(!msgList.isEmpty()){
            Messaging.sendEmail(msgList);
        }
        else 
            system.debug(LoggingLevel.ERROR, 'emails not sent !');
    }
   
    //INC253595 - End
   
}