src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Top_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Top Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AMPCoreGroups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of the most important groups, used in the Core Relationships listing</description>
    <label>AMP Core Groups</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AM_First_Name_Latin_Char__c</fullName>
        <inlineHelpText>The transcript of the First Name in latin characters (only if using a different character set)</inlineHelpText>
        <label>First Name - Latin Char.</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AM_Job_Title_English__c</fullName>
        <inlineHelpText>The English translation of the title (only if Title is given in another language)</inlineHelpText>
        <label>Title - English</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AM_Last_Name_Latin_Char__c</fullName>
        <inlineHelpText>The transcript of the Last Name in latin characters (only if using a different character set)</inlineHelpText>
        <label>Last Name - Latin Char.</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas, The</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LocalGovernance__c.object
<CustomObject>
    <description>Used to manage the APJC forums, the participants, and the meetings. All by IDFS ISS.</description>
    <fields>
        <fullName>AM_Under__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the top-most conference or committee under which the group is found, before the DG / AGM / Board of Governors. Used in the Account Management project for displaying the group participation information at HQ account level.</description>
        <label>Under</label>
        <referenceTo>LocalGovernance__c</referenceTo>
        <relationshipLabel>Industry Groups (Under)</relationshipLabel>
        <relationshipName>Industry_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipName>Local_Governance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Owner_Text__c</fullName>
        <description>Group owner in free text for Reg/Div Groups</description>
        <inlineHelpText>Name of Group Owner</inlineHelpText>
        <label>Group Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>For local groups, if empty, this field will be populated with the country manager</inlineHelpText>
        <label>Group Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Local_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <label>Industry Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Industry Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Junction object. Used by IDFS ISS to manage the APJC participants per APJC (specific object)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR 3 OR (4 AND 5 AND 2)</booleanFilter>
            <errorMessage>The new participant is not related to an Airline or an Agency or this group does not allow participants from Agencies</errorMessage>
            <filterItems>
                <field>Contact.Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Agency</value>
            </filterItems>
            <filterItems>
                <field>$Source.Local_Group_Type__c</field>
                <operation>equals</operation>
                <value>ALWG, APJC, APJC / FAG, CAPJC, CEC, CGA, EACP JC, JALWG</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Airline Headquarters, Airline Branch</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.Sector__c</field>
                <operation>equals</operation>
                <value>Association</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Others</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>APJC_Participants</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Contact__r.Account.IATA_ISO_Country__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Participant Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hidden_Account_Id__c</fullName>
        <formula>IF(Contact__r.Account.RecordType.Name = &quot;Airline Headquarters&quot;, Contact__r.AccountId,
IF(Contact__r.Account.RecordType.Name = &quot;Airline Branch&quot;,Contact__r.Account.Parent.Id,
IF(Contact__r.Account.RecordType.Name = &quot;Agency&quot;,
IF(NOT(ISBLANK(Contact__r.Account.Parent.Id)),

Contact__r.Account.Parent.Id,
Contact__r.AccountId),

Contact__r.AccountId
)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hidden Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Governance__c</fullName>
        <label>Local Governance</label>
        <referenceTo>LocalGovernance__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>LocalGovernance_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Participant_Type__c</fullName>
        <label>Participant Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chair</fullName>
                </value>
                <value>
                    <fullName>Co-Chair</fullName>
                </value>
                <value>
                    <fullName>Vice-Chair</fullName>
                </value>
                <value>
                    <fullName>Accredited Representative</fullName>
                </value>
                <value>
                    <fullName>Designated Alternate</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Observer</fullName>
                </value>
                <value>
                    <fullName>Facilitator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Representing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the participant is not representing his/her employer on this specific group, enter the name of the company represented.</inlineHelpText>
        <label>Representing</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Airline Headquarters, IATA Country Office, Operator, Agency, General Sales Agent Headquarters, Others, Standard Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participants (Representing)</relationshipLabel>
        <relationshipName>Participants1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>Group Participant - {0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AWW_AccountGroupsCtrl.cls
public with sharing class AWW_AccountGroupsCtrl {

    public Response wrapper {get;set;}

    public AWW_AccountGroupsCtrl (ApexPages.StandardController stdController) {
        Account acc = (Account) stdController.getRecord();
        this.wrapper = getParticipants(acc.Id, true);
    }    

    @AuraEnabled
    public static Id getReportId(){
        return [SELECT Id FROM Report WHERE DeveloperName = 'AGM_Groups_Participation_DO_NOT_EDIT' LIMIT 1].Id;
    }

    @AuraEnabled
    public static Response getParticipants(Id accountId, Boolean retrieveMainGroupParticipants){
        List<Account> relatedAccounts = [SELECT Id 
                                         FROM Account 
                                         WHERE Id = :accountId OR World_Wide_Account__c = :accountId OR 
                                            Top_Parent__r.World_Wide_Account__c = :accountId];


        String whereClause = ' AND Local_Governance__r.AM_Under__c <> null';
        List<Participant__c> participants = getParticipants(whereClause, relatedAccounts);
        Response res = processGroups(participants);
        
        if(retrieveMainGroupParticipants) {
            processMainGroupMembers(res,relatedAccounts);
        }

        return res;
    }

    private static List<Participant__c> getParticipants(String whereClause, List<Account> relatedAccounts) {
        String query = 'SELECT Id, Contact__r.FirstName, Contact__r.LastName, Contact__r.Salutation, Contact__r.Title, Participant_Type__c,' +
            'Contact__r.AM_First_Name_Latin_Char__c, Contact__r.AM_Last_Name_Latin_Char__c, Contact__r.AM_Job_Title_English__c,' +
            'Contact__r.Email,Hidden_Account_Id__c, Local_Governance__c, Local_Governance__r.Group_Owner__c,' +
            'Local_Governance__r.Name, Local_Governance__r.Mission__c, Local_Governance__r.Group_Owner__r.Name,' + 
            'Local_Governance__r.Group_Owner_Text__c, Local_Governance__r.AM_Under__r.Name, Representing__c,' + 
            'Local_Governance__r.AM_Under__r.Group_Owner__c, Local_Governance__r.AM_Under__r.Group_Owner__r.Name, Local_Governance__r.Country__c ' +
            'FROM Participant__c ';
        
        query += 'WHERE (Representing__c IN :relatedAccounts OR Contact__r.AccountId IN :relatedAccounts) AND Local_Governance__r.Active__c = true ';
        query += whereClause;
        query += ' ORDER BY Local_Governance__r.AM_Under__r.Name, Local_Governance__r.Name, Participant_Type__c';
        
        System.debug('query: ' +  query);

        return Database.query(query);
    }

    private static void processMainGroupMembers(Response res, List<Account> relatedAccounts) {
        List<AMPCoreGroups__c> coreGroups = AMPCoreGroups__c.getAll().values();
        List<String> groupNames = new List<String>();
        for(AMPCoreGroups__c coreGroup : coreGroups) {
            groupNames.add(coreGroup.Name);
        }
        
        Map<String,TopGroup> currentMainGroups = new Map<String,TopGroup>();
        for(TopGroup mainGroup : res.groups) {
            currentMainGroups.put(mainGroup.printableGoupName, mainGroup);
        }

        String whereClause = 'AND Local_Governance__r.Name IN (\'' + String.join(groupNames, '\',\'')+ '\')';
        List<Participant__c> participants = getParticipants(whereClause, relatedAccounts);
        System.debug('participants: ' + participants);
        for(Participant__c p : participants) {
            TopGroup mainGroup = currentMainGroups.get(p.Local_Governance__r.Name);
            if(mainGroup == null) {
                String ownerName = p.Local_Governance__r.Group_Owner__c == null ? '' : p.Local_Governance__r.Group_Owner__r.Name;
                mainGroup = new TopGroup(null, p.Local_Governance__r.Name, ownerName);
                currentMainGroups.put(p.Local_Governance__r.Name, mainGroup);
            }

            String role = p.Participant_Type__c == null ? '' : p.Participant_Type__c.replace('/^\\d+\\s/','');
            String salutation = p.Contact__r.Salutation;
            String firstName = p.Contact__r.FirstName;
            String lastName = p.Contact__r.LastName;
            String title = p.Contact__r.Title;
            String email = p.Contact__r.Email;
            Member m = new Member(null,role,salutation,firstName,lastName,title,email,p.Representing__c <> null);
            mainGroup.members.add(m);
        }
    }

    private static Response processGroups(List<Participant__c> participants) {
        Response res = new Response();
        Map<String,TopGroup> topGroups = new Map<String,TopGroup>();
        Map<String,LocalGroup> localGroups = new Map<String,LocalGroup>();
        Map<String,List<String>> childRelations = new Map<String,List<String>>();

        Integer index = 0;
        for(Participant__c p : participants) {
            TopGroup tg = topGroups.get(p.Local_Governance__r.AM_Under__r.Name);
            if(tg == null) {
                String ownerName = p.Local_Governance__r.AM_Under__r.Group_Owner__c == null ? '' : p.Local_Governance__r.AM_Under__r.Group_Owner__r.Name;
                tg = new TopGroup('top-group-'+index, p.Local_Governance__r.AM_Under__r.Name, ownerName);
                topGroups.put(p.Local_Governance__r.AM_Under__r.Name, tg);
                childRelations.put(tg.rowId, new List<String>());
                index++;
            }

            LocalGroup lg = localGroups.get(p.Local_Governance__r.Name);
            if(lg == null) {
                String ownerName = p.Local_Governance__r.Group_Owner__c == null ? '' : p.Local_Governance__r.Group_Owner__r.Name;
                lg = new LocalGroup('local-group-'+index,p.Local_Governance__r.Name,p.Local_Governance__c, ownerName, p.Local_Governance__r.Mission__c, p.Local_Governance__r.Country__c);
                localGroups.put(p.Local_Governance__r.Name, lg);
                tg.childrens.add(lg);
                childRelations.put(lg.rowId, new List<String>());
                childRelations.get(tg.rowId).add(lg.rowId);
                index++;
            }

            String role = p.Participant_Type__c == null ? '' : p.Participant_Type__c.replace('/^\\d+\\s/','');
            String salutation = p.Contact__r.Salutation;
            String firstName = p.Contact__r.FirstName;
            String lastName = p.Contact__r.LastName;
            String title = p.Contact__r.Title;
            String email = p.Contact__r.Email;
            Member m = new Member('member-'+index, role, salutation, firstName, lastName, title, email,  p.Representing__c <> null);
            lg.childrens.add(m);
            childRelations.get(lg.rowId).add(m.rowId);
            index++;

            res.hasRepresentatives |= p.Representing__c <> null;
        }

        res.groups = topGroups.values();
        res.expandedRows = childRelations;
        return res;
    }

    public class Response {
        @AuraEnabled public List<TopGroup> groups {get;set;}
        @AuraEnabled public Map<String,List<String>> expandedRows {get;set;}
        @AuraEnabled public Boolean hasRepresentatives {get;set;}
        @AuraEnabled public List<IATA_ISO_Country__c> countries {get;set;}

        public Response() {
            this.groups = new List<TopGroup>();
            this.expandedRows = new Map<String,List<String>>();
            this.hasRepresentatives = false;
            this.countries = new List<IATA_ISO_Country__c> {new IATA_ISO_Country__c(Name= 'All')};
            this.countries.addAll([
                SELECT Id, Name 
                FROM IATA_ISO_Country__c 
                WHERE NOT ISO_Code__c IN ('XX', 'WW') 
                ORDER BY Name ASC NULLS FIRST]);
        }

    }

    public class TopGroup {
        @AuraEnabled public String rowId {get;set;}
        @AuraEnabled public String rowId_expand {get;set;}
        @AuraEnabled public String rowId_collapse {get;set;}
        @AuraEnabled public String groupName {get;set;}
        @AuraEnabled public List<LocalGroup> childrens {get;set;}
        //only used for print
        public List<Member> members {get;set;}
        public String printableGoupName {get;set;}
        public String ownerName {get;set;}

        public TopGroup(String rowId, String groupName, String ownerName) {
            this.rowId = rowId;
            this.rowId_collapse = 'collapse_' + rowId;
            this.rowId_expand = 'expand_' + rowId;
            this.groupName = 'Under ' + groupName;
            this.printableGoupName = groupName;
            this.ownerName = ownerName;
            this.childrens = new List<LocalGroup>();
            this.members = new List<Member>();
        }
    }

    public class LocalGroup {
        @AuraEnabled public String rowId {get;set;}
        @AuraEnabled public String rowId_expand {get;set;}
        @AuraEnabled public String rowId_collapse {get;set;}
        @AuraEnabled public String groupName {get;set;}
        @AuraEnabled public String groupLink {get;set;}
        @AuraEnabled public String ownerName {get;set;}
        @AuraEnabled public String mission {get;set;}
        @AuraEnabled public List<Member> childrens {get;set;}
        @AuraEnabled public Id countryId {get;set;}
    
        public LocalGroup(String rowId, String groupName, String groupLink, String ownerName, String mission, Id countryId) {
            this.rowId = rowId;
            this.rowId_collapse = 'collapse_' + rowId;
            this.rowId_expand = 'expand_' + rowId;
            this.groupName = groupName;
            this.groupLink = '/' + groupLink;
            this.ownerName = ownerName;
            this.mission = mission;
            this.countryId = countryId;
            this.childrens = new List<Member>();
        }
    }

    public class Member {
        @AuraEnabled public String rowId {get;set;}
        @AuraEnabled public String role {get;set;}
        @AuraEnabled public String salutation {get;set;}
        @AuraEnabled public String firstName {get;set;}
        @AuraEnabled public String lastName {get;set;}
        @AuraEnabled public String title {get;set;}
        @AuraEnabled public String email {get;set;}
        @AuraEnabled public Boolean isRepresentative {get;set;}

        public Member(String rowId, String role, String salutation, String firstName, String lastName, String title, String email, Boolean isRepresentative) {
            this.rowId = rowId;
            this.role = role;
            this.salutation = salutation;
            this.firstName = firstName;
            this.lastName = lastName;
            this.title = title;
            this.email = email;
            this.isRepresentative = isRepresentative;
        }
    }
    
}