src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AOC_Expiry_Date__c</fullName>
        <label>AOC Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Accounting_Code__c</fullName>
        <label>Three letter Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_Prefix__c</fullName>
        <label>Airline Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_designator__c</fullName>
        <description>Field used for the airline designator code e.g. BA</description>
        <label>IATA Designator</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sector__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Academic/Research Body</fullName>
                </value>
                <value>
                    <fullName>Agency Holding Company</fullName>
                </value>
                <value>
                    <fullName>Aircraft Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Airline Alliance</fullName>
                </value>
                <value>
                    <fullName>Airline Global Card Acquirer</fullName>
                </value>
                <value>
                    <fullName>Airline Holding Company</fullName>
                </value>
                <value>
                    <fullName>Airline Point of Sale</fullName>
                </value>
                <value>
                    <fullName>Airport Authority</fullName>
                </value>
                <value>
                    <fullName>Airport Concessionaire</fullName>
                </value>
                <value>
                    <fullName>Airport Operator</fullName>
                </value>
                <value>
                    <fullName>ANSP</fullName>
                </value>
                <value>
                    <fullName>Apartment &amp; Villa Rental</fullName>
                    <label>Apartment and Villa Rental</label>
                </value>
                <value>
                    <fullName>Banking Service</fullName>
                </value>
                <value>
                    <fullName>Box Office</fullName>
                </value>
                <value>
                    <fullName>Bus Line</fullName>
                </value>
                <value>
                    <fullName>Card Brand</fullName>
                </value>
                <value>
                    <fullName>Cargo only</fullName>
                </value>
                <value>
                    <fullName>Car Rental</fullName>
                </value>
                <value>
                    <fullName>Casino</fullName>
                </value>
                <value>
                    <fullName>CASS Associate</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Civil Aviation Authority</fullName>
                </value>
                <value>
                    <fullName>Consultancy Firm</fullName>
                </value>
                <value>
                    <fullName>Coordinator</fullName>
                </value>
                <value>
                    <fullName>Courier</fullName>
                </value>
                <value>
                    <fullName>Cruise Line</fullName>
                </value>
                <value>
                    <fullName>Domestic Agent</fullName>
                </value>
                <value>
                    <fullName>DPC</fullName>
                </value>
                <value>
                    <fullName>Engine Manufacturer</fullName>
                </value>
                <value>
                    <fullName>ERSP Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email at Account level</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_name__c</fullName>
        <description>Field used for the legal name of the airlines and the travel agents</description>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accommodation</fullName>
                </value>
                <value>
                    <fullName>Airline</fullName>
                </value>
                <value>
                    <fullName>Airline Supplier</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Equipment Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Cargo Agent</fullName>
                    <label>Freight Forwarder</label>
                </value>
                <value>
                    <fullName>General Public</fullName>
                </value>
                <value>
                    <fullName>General Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Governmental Institution</fullName>
                </value>
                <value>
                    <fullName>Holding Company</fullName>
                </value>
                <value>
                    <fullName>IATA</fullName>
                </value>
                <value>
                    <fullName>Infrastructure Partner</fullName>
                </value>
                <value>
                    <fullName>Internal Use</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Non-Airline Transportation</fullName>
                </value>
                <value>
                    <fullName>Recreational</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TradeName__c</fullName>
        <label>Trade Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ISSP_AMC_Change_Comp_Info.cls
public class ISSP_AMC_Change_Comp_Info {
//public Account cenas {get;set;}

	public Account accountRecord {get; set;}
	public Boolean hasValue {get; set;}
	public Boolean hasLegalName {get;set;}
	public Boolean hasTradeName {get;set;}
	public Boolean hasDesignatorValue {get; set;}
	public Boolean hasAccountingCode {get; set;}
	public Boolean hasPrefixCode {get;set;}
	public Boolean hasSector {get;set;}
	public Boolean hasCategory {get;set;}
	public Boolean hasBusinessPhone {get;set;}
	public Boolean hasOfficeEmail {get;set;}
	public Boolean hasWebsite {get;set;}
	public Boolean hasISOCountry {get;set;}
	public Boolean hasAddressInfo {get;set;}
	public Boolean hasAOCExpirationDate {get;set;}
	public String scenario {get;set;}
	public String description {get;set;}
	public String address {get;set;}
	public String subtopic {get;set;}
	public String reason {get;set;}
	public String erro {get;set;}

	public ISSP_AMC_Change_Comp_Info(){
		hasValue = true;
		hasLegalName = true;
		hasTradeName = true;
		hasDesignatorValue = true;
		hasAccountingCode = true;
		hasPrefixCode = true;
		hasSector = true;
		hasCategory = true;
		hasBusinessPhone = true;
		hasOfficeEmail = true;
		hasWebsite = true;
		hasISOCountry = true;
		hasAddressInfo = true;
		hasAOCExpirationDate = true;

		erro = ' ';
		getAccountInfo();
	}

	public void getAccountInfo(){
		accountRecord = ISSP_AMC_DAO.getAccountInfo();

		if(accountRecord.AOC_Expiry_Date__c == null){
			hasAOCExpirationDate = false;
		}

		if(accountRecord.Legal_name__c == null || accountRecord.Legal_name__c == ''){
			hasLegalName = false;
		}

		if(accountRecord.TradeName__c == null || accountRecord.TradeName__c == ''){
			hasTradeName = false;
		}

		if(accountRecord.Airline_designator__c == null || accountRecord.Airline_designator__c == ''){
			hasDesignatorValue = false;
		}

		if(accountRecord.Accounting_Code__c == null || accountRecord.Accounting_Code__c == ''){
			hasAccountingCode = false;
		}
		
		if(accountRecord.Airline_Prefix__c == null || accountRecord.Airline_Prefix__c == ''){
			hasPrefixCode = false;
		}

		if(accountRecord.Sector__c == null || accountRecord.Sector__c == ''){
			hasSector = false;
		}

		if(accountRecord.Category__c == null || accountRecord.Category__c == ''){
			hasCategory = false;
		}

		if(accountRecord.Phone == null || accountRecord.Phone == ''){
			hasBusinessPhone = false;
		}

		if(accountRecord.Email__c == null || accountRecord.Email__c == ''){
			hasOfficeEmail = false;
		}

		if(accountRecord.Website == null || accountRecord.Website == ''){
			hasWebsite = false;
		}

		if(accountRecord.IATA_ISO_Country__r.Name == null || accountRecord.IATA_ISO_Country__r.Name == ''){
			hasISOCountry = false;
		}

		if((accountRecord.ShippingStreet == null || accountRecord.ShippingStreet == '') && (accountRecord.ShippingCity == null || accountRecord.ShippingCity == '') &&
			(accountRecord.ShippingPostalCode == null || accountRecord.ShippingPostalCode == '') && (accountRecord.ShippingCountry == null || accountRecord.ShippingCountry == '')){
			hasAddressInfo = false;
		}

		address = accountRecord.ShippingStreet + ', ' + accountRecord.ShippingCity + ' ' + accountRecord.ShippingPostalCode + ' ' + accountRecord.ShippingCountry;
	}

	public PageReference createCase(){
		Case newCase = new Case();
		description = 'values from form: ' + '\n' + 'Business phone - ' + accountRecord.phone +
		'\n' + 'Office Email - ' + accountRecord.email__c + '\n \t' + 'Website - ' + accountRecord.website +
		'\n' + 'ISO Country - ' + accountRecord.IATA_ISO_Country__r.Name + '\n \t' + 'Address information - ' + address;

		scenario = ISSP_AMC_Constants.AMC_PAR_ACLI_CODES_CHANGE_COMPANY_INFO;
		subtopic = ISSP_AMC_Constants.AMC_CASE_SUBTOPIC_CHANGE_COMPANY_INFO;
		reason = ISSP_AMC_Constants.AMC_CASE_REASON_COMPANY_INFO;

		//newCase = ISSP_AMC_DAO.getCase(scenario, description, subtopic, reason);

		try{
			newCase = ISSP_AMC_DAO.getCase(scenario, description, subtopic, reason, true);
			PageReference pr = new PageReference('/ISSP_Case?caseId=' + newCase.Id + '&mid=M1S2');
			pr.setRedirect(true);
			return pr;
		}
		catch(Exception ex){
			if(ex.getMessage().contains('There is already an open Airline Coding Application case with Reason')) {
				//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'There is already an open Airline Coding Application case with Reason "Manage Changes / Minor" on the selected Account'));
				erro = 'There is already an open Airline Coding Application case for this Account';
			}
			else {
				throw new errorPageException(ex.getMessage());
			}
		}

		return null;
	}


	public void clearMessage(){
		erro = ' ';
	}
	public class errorPageException extends Exception {
	}
}