src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Role__c</fullName>
        <description>The roles covered by the account (e.g. Payment Provider)</description>
        <inlineHelpText>The roles covered by the account</inlineHelpText>
        <label>Account Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Payment Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact_Role__c.object
<CustomObject>
    <description>Related to the Account Role, used to designate an existing contact, under the account, that acts as a primary contact for the associated type of account role.</description>
    <fields>
        <fullName>Account_Role__c</fullName>
        <description>Reference to the Account Role</description>
        <label>Account Role</label>
        <referenceTo>Account_Role__c</referenceTo>
        <relationshipLabel>Account Contacts Role</relationshipLabel>
        <relationshipName>Account_Contacts_Role</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the account referenced</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts Role</relationshipLabel>
        <relationshipName>Account_Contacts_Role</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Name__c</fullName>
        <description>A functional role that a Contact belonging to an Account may assume when interacting with an IATA Salesforce functional capability. This designation technically supports the provisioning and delivery of IATA Salesforce functional capabilities.</description>
        <inlineHelpText>Contact Role Name to fill accordingly to the application using the record</inlineHelpText>
        <label>Contact Role Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Reference to the contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Contacts Role</relationshipLabel>
        <relationshipName>Account_Contacts_Role</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <description>Business context this detailed role will be related to</description>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Functional_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Rendered__c</fullName>
        <description>To Which Service the contact is associated</description>
        <inlineHelpText>To Which Service the contact is associated</inlineHelpText>
        <label>Service Rendered</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GADM</fullName>
                </value>
                <value>
                    <fullName>IFTP</fullName>
                </value>
                <value>
                    <fullName>Medaire</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>TIP</fullName>
                </value>
                <value>
                    <fullName>ONE Source</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Contact Role</label>
    <nameField>
        <displayFormat>ACR-{000000000}</displayFormat>
        <label>Account Contact Role Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts Role</pluralLabel>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <description>Master RecordType</description>
        <label>Master</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Role__c.object
<CustomObject>
    <description>Used to extend the role of any existing account type e.g. an airline that also acts as a payment provider. A record type should be created for each type of account role required.</description>
    <fields>
        <fullName>Account_Role_Name__c</fullName>
        <description>A functional role that an Account may assume when interacting with an IATA Salesforce functional capability. This designation technically supports the provisioning of IATA Salesforce functional capabilities.

The Account Role record should be named after the functional capability for which the record applies. If required, Account related data, within the context of the functional capability, could be held on a related Account Role Detail record.</description>
        <inlineHelpText>Account Role Name to fill accordingly to the application using the record</inlineHelpText>
        <label>Account Role Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Id to account record</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <description>Business context this detailed role will be related to</description>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Functional_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Satus of account role record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Role</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <description>Master recordType</description>
        <label>Master</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IATA_ISO_State__c.object
<CustomObject>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>IATA ISO States</relationshipLabel>
        <relationshipName>IATA_ISO_States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <externalId>true</externalId>
        <label>ISO Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IATA ISO State</label>
    <nameField>
        <label>ISO State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <label>Functional Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Functional_Roles</valueSetName>
        </valueSet>
    </fields>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Term_and_Condition__c.object
<CustomObject>
    <fields>
        <fullName>Is_Latest__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the this record is the latest version of the T&amp;C of the related Service</description>
        <label>Is Latest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NewGenApp_PortalService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Portal Service Item</description>
        <label>NewGenApp Portal Service</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Terms &amp; Conditions</relationshipLabel>
        <relationshipName>Terms_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Term &amp; Condition</label>
    <nameField>
        <label>Term &amp; Condition&apos;s Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms &amp; Conditions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Training_Contact_Role_Details__c.object
<CustomObject>
    <description>Contains information of the Training Student Contact</description>
    <fields>
        <fullName>Account_Contact_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Connection to the Account Contact Role record</description>
        <inlineHelpText>Connection to the Account Contact Role record</inlineHelpText>
        <label>Account Contact Role</label>
        <referenceTo>Account_Contact_Role__c</referenceTo>
        <relationshipLabel>Training Contact Details</relationshipLabel>
        <relationshipName>Training_Contact_Role_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Contact Role Detail</label>
    <nameField>
        <displayFormat>TCRD-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Contact Role Details</pluralLabel>
    <recordTypes>
        <fullName>Yardstick_Trainee</fullName>
        <active>true</active>
        <description>Yardstick Trainee</description>
        <label>Yardstick Trainee</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Functional_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>E&amp;F</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>One Source</fullName>
    </customValue>
    <customValue>
        <fullName>One Source</fullName>
    </customValue>
    <description>Functional Roles</description>
    <masterLabel>Functional Roles</masterLabel>
</GlobalValueSet>

src/classes/AccountRolesAlignBatch_Test.cls
@isTest
private class AccountRolesAlignBatch_Test {

	@testSetup
	static void setup(){

		IATA_ISO_Country__c isoc = new IATA_ISO_Country__c(Name = 'United States', ISO_Code__c = 'US');
		insert isoc;

		IATA_ISO_State__c isoState = new IATA_ISO_State__c(Name = 'New York', IATA_ISO_Country__c = isoc.Id, ISO_Code__c = 'NY');
		insert isoState;

		Account acc = new Account(Name = 'Test Account');
		insert acc;
		Account acc2 = new Account(Name = 'Test Account2');
		insert acc2;

		Contact c = new Contact(LastName = 'Doe', AccountId = acc.Id, Email = 'doetest@test.com');
		insert c;

		Contact c2 = new Contact(LastName = 'Don', AccountId = acc.Id, Email = 'dontest@test.com');
		insert c2;

		String RECTYPE_Master_AccRole = RecordTypeSingleton.getInstance().getRecordTypeId('Account_Role__c', 'Master');
		Account_Role__c accRole = new Account_Role__c(Account__c = acc.Id, Account_Role_Name__c = 'Training',Functional_Role__c = 'Training', RecordTypeId = RECTYPE_Master_AccRole );
		insert accRole;

		Id accContactRole_RT = RecordTypeSingleton.getInstance().getRecordTypeId('Account_Contact_Role__c', 'Master');
		Account_Contact_Role__c acr = new Account_Contact_Role__c(Account_Role__c = accRole.Id, Contact__c = c2.Id, Service_Rendered__c = 'Other', RecordTypeId = accContactRole_RT, Contact_Role_Name__c = 'Trainee', Functional_Role__c =  'Training');
		insert acr;

		String RECTYPE_Trainee_YASContDet = RecordTypeSingleton.getInstance().getRecordTypeId('Training_Contact_Role_Details__c', 'Yardstick_Trainee');
		Training_Contact_Role_Details__c tcrd = new Training_Contact_Role_Details__c(Account_Contact_Role__c = acr.Id, RecordTypeId = RECTYPE_Trainee_YASContDet);
		insert tcrd;

		Portal_Applications__c pa = new Portal_Applications__c(Name = 'Training Platform (LMS)');
		insert pa;

		Term_and_Condition__c tos = new Term_and_Condition__c(NewGenApp_PortalService__c = pa.Id, Is_Latest__c = true, Status__c = 'Final', Effective_Start_Date__c = Date.today());
		insert tos;

	}

	@isTest
	static void testChangeContactAccount(){
		Account acc2 = [SELECT Id, Name FROM Account WHERE Name = 'Test Account2' LIMIT 1];
		Contact contact = [SELECT Id, Name, Email,AccountId FROM Contact WHERE LastName = 'Don' LIMIT 1];

		test.startTest();

		contact.AccountId = acc2.Id;
		update contact;

		system.assert(contact.AccountId == acc2.Id);

		test.stopTest();
	}

	@isTest
	static void testChangeContactAccount_switchAccountRoles(){
		Account acc2 = [SELECT Id, Name FROM Account WHERE Name = 'Test Account2' LIMIT 1];
		Contact contact = [SELECT Id, Name, Email,AccountId FROM Contact WHERE LastName = 'Don' LIMIT 1];

		test.startTest();

		contact.AccountId = acc2.Id;
		
		Map<Id,sObject> contactMap = new Map<Id,sObject>();
		contactMap.put(contact.Id, contact);

		AccountRolesAlignBatch.switchAccountRoles(contactMap);

		Account_Contact_Role__c acr = [SELECT Id,Account_Role__c,Account_Role__r.Account__c,Contact__c
			FROM Account_Contact_Role__c
			WHERE Contact__c = :contact.Id
			AND Contact_Role_Name__c = 'Trainee'
			AND Functional_Role__c =  'Training' LIMIT 1];

		system.assert(acr.Account_Role__r.Account__c == acc2.Id);

		test.stopTest();
	}
	
	@isTest
	static void testChangeContactAccount_switchAccountRoles_Invocable(){
		Account acc2 = [SELECT Id, Name FROM Account WHERE Name = 'Test Account2' LIMIT 1];
		Contact contact = [SELECT Id, Name, Email,AccountId FROM Contact WHERE LastName = 'Don' LIMIT 1];

		test.startTest();

		contact.AccountId = acc2.Id;
		
		List<Contact> contactList = new List<Contact>();
		contactList.add(contact);

		AccountRolesAlignBatch.switchAccountRoles(contactList);

		Account_Contact_Role__c acr = [SELECT Id,Account_Role__c,Account_Role__r.Account__c,Contact__c
			FROM Account_Contact_Role__c
			WHERE Contact__c = :contact.Id
			AND Contact_Role_Name__c = 'Trainee'
			AND Functional_Role__c =  'Training' LIMIT 1];

		system.assert(acr.Account_Role__r.Account__c == acc2.Id);

		test.stopTest();
	}
}