src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Airline_designator__c</fullName>
        <description>Field used for the airline designator code e.g. BA</description>
        <label>IATA Designator</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area_of_Operation__c</fullName>
        <label>Area of Operation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>International only</fullName>
                </value>
                <value>
                    <fullName>Domestic only</fullName>
                </value>
                <value>
                    <fullName>International and Domestic</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BSP_CI_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BSP CI Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BSP_FOC_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BSP FOC Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CASS_CI_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CASS CI Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CASS_FOC_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CASS FOC Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_AIMS_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is AIMS Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TradeName__c</fullName>
        <label>Trade Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Service__c</fullName>
        <label>Type of Service</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Scheduled only</fullName>
                </value>
                <value>
                    <fullName>Scheduled and Non-Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <recordTypes>
        <fullName>IATA_Airline_BR</fullName>
        <active>true</active>
        <description>The new record type for ALL Airline Branches with NEW data model - Use this for all Airlines Branches</description>
        <label>Airline Branch</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/trgCopyInfoFromHQToBROnHQUpdateTest.cls
@istest
private class trgCopyInfoFromHQToBROnHQUpdateTest {

    static testMethod void positiveTest() {
        
        IATA_ISO_Country__c myIataIso = new IATA_ISO_Country__c(ISO_Code__c = '12',name = 'moooon');
        insert myIataIso;
        
        
         Account head  = new Account(name = 'HEAD', Is_AIMS_Account__c = false,iatacode__c ='codasd',
                                IATA_ISO_Country__c = myIataIso.id, billingcity = 'Mars'
                                , recordtypeId = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline'),
                                 Area_of_Operation__c = '1', 
                                 Type_of_Service__c = '1', 
                                BSP_CI_Valid__c = true,
                                 BSP_FOC_Valid__c= true, 
                                 CASS_CI_Valid__c= true,
                                CASS_FOC_Valid__c= true,
                                 Airline_designator__c= 'sdd');
        insert head;
         
        Account branch  = new Account(parentID = head.id, name = 'BRANCH', Is_AIMS_Account__c = false,iatacode__c ='codasd'
                                ,IATA_ISO_Country__c = myIataIso.id, billingcity = 'Maasdasdasdasdrs' 
                                , recordtypeId = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline_BR'));
        insert branch;
        
        set<string> fieldValuesToCheck =  new set<String>{   'Area_of_Operation__c',
                                                                'Type_of_Service__c', 
                                                                'BSP_CI_Valid__c', 
                                                                'BSP_FOC_Valid__c', 'CASS_CI_Valid__c', 
                                                                'CASS_FOC_Valid__c',
                                                                'Airline_designator__c', 
                                                            'TradeName__c'};
        
       branch = [SELECT Area_of_Operation__c, Type_of_Service__c, 
                                                     BSP_CI_Valid__c, BSP_FOC_Valid__c, CASS_CI_Valid__c, CASS_FOC_Valid__c,
                                                     Airline_designator__c,TradeName__c
                FROM ACCOUNT 
                WHERE ID =:branch.ID ]; 
       
       for(String field:fieldValuesToCheck ) {
       
        system.assertEquals(branch.get(field),head.get(field));
       
       }
        
        
    }


}