src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AIMS_ID__c</fullName>
        <externalId>true</externalId>
        <label>AIMS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_Code__c</fullName>
        <label>STD Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WebStar_ID__c</fullName>
        <externalId>true</externalId>
        <label>WebStar ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GDP_Agency_Profile_Specialization__c.object
<CustomObject>
    <fields>
        <fullName>AIMS_ID__c</fullName>
        <externalId>true</externalId>
        <label>AIMS ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Main_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Activity</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Destination_Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Destination Specialization</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Main Destination Specialization)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_SpecializatiOCBG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Market_Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Market Specialization</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Main Market Specialization)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Focus_Corporate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Focus - Corporate</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Market Focus - Corporate)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Focus_Leisure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Focus - Leisure</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Market Focus - Leisure)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_GDP_Products_Account_View__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related GDP Products - Account View</label>
        <referenceTo>GDP_Products_Account_View__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Accomodation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales % - Accomodation</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Sales % - Accomodation)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Air__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales % - Air</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Sales % - Air)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Land__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales % - Land</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Sales % - Land)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Sea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales % - Sea</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Sales % - Sea)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales % - Tour</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Sales % - Tour)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Volume__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Volume</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Sales Volume)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_Specializations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Destination_Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Destination Specialization</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Secondary Destination Specialization)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_SpecializatiOCBQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Market_Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Market Specialization</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Secondary Market Specialization)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_SpecializatiOCAw</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tertiary_Destination_Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tertiary Destination Specialization</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Tertiary Destination Specialization)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_SpecializatiOCBa</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tertiary_Market_Specialization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tertiary Market Specialization</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>GDP Agency Profiles and Specializations (Tertiary Market Specialization)</relationshipLabel>
        <relationshipName>GDP_Agency_Profiles_and_SpecializatiOCB6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WebStar_ID__c</fullName>
        <externalId>true</externalId>
        <label>WebStar ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>GDP Agency Profile and Specialization</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>GDP Agency Profile and Specialization Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDP Agency Profiles and Specializations</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <label>GDP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Live</fullName>
        <active>true</active>
        <label>Live</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Phone__c.object
<CustomObject>
    <fields>
        <fullName>AIMS_ID__c</fullName>
        <externalId>true</externalId>
        <label>AIMS ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISD_Code__c</fullName>
        <label>ISD Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Type__c</fullName>
        <label>Phone Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone 1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Phone 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toll Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GDP Phones</relationshipLabel>
        <relationshipName>GDP_Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_GDP_Products_Account_View__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related GDP Products - Account View</label>
        <referenceTo>GDP_Products_Account_View__c</referenceTo>
        <relationshipLabel>GDP Phones</relationshipLabel>
        <relationshipName>GDP_Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>STD_Code__c</fullName>
        <label>STD Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebStar_ID__c</fullName>
        <externalId>true</externalId>
        <label>WebStar ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>GDP Phone</label>
    <nameField>
        <label>Full Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP Phones</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <label>GDP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Live</fullName>
        <active>true</active>
        <label>Live</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Products_Account_View__c.object
<CustomObject>
    <fields>
        <fullName>AIMS_ID__c</fullName>
        <externalId>true</externalId>
        <label>AIMS ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WebStar_ID__c</fullName>
        <externalId>true</externalId>
        <label>WebStar ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>GDP Products - Account View</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP Products - Accounts View</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <description>Used for GDP Live Applications</description>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IEC_Batch_Replication__c.object
<CustomObject>
    <description>Used to get existing or create new batch replicatoins like &quot;GDP Replicates: GDS&quot;, &quot;GDP Replicate: Account&quot;, &quot;GDP Replicate: Territories&quot;</description>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <description>Stores a custom date for last modified date for a batch. If the batch was not existing and is newly created the Last Modified date is set to 1999.1.1. This last modified date can be changed manually</description>
        <label>Last Modified Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>IEC Batch Replication</label>
    <nameField>
        <displayFormat>BN-{0000}</displayFormat>
        <label>Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IEC Batch Replications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IEC_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>IATACODE__c</fullName>
        <label>IATA Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>IEC Error Log</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>IEC Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IEC Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BtchGDPReplicateAgencyProfiles.cls
/**  
  * Description: This class contains batchable class for GDP Replication - GDP Agency Profile and Specialization
  * Author: Samy Saied
  * Version: 1.0
  * History: 
  */
  
global class BtchGDPReplicateAgencyProfiles implements Database.Batchable<sObject>, Database.Stateful {
    global List<IEC_Error_Log__c> logs;

    public String query;
    public Id idRecordTypeGDP;
    public DateTime dtSystemNow;
    private Boolean bErrorFound;
    
    // Initialize error log
    global BtchGDPReplicateAgencyProfiles () {
    	logs = new List<IEC_Error_Log__c>();
    }

    global Database.querylocator start(Database.BatchableContext BC){
		bErrorFound = false;
		return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
		List<GDP_Agency_Profile_Specialization__c> lstAIMS = new List<GDP_Agency_Profile_Specialization__c>();
		List<GDP_Agency_Profile_Specialization__c> lstWebStar = new List<GDP_Agency_Profile_Specialization__c>();
		List<String> lstAIMSIATACode = new List<String>();
		List<String> lstWebStarIATACode = new List<String>();
		List<Id> lstAIMSSFID = new List<Id>();
		List<Id> lstWebStarSFID = new List<Id>();

        for(sObject s : scope) {
			GDP_Agency_Profile_Specialization__c liveRecord = (GDP_Agency_Profile_Specialization__c) s;
			try {
				GDP_Agency_Profile_Specialization__c gdpRecord = new GDP_Agency_Profile_Specialization__c ();
				gdpRecord.RecordTypeId = idRecordTypeGDP;

				/**
				 * Direct Mapping
				 **/
				gdpRecord.Main_Activity__c = liveRecord.Main_Activity__c;
				gdpRecord.Main_Destination_Specialization__c = liveRecord.Main_Destination_Specialization__c;
				gdpRecord.Main_Market_Specialization__c = liveRecord.Main_Market_Specialization__c;
				gdpRecord.Market_Focus_Corporate__c = liveRecord.Market_Focus_Corporate__c;
				gdpRecord.Market_Focus_Leisure__c = liveRecord.Market_Focus_Leisure__c;
				gdpRecord.Sales_Accomodation__c = liveRecord.Sales_Accomodation__c;
				gdpRecord.Sales_Air__c = liveRecord.Sales_Air__c;
				gdpRecord.Sales_Land__c = liveRecord.Sales_Land__c;
				gdpRecord.Sales_Sea__c = liveRecord.Sales_Sea__c;
				gdpRecord.Sales_Tour__c = liveRecord.Sales_Tour__c;
				gdpRecord.Sales_Volume__c = liveRecord.Sales_Volume__c;
				gdpRecord.Secondary_Destination_Specialization__c = liveRecord.Secondary_Destination_Specialization__c;
				gdpRecord.Secondary_Market_Specialization__c = liveRecord.Secondary_Market_Specialization__c;
				gdpRecord.Tertiary_Destination_Specialization__c = liveRecord.Tertiary_Destination_Specialization__c;
				gdpRecord.Tertiary_Market_Specialization__c = liveRecord.Tertiary_Market_Specialization__c;

				if (!String.isBlank(liveRecord.AIMS_ID__c)) {
					gdpRecord.Related_GDP_Products_Account_View__r = new GDP_Products_Account_View__c (AIMS_ID__c = liveRecord.Related_Account__r.AIMS_ID__c + 'GDP');
					gdpRecord.AIMS_ID__c = liveRecord.AIMS_ID__c + 'GDP';
					lstAIMS.add(gdpRecord);
					lstAIMSSFID.add(liveRecord.Id);
					lstAIMSIATACode.add(liveRecord.Related_Account__r.IATACode__c);
				}
				else if (!String.isBlank(liveRecord.WebStar_ID__c)) {
					gdpRecord.Related_GDP_Products_Account_View__r = new GDP_Products_Account_View__c (WebStar_ID__c = liveRecord.Related_Account__r.WebStar_ID__c + 'GDP');
					gdpRecord.WebStar_ID__c = liveRecord.WebStar_ID__c + 'GDP';
					lstWebStar.add(gdpRecord);
					lstWebStarSFID.add(liveRecord.Id);
					lstWebStarIATACode.add(liveRecord.Related_Account__r.IATACode__c);
				}
	    	
	    		if (Test.isRunningTest()) throw new IECApplicationException('Test');
			}
			catch (Exception e) {
				logs.add(IECErrorLogger.logBatchError('Error processing records.', e.getMessage(), 'Live GDP Agency Profile and Specialization ID: ' + liveRecord.Id + ', IATA Code: ' + liveRecord.Related_Account__r.IATACode__c, 'GDP Replicate: GDP Agency Profile and Specialization', e.getStackTraceString()));
			}
		}

		// Process AIMS records
		try {
			if (!lstAIMS.isEmpty()) {
				List<Database.UpsertResult> lstResult = Database.upsert(lstAIMS, GDP_Agency_Profile_Specialization__c.AIMS_ID__c, false);
				List<IEC_Error_Log__c> lstErrors = IECErrorLogger.captureDMLError(lstAIMS, lstResult, 'GDP Replicate: GDP Agency Profile and Specialization', new List<String> {'Live GDP Agency Profile and Specialization ID', 'IATA Code'}, new List<List<String>> {lstAIMSSFID, lstAIMSIATACode});
				if (lstErrors != null && lstErrors.size() > 0)
					logs.addAll(lstErrors);
			}
	    	
	    	if (Test.isRunningTest()) throw new IECApplicationException('Test');
		}
		catch (Exception e) {
			logs.add(IECErrorLogger.logBatchError('Could not upsert AIMS records.', e.getMessage(), null, 'GDP Replicate: GDP Agency Profile and Specialization', e.getStackTraceString()));
		}

		// Process WebStar records
		try {
			if (!lstWebStar.isEmpty()) {
				List<Database.UpsertResult> lstResult = Database.upsert(lstWebStar, GDP_Agency_Profile_Specialization__c.WebStar_ID__c, false);
				
				List<IEC_Error_Log__c> lstErrors = IECErrorLogger.captureDMLError(lstWebStar, lstResult, 'GDP Replicate: GDP Agency Profile and Specialization', new List<String> {'Live GDP Agency Profile and Specialization ID', 'IATA Code'}, new List<List<String>> {lstWebStarSFID, lstWebStarIATACode});
				if (lstErrors != null && lstErrors.size() > 0)
					logs.addAll(lstErrors);
			}
	    	
	    	if (Test.isRunningTest()) throw new IECApplicationException('Test');
		}
		catch (Exception e) {
			logs.add(IECErrorLogger.logBatchError('Could not upsert WebStar records.', e.getMessage(), null, 'GDP Replicate: GDP Agency Profile and Specialization', e.getStackTraceString()));
		}
    	
    	// Insert error logs if applicable
    	if (!logs.isEmpty()) {
    		bErrorFound = true;
    		insert logs;
    		logs.clear();
    	}
    }

    global void finish(Database.BatchableContext BC) {
	    try {
	    	// Update the last modified date for the batch
	    	IECUtil.SetBatchReplication('GDP Replicate: GDP Agency Profile and Specialization', dtSystemNow);
	    	
	    	if (Test.isRunningTest()) throw new IECApplicationException('Test');
		}
		catch (Exception e) {
			logs.add(IECErrorLogger.logBatchError('Could not set Batch Replication last modified date.', e.getMessage(), null, 'GDP Replicate: GDP Agency Profile and Specialization', e.getStackTraceString()));
		}
	    
	    try {
	    	/**
	    	 * Call next batch step in the process
	    	 **/
			IEC_Batch_Replication__c btchRepAcc = IECUtil.GetBatchReplication('GDP Replicate: Account');
			IEC_Batch_Replication__c btchRep = IECUtil.GetBatchReplication('GDP Replicate: GDP Phone');
			
			// Only run the job if the schedule interface is activated through the custom settings
			if (IECConstants.GDPReplication_ScheduleActive) {
				BtchGDPReplicatePhone btchProc = new BtchGDPReplicatePhone();
				btchProc.idRecordTypeGDP = IECUtil.GetRecordTypeId('GDP_Phone__c', 'GDP');
				btchProc.dtSystemNow = btchRepAcc.Last_Modified_Date__c;
				btchProc.query =
					'SELECT AIMS_ID__c, WebStar_ID__c, Name, ISD_Code__c, Number__c, Phone_Type__c, STD_Code__c'
					+ '		, Related_Account__r.AIMS_ID__c, Related_Account__r.WebStar_ID__c, Related_Account__r.IATACode__c'
					+ '	FROM GDP_Phone__c'
					+ '	WHERE LastModifiedDate >= ' + btchRep.Last_Modified_Date__c.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'')
					+ '		AND LastModifiedDate < ' + btchRepAcc.Last_Modified_Date__c.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'')
					+ '		AND (AIMS_ID__c != null OR Webstar_ID__c != null)'
					+ '		AND RecordTypeId = \'' + IECUtil.GetRecordTypeId('GDP_Phone__c', 'Live') + '\''
					+ '     AND Related_Account__c IN (SELECT Id FROM Account WHERE Location_Class__c IN (\'C\',\'D\',\'E\',\'F\',\'G\',\'K\',\'M\',\'N\',\'O\',\'P\',\'S\',\'T\',\'V\',\'X\') AND Main_Accreditation_Organization__c IN (\'IATA\',\'IATAN\',\'DOM\'))';                   

				System.debug('SSS: SOQL Query: ' + btchProc.query);
	
				Database.executeBatch(btchProc);
			}
	    	
	    	if (Test.isRunningTest()) throw new IECApplicationException('Test');
		}
		catch (Exception e) {
			logs.add(IECErrorLogger.logBatchError('Could not start next batch process.', e.getMessage(), null, 'GDP Replicate: GDP Agency Profile and Specialization', e.getStackTraceString()));
		}
    	
    	// Insert error logs if applicable
    	if (!logs.isEmpty()) {
    		bErrorFound = true;
    		insert logs;
    	}
    	
    	// Send email notification when errors are found
    	if (bErrorFound) {
    		if (!IECEmailUtility.notificationExistsToday(IECConstants.GDPReplication_SystemAdminEmail, IECConstants.Email_Template_GDPError)) {
    			IECEmailUtility.sendEmail(null, IECConstants.GDPReplication_SystemAdminEmail, IECConstants.Email_Template_GDPError, null, null, null, null, null, null, null);
    		}
    	}
	}
}