src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ANG_Accreditation_Model__c</fullName>
        <description>To store Accreditation Model selected by the agency.</description>
        <label>Accreditation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Accreditation_Models</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ANG_HE_CashCondition__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cash Condition HE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ANG_HE_RiskStatus__c</fullName>
        <label>Risk Status HE</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Risk_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financial_Review_Result__c</fullName>
        <description>Used to copy the last one from the case IATA FINANCIAL REVIEW IFAP</description>
        <label>Last Financial Review Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>Map the objects AGT from AIMS. This is a value equal to category.</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remittance_frequency__c</fullName>
        <label>Remittance frequency</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>M</fullName>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Fortnightly</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>Every 10 days</label>
                </value>
                <value>
                    <fullName>W</fullName>
                    <label>4 times per month</label>
                </value>
                <value>
                    <fullName>V</fullName>
                    <label>Weekly</label>
                </value>
                <value>
                    <fullName>S</fullName>
                    <label>Every 5 days</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Twice a week</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>Every 3 days</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Daily</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accommodation</fullName>
                </value>
                <value>
                    <fullName>Airline</fullName>
                </value>
                <value>
                    <fullName>Airline Supplier</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Equipment Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Cargo Agent</fullName>
                    <label>Freight Forwarder</label>
                </value>
                <value>
                    <fullName>General Public</fullName>
                </value>
                <value>
                    <fullName>General Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Governmental Institution</fullName>
                </value>
                <value>
                    <fullName>Holding Company</fullName>
                </value>
                <value>
                    <fullName>IATA</fullName>
                </value>
                <value>
                    <fullName>Infrastructure Partner</fullName>
                </value>
                <value>
                    <fullName>Internal Use</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Non-Airline Transportation</fullName>
                </value>
                <value>
                    <fullName>Recreational</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IATA_Agency</fullName>
        <active>true</active>
        <description>The new record type for ALL Agencies with NEW data model - Use this for all Agencies</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ANG_Agency_Risk_Calculation__c.object
<CustomObject>
    <fields>
        <fullName>ANG_Accreditation_Model__c</fullName>
        <label>Accreditation Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Accreditation_Models</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ANG_Financial_Review_Result__c</fullName>
        <label>Financial Review Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Financial_Review_Result</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ANG_Risk_History_Assessment__c</fullName>
        <label>Risk History Assessment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_HE_RiskHistoryAssessment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ANG_Risk_History__c</fullName>
        <label>Risk History</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Risk_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agency Risk Calculation</label>
    <nameField>
        <displayFormat>ARC-{00000000}</displayFormat>
        <label>Agency Risk Calculation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Risk Calculations</pluralLabel>
    <recordTypes>
        <fullName>Risk_Status_Assessment</fullName>
        <active>true</active>
        <label>Risk Status Assessment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ANG_Risk_Event_Type__c.object
<CustomObject>
    <fields>
        <fullName>ANG_Agency_Risk_Calculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Risk Calculation</label>
        <referenceTo>ANG_Agency_Risk_Calculation__c</referenceTo>
        <relationshipLabel>Risk Event Types</relationshipLabel>
        <relationshipName>Risk_Event_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Risk Event Type</label>
    <nameField>
        <label>Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Event Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/ANG_Accreditation_Models.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Cashless</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Multicountry</fullName>
    </customValue>
    <customValue>
        <fullName>CNS Endorsement</fullName>
    </customValue>
    <masterLabel>Accreditation Models</masterLabel>
</GlobalValueSet>

src/globalValueSets/ANG_Financial_Review_Result.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Satisfactory</fullName>
    </customValue>
    <customValue>
        <fullName>Satisfactory - New Financial Security</fullName>
    </customValue>
    <customValue>
        <fullName>Satisfactory - Update Financial Security</fullName>
    </customValue>
    <customValue>
        <fullName>Satisfactory - Release Financial Security</fullName>
    </customValue>
    <customValue>
        <fullName>Satisfactory - No Action</fullName>
    </customValue>
    <customValue>
        <fullName>Unsatisfactory - New Financial Security</fullName>
    </customValue>
    <customValue>
        <fullName>Unsatisfactory - Update Financial Security</fullName>
    </customValue>
    <customValue>
        <fullName>Unsatisfactory - Release Financial Security</fullName>
    </customValue>
    <customValue>
        <fullName>Unsatisfactory - No action</fullName>
    </customValue>
    <masterLabel>ANG Financial Review Result</masterLabel>
</GlobalValueSet>

src/globalValueSets/ANG_HE_RiskHistoryAssessment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <masterLabel>Risk History Assessment Values</masterLabel>
</GlobalValueSet>

src/globalValueSets/ANG_Risk_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <masterLabel>Risk Status</masterLabel>
</GlobalValueSet>

src/classes/ANG_RiskForecastPropertiesControllerTest.cls
@isTest
private class ANG_RiskForecastPropertiesControllerTest {
	

	@testSetup static void setup(){

		Id sIDRALiteRTId = RecordTypeSingleton.getInstance().RtIDsPerDeveloperNamePerObj.get('Case').get('SIDRA_Lite');

		IATA_ISO_Country__c ctry = new IATA_ISO_Country__c (Name='US',ISO_Code__c='US')  ;
        insert ctry ;

        Id accountAgencyRT = AMS_Utils.getId('Account', 'IATA_Agency');
        Account a1 = new Account(Remittance_frequency__c = 'Every 5 days' , ANG_Accreditation_Model__c = 'Cash', Financial_Review_Result__c = 'Satisfactory - No Action' ,ANG_HE_CashCondition__c = false , ANG_HE_RiskStatus__c = 'B' , IATA_ISO_Country__c = ctry.id, RecordTypeId = accountAgencyRT, IATACode__c='1234561',Location_Type__c='HE',Name='Test1 Agency OK',Short_Name__c='Test1 Agency', Sector__c = 'Travel Agent', Location_Class__c = 'P', Status__c = 'Approved');
        insert a1;
        
        Case sidraLiteCase = new Case();
        sidraLiteCase.AccountId = a1.Id;
        sidraLiteCase.recordtypeId = sIDRALiteRTId;

        insert sidraLiteCase;



		list<ANG_Agency_Risk_Calculation__c> adjustmentList = new list<ANG_Agency_Risk_Calculation__c>();

		Id risk_Status_AssessmentRTId =RecordTypeSingleton.getInstance().RtIDsPerDeveloperNamePerObj.get('ANG_Agency_Risk_Calculation__c').get('Risk_Status_Assessment');

		ANG_Agency_Risk_Calculation__c adj1= new ANG_Agency_Risk_Calculation__c(
			ANG_Financial_Review_Result__c = 'Satisfactory' ,
			ANG_Risk_History__c = 'B',
			ANG_Risk_History_Assessment__c = 'Failed',
			recordtypeId=risk_Status_AssessmentRTId		
			);
		adjustmentList.add(adj1);

		ANG_Agency_Risk_Calculation__c adj2= new ANG_Agency_Risk_Calculation__c(
			ANG_Financial_Review_Result__c = 'Unsatisfactory - New Financial Security' ,
			ANG_Risk_History__c = 'C',
			ANG_Risk_History_Assessment__c = 'Failed',
			recordtypeId=risk_Status_AssessmentRTId			
			);
		adjustmentList.add(adj2);

		ANG_Agency_Risk_Calculation__c adj3= new ANG_Agency_Risk_Calculation__c(
			ANG_Financial_Review_Result__c = 'Satisfactory - No Action' ,
			ANG_Risk_History__c = 'C',
			ANG_Risk_History_Assessment__c = 'Passed',
			recordtypeId=risk_Status_AssessmentRTId			
			);

		adjustmentList.add(adj3);

		insert adjustmentList;
        
       		ANG_Risk_Event_Type__c ret = new ANG_Risk_Event_Type__c(
			name='Risk Event Test',
			ANG_Description__c='Risk Event Test',
			ANG_Expiration__c=24,
			ANG_Risk_ID__c='testRiskId',
			Limit_Cash_conditions__c = true,
			ANG_Agency_Risk_Calculation__c = adj3.Id

                
		);
		
		insert ret;

        List<ANG_Agency_Risk_Event__c> listAREs = new list<ANG_Agency_Risk_Event__c>();

		ANG_Agency_Risk_Event__c are1= new ANG_Agency_Risk_Event__c(
			ANG_AccountId__c=a1.id,
			ANG_Risk_Type__c=ret.id,
			ANG_Issued_Date__c =System.today(),
			ANG_Event_Status__c='Inactive'
		);

		listAREs.add(are1);

		insert listAREs;

	}



	@isTest static void test_method_one() {

		PageReference pageRef = Page.ANG_RiskForecastPropertiesPage;

 		Test.setCurrentPageReference(pageRef);
 		
		Case sidraLiteCase = [Select Id from Case where RecordType.developerName='SIDRA_Lite'];

		ApexPages.StandardController sc = new ApexPages.StandardController(sidraLiteCase);

 		ANG_RiskForecastPropertiesController pgController = new ANG_RiskForecastPropertiesController(sc);

 		pgController.riskOpt = 'testRiskId';

 		pgController.getriskOption();

 		pgController.closePopup();

 		pgController.redirectPopup();

 		pgController.getcanExecuteForecast();

 		pgController.showPopup();

 		System.assertEquals('C',pgController.newRiskStatus);
 		System.assertEquals(true,pgController.newCashCondition);

 	}
	
}