src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Airline_designator__c</fullName>
        <description>Field used for the airline designator code e.g. BA</description>
        <label>IATA Designator</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ICCS_Membership_Status__c</fullName>
        <label>ICCS Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_status__c</fullName>
        <description>Field used to specify the membership status</description>
        <label>IATA Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IATA member</fullName>
                </value>
                <value>
                    <fullName>Non-IATA member</fullName>
                </value>
                <value>
                    <fullName>Ex-IATA Member</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>China &amp; North Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East &amp; North Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Russia &amp; CIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Airline_Designator__c</fullName>
        <formula>Account.Airline_designator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Airline Designator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CEO_CFO__c</fullName>
        <label>CEO/CFO/COO/CCO/CIO</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>COO</fullName>
                </value>
                <value>
                    <fullName>CCO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_Function__c</fullName>
        <label>Job Function</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aeropolitical</fullName>
                </value>
                <value>
                    <fullName>Aeropolitico</fullName>
                    <isActive>false</isActive>
                    <label>Aeropolitico</label>
                </value>
                <value>
                    <fullName>Aéropolitique</fullName>
                    <isActive>false</isActive>
                    <label>Aéropolitique</label>
                </value>
                <value>
                    <fullName>Altro</fullName>
                    <isActive>false</isActive>
                    <label>Altro</label>
                </value>
                <value>
                    <fullName>An ninh&amp; Cơ sở vật chất</fullName>
                    <isActive>false</isActive>
                    <label>An ninh&amp; Cơ sở vật chất</label>
                </value>
                <value>
                    <fullName>An toàn</fullName>
                    <isActive>false</isActive>
                    <label>An toàn</label>
                </value>
                <value>
                    <fullName>Autre</fullName>
                    <isActive>false</isActive>
                    <label>Autre</label>
                </value>
                <value>
                    <fullName>Betrieb</fullName>
                    <isActive>false</isActive>
                    <label>Betrieb</label>
                </value>
                <value>
                    <fullName>Cargo</fullName>
                </value>
                <value>
                    <fullName>Cargo,Marketing&amp;Sales</fullName>
                    <isActive>false</isActive>
                    <label>Cargo,Marketing&amp;Sales</label>
                </value>
                <value>
                    <fullName>Chính trị hàng không</fullName>
                    <isActive>false</isActive>
                    <label>Chính trị hàng không</label>
                </value>
                <value>
                    <fullName>Comercial</fullName>
                    <isActive>false</isActive>
                    <label>Comercial</label>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Commerciale</fullName>
                    <isActive>false</isActive>
                    <label>Commerciale</label>
                </value>
                <value>
                    <fullName>Corporate Planning</fullName>
                    <isActive>false</isActive>
                    <label>Corporate Planning</label>
                </value>
                <value>
                    <fullName>Customer &amp; Service</fullName>
                    <isActive>false</isActive>
                    <label>Customer &amp; Service</label>
                </value>
                <value>
                    <fullName>Enviornment</fullName>
                    <isActive>false</isActive>
                    <label>Enviornment</label>
                </value>
                <value>
                    <fullName>Environement</fullName>
                    <isActive>false</isActive>
                    <label>Environement</label>
                </value>
                <value>
                    <fullName>Environment</fullName>
                </value>
                <value>
                    <fullName>Environment,Human Resources</fullName>
                    <isActive>false</isActive>
                    <label>Environment,Human Resources</label>
                </value>
                <value>
                    <fullName>Environnement</fullName>
                    <isActive>false</isActive>
                    <label>Environnement</label>
                </value>
                <value>
                    <fullName>Exploitation</fullName>
                    <isActive>false</isActive>
                    <label>Exploitation</label>
                </value>
                <value>
                    <fullName>Finanças</fullName>
                    <isActive>false</isActive>
                    <label>Finanças</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance,other</fullName>
                    <isActive>false</isActive>
                    <label>Finance,other</label>
                </value>
                <value>
                    <fullName>Financement</fullName>
                    <isActive>false</isActive>
                    <label>Financement</label>
                </value>
                <value>
                    <fullName>Finanzas</fullName>
                    <isActive>false</isActive>
                    <label>Finanzas</label>
                </value>
                <value>
                    <fullName>Finanze</fullName>
                    <isActive>false</isActive>
                    <label>Finanze</label>
                </value>
                <value>
                    <fullName>Finanzen</fullName>
                    <isActive>false</isActive>
                    <label>Finanzen</label>
                </value>
                <value>
                    <fullName>Flight Operation</fullName>
                    <isActive>false</isActive>
                    <label>Flight Operation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard_Contact</fullName>
        <active>true</active>
        <description>The new record type for ALL contacts with NEW data model - Use this for all contacts</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Africa &amp; Middle East</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Asia &amp; Pacific</fullName>
                </value>
                <value>
                    <fullName>China &amp; North Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ImportantContactsControllerTest.cls
@isTest
private class ImportantContactsControllerTest {
    static testMethod void test() {

        // CREATE TEST DATA

        // Create a new ISO Country
        IATA_ISO_Country__c country_fr = new IATA_ISO_Country__c(Name = 'France', ISO_Code__c = 'FR', Region__c = 'Europe');
        insert country_fr;

        // Create an Airline HQ account
        Id AirlineHQ_RT_Id = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline');
        Account acct_hq = new Account(Name = 'Qatar Airways', Airline_designator__c = 'QR', ICCS_Membership_Status__c = 'Member', Industry='Airline', Type='Passenger',
                                RecordTypeId = AirlineHQ_RT_Id, IATA_ISO_Country__c = country_fr.Id, Membership_status__c = 'Aeropolitical');
        insert acct_hq;

        Id ContactStd_RT_Id = RecordTypeSingleton.getInstance().getRecordTypeId('Contact', 'Standard_Contact');
        Contact c1 = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'test@test.com', AccountId = acct_hq.Id, RecordTypeId = ContactStd_RT_Id);
        insert c1;

        Contact c2 = new Contact(FirstName = 'Another', LastName = 'Contact', Email = 'test2@test.com', Title = 'CEO', AccountId = acct_hq.Id, RecordTypeId = ContactStd_RT_Id, CEO_CFO__c = 'CEO',
                                Membership_Function__c = 'Aeropolitical');
        insert c2;

        test.startTest();
        	// instantiate the important contacts page controller
	        ApexPages.StandardController std = new ApexPages.StandardController(acct_hq);
	        ImportantContactsController controller = new ImportantContactsController(std);

	        // assess that the important contacts list only contains one of the 2 contacts above
	        system.assertEquals(1, controller.lstImportantContacts.size());

        test.stopTest();
    }
}