src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email at Account level</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Top_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Top Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invitation__c.object
<CustomObject>
    <description>Store information send by Fred Plus in verifier process. It will be used to prefilled registration form</description>
    <label>Invitation</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invitation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>Account Id send by FRED application</description>
        <label>AccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Fax__c</fullName>
        <label>Business Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Business_Phone__c</fullName>
        <label>Business Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email address for the Person being invited.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mr.</fullName>
                </value>
                <value>
                    <fullName>Mrs:</fullName>
                </value>
                <value>
                    <fullName>Ms</fullName>
                </value>
                <value>
                    <fullName>Ms.</fullName>
                </value>
                <value>
                    <fullName>Mrs.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/Invite_User_CTRL.cls
public without sharing class Invite_User_CTRL {
    
    @AuraEnabled
    public static string sendInvitation(string contactStr, string invitationStr) {
        Invitation__c invitation = null;
        Contact contact = null;
        try{
            contact = (Contact)JSON.deserialize(contactStr, Contact.Class);
        } catch (Exception ex){}
        try{
            invitation = (Invitation__c)JSON.deserialize(invitationStr, Invitation__c.Class);
        } catch (Exception ex){}
        
        try{
            if(contact == null && invitation != null){
                insert invitation;
                invitation = [SELECT Id, Email__c FROM Invitation__c WHERE Id =: invitation.Id];
                return sendEmail(true, invitation);
            } else if (contact != null) {
           		return sendEmail(false, contact);
            }
            return invitationStr;
            } catch(Exception e) {
    			return 'err:'+e.getMessage();
		}
    }
        
    private static string getEmailFromSObject(SObject obj){
        string objName = ((SObject)obj).getSObjectType().getDescribe().getName();
        switch on objName.toUpperCase() {
       when 'CONTACT'{
           return (String) obj.get('Email');
       }
       when 'INVITATION__C' {
            return (String) obj.get('Email__c');
       }
       when else {
           return '';
       }
        }
    }
    private static string sendEmail(boolean newUser, SObject obj){
        string linkSuffix = '';
        string emailTemplate = '';
        
        if (newUser){
            emailTemplate = 'Invite_user_new';
            linkSuffix = '/login/SelfRegister?serviceName=GADM&token='+obj.get('Id');
        } else {
            emailTemplate = 'Invite_user_already_exists';
            linkSuffix = '/login/';
        }
        EmailTemplate et = [SELECT Id, Name, Subject, Body FROM EmailTemplate WHERE DeveloperName =: emailTemplate];
        Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(et.Id, UserInfo.getUserId(), obj.Id);
        string link = OneIdUtils.getSiteCompleteUrl(OneIdUtils.Mode.IDENTITY) + linkSuffix;

		mail.setToAddresses(new List<string>{'pavel.pop@b-i.com'});
	    mail.setSaveAsActivity(false);
        string body = mail.getHtmlBody();
        mail.setHtmlBody(body.replace('*link*', link) + getEmailFromSObject(obj));
        mail.setUseSignature(false);
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        allmsg.add(mail);
        system.debug(mail);
        try {
            Messaging.sendEmail(allmsg,false);
            return 'sent';
        } catch (Exception e) {
            System.debug(e.getMessage());
            return e.getMessage();
        }
    }
    @AuraEnabled 
    public static List<Account> getUserAccounts(){
        Id userId = UserInfo.getUserId();
        return Contact_Roles_Helper.getUserAccounts(userId);
    }
    @AuraEnabled
    public static List<String> getContactJobFunctionValues() {
        return OneId_RegistrationProcessController.getContactJobFunctionValues();
    }
    @AuraEnabled
    public static Map<String,String> getContactLabels() {
        return OneId_RegistrationProcessController.getContactLabels();
    }
    @AuraEnabled
    public static UserInformationWrapper getUserInformationFromEmail(String email, String serviceName){
        List<Contact> existingContacts = OneId_RegistrationProcessController.returnExistingContact(email);
        
        boolean emailAddressAvailable = OneId_RegistrationProcessController.checkIsUsernameIsAvailableInGlobalSalesforce(email, existingContacts);
        boolean contactExists = existingContacts.size() > 0;
        boolean contactOrUserExists = !emailAddressAvailable || contactExists;
        
        UserInformationWrapper wrapper = new UserInformationWrapper(
        	contactExists ? existingContacts[0] : null, new Invitation__c());
        
        wrapper.showNotifyButton = !(!emailAddressAvailable && !contactExists);
              
        wrapper.createNewInvitation = !contactOrUserExists;
        if(emailAddressAvailable && contactExists){
            Contact con = existingContacts[0];
            Account acc = [SELECT Id, Top_Parent__c	FROM Account WHERE Id =: con.AccountId][0];
        	Invitation__c invitation = new Invitation__c();
            invitation.AccountId__c = acc.Top_Parent__c != null ? acc.Top_Parent__c : con.AccountId;
            invitation.Business_Fax__c = con.Fax;
            invitation.Business_Phone__c = con.Phone;
            invitation.Email__c = con.Email;
            invitation.First_Name__c = con.FirstName;
            invitation.Last_Name__c = con.LastName;
            
            invitation.Job_Title__c = con.Title;
            invitation.Mobile_Phone__c = con.MobilePhone;
            invitation.Salutation__c = con.Salutation;
            wrapper.invitation = invitation;    
        	wrapper.contact = null;
        }
        
        if(!emailAddressAvailable && !contactExists){
            //internal user
            wrapper.invitation = null;    
        	wrapper.contact = null;
        }
         system.debug(contactOrUserExists);
        system.debug(emailAddressAvailable);
        system.debug(wrapper);
        return wrapper;
}
    public class UserInformationWrapper{
        @AuraEnabled
        public boolean createNewInvitation{get;set;}
        @AuraEnabled
        public boolean showNotifyButton{get;set;}
        @AuraEnabled
        public Invitation__c invitation {get;set;}
        @AuraEnabled
        public Contact contact {get;set;}
        public UserInformationWrapper(Contact contact, Invitation__c invitation){
            this.contact = contact;
            this.invitation = invitation;
        }
    }
}