src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Airline_Prefix__c</fullName>
        <label>Airline Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_designator__c</fullName>
        <description>Field used for the airline designator code e.g. BA</description>
        <label>IATA Designator</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BIETA_Bilateral_Date__c</fullName>
        <label>BIETA Bilateral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIETA_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BIETA Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BIETA_One_way_Electronic_Issuing_Airline__c</fullName>
        <label>BIETA One way Electronic Issuing Airline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIETA_One_way_Electronic_Participating__c</fullName>
        <label>BIETA One way Electronic Participating</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIETA_One_way_Intermodal_Issuing_Airline__c</fullName>
        <label>BIETA One way Intermodal Issuing Airline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIETA_One_way_Intermodal_Participating__c</fullName>
        <label>BIETA One way Intermodal Participating</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Company_Logo__c</fullName>
        <formula>IMAGE(Logo_File_ID__c,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Logo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Cargo__c</fullName>
        <label>MITA IATA Interline Cargo</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Passenger__c</fullName>
        <label>MITA IATA Interline Passenger</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MITA Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MITA_One_way_Pass_Issuing_Airline__c</fullName>
        <label>MITA One way Pass. Issuing Airline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_One_way_Pass_Participating__c</fullName>
        <label>MITA One way Pass. Participating</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_status__c</fullName>
        <description>Field used to specify the membership status</description>
        <label>IATA Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IATA member</fullName>
                </value>
                <value>
                    <fullName>Non-IATA member</fullName>
                </value>
                <value>
                    <fullName>Ex-IATA Member</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Top_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Top Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Airline_Designator__c</fullName>
        <formula>Account.Airline_designator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Airline Designator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MITA_Contact_Type__c</fullName>
        <label>MITA Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Interline Passenger Agreement Manager</fullName>
                </value>
                <value>
                    <fullName>Passenger Protection Agreement</fullName>
                </value>
                <value>
                    <fullName>Interline Airline Generic Contact</fullName>
                </value>
                <value>
                    <fullName>Interline Cargo Agreement Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MITA_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MITA Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ContactId__c</fullName>
        <formula>Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Terms_Acceptance_Date__c</fullName>
        <description>When the user accepted terms and conditions</description>
        <label>Terms Acceptance Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Terms_Acceptance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if terms and conditions have been accepted</description>
        <label>Terms Acceptance</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <fields>
        <fullName>Application_icon_URL__c</fullName>
        <defaultValue>&quot;http://greencyprus.net/wp-content/uploads/image/question%20mark.jpg&quot;</defaultValue>
        <description>URL to the Application icon</description>
        <label>Application icon URL</label>
        <type>Url</type>
    </fields>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IA_HomeController.cls
public with sharing class IA_HomeController {
	public static final String APP_NAME = 'Interline agreements';

	public list<String> listMessages {get; set;}
	public Account airlineHQ {get;set;}
	//5 sections available: CONTACTS, MEMOS, ALL, REQ and NEW
	public String showSection {get;set;}

	public String getMapAgreementsByNameJson() {
		return Json.serialize(IA_util.MAP_AGREEMENTS_BY_NAME);
	}

	private User currentUser;

	public IA_HomeController(){
		this.listMessages = new list<String>();
		this.showSection = 'ALL';
		Id userid = UserInfo.getUserId();

		this.currentUser = [
			SELECT Id, UserName, Profile.Name, ContactId, Contact.AccountId, Contact.MITA_Contact__c, Contact.MITA_Contact_Type__c,
				Contact.Account.Name,Contact.Account.ParentId, Contact.Account.Top_Parent__c
			FROM User WHERE ID = :userId];

		// find the related Airline Headquarter
		Id airlineHQId = this.currentUser.Contact.Account.Top_Parent__c ==null? this.currentUser.Contact.AccountId: this.currentUser.Contact.Account.Top_Parent__c;

		List<Account> accs = [
			SELECT Name, Airline_Prefix__c, Airline_designator__c, IATAcode__c, Membership_status__c, MITA_Member__c, BIETA_Member__c, Company_Logo__c,
			MITA_IATA_Interline_Passenger__c, MITA_IATA_Interline_Cargo__c, MITA_One_way_Pass_Issuing_Airline__c, MITA_One_way_Pass_Participating__c,
			BIETA_Bilateral_Date__c, BIETA_One_way_Electronic_Issuing_Airline__c, BIETA_One_way_Electronic_Participating__c, BIETA_One_way_Intermodal_Issuing_Airline__c,
			BIETA_One_way_Intermodal_Participating__c
			FROM Account
			WHERE Id = :airlineHQId];
		
		if(accs.size()!=1) {
			listMessages.add(Label.ISSP_cannot_open_the_selected_account);
		}else{
			this.airlineHQ = accs[0];
		}
	}

	/**
		Start actions: check rights
	**/
	public PageReference initActions() {
		try {
			String strId = this.currentUser.ContactId;
			Portal_Application_Right__c appRight = [
				Select Id, Terms_Acceptance__c, Terms_Acceptance_Date__c, Right__c
				From Portal_Application_Right__c
				Where ContactId__c = :strId.left(15)
				And Portal_Application__r.Name = :APP_NAME
			];
			// If user has no rights to access to Account statements app then is redirected to Home
			if (appRight.Right__c=='Access Granted') {
				return null;
			}

		} catch(Exception e) {
			//if error happens return to home page
		}
		// default action, return to home page (if no Access granted was found)
		Pagereference pageref = new PageReference(Label.CSP_PortalBaseURL + Label.CSP_PortalPath);
		pageref.setRedirect(true);
		return pageref;
	}

	/**
	 * Get the logo image from the Portal application record
	 */
	public String appLogoURL {
		get {
			if (appLogoURL==null) {
				appLogoURL = [SELECT Id, Application_icon_URL__c FROM Portal_Applications__c WHERE Name = :APP_NAME].Application_icon_URL__c;
			}
			return appLogoURL;
		}
		private set;
	}

	public Boolean getWithdrawPermission() {
		return true;
	}

	public Boolean getApprovePermission() {
		return true;
	}

	public Boolean getRequestPermission() {
		return true;
	}

	public Boolean getEditContactsPermission() {
		return true;
	} 
}