src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Check_Digit__c</fullName>
        <label>Check Digit</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Accreditation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>Accreditation</relationshipLabel>
        <relationshipName>Accreditation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accreditation</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Accreditation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accreditation</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/GDP_Products_Account_View__c.object
<CustomObject>
    <fields>
        <fullName>Check_Digit__c</fullName>
        <label>Check Digit</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Accreditation_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to GDP Accreditation</inlineHelpText>
        <label>Related Accreditation</label>
        <referenceTo>Accreditation__c</referenceTo>
        <relationshipLabel>GDP Products - Accounts View</relationshipLabel>
        <relationshipName>GDP_Products_Accounts_View</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GDP Products - Account View</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP Products - Accounts View</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <description>Used for GDP Live Applications</description>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Reference_Table__c.object
<CustomObject>
    <label>GDP Reference Table</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP References Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IEC_Application_Filter__c.object
<CustomObject>
    <description>Used to save advanced search filters by customers so they can reuse them (for now only for GAD)</description>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related contact</description>
        <inlineHelpText>The related contact</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>IEC Application Filters</relationshipLabel>
        <relationshipName>IEC_Application_Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IEC Application Filter</label>
    <nameField>
        <displayFormat>IEC-AF-{00000}</displayFormat>
        <label>IEC Application Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IEC Application Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IEC_Subscription_History__c.object
<CustomObject>
    <description>Object that tracks different aspects of a subscription purchase for the IATA eCommerce project (e.g. subscription, invoice, payment method, T&amp;C accepted, etc)</description>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact that made the purchase</description>
        <inlineHelpText>Contact that made the purchase</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>IEC Subscriptions History</relationshipLabel>
        <relationshipName>IEC_Subscriptions_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IEC Subscription History</label>
    <nameField>
        <displayFormat>SH-{000000000}</displayFormat>
        <label>IEC Subscription History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IEC Subscriptions History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Category__c.object
<CustomObject>
    <description>Contains the main product categories and their related information to be displayed on the product viewer page, and some extra configurations used for browsing products and rate plans.</description>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Information__c.object
<CustomObject>
    <description>Represents the Product Information in Salesforce, this Product level is configurable and linked to a parent (Product Category) and can have multiple Rate Plan information as Children</description>
    <fields>
        <fullName>Product_Audience__c</fullName>
        <label>Product Audience</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>IATA Employee</fullName>
                </value>
                <value>
                    <fullName>Strategic Member</fullName>
                </value>
                <value>
                    <fullName>Member Airline</fullName>
                </value>
                <value>
                    <fullName>Non Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Information</label>
    <nameField>
        <label>Product Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan_Information__c.object
<CustomObject>
    <description>Contains the main Rate Plans information to be displayed on the product browsing page UI</description>
    <fields>
        <fullName>Display_As_Monthly_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display As Monthly Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Usage_Qty__c</fullName>
        <description>Usage assigned to the subscription once purchased (for usage-base products). 0 or null for unlimited.</description>
        <inlineHelpText>Usage assigned to the subscription once purchased (for usage-base products). 0 or null for unlimited.</inlineHelpText>
        <label>Subscription Usage Qty</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Information</label>
    <nameField>
        <label>Product Rate Plan Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Related_Contact__c.object
<CustomObject>
    <description>Junction object between the Contact and Account objects that allows for a Contact to be linked to multiple accounts.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Contact</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Related Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Terms_and_Conditions__c.object
<CustomObject>
    <description>This object is used to store Attachments holding the terms and conditions on IEC Checkout page</description>
    <fields>
        <fullName>Product_Information__c</fullName>
        <label>Related Product Information</label>
        <referenceTo>Product_Information__c</referenceTo>
        <relationshipLabel>Terms and Conditions</relationshipLabel>
        <relationshipName>IEC_Terms_and_Conditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the T&amp;Cs. Can only be modified when it&apos;s Draft.</description>
        <inlineHelpText>Status of the T&amp;Cs. Can only be modified when it&apos;s Draft.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IEC Terms and Conditions</label>
    <nameField>
        <label>Terms and Conditions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IEC Terms and Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fixingUpdate/objects/zqu__ZProduct__c.object
<CustomObject>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/vfIECGADResult_tst.cls
/**
 * This class contains unit tests for validating the behavior of class vfIECGADResult
 */
@isTest
public with sharing class vfIECGADResult_tst {

	private static Product_Category__c oProductCategory;
	private static Product_Information__c oProductInfo;
	private static Product_Rate_Plan_Information__c oProductRatePlanInfo;
	private static Terms_and_Conditions__c oTC;
	private static zqu__ZProduct__c oProduct;
	private static zqu__ProductRatePlan__c oProductRatePlan;
	private static Zuora__Subscription__c oSubscription;
	private static Zuora__SubscriptionProductCharge__c oSubscriptionCharge;
	private static IEC_Subscription_History__c oSubscriptionHist;
	private static Account oAccount;
	private static Account oAgencyAccount;
	private static Zuora__CustomerAccount__c oBillingAccount;
	private static Contact oContact;
	private static Date dtSubscriptionEnddate;
	
	private static GDP_Reference_Table__c oRefAgencyStatus;
	private static GDP_Reference_Table__c oRefAgencyStatusTerminated;
	private static GDP_Reference_Table__c oRefIncorporationType;
	private static GDP_Reference_Table__c oRefLocationType;
	private static GDP_Products_Account_View__c oGDPAccount1;
	private static GDP_Products_Account_View__c oGDPAccount2;
	private static GDP_Products_Account_View__c oGDPAccount3;
	private static Accreditation__c oAccreditation1;
	private static Accreditation__c oAccreditation2;
	private static Accreditation__c oAccreditation3;
	
	private static final Integer SUB_USAGE_QTY = 42;
	private static final String AGENCY1_CODE = '5555555';
	private static final String AGENCY2_CODE = '6666666';
	private static final String AGENCY3_CODE = '7777777';
	private static final String AGENT_VER_NUMBER = '5578000523';
	private static final String AGENCY_CHECK_DIGIT = '9';
	private static final String AGENCY1_NAME = 'Chillwave Agency';
	private static final String AGENCY2_NAME = 'Chilly Cheese Agency';
	private static final String AGENCY3_NAME = 'Kashmir Coats';
	
	static void setupData() {
		oProductCategory = IECTestUtil.CreateSampleProductCategory(IECConstants.ProductCategory_SF_GAD, true);
		insert oProductCategory;
		
		oProduct = IECTestUtil.CreateSampleProduct('PTST');
		insert oProduct;
		
		oProductInfo = IECTestUtil.CreateSampleProductInfo('PITST', oProductCategory, oProduct);
		oProductInfo.Product_Audience__c = IECConstants.ProductInformationAudience_DEFAULT;
		insert oProductInfo;

		oProductRatePlan = IECTestUtil.CreateSampleProductRatePlan('PRPTST', false, oProduct);
		insert oProductRatePlan;

		oProductRatePlanInfo = IECTestUtil.CreateSampleProductRatePlanInfo('PCRPTST', false, oProductRatePlan, oProductInfo);
		oProductRatePlanInfo.Display_As_Monthly_Fee__c = true;
		oProductRatePlanInfo.Subscription_Usage_Qty__c = null; // make it unlimited
		insert oProductRatePlanInfo;
		
		// create a Terms & Conditions
		oTC = IECTestUtil.CreateSampleTermsAndConditions('My T&Cs', oProductInfo, true);
        insert oTC;
        
        oRefAgencyStatus = IECTestUtil.createSampleGDPReferenceTableEntry('4', 'Valid');
        insert oRefAgencyStatus;
        
        oRefAgencyStatusTerminated = IECTestUtil.createSampleGDPReferenceTableEntry('0', 'Terminated');
        insert oRefAgencyStatusTerminated;
        
        oRefIncorporationType = IECTestUtil.createSampleGDPReferenceTableEntry('i', 'Incorporated');
        insert oRefIncorporationType;
        
        oRefLocationType = IECTestUtil.createSampleGDPReferenceTableEntry('HO', 'Head Office');
        insert oRefLocationType;

        List<RecordType> rtypes = [Select Name, Id 
        							From RecordType
									where sObjectType='Account'
										and Name = 'Agency'
										and isActive = true];
        
        oAgencyAccount = IECTestUtil.createSampleAccount();
        oAgencyAccount.Name = AGENCY1_NAME;
        oAgencyAccount.IATACode__c = AGENCY1_CODE;
        oAgencyAccount.Status__c = 'Approved';
        oAgencyAccount.RecordTypeId = rtypes.get(0).Id;
        insert oAgencyAccount;
        
        oGDPAccount1 = IECTestUtil.createSampleGDPAccount(AGENCY1_NAME, AGENCY1_CODE, oRefAgencyStatus, oRefIncorporationType, oRefLocationType);
        oGDPAccount1.Check_Digit__c = AGENCY_CHECK_DIGIT;
        insert oGDPAccount1;
        
        oGDPAccount2 = IECTestUtil.createSampleGDPAccount(AGENCY2_NAME, AGENCY2_CODE, oRefAgencyStatus, oRefIncorporationType, oRefLocationType);
        insert oGDPAccount2;
        
        oGDPAccount3 = IECTestUtil.createSampleGDPAccount(AGENCY3_NAME, AGENCY3_CODE, oRefAgencyStatusTerminated, oRefIncorporationType, oRefLocationType);
        insert oGDPAccount3;
        
        oAccreditation1 = IECTestUtil.CreateSampleAccreditation(null, oGDPAccount1, 'GDP');
        oAccreditation1.Status__c = oRefAgencyStatus.Id;
    	insert oAccreditation1;

        oAccreditation2 = IECTestUtil.CreateSampleAccreditation(null, oGDPAccount2, 'GDP');
    	oAccreditation2.Status__c = oRefAgencyStatus.Id;
    	insert oAccreditation2;

        oAccreditation3 = IECTestUtil.CreateSampleAccreditation(null, oGDPAccount3, 'GDP');
    	oAccreditation3.Status__c = oRefAgencyStatusTerminated.Id;
    	insert oAccreditation3;
    	
    	oGDPAccount1.Related_Accreditation_Class__c = oAccreditation1.Id;
    	oGDPAccount2.Related_Accreditation_Class__c = oAccreditation2.Id;
    	oGDPAccount3.Related_Accreditation_Class__c = oAccreditation3.Id;
    	update new List<GDP_Products_Account_View__c> {oGDPAccount1, oGDPAccount2, oGDPAccount3};
	}
	
	private static void initSubscription(){

		IECCustomer currentCustomer = IECCustomer.getCurrentIECCustomer();
		oAccount = currentCustomer.RelatedAccount; 
		oContact = currentCustomer.RelatedContact;
		oBillingAccount = currentCustomer.RelatedBillingAccount;
		
		dtSubscriptionEnddate = Date.today().addMonths(6);

		oSubscription = IECTestUtil.createSampleSubscription(oAccount.Id, 'Subs 01', dtSubscriptionEnddate);
		oSubscription.Product_Rate_Plan_Information__c = oProductRatePlanInfo.Id;
		oSubscription.Zuora__CustomerAccount__c = oBillingAccount.Id;
		insert oSubscription;
		
		// create dummy subscription charge
        oSubscriptionCharge = IECTestUtil.createSampleSubscriptionCharge(oSubscription.Id, dtSubscriptionEnddate.addYears(-1).addDays(1), oProduct, oProductRatePlan);
        insert oSubscriptionCharge;
		
		oSubscriptionHist = IECTestUtil.createSampleSubscriptionHistory(oAccount.Id, oContact.Id, oSubscription.Name, oProductCategory.Id, oProductInfo.Id, oProductRatePlanInfo.Id, IECConstants.PaymentType.CREDIT_CARD, oTC);
		insert oSubscriptionHist;
	}
	
	@isTest(SeeAllData=true)
	static void testDisplayAgencyList() {
		try {
			TransformationHelper.trgAccountISSP_AfterBeforInsertDeleteUpdateUndelete = true;
			User u = IECTestUtil.createSampleGuestUserAndLogin();
	    	System.runAs(u) {

	    		Test.startTest();
	    		
	    		// setup data
				setupData();
				initSubscription();

				// trigger the Product Access creation
				update oSubscription;
				
                SchdlGDPProductsAccountSnapshotCleanup bat = new SchdlGDPProductsAccountSnapshotCleanup();
                bat.execute(null);
				Test.stopTest();
	    		
	    		// Set current page
	    		PageReference pgRef = Page.IECGADResult;
                pgRef.getParameters().put(IECConstants.PARAM_PRODUCT_CODE, IECUtil.EncryptEncodeParameter('GAD'));
	    		Test.setCurrentPage(pgRef);
	    		
	    		// instantiate Controller
		    	vfIECGADResult pgCont = new vfIECGADResult(); // test default constructor
		    	pgCont = new vfIECGADResult(2); // since we'll have 3 agencies, use 2 per page so we can have 2 pages
	    		
	    		// Test #1 - don't provide an IEC Application Filter ID
	    		pgCont.pageLoad();
	    		system.assert(IECTestUtil.PageContainsMessage(ApexPages.getMessages(), Label.IEC_Error_InvalidPageParameter));
	    		system.assertEquals(true, pgCont.ctrSubsInfo.hasPageAccess, 'The customer should have access to GAD');
	    		
	    		// Test #2 - provide an invalid IEC Application Filter ID
	    		pgRef.getParameters().put(IECConstants.PARAM_APPFILTER_ID, IECUtil.EncryptEncodeParameter('WeThrewGasolineOnTheFire'));
	    		pgCont.pageLoad();
	    		system.assert(IECTestUtil.PageContainsMessage(ApexPages.getMessages(), Label.IEC_Error_InvalidPageParameter));
	    		
	    		// Test #3 - provide a valid IEC Application Filter ID with no filter
	    		IEC_Application_Filter__c oAppFilters = new IEC_Application_Filter__c();
	    		oAppFilters.Related_Contact__c = oContact.Id;
	    		insert oAppFilters;
	    		
	    		pgRef.getParameters().put(IECConstants.PARAM_APPFILTER_ID, IECUtil.EncryptEncodeParameter(oAppFilters.Id));
	    		pgCont.pageLoad();
	    		
	    		system.assertEquals(oAppFilters.Id, pgCont.sIECApplicationFiltersID, 'The app filter Id should be loaded correctly');
	    		system.assertEquals(oAppFilters.Id, pgCont.oApplicationFilters.Id, 'The app filter should be loaded correctly');
	    		system.assertEquals(2, pgCont.lstAgencies == null ? 0 : pgCont.lstAgencies.size(), '2 agencies should be found');
	    		system.assertEquals(2, pgCont.iTotalResult, 'The total result should be appropriated');
	    		for (GDP_Products_Account_View__c agency : pgCont.lstAgencies)
	    			system.assert(agency.Id == oGDPAccount1.ID || agency.Id == oGDPAccount2.ID, 'agency1 and agency2 should be found (agency3 is terminated)');

	    		// un-terminate agency3
		    	oAccreditation3.Status__c = oRefAgencyStatus.Id;
		    	update oAccreditation3;
                bat = new SchdlGDPProductsAccountSnapshotCleanup();
                List<GDP_Products_Account_View__c> gpav = Database.query(SchdlGDPProductsAccountSnapshotCleanup.query);
                bat.execute(null, gpav);

	    		pgCont = new vfIECGADResult(2); // since we'll have 3 agencies, use 2 per page so we can have 2 pages
	    		pgRef.getParameters().put(IECConstants.PARAM_APPFILTER_ID, IECUtil.EncryptEncodeParameter(oAppFilters.Id));
	    		pgCont.pageLoad();
	    		system.assert(pgCont.lstAgencies != null && pgCont.lstAgencies.size() == 3, 'All 3 agencies should be found');
	    		system.assert(pgCont.sTextRepresentationOfFilters=='', 'The text search criteria should be empty');
	    		
	    		// Test #4 - browse tru the pages
	    		system.assertEquals(0, pgCont.iCurrentPageIndex, 'Page index should be 0');
	    		system.assertEquals(2, pgCont.iTotalPage, 'Total nbr of page should be 2');
	    		system.assertEquals(false, pgCont.bPreviousPageIsEnabled, 'We are at the first page so previous page link should be disabled');
	    		system.assertEquals(true, pgCont.bNextPageIsEnabled, 'We are at the first page of 2 so next page link should be enabled');
	    		system.assertEquals(false, pgCont.bShowStateProvinceColumn, 'State/Province column shoud not be displayed');
	    		system.assertEquals(false, pgCont.bShowCityColumn, 'City column shoud not be displayed');
	    		system.assertEquals(false, pgCont.bShowZipPostalCodeColumn, 'Zip/Postal Code column shoud not be displayed');
	    		system.assertEquals(false, pgCont.bShowLegalName, 'By default, Trading Name should be displayed');
	    		pgCont.nextPage();
	    		system.assertEquals(1, pgCont.iCurrentPageIndex, 'Page index should be 1');
	    		system.assertEquals(true, pgCont.bPreviousPageIsEnabled, 'We are at the second page so previous page link should be enabled');
	    		system.assertEquals(false, pgCont.bNextPageIsEnabled, 'We are at the second page of 2 so next page link should be disabled');
	    		pgCont.previousPage();
	    		system.assertEquals(0, pgCont.iCurrentPageIndex, 'Page index should be 0');
	    		system.assertEquals(false, pgCont.bPreviousPageIsEnabled, 'We are at the first page so previous page link should be disabled');
	    		
	    		// Test #5 - browse tru the agencies from the detail view
	    		pgCont.selectAgency();
	    		pgCont.previousAgency();
	    		pgCont.nextAgency();
	    		pgCont.sSelectedAgencyId = oGDPAccount2.Id;
	    		pgCont.selectAgency();
	    		system.assertEquals(oGDPAccount2.Id, pgCont.sAgencyIDToViewDetail, 'The appropriate agency id should be selected');
	    		system.assertEquals(1, pgCont.iCurrentAgencyIndex, 'Index of Agency should be 1');
	    		system.assertEquals(true, pgCont.bPreviousAgencyIsEnabled, 'bPreviousAgencyIsEnabled should be true');
	    		system.assertEquals(true, pgCont.bNextAgencyIsEnabled, 'bNextAgencyIsEnabled should be true');
	    		pgCont.previousAgency();
	    		system.assertEquals(0, pgCont.iCurrentAgencyIndex, 'Index of Agency should be 0');
	    		system.assertEquals(false, pgCont.bPreviousAgencyIsEnabled, 'bPreviousAgencyIsEnabled should not be true');
	    		system.assertEquals(true, pgCont.bNextAgencyIsEnabled, 'bNextAgencyIsEnabled should be true');
	    		pgCont.nextAgency();
	    		pgCont.nextAgency();
	    		system.assertEquals(2, pgCont.iCurrentAgencyIndex, 'Index of Agency should be 2');
	    		system.assertEquals(true, pgCont.bPreviousAgencyIsEnabled, 'bPreviousAgencyIsEnabled should be true');
	    		system.assertEquals(false, pgCont.bNextAgencyIsEnabled, 'bNextAgencyIsEnabled should not be true');
	    		
	    		pgCont.backToResultList();
	    		system.assertEquals(null, pgCont.sAgencyIDToViewDetail, 'sAgencyIDToViewDetail should be null');
	    		system.assertEquals(0, pgCont.iCurrentAgencyIndex, 'iCurrentAgencyIndex should be reset to 0');
	    		
	    		pgCont.backToSearchPage();
	    	}
		}
		catch(Exception ex) {
			system.assert(false, 'Test testDisplayAgencyDetails should not throw an exception: ' + ex.getMessage() + '\r\n' + ex.getStacktraceString());
		}
	}
	
	@isTest(SeeAllData=true)
	static void testDisplayAgencyList_Misc() {
    	// Set current page
		PageReference pgRef = Page.IECGADResult;
		Test.setCurrentPage(pgRef);
		
		vfIECGADResult pgCont = new vfIECGADResult(); // test default constructor
		pgCont.pageLoad();
		String sTest = pgCont.sProductCode;
	}
}