src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACH_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ACH Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACLI_Status__c</fullName>
        <label>ACLI Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive Company</fullName>
                </value>
                <value>
                    <fullName>Active Company</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Airline_designator__c</fullName>
        <description>Field used for the airline designator code e.g. BA</description>
        <label>IATA Designator</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BIETA_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BIETA Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ICH_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ICH Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MITA_Currency__c</fullName>
        <label>MITA Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US Dollar</fullName>
                </value>
                <value>
                    <fullName>Euro</fullName>
                </value>
                <value>
                    <fullName>Pound Sterling</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Art3_Excepted_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MITA IATA Interline Art3 Excepted Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Cargo_Charges__c</fullName>
        <label>MITA IATA Interline Cargo Charges</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Cargo_Claims__c</fullName>
        <label>MITA IATA Interline Cargo Claims</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Cargo__c</fullName>
        <label>MITA IATA Interline Cargo</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Pass_Art3_Joined__c</fullName>
        <label>MITA IATA Interline Pass Art3 Joined</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Passenger_Charges__c</fullName>
        <label>MITA IATA Interline Passenger Charges</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Passenger__c</fullName>
        <label>MITA IATA Interline Passenger</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MITA Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MITA_One_way_Pass_Issuing_Airline__c</fullName>
        <label>MITA One way Pass. Issuing Airline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_One_way_Pass_Participating__c</fullName>
        <label>MITA One way Pass. Participating</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_status__c</fullName>
        <description>Field used to specify the membership status</description>
        <label>IATA Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IATA member</fullName>
                </value>
                <value>
                    <fullName>Non-IATA member</fullName>
                </value>
                <value>
                    <fullName>Ex-IATA Member</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name_on_AOC__c</fullName>
        <label>Name on AOC</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Top Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Airline_Designator__c</fullName>
        <formula>Account.Airline_designator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Airline Designator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MITA_Contact_Type__c</fullName>
        <label>MITA Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Interline Passenger Agreement Manager</fullName>
                </value>
                <value>
                    <fullName>Passenger Protection Agreement</fullName>
                </value>
                <value>
                    <fullName>Interline Airline Generic Contact</fullName>
                </value>
                <value>
                    <fullName>Interline Cargo Agreement Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MITA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Airline_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airline 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Airline Headquarters</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MITA Agreements (Account)</relationshipLabel>
        <relationshipName>MITA_Agreements_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Airline_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airline 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Airline Headquarters</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MITA Agreements (Account)</relationshipLabel>
        <relationshipName>MITA_Agreements_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MITAorBIETA__c</fullName>
        <label>MITA/BIETA/EMD</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MITA</fullName>
                    <default>true</default>
                    <label>MITA</label>
                </value>
                <value>
                    <fullName>BIETA</fullName>
                </value>
                <value>
                    <fullName>EMD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MITA Agreement</label>
    <nameField>
        <displayFormat>MA-{YYYY}{MM}-{0000}</displayFormat>
        <label>MITA Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MITA Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MITA_TxtCtrlTest.cls
@isTest
private class MITA_TxtCtrlTest {

	@isTest static void testControllerOK() {

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getTitle();
		controller.getContent();
		Test.stopTest();
	}

	@testSetup static void initData() {
		Id rtHQ =  RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline');
		//ge
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < 4; i++ ) {
			accounts.add(new Account(
			                 Name = 'test account ' + i ,
			                 BillingStreet = '123 Test',
			                 ACLI_Status__c = 'Active Company',
			                 IATACode__c = '123' + i,
			                 Name_on_AOC__c = 'AOC',
			                 MITA_IATA_Interline_Passenger__c = Date.today(),
			                 MITA_IATA_Interline_Cargo__c = Date.today(),
			                 MITA_One_way_Pass_Participating__c = Date.today(),
			                 MITA_Member__c = true,
			                 BIETA_Member__c = true,
			                 RecordTypeId = rtHQ,
			                 Airline_designator__c = 'AA',
			                 MITA_One_way_Pass_Issuing_Airline__c = Date.today(),
			                 MITA_IATA_Interline_Art3_Excepted_Status__c = true,
			                 MITA_IATA_Interline_Pass_Art3_Joined__c = Date.newInstance(2016 , 11 ,1),
			                 MITA_IATA_Interline_Cargo_Claims__c = Date.today(),
			                 MITA_IATA_Interline_Passenger_Charges__c = Date.today(),
			                 MITA_IATA_Interline_Cargo_Charges__c = Date.today(),
			                 ICH_Member__c = true,
			                 ACH_Member__c = true
			             ));
		}

		accounts[0].Membership_status__c = 'IATA Member';
		accounts[0].MITA_Currency__c = 'Euro';		
		accounts[1].Membership_status__c = 'Associate';
		accounts[1].MITA_Currency__c = 'US Dollar';	
		accounts[1].Top_Parent__c = accounts[0].id;	
		accounts[2].Membership_status__c = 'Non-IATA member';
		accounts[2].MITA_Currency__c = 'Pound Sterling';			
		accounts[2].Top_Parent__c = accounts[0].id;	
		accounts[3].Membership_status__c = 'XXX';
		accounts[3].MITA_Currency__c = '';	
		accounts[3].Top_Parent__c = accounts[0].id;	
		//accounts[3].id = '001w0000015LHUsAAO';	
		insert accounts;

		MITA_Agreement__c agr = new MITA_Agreement__c(
			Airline_1__c = accounts[0].Id,
			Airline_2__c = accounts[3].Id,
			MITAorBIETA__c = 'MITA'
		);
		insert agr;
		
		List<Contact> contacts = new List<Contact>();
		for(Account a : accounts)
			contacts.add(new Contact(FirstName = 'Name', LastName='Contact '+a.Name, AccountId=a.Id, Email='contact@'+a.Name.replace(' ','')+'.com', MITA_Contact_Type__c='CGO Billing'));
		insert contacts;

	}

	@isTest static void testControllerIAB2D1() {
		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB2D1);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB2D2() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB2D2);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB2D3() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB2D3);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB2D4() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB2D4);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB2D5() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB2D5);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB2D6() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB2D6);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}

	@isTest static void testControllerIAB2P2() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB2P2);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB3D1() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB3D1);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB3D2() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB3D2);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}

	@isTest static void testControllerIAB4D2() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB4D2);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB5D3() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB5D3);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB7D1() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB7D1);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerIAB7D2() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.IAB7D2);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
	@isTest static void testControllerMITA27() {

		PageReference pageRef = Page.MITA_Txt;
		pageRef.getParameters().put('type', MITA_TxtCtrl.MITA27);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		MITA_TxtCtrl controller = new MITA_TxtCtrl();
		controller.getContent();
		Test.stopTest();
	}
}