src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Standard_Account</fullName>
        <active>true</active>
        <description>Use for all other accounts.</description>
        <label>Standard Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Portal_Status__c</fullName>
        <label>User Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved User</fullName>
                </value>
                <value>
                    <fullName>Approved Admin</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Regional Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard_Contact</fullName>
        <active>true</active>
        <description>The new record type for ALL contacts with NEW data model - Use this for all contacts</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Amount_Blocked__c</fullName>
        <label>Actual Amount Blocked</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country Name</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Country Profiles</relationshipLabel>
        <relationshipName>Country_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <label>ISO Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Notification_Message__c</fullName>
        <label>Notification Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Publish_News__c</fullName>
        <label>Publish News?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send_Notifications__c</fullName>
        <label>Send Notifications ?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Country Profile</label>
    <nameField>
        <label>Country Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country_Profile_History__c.object
<CustomObject>
    <description>Used by the ICCS Currency Center project to store historical values of the fields which normally are not allowed to be tracked as part of the standard functionality.</description>
    <fields>
        <fullName>Country_Profile__c</fullName>
        <description>Related Country Profile</description>
        <label>Country Profile</label>
        <referenceTo>Country_Profile__c</referenceTo>
        <relationshipLabel>Country Profile Histories</relationshipLabel>
        <relationshipName>Country_Profile_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <description>Represents the field name on Country Profile</description>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewValue__c</fullName>
        <description>Stores the new value of the represented field</description>
        <label>NewValue</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OldValue__c</fullName>
        <description>Stores the old value of the represented field</description>
        <label>OldValue</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Country Profile History</label>
    <nameField>
        <displayFormat>CPH-{00000}</displayFormat>
        <label>Country Profile History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Profile Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country_Profile_History_Tracking__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to define fields for custom tracking solution on Country Profile object.</description>
    <label>Country Profile History Tracking</label>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <fields>
        <fullName>Application_URL__c</fullName>
        <label>Application URL</label>
        <type>Url</type>
    </fields>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>License_Cost_Center__c</fullName>
        <inlineHelpText>The IATA cost center that is paying for your Salesforce.com license.</inlineHelpText>
        <label>License Cost Center</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CountryProfileTriggerHandlerTest.cls
@isTest
private class CountryProfileTriggerHandlerTest {
	
	@isTest static void checkIfHistoryRecordWasCreated() {
		Test.startTest();

		IATA_ISO_Country__c iso = new IATA_ISO_Country__c(ISO_Code__c='FR');
		insert iso;

		Country_Profile__c cp1 = new Country_Profile__c(Name='France', Country_Name__c=iso.Id, ISO_Code__c='');
		cp1.Actual_Amount_Blocked__c = '123';		
		Country_Profile_History_Tracking__c cpht = new Country_Profile_History_Tracking__c(Name='Actual_Amount_Blocked__c');
		insert cpht;
		insert cp1;

		//for some reason, the excecution of trigger method is reversed during test run... need to reset the firstExec var 
		CountryProfileTriggerHandler.firstExec = true;
		cp1.Actual_Amount_Blocked__c = '999';
		update cp1;
		
		Test.stopTest();
		List<Country_Profile_History__c> histories = [SELECT Id,OldValue__c,NewValue__c,Field__c FROM Country_Profile_History__c WHERE Country_Profile__c =: cp1.Id];

		system.assertEquals('123',histories[0].OldValue__c);
		system.assertEquals('999',histories[0].NewValue__c);
		system.assertEquals('Actual_Amount_Blocked__c',histories[0].Field__c);

	}

	@isTest static void checkNonExistingField() {
		Country_Profile__c cp1 = new Country_Profile__c();
		cp1.Actual_Amount_Blocked__c = '123';		
		Country_Profile_History_Tracking__c cpht = new Country_Profile_History_Tracking__c(Name='somerandomfield');

		Test.startTest();
		insert cpht;
		insert cp1;
		//for some reason, the excecution of trigger method is reversed during test run... need to reset the firstExec var 
		CountryProfileTriggerHandler.firstExec = true;
		cp1.Actual_Amount_Blocked__c = '999';
		update cp1;
		Test.stopTest();
		List<Country_Profile_History__c> histories = [SELECT Id,OldValue__c,NewValue__c,Field__c FROM Country_Profile_History__c WHERE Country_Profile__c =: cp1.Id];
	}

	@isTest static void checkValidations() {
		Country_Profile__c cp1 = new Country_Profile__c();

		Test.startTest();
		insert cp1;
		try{
			cp1.Publish_News__c = 'Yes';
			update cp1;
		} catch (Exception e) {
		}
		try{
			cp1.Send_Notifications__c = 'Yes';
			update cp1;
		} catch (Exception e) {
		}
		
		Test.stopTest();
	}

	@isTest static void checkSubscribeUsersToNewCountryProfile() {
		Test.startTest();

		Id conRtId = RecordTypeSingleton.getInstance().getRecordTypeId('Contact', 'Standard_Contact');
        Id accRtId = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'Standard_Account');

        //Set<String> customerUserTypes = new Set<String> {'CSPLiteUser','PowerPartner','PowerCustomerSuccess','CustomerSuccess'};
        Account acc = new Account (
        RecordTypeId = accRtId, 
        Name = 'testAcc'
        );  
        insert acc;

        Contact con = new Contact (
        AccountId = acc.id,
        RecordTypeId = conRtId, 
        LastName = 'portalUser',
        FirstName = 'Name',
        User_Portal_Status__c = 'Approved User'
        );
        insert con;

        Id communityId = [SELECT Id FROM Network WHERE Name = 'IATA Portal'].Id;
        //Id nmgId = [SELECT Id,ParentId FROM NetworkMemberGroup WHERE NetworkId =: communityId LIMIT 1].ParentId;
        Profile p = [select Id,name from Profile where Name = 'ISS Portal Airline User (Partner)' limit 1];
         
        User newUser = new User(
        profileId = p.id,
        username = 'someuser@iata.org',
        email = 'someuser@iata.org',
        emailencodingkey = 'UTF-8',
        localesidkey = 'en_US',
        languagelocalekey = 'en_US',
        timezonesidkey = 'America/Los_Angeles',
        alias='nuser',
        lastname='lastname',
        contactId = con.id,
        License_Cost_Center__c = 'ISF005CH01'
        );
        insert newUser;

        Portal_Applications__c app = new Portal_Applications__c(Application_URL__c='/ISSP_CurrencyCenterHome');
        insert app;

        Portal_Application_Right__c par = 
            new Portal_Application_Right__c(Contact__c=newUser.ContactId,Right__c = 'Access Granted',Portal_Application__c=app.Id);
        insert par;

        Country_Profile__c cp1 = new Country_Profile__c();
        insert cp1;

        Test.stopTest();
	}


	/***
	no way to insert network through API ?
	@isTest static void checkNotifications() {
		Country_Profile__c cp1 = new Country_Profile__c();

		Test.startTest();
		Network n = new Network(Name = 'IATA Portal');
		insert n;
		EntitySubscription es = new EntitySubscription(ParentId=cp1.Id,NetworkId=n.Id);

		cp1.Send_Notifications__c = 'Yes';
		cp1.Notification_Message__c = 'Some notification';
		insert cp1;

		Test.stopTest();
	}
	***/
	
}