src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACLI_Status__c</fullName>
        <label>ACLI Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive Company</fullName>
                </value>
                <value>
                    <fullName>Active Company</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_code_secondary_flag__c</fullName>
        <label>Account code secondary flag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Accounting_Code__c</fullName>
        <label>Three letter Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_Prefix__c</fullName>
        <label>Airline Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_designator__c</fullName>
        <description>Field used for the airline designator code e.g. BA</description>
        <label>IATA Designator</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Head_Office__c</fullName>
        <label>Headquarter / Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Headquarter</fullName>
                </value>
                <value>
                    <fullName>Branch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_name__c</fullName>
        <description>Field used for the legal name of the airlines and the travel agents</description>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Membership_SITA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SITA Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_status__c</fullName>
        <description>Field used to specify the membership status</description>
        <label>IATA Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IATA member</fullName>
                </value>
                <value>
                    <fullName>Non-IATA member</fullName>
                </value>
                <value>
                    <fullName>Ex-IATA Member</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Memmership_ARINC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership ARINC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Memmership_ATA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership ATA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name_on_AOC__c</fullName>
        <label>Name on AOC</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_index__c</fullName>
        <description>if(ISPICKVAL(Industry,&apos;Travel Agent&apos;),Site, if( ISBLANK(IATACode__c),
Airline_designator__c + &apos; &apos;+IATA_ISO_Country__r.ISO_Code__c,
Airline_designator__c + &apos; &apos; + IATACode__c + &apos; &apos; + IATA_ISO_Country__r.ISO_Code__c))</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is used just for indexing purpose</inlineHelpText>
        <label>Site_index</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of__c</fullName>
        <label>Type of Operations code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AcliParser.cls
public  class AcliParser {

		 public static AcliWrapper AcliParsingNotFound(String acliTxtFile,integer MINLEVEL, integer MAXLEVEL,boolean stateOFF){
										//  throw new transformationException('acliTxtFileString???  '+acliTxtFile +  ' MINLEVEL ' +   MINLEVEL +  '  MAXLEVEL ' + MAXLEVEL);

						return  AcliParsing(acliTxtFile,false,MINLEVEL,MAXLEVEL,stateOFF);

				}
				public static AcliWrapper AcliParsingFound(String acliTxtFile,integer MINLEVEL, integer MAXLEVEL,boolean stateOFF){

						return  AcliParsing(acliTxtFile,true,MINLEVEL,MAXLEVEL,stateOFF);


				}



		 public static AcliWrapper AcliParsing(String acliTxtFile,boolean found,integer MINLEVEL, integer MAXLEVEL,boolean stateOFF){

					 AcliWrapper AcliWrapper;
					 AcliWrapper AcliWrapperMethod =AcliAcctsPerSitePlusStateRETURN(acliTxtFile,found,MAXLEVEL,stateOFF);

						map<String,AcliAccount> AcliAcctsPerSitePlusStateTmp = AcliWrapperMethod.AcliAccount;
						integer numOfLines=AcliWrapperMethod.NumberOfLines;
						map<String,AcliAccount> AcliAcctsPerSitePlusStateRETURN = new map<String,AcliAccount>();

						map<integer,string> sitePerLine =new  map<integer,string>();
						integer index = 0;
						for(string site:AcliAcctsPerSitePlusStateTmp.keySet()){
										sitePerLine.put(index,site);
										index++;
						}

						for(integer i=MINLEVEL;i<MAXLEVEL;i++){
										string key = sitePerLine.get(i);
										if(key <> null)
										AcliAcctsPerSitePlusStateRETURN.put(key,AcliAcctsPerSitePlusStateTmp.get(key));
						}


					 AcliWrapper = new  AcliWrapper(MAXLEVEL,numOfLines,AcliAcctsPerSitePlusStateRETURN);
									//      throw new transformationException(''+AcliWrapper );
					 return AcliWrapper;
				}


				private static AcliWrapper AcliAcctsPerSitePlusStateRETURN(String acliTxtFile,boolean found,integer MAXLEVEL,boolean stateOFF ){
						AcliWrapper returnValue;
						map<String,AcliAccount> AcliAcctsPerSitePlusStateRETURN = new map<String,AcliAccount>();
						map<String,AcliAccount> AcliAcctsPerSitePlusState = new map<String,AcliAccount>();
						map<String,AcliAccount> AcliAcctsPerREALSite = new map<String,AcliAccount>();

						set<string> sites = new set<string>();

									 AcliAccount tmp;
										INTEGER SKIPPED = 0;
										string separator =  acliTxtFile.contains('<br>') ?  '<br>' : '\\n';
										for(String line : acliTxtFile.split(separator)) {

														 tmp = new AcliAccount(line,stateOFF);


												// we exclude some of the airlines cause of some IATA accts that are there and there should not be
														 if(!
																		(    tmp.twoCaracterCOde.trim() =='XD'
																				|| tmp.twoCaracterCOde.trim() =='XB'
																				|| tmp.AirlineName.contains('Settlement Plan')
																				|| tmp.AccountingCode.trim() == '950'
																				|| tmp.AccountingCode.trim() == '952'
																				||(stateOFF && tmp.twoCaracterCOde.trim() =='1I')
																		)
																){

	 //if(tmp.AccountSite.contains('1G 773 GB'))
		 //                               throw new transformationException('-'+tmp.AccountSite+'-');
																 AcliAcctsPerSitePlusState.put(tmp.AccountSite,tmp);
																	AcliAcctsPerREALSite.put(tmp.realSite,tmp);
																 sites.add(tmp.RealSite);
														 }ELSE{


																		 SKIPPED ++;
																}
										system.debug('@@@ skipped lines  ' + skipped );
										}

								integer totalLines =0;
								list<Account> acctOnDb = [SELECT ID, site_index__c, billingState ,ACLI_Status__c,
																								 name, billingCity,billingCountry,billingPostalCode,
																								 billingStreet,Name_on_AOC__c,
																								 site,Airline_designator__c,Account_code_secondary_flag__c,
																								 Accounting_Code__c,Airline_Prefix__c,Field_Head_Office__c,
																								 Industry,Type,IATACode__c,Membership_status__c,
																								 IATA_ISO_Country__c,IATA_ISO_Country__r.ISO_Code__c,
																								 Legal_name__c,Membership_SITA__c,
																								 Memmership_ARINC__c,Memmership_ATA__c,
																								 Type_of__c,LastModifiedDate  //type of operations
																					FROM Account
																					WHERE site_index__c In:sites
																					AND recordtype.developername = 'IATA_Airline'
																					AND Acli_Status__c <> 'Inactive Company'
																					];

						map<string,Account> accountOnDbPerChiave = new map<string,Account>();

						string site;
						for(Account a:acctOnDb){
//throw new transformationException(''+a);
								site ='';
								site = TransformationHelper.buildSiteForAcli(a.IATACode__c, a.Airline_designator__c,a.IATA_ISO_Country__r.ISO_Code__c,null ) ;
										site = site.toUpperCase();
										string realSite = site;
										string bilstate = a.BillingState <> null ? a.BillingState:'';
									if(!stateOFF && bilstate <> '')site +=bilstate.trim();

										accountOnDbPerChiave.put(site,a);


						if(found && AcliAcctsPerSitePlusState.get(site)<> null){

																				AcliAcctsPerSitePlusState.get(site).ExistingInSFDC = true;
																				AcliAcctsPerSitePlusState.get(site).AcctID = accountOnDbPerChiave.get(site).id;
																				AcliAcctsPerSitePlusState.get(site).LastModifiedDate = accountOnDbPerChiave.get(site).LastModifiedDate;
																				AcliAcctsPerSitePlusStateRETURN.put(site,AcliAcctsPerSitePlusState.get(site));
																				AcliAcctsPerSitePlusStateRETURN.get(site).ExistingInSFDC = true;
																				totalLines++;

										}else if(!found && AcliAcctsPerSitePlusState.get(site)== null && AcliAcctsPerREALSite.get(realSite) <> null){

																		AcliAcctsPerSitePlusStateRETURN.put(site,AcliAcctsPerREALSite.get(realSite)); //AcliAcctsPerSitePlusState.get(site)
																		totalLines++;

										}


						}

						if(!found){
										for(string siteKey: AcliAcctsPerSitePlusState.keyset()){
																if(accountOnDbPerChiave.get(siteKey) == null && siteKey <> null) {
																		AcliAcctsPerSitePlusStateRETURN.put(siteKey,AcliAcctsPerSitePlusState.get(siteKey));
																		totalLines++;
																		}
										 }
						}
						returnValue = new  AcliWrapper(MAXLEVEL,totalLines,AcliAcctsPerSitePlusStateRETURN);

						return returnValue;
				}


}