src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Airline_Contact_Type__c</fullName>
        <formula>IF(TEXT(CEO_CFO__c)=&quot;CEO&quot;,IMAGE(&quot;/resource/CEO_Contact_image&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(TEXT(CEO_CFO__c)=&quot;CFO&quot;,IMAGE(&quot;/resource/CFO_Contact_image&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(TEXT(CEO_CFO__c)=&quot;COO&quot;,IMAGE(&quot;/resource/COO_Contact_image&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(TEXT(CEO_CFO__c)=&quot;CCO&quot;,IMAGE(&quot;/resource/CCO_Contact_image&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(TEXT(CEO_CFO__c)=&quot;CIO&quot;,IMAGE(&quot;/resource/CIO_Contact_image&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(Airline_Credit_Risk_Manager__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=0151r000007L6nF&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(Distribution_Risk_Expert__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=0151r000007L6nK&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(PSG_Member__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w00000037SgT&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(PAPGCJ_Participant__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w00000037ShC&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(PaConf_Representative__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w0000002rRYu&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(LCAG_Member__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w00000037ShM&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(ICCS_Contact__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w00000037SiK&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(Invoicing_Contact__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w00000037Si0&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(APJC_Participant__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w00000037Sjw&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(BSP_CASS_Payment_contact__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w00000037Sjc&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(Financial_Assessment_Contact__c,IMAGE(&quot;/servlet/servlet.FileDownload?file=015w00000037Sj8&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(NOT(ISBLANK(Function__c)),IMAGE(&quot;/resource/Primary_Contact_image&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(Membership_Main_Contact__c,IMAGE(&quot;/resource/Main_Contact_image&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(TEXT(EF_Status__c)=&quot;Active&quot;,IMAGE(&quot;/resource/EF_contact_image&quot; ,&quot;&quot;,40,40),&quot;&quot;)
&amp;&quot; &quot;&amp;
IF(Authorized_Signatory__c,IMAGE(&quot;/resource/authsign&quot; ,&quot;&quot;,40,40),&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Function__c</fullName>
        <label>Job Function</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aeropolitical</fullName>
                </value>
                <value>
                    <fullName>Aeropolitico</fullName>
                    <isActive>false</isActive>
                    <label>Aeropolitico</label>
                </value>
                <value>
                    <fullName>Aéropolitique</fullName>
                    <isActive>false</isActive>
                    <label>Aéropolitique</label>
                </value>
                <value>
                    <fullName>Altro</fullName>
                    <isActive>false</isActive>
                    <label>Altro</label>
                </value>
                <value>
                    <fullName>An ninh&amp; Cơ sở vật chất</fullName>
                    <isActive>false</isActive>
                    <label>An ninh&amp; Cơ sở vật chất</label>
                </value>
                <value>
                    <fullName>An toàn</fullName>
                    <isActive>false</isActive>
                    <label>An toàn</label>
                </value>
                <value>
                    <fullName>Autre</fullName>
                    <isActive>false</isActive>
                    <label>Autre</label>
                </value>
                <value>
                    <fullName>Betrieb</fullName>
                    <isActive>false</isActive>
                    <label>Betrieb</label>
                </value>
                <value>
                    <fullName>Cargo</fullName>
                </value>
                <value>
                    <fullName>Cargo,Marketing&amp;Sales</fullName>
                    <isActive>false</isActive>
                    <label>Cargo,Marketing&amp;Sales</label>
                </value>
                <value>
                    <fullName>Chính trị hàng không</fullName>
                    <isActive>false</isActive>
                    <label>Chính trị hàng không</label>
                </value>
                <value>
                    <fullName>Comercial</fullName>
                    <isActive>false</isActive>
                    <label>Comercial</label>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Commerciale</fullName>
                    <isActive>false</isActive>
                    <label>Commerciale</label>
                </value>
                <value>
                    <fullName>Corporate Planning</fullName>
                    <isActive>false</isActive>
                    <label>Corporate Planning</label>
                </value>
                <value>
                    <fullName>Customer &amp; Service</fullName>
                    <isActive>false</isActive>
                    <label>Customer &amp; Service</label>
                </value>
                <value>
                    <fullName>Enviornment</fullName>
                    <isActive>false</isActive>
                    <label>Enviornment</label>
                </value>
                <value>
                    <fullName>Environement</fullName>
                    <isActive>false</isActive>
                    <label>Environement</label>
                </value>
                <value>
                    <fullName>Environment</fullName>
                </value>
                <value>
                    <fullName>Environment,Human Resources</fullName>
                    <isActive>false</isActive>
                    <label>Environment,Human Resources</label>
                </value>
                <value>
                    <fullName>Environnement</fullName>
                    <isActive>false</isActive>
                    <label>Environnement</label>
                </value>
                <value>
                    <fullName>Exploitation</fullName>
                    <isActive>false</isActive>
                    <label>Exploitation</label>
                </value>
                <value>
                    <fullName>Finanças</fullName>
                    <isActive>false</isActive>
                    <label>Finanças</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance,other</fullName>
                    <isActive>false</isActive>
                    <label>Finance,other</label>
                </value>
                <value>
                    <fullName>Financement</fullName>
                    <isActive>false</isActive>
                    <label>Financement</label>
                </value>
                <value>
                    <fullName>Finanzas</fullName>
                    <isActive>false</isActive>
                    <label>Finanzas</label>
                </value>
                <value>
                    <fullName>Finanze</fullName>
                    <isActive>false</isActive>
                    <label>Finanze</label>
                </value>
                <value>
                    <fullName>Finanzen</fullName>
                    <isActive>false</isActive>
                    <label>Finanzen</label>
                </value>
                <value>
                    <fullName>Flight Operation</fullName>
                    <isActive>false</isActive>
                    <label>Flight Operation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ImportantContactsController.cls
public with sharing class ImportantContactsController {
	public Id AccountId {get; set;}
	public list<Contact> lstImportantContacts {
		get{
			if (AccountId != null) {
				list<Contact> lstTmpContacts = new list<Contact>();
				for (Contact c : [SELECT Id, FirstName, LastName, Email, Phone, Title, Membership_Function__c, Airline_Contact_Type__c FROM Contact WHERE AccountId = :AccountId AND Status__c = 'Active']) {
					if (c.Airline_Contact_Type__c != null && c.Airline_Contact_Type__c.trim() != '') {
						lstTmpContacts.add(c);
					}
				}

				return lstTmpContacts;
			} else {
				return new list<Contact>();
			}
		} set;}

	public ImportantContactsController (ApexPages.StandardController controller) {
		if (controller.getRecord().Id != null ) {
			AccountId = controller.getRecord().Id;
		} else {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Invalid Account'));
			system.debug('Error: invalid account');
		}
	}
}