src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Membership_Function__c</fullName>
        <label>Job Function</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aeropolitical</fullName>
                </value>
                <value>
                    <fullName>Aeropolitico</fullName>
                    <isActive>false</isActive>
                    <label>Aeropolitico</label>
                </value>
                <value>
                    <fullName>Aéropolitique</fullName>
                    <isActive>false</isActive>
                    <label>Aéropolitique</label>
                </value>
                <value>
                    <fullName>Altro</fullName>
                    <isActive>false</isActive>
                    <label>Altro</label>
                </value>
                <value>
                    <fullName>An ninh&amp; Cơ sở vật chất</fullName>
                    <isActive>false</isActive>
                    <label>An ninh&amp; Cơ sở vật chất</label>
                </value>
                <value>
                    <fullName>An toàn</fullName>
                    <isActive>false</isActive>
                    <label>An toàn</label>
                </value>
                <value>
                    <fullName>Autre</fullName>
                    <isActive>false</isActive>
                    <label>Autre</label>
                </value>
                <value>
                    <fullName>Betrieb</fullName>
                    <isActive>false</isActive>
                    <label>Betrieb</label>
                </value>
                <value>
                    <fullName>Cargo</fullName>
                </value>
                <value>
                    <fullName>Cargo,Marketing&amp;Sales</fullName>
                    <isActive>false</isActive>
                    <label>Cargo,Marketing&amp;Sales</label>
                </value>
                <value>
                    <fullName>Chính trị hàng không</fullName>
                    <isActive>false</isActive>
                    <label>Chính trị hàng không</label>
                </value>
                <value>
                    <fullName>Comercial</fullName>
                    <isActive>false</isActive>
                    <label>Comercial</label>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Commerciale</fullName>
                    <isActive>false</isActive>
                    <label>Commerciale</label>
                </value>
                <value>
                    <fullName>Corporate Planning</fullName>
                    <isActive>false</isActive>
                    <label>Corporate Planning</label>
                </value>
                <value>
                    <fullName>Customer &amp; Service</fullName>
                    <isActive>false</isActive>
                    <label>Customer &amp; Service</label>
                </value>
                <value>
                    <fullName>Enviornment</fullName>
                    <isActive>false</isActive>
                    <label>Enviornment</label>
                </value>
                <value>
                    <fullName>Environement</fullName>
                    <isActive>false</isActive>
                    <label>Environement</label>
                </value>
                <value>
                    <fullName>Environment</fullName>
                </value>
                <value>
                    <fullName>Environment,Human Resources</fullName>
                    <isActive>false</isActive>
                    <label>Environment,Human Resources</label>
                </value>
                <value>
                    <fullName>Environnement</fullName>
                    <isActive>false</isActive>
                    <label>Environnement</label>
                </value>
                <value>
                    <fullName>Exploitation</fullName>
                    <isActive>false</isActive>
                    <label>Exploitation</label>
                </value>
                <value>
                    <fullName>Finanças</fullName>
                    <isActive>false</isActive>
                    <label>Finanças</label>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Finance,other</fullName>
                    <isActive>false</isActive>
                    <label>Finance,other</label>
                </value>
                <value>
                    <fullName>Financement</fullName>
                    <isActive>false</isActive>
                    <label>Financement</label>
                </value>
                <value>
                    <fullName>Finanzas</fullName>
                    <isActive>false</isActive>
                    <label>Finanzas</label>
                </value>
                <value>
                    <fullName>Finanze</fullName>
                    <isActive>false</isActive>
                    <label>Finanze</label>
                </value>
                <value>
                    <fullName>Finanzen</fullName>
                    <isActive>false</isActive>
                    <label>Finanzen</label>
                </value>
                <value>
                    <fullName>Flight Operation</fullName>
                    <isActive>false</isActive>
                    <label>Flight Operation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Senior_Contact_Email__c</fullName>
        <description>The Email for the Senior Contacts only</description>
        <label>Senior Contact - Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>User_Portal_Status__c</fullName>
        <label>User Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved User</fullName>
                </value>
                <value>
                    <fullName>Approved Admin</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Regional Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OneIdProfileCompanySettingsTest.cls
@IsTest
private class OneIdProfileCompanySettingsTest {
    
     @isTest static void testMethod01()
     {  
        
        UserRole ur = [SELECT id  FROM UserRole where DeveloperName = 'TAPPartnerUser'];
        
        Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal (Partner)'];
        
        Contact con = [select id, email,firstName,lastname,accountid from contact where Senior_Contact_Email__c = 'senior@dev.com'  limit 1 ];
        System.assert(con != null, 'User Contact is null');
        
        User newUser = ISSP_ObjectFactory.createPortalUser(con);   
         
        con.OwnerId = newUser.Id;
        update con;                                     
        
        System.runAs (newUser){
         
            Test.startTest();
          
            system.debug('Running as user: ' + newUser);
             
            Contact cnt = OneIdProfileCompanySettings.getUserContact();
         
            System.assert(Cnt != null, 'Contact is null');
         
            OneIdProfileCompanySettings.getCategoryPicklistValues();         
            OneIdProfileCompanySettings.getPreferredLanguagePicklistValues();
            OneIdProfileCompanySettings.getUserInfo();         
            OneIdProfileCompanySettings.saveProfileEdit('string' , 'string1', 'string2', 'string3', 'string4', 'string5', 'string6', 'string7');               

            Test.stopTest();
            
            /*EM The functionality used to create the contact has been completely changed
            system.assertEquals('test', [Select Firstname From Contact where id=:con.id].Firstname);        
            system.assertEquals('string2',[Select Phone From Contact where id=:con.id].Phone);
            system.assertEquals('string3',[Select MobilePhone From Contact where id=:con.id].Phone);
            system.assertEquals('string4',[Select Fax From Contact Where id=:con.id].Fax);
            system.assertEquals('string5',[Select Title From Contact Where id =:con.id].Title);
            system.assertEquals('string6',[Select Membership_Function__c From Contact Where id=:con.id].Membership_Function__c);
            system.assertEquals('string7',[Select Preferred_Language__c From Contact Where id =:con.id].Preferred_Language__c); */
         
        }
           
    }
     
    @testSetup static void setup() {
        Id recordTypeId = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline');
        Account acc = ISSP_ObjectFactory.createNewAccount();
        acc.RecordTypeId = recordTypeId;       
        insert acc;
          
        Contact con = ISSP_ObjectFactory.createNewContact();
        con.Senior_Contact_Email__c = 'senior@dev.com';
        con.AccountId= acc.Id;
        con.User_Portal_Status__c = 'Approved User';
        insert con;

    }     

}