src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ANG_Accreditation_Model__c</fullName>
        <description>To store Accreditation Model selected by the agency.</description>
        <label>Accreditation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Accreditation_Models</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operation</label>
        <referenceTo>AMS_Operation__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>IATA_Agency</fullName>
        <active>true</active>
        <description>The new record type for ALL Agencies with NEW data model - Use this for all Agencies</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AMS_Accreditation_Country_CheckList__c.object
<CustomObject>
    <description>Used to display Country HO &amp; Branch requirements for the online accreditation application process</description>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related ISO Country</description>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>AMS Accreditation Country Checklists</relationshipLabel>
        <relationshipName>AMS_Accreditation_Country_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>Values must correspond to Sector on Account</description>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Travel Agent</fullName>
                </value>
                <value>
                    <fullName>Cargo Agent</fullName>
                </value>
                <value>
                    <fullName>Travel Agent - International</fullName>
                </value>
                <value>
                    <fullName>Travel Agent - Domestic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AMS Accreditation Country Checklist</label>
    <nameField>
        <displayFormat>AMS-CHECKLIST-{0000}</displayFormat>
        <label>AMS Accreditation Country Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Accreditation Country Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Accreditation_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>AMS_Accreditation_Country_CheckList__c</fullName>
        <label>AMS Accreditation Country Requirement</label>
        <referenceTo>AMS_Accreditation_Country_CheckList__c</referenceTo>
        <relationshipLabel>Accreditation Requirements</relationshipLabel>
        <relationshipName>AMS_Accreditation_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ANG_Accreditation_Model__c</fullName>
        <label>Accreditation Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Accreditation_Models</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_type__c</fullName>
        <label>Location type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Branch</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requirement_text__c</fullName>
        <label>Requirement text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>AMS Accreditation Requirement</label>
    <nameField>
        <label>AMS Accreditation Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AMS Accreditation Requirements</pluralLabel>
    <recordTypes>
        <fullName>Travel_Agent</fullName>
        <active>true</active>
        <label>Travel Agent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AP_Country_Requierment__c.object
<CustomObject>
    <description>Used for airline participation to define the country requirement depending on the business line selected.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>AP Country  Requirements</relationshipLabel>
        <relationshipName>AP_Country_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Line_of_business__c</fullName>
        <label>Line of business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BSP</fullName>
                </value>
                <value>
                    <fullName>CASS</fullName>
                </value>
                <value>
                    <fullName>ICH</fullName>
                </value>
                <value>
                    <fullName>PASS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AP Country  Requirement</label>
    <nameField>
        <label>AP Country  Requierment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Country  Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas, The</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Portugal</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ANG_Enable_NewGen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To enable the agency’s country to use the new accreditations model used in NewGen and Risk Event</description>
        <label>New Accr. Model &amp; Risk Events enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ANG_Accreditation_Model__c</fullName>
        <formula>TEXT(Contact.Account.ANG_Accreditation_Model__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accreditation Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/ANG_Accreditation_Models.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Cashless</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Multicountry</fullName>
    </customValue>
    <customValue>
        <fullName>CNS Endorsement</fullName>
    </customValue>
    <masterLabel>Accreditation Models</masterLabel>
</GlobalValueSet>

src/classes/ISSP_Ctrl_Country_Requirements_Test.cls
@isTest
private class ISSP_Ctrl_Country_Requirements_Test {
	static list<IATA_ISO_Country__c> listCountries;

	@testSetup static void setup() {
		IATA_ISO_Country__c c1 = new IATA_ISO_Country__c(Name = 'Switzerland', ISO_Code__c = 'CH', ANG_Enable_NewGen__c = true);
		IATA_ISO_Country__c c2 = new IATA_ISO_Country__c(Name = 'Canada', ISO_Code__c = 'CA');
		IATA_ISO_Country__c c3 = new IATA_ISO_Country__c(Name = 'Portugal', ISO_Code__c = 'PT', ANG_Enable_NewGen__c = true);

		insert new List<IATA_ISO_Country__c>{c1, c2, c3};
		
		AP_Country_Requierment__c apcr1 = new AP_Country_Requierment__c(Name = 'Req1', 
																		Country__c = c1.Id,
																		Line_of_business__c = 'BSP');

		AP_Country_Requierment__c apcr2 = new AP_Country_Requierment__c(Name = 'Req2',
																		Country__c = c2.Id,
																		Line_of_business__c = 'CASS');
		
		AP_Country_Requierment__c apcr3 = new AP_Country_Requierment__c(Name = 'Req3',
																		Country__c = c3.Id,
																		Line_of_business__c = 'XPTO');
	
		insert new List<AP_Country_Requierment__c>{apcr1, apcr2, apcr3};
		
		AMS_Accreditation_Country_CheckList__c cc1 = new AMS_Accreditation_Country_CheckList__c(IATA_ISO_Country__c = c3.Id,
																								Operation__c = 'Airline');

		AMS_Accreditation_Country_CheckList__c cc2 = new AMS_Accreditation_Country_CheckList__c(IATA_ISO_Country__c = c3.Id,
																								Operation__c = 'Travel Agent');

		AMS_Accreditation_Country_CheckList__c cc3 = new AMS_Accreditation_Country_CheckList__c(IATA_ISO_Country__c = c1.Id,
																								Operation__c = 'Travel Agent');

		insert new List<AMS_Accreditation_Country_CheckList__c>{cc1, cc2, cc3};

		AMS_Accreditation_Requirement__c ar1 = new AMS_Accreditation_Requirement__c(AMS_Accreditation_Country_CheckList__c = cc1.id,
																					Name = 'Name1',
																					Requirement_text__c = 'Text1',
																					Location_type__c = 'HO',
																					ANG_Accreditation_Model__c = 'Legacy',
																					Language__c = 'en_AU');

		AMS_Accreditation_Requirement__c ar2 = new AMS_Accreditation_Requirement__c(AMS_Accreditation_Country_CheckList__c = cc1.id,
																					Name = 'Name2',
																					Requirement_text__c = 'Text2',
																					Location_type__c = 'HO',
																					ANG_Accreditation_Model__c = 'Cash',
																					Language__c = 'pt_PT');

		AMS_Accreditation_Requirement__c ar3 = new AMS_Accreditation_Requirement__c(AMS_Accreditation_Country_CheckList__c = cc1.id,
																					Name = 'Name3',
																					Requirement_text__c = 'Text3',
																					Location_type__c = 'HO',
																					ANG_Accreditation_Model__c = 'Cashless',
																					Language__c = 'de');

		AMS_Accreditation_Requirement__c ar4 = new AMS_Accreditation_Requirement__c(AMS_Accreditation_Country_CheckList__c = cc2.id,
																					Name = 'Name3',
																					Requirement_text__c = 'Text3',
																					Location_type__c = 'HO',
																					ANG_Accreditation_Model__c = 'Legacy',
																					Language__c = 'de');

		AMS_Accreditation_Requirement__c ar5 = new AMS_Accreditation_Requirement__c(AMS_Accreditation_Country_CheckList__c = cc3.id,
																					Name = 'Name3',
																					Requirement_text__c = 'Text3',
																					Location_type__c = 'HO',
																					ANG_Accreditation_Model__c = 'Legacy',
																					Language__c = 'de');		

		insert new List<AMS_Accreditation_Requirement__c>{ar1, ar2, ar3, ar4, ar5};
	}

	@isTest static void test_Controller() {
		Test.startTest();
		ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();
		Test.stopTest();

		System.assertEquals(controller.countryRequirement,null);
	}

	@isTest static void test_GetCountries() {
		ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();

		Test.startTest();
		List<SelectOption> listResult = controller.getCountries();
		Test.stopTest();

		// 2 elements + null value
		System.assertEquals(listResult.size(),4);
	}

	@isTest static void test_GetParticipationTypes() {
		ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();

		Test.startTest();
		List<SelectOption> listResult = controller.getParticipationTypes();
		Test.stopTest();

		// 2 elements + null value
		System.assertEquals(listResult.size(),3);
	}

	// with type filter, 1 results
	@isTest static void test_ControllerWithTypeFilter() {
		Test.startTest();
		ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();
		controller.typeFilter = 'CASS';
		controller.runSearch();
		Test.stopTest();

        System.assert(controller.countryRequirement==null);
	}

	// with country filter, 1 results
	@isTest static void test_ControllerWithCountryFilter() {
		Test.startTest();
		ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();
		controller.countryFilter = [Select Id from IATA_ISO_Country__c where Name = 'Canada'].id;
        controller.typeFilter = 'CASS';
		controller.runSearch();
		Test.stopTest();

        System.assert(controller.countryRequirement!=null);
	}

	// with string filter, 1 results
	@isTest static void test_ControllerWithStringFilter() {
		Test.startTest();
		ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();
		controller.searchFilter = 'Req1';
		controller.runSearch();
		Test.stopTest();

        System.assert(controller.countryRequirement==null);
	}

    private static User createPortalUser() {
        Account account = ISSP_ObjectFactory.createNewAccount();
        insert account;

        Contact con = ISSP_ObjectFactory.createNewContact();
        con.AccountId = account.Id;
        con.Email = 'Test@test11.com';
        insert con;

        User newUser = ISSP_ObjectFactory.createPortalUser(con);
        con.OwnerId = newUser.Id;
        update con;

        newUser = [Select Id, ContactId from User where Id = :newUser.Id];
        return newUser;
     }

    @isTest static void test_checkAccess_False() {
        User testUser = ISSP_Ctrl_AccountStatements_AcceptTest.createPortalUser();

        PageReference result;
        Test.startTest();
        System.runAs(testUser) {
            ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();
            result = controller.checkAccess();
        }
        Test.stopTest();

        System.assert(result!=null);
    }

    @isTest static void test_checkAccess_True() {
    	IATA_ISO_Country__c country = [SELECT Id FROM IATA_ISO_Country__c WHERE Name = 'Portugal'];

        User testUser = ISSP_Ctrl_AccountStatements_AcceptTest.createPortalUser();

        Account acc = [Select Sector__c from Account limit 1];
        acc.Sector__c = 'Airline';
        acc.IATACode__c = '1234567890';
        acc.IATA_ISO_Country__c = country.Id;
        update acc;

        PageReference result;
        Test.startTest();

        System.runAs(testUser) {
            ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();
            result = controller.checkAccess();
            controller.getNewLayout();
            controller.getCountryRequirementsList();
            controller.getAccreditationTypes();
            controller.refreshRequirementsList();
        }	

        Test.stopTest();

        System.assert(result==null);
    }

    @isTest static void test_checkAccess_True_2() {
    	IATA_ISO_Country__c country = [SELECT Id FROM IATA_ISO_Country__c WHERE Name = 'Portugal'];

        Account topParent = new Account (
                name = 'AccountTest',
                IATA_ISO_Country__c = country.Id,
                Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_IEP_Status__c = ANG_ISSP_PortalServiceHelper.STATUS_OPEN,
                Location_type__c = 'HE',
				Location_Class__c = 'P'
            );

        insert topParent;

        Account a = new Account (
                name = 'AccountTest',
                IATA_ISO_Country__c = country.Id,
                Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_IEP_Status__c = ANG_ISSP_PortalServiceHelper.STATUS_OPEN,
                Location_type__c = 'HE',
                status__c = 'Approved',
                Top_Parent__c = topParent.id,
				Location_Class__c = 'P'
            );

        insert a;

        User testUser = ISSP_Ctrl_AccountStatements_AcceptTest.createPortalUser();
        
        PageReference result;
        Test.startTest();

        System.runAs(testUser) {
            ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();

            controller.getLanguagesMap();
            controller.getCountryRequirementsList();
        }	

        Test.stopTest();

        System.assert(result==null);
    } 

    @isTest static void test_getCountryRequirementsList() {
    	IATA_ISO_Country__c country = [SELECT Id FROM IATA_ISO_Country__c WHERE Name = 'Portugal'];

        User testUser = ISSP_Ctrl_AccountStatements_AcceptTest.createPortalUser();

        Account acc = [Select Sector__c from Account limit 1];
        acc.Sector__c = 'Travel Agent';
        acc.IATACode__c = '1234567890';
        acc.Location_type__c = 'HO';
        acc.IATA_ISO_Country__c = country.Id;
        update acc;

        PageReference result;
        Test.startTest();

        System.runAs(testUser) {
            ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();
            result = controller.checkAccess();
            controller.getNewLayout();
            controller.getCountryRequirementsList();
            controller.getAccreditationTypes();
            controller.refreshRequirementsList();
        }	

        Test.stopTest();
    }

    @isTest static void test_getCountryRequirementsList2() {
    	IATA_ISO_Country__c country = [SELECT Id FROM IATA_ISO_Country__c WHERE Name = 'Switzerland'];

        User testUser = ISSP_Ctrl_AccountStatements_AcceptTest.createPortalUser();

        Account acc = [Select Sector__c from Account limit 1];
        acc.recordTypeId = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');
        acc.Sector__c = 'Travel Agent';
        acc.IATACode__c = '1234567890';
        acc.Location_type__c = 'HO';
        acc.Status__c = 'Approved';
        acc.Category__c = AMS_UTILS.CATEGORY_PASSENGER_SALES_AGENT;
        acc.IATA_ISO_Country__c = country.Id;
        update acc;

        PageReference result;
        Test.startTest();

        System.runAs(testUser) {
            ISSP_Ctrl_Country_Requirements controller = new ISSP_Ctrl_Country_Requirements();
            result = controller.checkAccess();
            controller.getNewLayout();
            controller.getCountryRequirementsList();
            controller.getAccreditationTypes();
            controller.refreshRequirementsList();
        }	

        Test.stopTest();
    }
}