src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Role__c</fullName>
        <description>The roles covered by the account (e.g. Payment Provider)</description>
        <inlineHelpText>The roles covered by the account</inlineHelpText>
        <label>Account Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Payment Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Role__c.object
<CustomObject>
    <description>Used to extend the role of any existing account type e.g. an airline that also acts as a payment provider. A record type should be created for each type of account role required.</description>
    <fields>
        <fullName>Account_Role_Name__c</fullName>
        <description>A functional role that an Account may assume when interacting with an IATA Salesforce functional capability. This designation technically supports the provisioning of IATA Salesforce functional capabilities.

The Account Role record should be named after the functional capability for which the record applies. If required, Account related data, within the context of the functional capability, could be held on a related Account Role Detail record.</description>
        <inlineHelpText>Account Role Name to fill accordingly to the application using the record</inlineHelpText>
        <label>Account Role Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Id to account record</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Role</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Airport_Detail__c.object
<CustomObject>
    <description>Represents Airport related data and must be related to an Account where data for the airport as a legal entity is stored.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account representing the Airport as a legal entity.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Airport Details</relationshipLabel>
        <relationshipName>Airport_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Airports</relationshipLabel>
        <relationshipName>Airports</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Airport Detail</label>
    <nameField>
        <displayFormat>APD-{0000000000}</displayFormat>
        <label>Airport Autoname</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airport Details</pluralLabel>
    <recordTypes>
        <fullName>Airport</fullName>
        <active>true</active>
        <description>Airports&apos; location information.</description>
        <label>Airport</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ICG_Account_Role_Detail__c.object
<CustomObject>
    <description>One Source Facilities</description>
    <fields>
        <fullName>Account_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Account_Role__c</description>
        <label>Link to Station Account</label>
        <referenceTo>Account_Role__c</referenceTo>
        <relationshipLabel>ONE Source Stations</relationshipLabel>
        <relationshipName>ICG_Account_Role_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to IATA_ISO_Country__c object</description>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>ONE Source Account Role Details</relationshipLabel>
        <relationshipName>ICG_Account_Role_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OS Account Role Detail</label>
    <nameField>
        <label>ONE Source Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OS Account Role Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>License_Cost_Center__c</fullName>
        <inlineHelpText>The IATA cost center that is paying for your Salesforce.com license.</inlineHelpText>
        <label>License Cost Center</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CW_EmailManagerTest.cls
@isTest
public class CW_EmailManagerTest {


	@TestSetup
	private static void setup(){
		String orgId=UserInfo.getOrganizationId(); 
		Profile pf= [Select Id from profile where Name = 'System Administrator' limit 1]; 
		String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
		Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
		String uniqueName=orgId+dateString+RandomId;

		IATA_ISO_Country__c isoCode = CW_TestDataFactory.newISOCountry();
		insert isoCode;

		Account acc = new Account (Name = 'Account01', IATA_ISO_Country__c = isoCode.Id);
		insert acc;

				
		Airport_Detail__c airport = CW_TestDataFactory.newAirport(isoCode.Id, acc.Id);
		insert airport;

		Account_Role__c accRole = new Account_Role__c(Account_Role_Name__c = 'Test', Account__c = acc.Id);
		insert accRole;

		ICG_Account_Role_Detail__c ard = CW_TestDataFactory.testICGAccountRoleDetail(accRole.Id, airport);
		insert ard;

		User uu=new User(firstname = 'IATAICGABCUnique', 
		lastName = 'IATAICGXYZUnique', 
		email = uniqueName + '@test' + orgId + '.org', 
		Username = uniqueName + '@test' + orgId + '.org', 
		EmailEncodingKey = 'ISO-8859-1', 
		Alias = uniqueName.substring(18, 23), 
		TimeZoneSidKey = 'America/Los_Angeles', 
		LocaleSidKey = 'en_US', 
		LanguageLocaleKey = 'en_US', 
		ProfileId = pf.Id,
		License_Cost_Center__c = 'XSMW01JO01'
	   );

		insert uu;

		System.runAs(uu) {

			Group gro = new Group(Name = 'TheTestQueue', type = 'Queue');
			insert gro;
			
			GroupMember member = new GroupMember();
			member.UserOrGroupId = uu.Id;
			member.GroupId = gro.Id;
			insert member;
			
			Group groStakeholders = new Group(Name = 'ICG_Stakeholders');
			insert groStakeholders;
			
			GroupMember stakeholderMember = new GroupMember();
			stakeholderMember.UserOrGroupId = uu.Id;
			stakeholderMember.GroupId = groStakeholders.Id;
			insert stakeholderMember;

			EmailTemplate template = new EmailTemplate();
			template.DeveloperName = 'Approve_Reject_to_company_admin';
			template.Name = 'Test';
			template.FolderId = uu.Id;
			template.TemplateType = 'text';
			template.isActive = true;
			insert template;
		}
	}

	@isTest 
	public static void prepareInternalEmails(){
		Test.startTest();

		ICG_Account_Role_Detail__c station = [Select Id from ICG_Account_Role_Detail__c LIMIT 1];
		List<User> iataAdmins = [Select id, name, email from User where Id IN (Select UserOrGroupId from GroupMember Where Group.Name = 'TheTestQueue')];
		Set<Id> whoIds = new Set<Id>();
		for(User us : iataAdmins){
			whoIds.add(us.Id);
		}
		
		String emailTemplate = 'Approve_Reject_to_company_admin';
		List<Messaging.SingleEmailMessage> emails =  CW_EmailManager.prepareInternalEmails(emailTemplate, station.Id, whoIds);
		System.assert(!emails.isEmpty(), 'No emails were prepared');
		Test.stopTest();
	}

	@isTest 
	public static void prepareInternalEmailsEmpty(){
		Test.startTest();

		String emailTemplate = 'Approve_Reject_to_company_admin';
		List<Messaging.SingleEmailMessage> emails =  CW_EmailManager.prepareInternalEmails(emailTemplate, null, new Set<Id>());
		System.assert(emails.isEmpty(), 'Emails were prepared when it should have been empty');
		Test.stopTest();
	}

	@isTest 
	public static void sendInternalEmails(){
		Test.startTest();

		ICG_Account_Role_Detail__c station = [Select Id from ICG_Account_Role_Detail__c LIMIT 1];
		List<User> iataAdmins = [Select id, name, email from User where Id IN (Select UserOrGroupId from GroupMember where Group.DeveloperName = 'ICG_Stakeholders')];
		Set<Id> whoIds = new Set<Id>();
		for(User us : iataAdmins){
			whoIds.add(us.Id);
		}
		
		String emailTemplate = 'Approve_Reject_to_company_admin';
		List<Messaging.SingleEmailMessage> emails =  CW_EmailManager.prepareInternalEmails(emailTemplate, station.Id, whoIds);
		Boolean result = CW_EmailManager.sendInternalEmails(emails);

		System.assert(!result, 'Emails were not sent successfully');
		Test.stopTest();
	}

	@isTest 
	public static void sendInternalEmailsEmpty(){
		Test.startTest();
		Boolean result = CW_EmailManager.sendInternalEmails(new List<Messaging.SingleEmailMessage>());
		System.assert(!result, 'Emails were successful even when they should not have been sent');
		Test.stopTest();
	}

	@isTest 
	public static void getIataAdminsIds(){
		Test.startTest();
		Set<Id> iataAdmins = CW_EmailManager.getIataAdminsIds();
		System.assert(!iataAdmins.isEmpty(), 'No iata admins were generated');
		Test.stopTest();
	}

	@isTest 
	public static void getCompanyAdminsIds(){
		Test.startTest();
		String accountId = [Select Id from Account Limit 1].Id;
		Contact con = CW_TestDataFactory.testContact(accountId);
		insert con;

		Set<Id> companyAdmins = CW_EmailManager.getCompanyAdminsIds(accountId);
		System.assert(!companyAdmins.isEmpty(), 'No company admins were generated');
		Test.stopTest();
	}
	
}