src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <description>IEC - type of customer</description>
        <label>Ecommerce Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member Airline</fullName>
                </value>
                <value>
                    <fullName>Non-member</fullName>
                    <default>true</default>
                    <label>Non-member</label>
                </value>
                <value>
                    <fullName>Accredited Training Schools (ATS)</fullName>
                </value>
                <value>
                    <fullName>Accredited Training Center (ATC)</fullName>
                </value>
                <value>
                    <fullName>Sales Agents (Platinum)</fullName>
                </value>
                <value>
                    <fullName>Sales Agents (Generic)</fullName>
                </value>
                <value>
                    <fullName>Strategic Partners</fullName>
                </value>
                <value>
                    <fullName>IATA Employees (work related reason)</fullName>
                </value>
                <value>
                    <fullName>IATA Employee (commercial purposes)</fullName>
                </value>
                <value>
                    <fullName>Service Providers</fullName>
                </value>
                <value>
                    <fullName>Sales Agent (Generic 2)</fullName>
                </value>
                <value>
                    <fullName>Sales Agent (Startup)</fullName>
                </value>
                <value>
                    <fullName>CNS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ICH_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ICH Member</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>IEC - Mapping between Salesforce and SAP for customer</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>IEC - Reference to account serving as SAP sold to</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Id__c</fullName>
        <label>SAP Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sold To</fullName>
                </value>
                <value>
                    <fullName>Bill To</fullName>
                </value>
                <value>
                    <fullName>Ship To</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Location</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SAP_Account__c.object
<CustomObject>
    <description>Represents an account on SAP</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SAP Accounts</relationshipLabel>
        <relationshipName>SAP_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GDP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SAP Account used by the e-Commerce GDP products. Only one SAP Account can be selected as GDP per Account.</description>
        <inlineHelpText>SAP Account used by the e-Commerce GDP products. Only one SAP Account can be selected as GDP per Account.</inlineHelpText>
        <label>GDP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <label>SAP ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SAP Account</label>
    <nameField>
        <displayFormat>SAP-{0000}</displayFormat>
        <label>Internal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Customer_type__c</fullName>
        <formula>CASE(Contact.Account.RecordType.Name, 
   &quot;Agency&quot;, If( OR(Contact.Account.CNS_Account__c, Contact.Account.CNS_Agency__c),&quot;CNS Agency&quot;, &quot;Agency&quot;),
   &quot;Airline Branch&quot;, &quot;Airline&quot;,
   &quot;Airline Headquarters&quot;, &quot;Airline&quot;,
   &quot;General Sales Agent Branch&quot;,IF(ISBLANK(Contact.Account.IATACode__c), &quot;GSA&quot;, &quot;GSSA&quot;),
   &quot;General Sales Agent Headquarters&quot;, IF(ISBLANK(Contact.Account.IATACode__c), &quot;GSA&quot;, &quot;GSSA&quot;),
   &quot;Other&quot;)+
If( Contact.Account.ICH_Member__c = true,&quot;ICH&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Customer_DTO.cls
public class Customer_DTO 
{
	private static Customer_DTO singleton = null;

	public User sfUser { get; set; }
    public Contact sfContact { get; set; }
    public Account sfAccount { get; set; }
    public String customerType { get; set; }

    public Address_DTO soldTo{get;set;}
    public Address_DTO billTo{get;set;}
    public List<Address_DTO> shipTos{get;set;}

    public Zuora__CustomerAccount__c zBillingAccount { get{
        if(zBillingAccount == null){
            Map<Id,Zuora__CustomerAccount__c> sfAccId_ZcustAccount = CustomerAccount_Sel.getZuoraCustmerAccount(new Set<Id>{sfContact.Id});
            zBillingAccount = (Test.isRunningTest()) ? IECZuoraHelper.getBillingAccountByContactId(sfContact.Id) : sfAccId_ZcustAccount.get(sfContact.Id);
        }
        return zBillingAccount;
    } set; }

    public Zuora.zObject zAccount{get{
        if(zAccount == null){
            zAccount = (Test.isRunningTest()) ? IECTestUtil.createSampleZuoraAccount('99999', sfAccount.Id, sfContact.Id) : IECZuoraHelper.getZuoraAccountBySFAccountId(sfAccount.Id, sfContact.Id);   
        }
        return zAccount;
    }set;}

    public List<IEC_CreditCard_DTO> creditCards {get{
        if(creditCards == null){
            loadCreditCards();
        }
        return creditCards;
    }set;}

    public void loadCreditCards()
    {
        creditCards = new List<IEC_CreditCard_DTO>(); 

        try
        {
            List<Zuora.zObject> z_creditCards = new List<Zuora.zObject>();
            
            if (!Test.isRunningTest()) {
                if(zAccount != null) z_creditCards = IECSubscriptionManager.getCreditCardsByAccountZId((String)zAccount.getValue('Id'));
            }
            else {
                z_creditCards.add(IECTestUtil.createSampleZuoraPaymentMethod('111', (String)zAccount.getValue('Id'), 2010, 1));
                z_creditCards.add(IECTestUtil.createSampleZuoraPaymentMethod('222', (String)zAccount.getValue('Id'), 2100, 1));
                z_creditCards.add(IECTestUtil.createSampleZuoraPaymentMethod('333', (String)zAccount.getValue('Id'), 2200, 1));
            }

            for(Zuora.zObject zCard : z_creditCards)
            {
                creditCards.add(new IEC_CreditCard_DTO(zAccount, zCard));
            }
        }
        catch(Exception ex)
        {
            System.debug('Error fetching credit cards::'+ex.getMessage());
        }   

    }

    public void loadActiveCreditCards()
    {
        creditCards = new List<IEC_CreditCard_DTO>(); 

        List<Zuora.zObject> z_creditCards = new List<Zuora.zObject>();
        
        if (!Test.isRunningTest()) {
            if(zAccount != null) z_creditCards = IECSubscriptionManager.getCreditCardsByAccountZId((String)zAccount.getValue('Id'));
        }
        else {
            z_creditCards.add(IECTestUtil.createSampleZuoraPaymentMethod('111', (String)zAccount.getValue('Id'), 2010, 1));
            z_creditCards.add(IECTestUtil.createSampleZuoraPaymentMethod('222', (String)zAccount.getValue('Id'), 2100, 1));
            z_creditCards.add(IECTestUtil.createSampleZuoraPaymentMethod('333', (String)zAccount.getValue('Id'), 2200, 1));
        }

        for(Zuora.zObject zCard : z_creditCards)
        {
            IEC_CreditCard_DTO cc = new IEC_CreditCard_DTO(zAccount, zCard);
           
            if(!cc.isExpired) 
                creditCards.add(cc);
        }
    }


    public Boolean canPayByICH()
    {
        // first validate if the customer is part of a Member Airline account
        if (sfAccount.Customer_Type__c != IECConstants.Account_ClientType_MemberAirline) return false;
            
        
        // check if Parent Account have access to ICH
        if (sfAccount.ParentId != null) 
        {
            Account oParentAccount = IECUserManager.getAccountById(sfAccount.ParentId);
            if (oParentAccount != null && oParentAccount.ICH_Member__c) return true;
        }
        
        // Make sure that there is a SAP Account configured
        List<SAP_Account__c> lstSAPAcc = [SELECT SAP_ID__c FROM SAP_Account__c WHERE Account__c = :sfAccount.Id AND  GDP__c  = true ];
        if (lstSAPAcc.size() == 0 || lstSAPAcc.get(0).SAP_ID__c == null) return false;
        
        // check if Account have access to ICH
        return (sfAccount != null && sfAccount.ICH_Member__c);
    }

    public static Customer_DTO getLoggedCustomer()
    {
    	//-- If logged user 
    	if(UserInfo.getUserType() == 'PowerPartner')
    	{
    		if(singleton == null)
	    	{
	    		Customer_DTO customer = getCustomerByUser(UserInfo.getUserId());  
                
                //-- Build Customer addresses 
                setCustomerAddresses(customer);
				singleton = customer; 
	    	}

	    	return singleton;
    	}
    	//-- Non logged user 
    	else
    	{
    		return null; 
    	}	
    }

    public static Customer_DTO getCustomerByUser(Id userId)
    {
        User_Sel uSelector = new User_Sel(); 
        Account_Sel aSelector = new Account_Sel(); 

        Customer_DTO customer = new Customer_DTO(); 
            customer.sfUser = uSelector.getUserDetails(userId); 
            customer.sfContact = Contact_Sel.getContactById(new Set<Id> {customer.sfUser.ContactId}).get(customer.sfUser.ContactId);
            customer.sfAccount = aSelector.getAccountById(customer.sfContact.AccountId);
            customer.customerType = customer.sfAccount.Customer_Type__c;

        return customer;
    }


    public static void setCustomerAddresses(Customer_DTO customer)
    {
        Location_Sel lSelector = new Location_Sel();
        Id contactId = customer.sfContact.Id;
                
        Location__c soldToLocation = lSelector.getSoldToLocationByContactId(new Set<Id>{contactId}).get(contactId);
        customer.soldTo = Address_DTO.format2DTO(soldToLocation);

        List<Location__c> locations =  lSelector.getContactsLocations(new Set<Id>{contactId}).values();
        for(Location__c loc : locations)
        {
            if(loc.Type__c == IECConstants.BILLTO)
            {
                customer.billTo = Address_DTO.format2DTO(loc);
            }
            else if(loc.Type__c == IECConstants.SHIPTO)
            {
                if(customer.shipTos == null)
                {
                    customer.shipTos = new List<Address_DTO>();
                }
                
                customer.shipTos.add(Address_DTO.format2DTO(loc));
            }
        }
    }

    public static void saveBillToAddress(Customer_DTO customer)
    {
        update customer.sfContact; 

    }
}