src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Role__c</fullName>
        <description>The roles covered by the account (e.g. Payment Provider)</description>
        <inlineHelpText>The roles covered by the account</inlineHelpText>
        <label>Account Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Payment Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account__e.object
<CustomObject>
    <description>Platform event definition to be used for ALL Account record changes that require an integration with MuleSoft.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>18 character, case insensitive, Salesforce record Id representing the record that was modified.</description>
        <label>AccountId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <description>The name of the record type of the record that was changed.</description>
        <label>RecordType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of operation that resulted in the platform event being fired (Create, Update, Delete, Undelete).</description>
        <label>Type</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account PE</label>
    <pluralLabel>Accounts PE</pluralLabel>
</CustomObject>

src/objects/Account_Contact_Role__c.object
<CustomObject>
    <description>Related to the Account Role, used to designate an existing contact, under the account, that acts as a primary contact for the associated type of account role.</description>
    <fields>
        <fullName>Account_Role__c</fullName>
        <description>Reference to the Account Role</description>
        <label>Account Role</label>
        <referenceTo>Account_Role__c</referenceTo>
        <relationshipLabel>Account Contacts Role</relationshipLabel>
        <relationshipName>Account_Contacts_Role</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the account referenced</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts Role</relationshipLabel>
        <relationshipName>Account_Contacts_Role</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Contact Role</label>
    <nameField>
        <displayFormat>ACR-{000000000}</displayFormat>
        <label>Account Contact Role Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts Role</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AccountContactRole__e.object
<CustomObject>
    <description>Platform event definition to be used for ALL Account Contact Role record changes that require an integration with middleware.</description>
    <fields>
        <fullName>EventType__c</fullName>
        <description>The type of operation that resulted in the platform event being fired (Create, Update, Delete, Undelete).</description>
        <label>EventType</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>8 character, case insensitive, Salesforce record Id representing the record that was modified.</description>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <description>The name of the record type of the record that was changed.</description>
        <label>RecordType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Contact Role PE</label>
    <pluralLabel>Account Contact Roles PE</pluralLabel>
</CustomObject>

src/objects/AccountRole__e.object
<CustomObject>
    <description>Platform event definition to be used for ALL Account Role record changes that require an integration with middleware.</description>
    <fields>
        <fullName>EventType__c</fullName>
        <description>The type of operation that resulted in the platform event being fired (Create, Update, Delete, Undelete).</description>
        <label>EventType</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>18 character, case insensitive, Salesforce record Id representing the record that was modified.</description>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <description>The name of the record type of the record that was changed.</description>
        <label>RecordType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Role PE</label>
    <pluralLabel>Account Roles PE</pluralLabel>
</CustomObject>

src/objects/Contact__e.object
<CustomObject>
    <description>Platform event published when a contact is created, updated, deleted or undeleted</description>
    <fields>
        <fullName>EventType__c</fullName>
        <label>EventType</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <label>RecordType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contact PE</label>
    <pluralLabel>Contacts PE</pluralLabel>
</CustomObject>

src/objects/ISSP_Web_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Input_Description__c</fullName>
        <label>Input Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Service__c</fullName>
        <label>Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ISSP Web Service Log</label>
    <nameField>
        <displayFormat>WSL-{00000000}</displayFormat>
        <label>ISSP Web Service Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ISSP Web Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PartnerProduct__e.object
<CustomObject>
    <description>Platform event definition to be used for ALL Partner Product record changes that require an integration with middleware.</description>
    <fields>
        <fullName>EventType__c</fullName>
        <description>The type of operation that resulted in the platform event being fired (Create, Update, Delete, Undelete).</description>
        <label>EventType</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>18 character, case insensitive, Salesforce record Id representing the record that was modified.</description>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <description>The name of the record type of the record that was changed.</description>
        <label>RecordType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Product PE</label>
    <pluralLabel>Partner Products PE</pluralLabel>
</CustomObject>

src/objects/Product_Bin_Range__e.object
<CustomObject>
    <description>Platform event definition to be used for ALL Product Bin Range record changes that require an integration with middleware.</description>
    <fields>
        <fullName>EventType__c</fullName>
        <description>The type of operation that resulted in the platform event being fired (Create, Update, Delete, Undelete).</description>
        <label>EventType</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>18 character, case insensitive, Salesforce record Id representing the record that was modified.</description>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <description>The name of the record type of the record that was changed.</description>
        <label>RecordType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Bin Range PE</label>
    <pluralLabel>Product Bin Ranges PE</pluralLabel>
</CustomObject>

src/objects/Product_Country_Config__e.object
<CustomObject>
    <description>Platform event definition to be used for ALL Product Country Configuration record changes that require an integration with middleware.</description>
    <fields>
        <fullName>EventType__c</fullName>
        <description>The type of operation that resulted in the platform event being fired (Create, Update, Delete, Undelete).</description>
        <label>EventType</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>18 character, case insensitive, Salesforce record Id representing the record that was modified.</description>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <description>The name of the record type of the record that was changed.</description>
        <label>RecordType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Country Config PE</label>
    <pluralLabel>Product Country Configs PE</pluralLabel>
</CustomObject>

src/objects/RemoteInvocation__e.object
<CustomObject>
    <description>Platform event published when a Remote Invocation is created, updated, deleted or undeleted</description>
    <fields>
        <fullName>EventType__c</fullName>
        <label>EventType</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <label>RecordType</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Remote Invocation PE</label>
    <pluralLabel>Remote Invocations PE</pluralLabel>
</CustomObject>

src/classes/PlatformEvents_Helper.cls
public class PlatformEvents_Helper {
    
    public static void publishEvents(Map<Id,sObject> ObjectMap, string PE_Name, string ObjSource, boolean bIsInsert, boolean bIsUpdate, boolean bIsDelete, boolean bIsUndelete){
    	//Map that stores the name of the platform event based on the type of object received
    	map<string, string> PEObjName = new map<String,String>{
                'Account' => 'Account__e',
                'Contact' => 'Contact__e',
                'Account_Contact_Role__c' => 'AccountContactRole__e',
                'Account_Role__c' => 'AccountRole__e',
                'Partner_products__c' => 'PartnerProduct__e',
                'TIP_Pay_Prov_Prod_Country_Config__c' => 'Product_Country_Config__e',
                'TIP_BIN_Range__c' => 'Product_Bin_Range__e',
                'Remote_Invocation__c' => 'RemoteInvocation__e'
		};
          
    	
        string sEventType = '';
        if(bIsInsert) sEventType = 'Create';
        if(bIsUpdate) sEventType = 'Update';
        if(bIsDelete) sEventType = 'Delete';
        if(bIsUndelete) sEventType = 'Undelete';
        
        if(sEventType=='') return;
        
        list<ISSP_Web_Service_Log__c> lsLogs = new list<ISSP_Web_Service_Log__c>();
        
        try{
            Map<Id,sObject> InternalObjectMap = new map<id, sObject>();
            List<RecordType> rtList = RecordTypeSingleton.getInstance().getRecordTypesBySObject(ObjSource);
            
            if(ObjSource == 'Account'){
            	rtList.addAll(RecordTypeSingleton.getInstance().getRecordTypesBySObject('Account_Role__c'));
            	InternalObjectMap = getAccountRoleToPublish(ObjectMap);
            }
            else if( ObjSource =='Contact'){
                rtList.addAll(RecordTypeSingleton.getInstance().getRecordTypesBySObject('Account_Contact_Role__c'));
            	InternalObjectMap = getAccountContactRoleToPublish(ObjectMap);
            }
            else InternalObjectMap = ObjectMap;
            
            List<SObject> lstSObjs = new list<SObject>();
            
            for(Id ObjId : InternalObjectMap.keySet()){
            	map<string, string> MapMapping = getMappingMap(PEObjName.get(string.valueOf(ObjId.getsobjecttype())));
            	if(MapMapping==null) continue;
                SObject sObj = Schema.getGlobalDescribe().get(PEObjName.get(string.valueOf(ObjId.getsobjecttype()))).newSObject();
                for(string FieldSource:MapMapping.keyset()){
                    if(FieldSource=='Recordtype')
                        if(!rtList.isEmpty()) 
                            //sObj.put(MapMapping.get(FieldSource) , RecordTypeSingleton.getInstance().getRecordTypeById(ObjSource, (Id)(InternalObjectMap.get(ObjId).get('RecordtypeId'))).Name);
                            sObj.put(MapMapping.get(FieldSource) , RTName(string.valueOf(ObjId.getsobjecttype()), (Id)(InternalObjectMap.get(ObjId).get('RecordtypeId'))));
                        else
                            sObj.put(MapMapping.get(FieldSource), null);
                        
                    else if(FieldSource=='EventType')
                        sObj.put(MapMapping.get(FieldSource), sEventType);
                    
                    else if(FieldSource=='Id')
                        sObj.put(MapMapping.get(FieldSource), ObjId);
                }
                
                lstSObjs.add(sObj);
            }
        
            
            if (!Test.isRunningTest()) {
                for (Database.SaveResult sr : EventBus.publish(lstSObjs)) {
                    if (!sr.isSuccess()){
                        for(Database.Error err : sr.getErrors()) {
                            lsLogs.add(CreateLog('Platform Events for ' + ObjSource + '. Event Type: ' + sEventType
                                     , err.getStatusCode() + ' - ' + err.getMessage()
                                     , PE_Name
                                     ,'PlatformEvents_Helper.publishEvents'
                                     ,'One of the following: ' + ObjectMap.keyset()));
                        }
                    }
                }
            }
            
        }catch(exception e){
            lsLogs.add(CreateLog('Platform Events for ' + ObjSource + '. Event Type: ' + sEventType
                                 , e.getMessage()
                                 , PE_Name
                                 ,'PlatformEvents_Helper.publishEvents'
                                 ,'One of the following: ' + ObjectMap.keyset()));
        }
        
        if(!lsLogs.isEmpty()) insert lsLogs;
    }
    
    private static string RTName(string theObject, id RTId){
        if(RTId==null)  return null;
        return RecordTypeSingleton.getInstance().getRecordTypeById(theObject, RTId).Name;
    }
    
    private static map<string, string> getMappingMap(string sObj){
        if(sObj=='Account__e'){
            return new map<String,String>{
                'Id' => 'AccountId__c',
                'Recordtype' => 'RecordType__c',
                'EventType' => 'Type__c'
            };
        }
        
        if(sObj=='Contact__e' || sObj=='Product_Bin_Range__e' || sObj=='PartnerProduct__e' 
        	|| sObj=='Product_Country_Config__e' || sObj=='AccountContactRole__e' || sObj=='AccountRole__e' || sObj=='RemoteInvocation__e'){
            return new map<String,String>{
                'Id' => 'RecordId__c',
                'Recordtype' => 'RecordType__c',
                'EventType' => 'EventType__c'
            };
        }
        
        return null;
    }
    
    @TestVisible
    private static ISSP_Web_Service_Log__c CreateLog(string theSystem, string ErrMess, string PE_Name, string theMethod, string theDesc){
        return new ISSP_Web_Service_Log__c(
                        System__c = theSystem,
                        Error_Message__c = ErrMess,
                        Web_Service__c = PE_Name,
                        Method__c = theMethod,
                        Input_Description__c = theDesc
                        );
    }
    
    
    //In case there is an Account Role related to TIP, it enrich the map with it
    private static Map<Id,sObject> getAccountRoleToPublish(Map<Id,sObject> mapAccnt){
    	map<id, sObject> mapToRet = new map<id, sObject>();
    	mapToRet.putAll(mapAccnt);

        if(mapAccnt.keyset().isEmpty()) return mapToRet;

    	for(Account_Role__c AccntRole: [select id, RecordTypeId, Account__c from Account_Role__c where Account__c in:mapAccnt.keyset() and recordtypeId=:TIP_UTILS.ACCOUNT_ROLE_PAYMENT_PROVIDER_RECORDTYPE_ID]){
//    		if(mapToRet.ContainsKey(accntRole.Account__c))
//    			mapToRet.remove(accntRole.Account__c);
    		mapToRet.put(accntRole.Id, AccntRole);
    	}
    	return mapToRet;
    }
    
     //In case there is an Account Contact Role related to TIP, it enrich the map with it
    private static Map<Id,sObject> getAccountContactRoleToPublish(Map<Id,sObject> mapCnt){
    	map<id, sObject> mapToRet = new map<id, sObject>();
    	mapToRet.putAll(mapCnt);
    	for(Account_Contact_Role__c AccntConRole: [select id, RecordTypeId, Account__c from Account_Contact_Role__c where Account__c in:mapCnt.keyset() and Service_Rendered__c = 'TIP']){
//    		if(mapToRet.ContainsKey(AccntConRole.Account__c))
//    			mapToRet.remove(AccntConRole.Account__c);
    		mapToRet.put(AccntConRole.Id, AccntConRole);
    	}
    	return mapToRet;
    }
}