src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Geo_Detail__c.object
<CustomObject>
    <description>Used to define and store geological locations (identified by location specific IDs and filtered out by sub continent) of GDP Agencies</description>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <description>Related IATA ISO Country</description>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipName>IEC_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GDP Geo Detail</label>
    <nameField>
        <label>GDP Geo Detail</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP Geo Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IATA_ISO_State__c.object
<CustomObject>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>IATA ISO States</relationshipLabel>
        <relationshipName>IATA_ISO_States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <externalId>true</externalId>
        <label>ISO Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IATA ISO State</label>
    <nameField>
        <label>ISO State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IEC_Agency_Type__c.object
<CustomObject>
    <description>Represents multiple agency types used for IEC</description>
    <label>IEC Agency Type</label>
    <nameField>
        <displayFormat>AT-{000}</displayFormat>
        <label>Agency Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IEC Agency Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IEC_Application_Filter__c.object
<CustomObject>
    <description>Used to save advanced search filters by customers so they can reuse them (for now only for GAD)</description>
    <fields>
        <fullName>Product_Line__c</fullName>
        <defaultValue>&apos;GAD&apos;</defaultValue>
        <description>Product Line to create isolation between GAD, PAL, CAL ASL</description>
        <inlineHelpText>Product Line to create isolation between GAD, PAL, CAL ASL</inlineHelpText>
        <label>Product Line</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>IEC Application Filter</label>
    <nameField>
        <displayFormat>IEC-AF-{00000}</displayFormat>
        <label>IEC Application Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IEC Application Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Category__c.object
<CustomObject>
    <description>Contains the main product categories and their related information to be displayed on the product viewer page, and some extra configurations used for browsing products and rate plans.</description>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Information__c.object
<CustomObject>
    <description>Represents the Product Information in Salesforce, this Product level is configurable and linked to a parent (Product Category) and can have multiple Rate Plan information as Children</description>
    <fields>
        <fullName>Product_Audience__c</fullName>
        <label>Product Audience</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>IATA Employee</fullName>
                </value>
                <value>
                    <fullName>Strategic Member</fullName>
                </value>
                <value>
                    <fullName>Member Airline</fullName>
                </value>
                <value>
                    <fullName>Non Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Information</label>
    <nameField>
        <label>Product Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan_Information__c.object
<CustomObject>
    <description>Contains the main Rate Plans information to be displayed on the product browsing page UI</description>
    <label>Product Rate Plan Information</label>
    <nameField>
        <label>Product Rate Plan Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/vfIECGADAdvanced_tst.cls
/**  
  * Description: This class contains unit tests for the (GAD - Advanced Search) webpage 
  * Author: Samy Saied
  * Version: 1.0
  * History: 
  */
@isTest(SeeAllData=true)
private class vfIECGADAdvanced_tst {
	private static Product_Category__c oProductCategory;
	private static Product_Information__c oProductInfo;
	private static Product2 oProduct;
	private static zqu__ProductRatePlan__c oProductRatePlan;
	private static zqu__ProductRatePlanCharge__c oProductRatePlanCharge;
	private static Product_Rate_Plan_Information__c oProductRatePlanInfo;
	private static Zuora__Subscription__c subscription;
	private static Zuora__SubscriptionProductCharge__c subscriptionCharge;
	private static IEC_Application_Filter__c filter1;
	private static IEC_Application_Filter__c filter2;
	private static IEC_Application_Filter__c filter3;
	private static IEC_Application_Filter__c filter4;
	private static IEC_Application_Filter__c filter5;

	private static IATA_ISO_Country__c iataCountry;
	private static IATA_ISO_Country__c iataCountry2;
	private static IATA_ISO_State__c iataState;
	private static GDP_Geo_Detail__c gdpGeoDetail;
	private static IEC_Agency_Type__c iecAgencyType;
	
	private static IECCustomer currentCustomer;
	
	static void Init() {
		System.debug('Unit Test: Start: Init');

        oProductCategory = IECTestUtil.CreateSampleProductCategory(IECConstants.ProductCategory_SF_GAD, true);
		insert oProductCategory;
		
		oProduct = IECTestUtil.CreateSampleProduct2('PTST');
		insert oProduct;
		
		oProductInfo = IECTestUtil.CreateSampleProductInfo2('PITST', oProductCategory, oProduct);
		oProductInfo.Product_Audience__c = IECConstants.ProductInformationAudience_DEFAULT;
		insert oProductInfo;
		
		oProductRatePlan = IECTestUtil.CreateSampleProductRatePlan2('PRPTST', false, oProduct);
		insert oProductRatePlan;
		
		oProductRatePlanCharge = IECTestUtil.CreateSampleProductRatePlanCharge(oProductRatePlan, 'CHARGETEST', 1);
    	insert oProductRatePlanCharge;
    	
		oProductRatePlanInfo = IECTestUtil.CreateSampleProductRatePlanInfo('PCRPTST', false, oProductRatePlan, oProductInfo);
		insert oProductRatePlanInfo;
		
		currentCustomer = IECCustomer.getCurrentIECCustomer();
		Account oAccount = currentCustomer.RelatedAccount;
		
		List<Zuora__CustomerAccount__c> lstBA =
			[SELECT Id
			FROM Zuora__CustomerAccount__c
			WHERE Contact__c = :currentCustomer.RelatedContact.Id 
				AND Zuora__Account__c =: currentCustomer.RelatedAccount.Id];
		
		System.assertEquals(lstBA.size(), 1);
		
        // create dummy subscription
        subscription = IECTestUtil.createSampleSubscription(oAccount.Id, 'Subs 01', Date.today().addMonths(6));
        subscription.Zuora__CustomerAccount__c = lstBA.get(0).Id;
        insert subscription;
        
        // create dummy subscription charge
        subscriptionCharge = IECTestUtil.createSampleSubscriptionCharge2(subscription.Id, Date.today().addMonths(-6), oProduct, oProductRatePlan);
        insert subscriptionCharge;

		// Create a dummy country
		iataCountry = IECTestUtil.CreateSampleIATAISOCountry();
		insert iataCountry;
		iataCountry2 = IECTestUtil.CreateSampleIATAISOCountry();
		iataCountry2.ISO_Code__c = 'AB';
		insert iataCountry2;
		
		// Create a dummy country
		iataState = IECTestUtil.CreateSampleIATAISOState(iataCountry);
		insert iataState;
		
		// Create a dummy country
		gdpGeoDetail = IECTestUtil.CreateSampleGDPGeoDetail(iataCountry);
		insert gdpGeoDetail;
		
		// Create dummy saved filters
		filter1 = IECTestUtil.CreateSampleApplicationFilter(currentCustomer.RelatedContact);
        filter1.Product_Line__c = 'GAD';
		insert filter1;
		filter2 = IECTestUtil.CreateSampleApplicationFilter(currentCustomer.RelatedContact);
        filter2.Product_Line__c = 'GAD';
		insert filter2;
		filter3 = IECTestUtil.CreateSampleApplicationFilter(currentCustomer.RelatedContact);
        filter3.Product_Line__c = 'GAD';
		insert filter3;
		filter4 = IECTestUtil.CreateSampleApplicationFilter(currentCustomer.RelatedContact);
        filter4.Product_Line__c = 'GAD';
		insert filter4;
		filter5 = IECTestUtil.CreateSampleApplicationFilter(currentCustomer.RelatedContact);
        filter5.Product_Line__c = 'GAD';
		insert filter5;
		
		// Create dummy AgencyType
		iecAgencyType = IECTestUtil.CreateSampleIECAgencyType();
		insert iecAgencyType;
		
		System.debug('Unit Test: Finish: Init');
	}
	
    static testMethod void TestGADAdvanced() {
    	System.debug('Unit Test: Start: TestGADAdvanced');
		TransformationHelper.trgAccountISSP_AfterBeforInsertDeleteUpdateUndelete = true;
    	//Set current page to GAD
    	PageReference pgRef = Page.IECGADAdvanced;
    	Test.setCurrentPage(pgRef);
    	
    	User usr = IECTestUtil.createSampleGuestUserAndLogin();
    	System.runAs(usr) {
	    	Init();
            
            Test.startTest();
	    	
	    	//Instantiate Base Controller
	    	IECPageController baseCont = new IECPageController();
	    	baseCont.loggedCustomer = IECCustomer.getCurrentIECCustomer();

	    	//Instantiate Controller
	        vfIECGADAdvanced pgCont = new vfIECGADAdvanced();
            pgCont.defaultproduct();
	        pgCont.pageLoad();
	        
	        //Test 001: All getters and setters
	        List<SelectOption> options;
	        options = pgCont.optAgencyNameSearchCondition;
	        options = pgCont.optAgencyNameSearchType;
	        options = pgCont.optCitySearchType;
	        options = pgCont.optHierarchy;
	        options = pgCont.optZipCodeSearchType;
	        
	        String sTest;
	        sTest = pgCont.sProductCode;
	        
	        String[] stringArray;
	        stringArray = pgCont.sCountry;
	        stringArray = pgCont.sState;
	        stringArray = pgCont.sHierarchy;
	        stringArray = pgCont.sAgencyProgram;
	        
	        pgCont.sCountry = new String[] {'a', 'b'};
	        pgCont.sState = new String[] {'a', 'b'};
	        pgCont.sHierarchy = new String[] {'a', 'b'};
	        pgCont.sAgencyProgram = new String[] {'a', 'b'};

	        //Test 002: Save filter while 5 already exists 
	        //
	        
            System.debug(pgCont.ctrSavedFilters.lstSavedFilters.size());
	        pgCont.filter = IECTestUtil.CreateSampleApplicationFilter(baseCont.loggedCustomer.RelatedContact);
            System.debug(pgCont.ctrSavedFilters.lstSavedFilters.size());
	        pgCont.saveFilter();
            System.debug(pgCont.ctrSavedFilters.lstSavedFilters.size());
            
    	}
    	
        System.debug('Unit Test: Finish: TestGADAdvanced');
    }

    static testMethod void TestGADAdvanced_Errors() {
    	System.debug('Unit Test: Start: TestGADAdvanced_Errors');
    	
    	//Set current page to GAD
    	PageReference pgRef = Page.IECGADAdvanced;
    	Test.setCurrentPage(pgRef);
    	
    	//Instantiate Controller
        vfIECGADAdvanced pgCont = new vfIECGADAdvanced();

        // Test 001: Accessing page as guest user
        pgCont.pageLoad();
        
		User usr = IECTestUtil.createSampleGuestUserAndLogin();
    	System.runAs(usr) {
	    	//Instantiate Controller
	    	IECPageController baseCont = new IECPageController();
	    	baseCont.loggedCustomer = IECCustomer.getCurrentIECCustomer();
	    	pgCont = new vfIECGADAdvanced();

	        // Test 002: Accessing page with no subscription for CAC
	        pgCont.pageLoad();
			//system.assert(IECTestUtil.PageContainsMessage(ApexPages.getMessages(), Label.IEC_Error_No_Application_Access));
    	}
        System.debug('Unit Test: Finish: TestGADAdvanced_Errors');
    }
}