src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email at Account level</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AMS_Account_Role__c.object
<CustomObject>
    <description>Object that represents a connection between an Account another entity. This other entity can be a Person, a Contact or another Account. This will replace the Agency Employee and Agency Ownership + Owner structure.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The main Account on this object. This Account will be connect with another Account, a Person or a Contact</description>
        <inlineHelpText>The main Account on this object. This Account will be connect with another Account, a Person or a Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Owners</relationshipLabel>
        <relationshipName>AMS_Account_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AMS Account Roles</relationshipLabel>
        <relationshipName>AMS_Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Assessment_Contact__c</fullName>
        <formula>Contact__r.Financial_Assessment_Contact__c == true</formula>
        <label>Financial Assessment Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person (AMS)</label>
        <referenceTo>AMS_Person__c</referenceTo>
        <relationshipLabel>AMS Account Roles</relationshipLabel>
        <relationshipName>AMS_Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AMS Account Role</label>
    <nameField>
        <displayFormat>AAR-{00000000}</displayFormat>
        <label>AMS Account Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Account Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Agency__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency (AMS)</label>
    <nameField>
        <label>AMS Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies (AMS)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Person__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Persons (AMS)</relationshipLabel>
        <relationshipName>Persons_AMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Person (AMS)</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons (AMS)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Financial_Assessment_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tell if the contact is define as Financial Assessment Contact.
IFAP Application.</description>
        <label>Financial Assessment Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>AMS_Person__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Portal_Status__c</fullName>
        <label>User Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved User</fullName>
                </value>
                <value>
                    <fullName>Approved Admin</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Regional Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AMS_AgencyContactsController.cls
public with sharing class AMS_AgencyContactsController {

	//private AMS_Agency__c ag; #AMSFTS
    private Account ag;
    //public List<ContactWrapper> contactTable {get;set;}

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public AMS_AgencyContactsController(ApexPages.StandardController stdController) {
        this.ag = (Account)stdController.getRecord();
    }

    public List<ContactWrapper> getcontactTable(){
        List<ContactWrapper> contactTable= new List<ContactWrapper>();
        List<AMS_Person__c> persons = [select id, Name, Contact__c, Phone__c, Mobile__c, Email__c, Contact__r.User_Portal_Status__c, Contact__r.Financial_Assessment_Contact__c from AMS_Person__c where id IN (select Person__c from AMS_Account_Role__c where Account__c =: this.ag.id and Person__c != null)];

        for(AMS_Person__c c: persons){
            Boolean isAdmin = false;
            Boolean isFin = false;
            Boolean hasContact = true;

            if(c.Contact__c == null){
                hasContact = false;
            }else{
                if(c.Contact__r.User_Portal_Status__c == 'Administrator' || c.Contact__r.User_Portal_Status__c == 'Approved Admin'){
                    isAdmin = true;
                }
                if(c.Contact__r.Financial_Assessment_Contact__c == true){
                    isFin = true;
                }
            }
            contactTable.add(new ContactWrapper(c, isAdmin, isFin, hasContact));
        }

        return contactTable;
    }

    public class ContactWrapper{
        public String adminImage {get;set;}
        public String adminName {get;set;}
        public String finImage {get;set;}
        public String finName {get;set;}
        public String perImage {get;set;}
        public String perName {get;set;}
        public String noContactImage {get;set;}
        public String noContactName {get;set;}
        
        public AMS_Person__c person {get;set;}

        public ContactWrapper(AMS_Person__c c, Boolean admin, Boolean fin, Boolean hasContact){
            
            if(!hasContact){
            	this.noContactImage = 'nocontactemp.png';
                this.noContactName = 'Person has no Contact';
            }
            else{
                if(!admin && !fin){
                    this.perImage = '/img/icon/people16.png';
                    this.perName = 'Person';
                }
                if(admin){
                    this.adminImage = '/img/icon/profile16.png';
                    this.adminName = 'Portal Admin';
                }
                if(fin){
                    this.finImage = '/img/icon/cash16.png';
                    this.finName = 'Financial Assessment Contact';
                }
            }

            this.person = c;
        }
    }
}