src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EBC_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Is_Step4_Valid__c</fullName>
        <description>Verify if the Step 4 is valid and meet the validation.</description>
        <formula>Is_Step3_Valid__c &amp;&amp; !ISBLANK(EBC_Design__c) &amp;&amp;  EBC_Design__r.Is_Tested__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Verify if the Step 4 is valid and meet the validation.</inlineHelpText>
        <label>Is Step4 Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Step5_Writable__c</fullName>
        <description>Is Step5 is writable based on other fields values</description>
        <formula>TEXT(Status__c) == &apos;DRAFT&apos; || TEXT(Status__c) == &apos;APPROVED&apos; ||  (Billing_Account__r.eBroadcast_Trusted_Sender__c &amp;&amp; TEXT(Status__c) == &apos;PENDING_APPROVAL&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Is Step5 is writable based on other fields values</inlineHelpText>
        <label>Is Step5 Writable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scheduled_Date__c</fullName>
        <description>The scheduled date of the campaign</description>
        <inlineHelpText>The scheduled date of the campaign</inlineHelpText>
        <label>Scheduled Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of the campaign</description>
        <inlineHelpText>The current status of the campaign</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                    <default>true</default>
                    <label>DRAFT</label>
                </value>
                <value>
                    <fullName>PENDING_APPROVAL</fullName>
                </value>
                <value>
                    <fullName>APPROVED</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>STARTED</fullName>
                </value>
                <value>
                    <fullName>SENT</fullName>
                </value>
                <value>
                    <fullName>DELETED</fullName>
                </value>
                <value>
                    <fullName>EMAIL RECOVER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EBC Campaign</label>
    <nameField>
        <label>eBroadcast Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBC Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductAudience__c</fullName>
        <label>Product Audience</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member Airline</fullName>
                </value>
                <value>
                    <fullName>Non-Member Single</fullName>
                </value>
                <value>
                    <fullName>Non-Member GDS</fullName>
                </value>
                <value>
                    <fullName>Non-Member Processor</fullName>
                </value>
                <value>
                    <fullName>Non-Member Franchise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Discontd w/o Replace</fullName>
                </value>
                <value>
                    <fullName>Discontd w Replacemt</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending approval</fullName>
                </value>
                <value>
                    <fullName>Technical Defect</fullName>
                </value>
                <value>
                    <fullName>Test Part</fullName>
                </value>
                <value>
                    <fullName>Under Development</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZProduct</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ZProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveEndDate__c</fullName>
        <description>The Effective End Date of the Product.</description>
        <inlineHelpText>The Effective End Date of the Product.</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveStartDate__c</fullName>
        <description>The Effective Start Date of the Product.</description>
        <inlineHelpText>The Effective Start Date of the Product.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>EBC_Cost_Per_Email__c</fullName>
        <description>Numeric value representing the the cost per e-mail in eBroadcast,, i.e. $0.20 / e-mail</description>
        <inlineHelpText>Numeric value representing the the cost per e-mail in eBroadcast, i.e. $0.20 / e-mail</inlineHelpText>
        <label>EBC Cost per Email</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBC_PrePaid_Emails__c</fullName>
        <description>This field stores the initial number of email credits per rate plan.</description>
        <inlineHelpText>This field stores the initial number of email credits per rate plan.</inlineHelpText>
        <label>EBC PrePaid Emails</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBC_SubscriptionType__c</fullName>
        <description>Identifies the type of eBroadcast subscription that represents the rate plan.</description>
        <inlineHelpText>Identifies the type of eBroadcast subscription that represents the rate plan.</inlineHelpText>
        <label>EBC Subscription Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveEndDate__c</fullName>
        <description>The Effective End Date of the Rate Plan.</description>
        <inlineHelpText>The Effective End Date of the Rate Plan.</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveStartDate__c</fullName>
        <description>The Effective Start Date of the Rate Plan.</description>
        <inlineHelpText>The Effective Start Date of the Rate Plan.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fixingUpdate/objects/zqu__ZProduct__c.object
<CustomObject>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>ClientType__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member Airline</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eBroadcast_Add_On_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For eBroadcast application, the field designates if the account is given access to the Extra Storage Add-on (one time payment required, usage forever)</description>
        <inlineHelpText>For eBroadcast application, the field designates if the account is given access to the Extra Storage Add-on (one time payment required, usage forever)</inlineHelpText>
        <label>eBroadcast Add-On Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>eBroadcast_Product_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For eBroadcast application, the field designates if the account is given access to the application area (one time payment required, access forever)</description>
        <inlineHelpText>For eBroadcast application, the field designates if the account is given access to the application area (one time payment required, access forever)</inlineHelpText>
        <label>eBroadcast Service Access</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/vfIECEBC_Dashboard.cls
/*
 *  Controller for IECEBC_Dashboard, a.k.a eBroadcast Dashboard
 *  - Main objects: Zuora__Subscription, Zuora__CustomerAccount__c, Product_Rate_Plan_Information 
 *  - Original writer: Mathieu Beausoleil
 * 
 * Note that we intentionally try to avoid using IECPageController.loggedCustomer for the following reasons: 
 *  - Any test class requiring IECCustomer creation currently requires seeAllData true. 
 *  - IECCustomer constructor has conditional value for test run, which creates its own ZuoraAccount and BillingAccount.
 *  - In creating that ZuoraAccount (regular Account), IECTestUtil calls Zuora.zObject and Zuora.zSchema which requires Zuora WSDL
 *  
 *
 *  Change log:
 *   20160521: Mathieu Beausoleil
 *   20160601-sl: GDP-75/GDP-667/GDP-709: display the Account Summary section with EBC account status
 *
*/

public with sharing class vfIECEBC_Dashboard {
	class Controller_Exception extends Exception{}
	
	private static final String DEFAULT_EBC_SUBSCRIPTION_TYPE =  'Pay-as-You-Go';
	
	private User thisUser; // current login user
	
	public List<EBC_Campaign__c> campaigns {
		get {
			if (campaigns == null) 
			{	
			
				campaigns = [select Id, Is_Step5_Writable__c, Is_Step4_Valid__c, Name, Status__c, Scheduled_Date__c, Owner.Name 
								from EBC_Campaign__c 
								where Account__c = :thisUser.Contact.AccountId 
								order by LastModifiedDate desc limit 3];
			}
			return campaigns;
		}
		private set;
	} // campaigns
	
	public Integer getCampaignsCount() {
		return [Select count() From EBC_Campaign__c];
	} // getCampaignsCount
	
	// ========================================================================
	// the following properties are to be displayed in Account Summary section
	public String billingPlanName { get; private set;} // Zuora__Subscription__c.Product_Rate_Plan_Information__r.Name
	public String billingPlanRate { get; private set;} // Zuora__Subscription__c.Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_Cost_Per_Email__c
	public String emailBalanceOnAccount { get; private set;} // Zuora__Subscription__c.Zuora__CustomerAccount__r.eBroadcast_Available_Email_Balance__c
	
	public String availableAddOns { get; private set;} 
	
	
	// ========================================================================
	// constructor
	public vfIECEBC_Dashboard() {
		thisUser = [select Id, ContactId, Contact.AccountId 
			from User 
			where id =: Userinfo.getUserid() limit 1];
			
		getEBCSubscriptionInformation();
	} // end of vfIECEBC_Dashboard constructor
	public vfIECEBC_Dashboard(ApexPages.StandardController controller) {
		thisUser = [select Id, ContactId, Contact.AccountId 
			from User 
			where id =: Userinfo.getUserid() limit 1];
			
		getEBCSubscriptionInformation();
	}
	
	// ========================================================================
	// get information related to EBC Subscription
	// billingPlanName, emailBalanceOnAccount, billingPlanName
	// source Zuora__Subscription, Zuora__CustomerAccount, zqu__ProductRatePlan__c
	private void getEBCSubscriptionInformation()
	{
		// get current subscription with Product Category = IECConstants.ProductCategory_SF_EBROADCAST
		// currently we do not care whether the Zuora Subscription__c.Zuora__Status__c = 'Active' or or not 
		List<Zuora__Subscription__c> subsList = [select Id, Name
				, Product_Rate_Plan_Information__r.Product_Rate_Plan__r.Name
				, Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_SubscriptionType__c
				, Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_Cost_Per_Email__c
				// , Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_PrePaid_Emails__c
				, Zuora__CustomerAccount__r.eBroadcast_Available_Email_Balance__c
				, Zuora__CustomerAccount__r.Contact__c
			from Zuora__Subscription__c
			where (Zuora__CustomerAccount__r.Contact__c = : thisUser.ContactId) 
				and ( (Zuora__SubscriptionEndDate__c >=  today) 
					or (Zuora__SubscriptionEndDate__c = null) )
				and (Product_Rate_Plan_Information__r.Related_Product_Information__r.Related_Product_Category__r.Name = : IECConstants.ProductCategory_SF_EBROADCAST)
				order by Zuora__Status__c ASC
						, Zuora__SubscriptionEndDate__c desc nulls first 
						, Zuora__SubscriptionStartDate__c desc
			];
		
		if (subsList.size() > 0) 
		{
			billingPlanRate = '$' + subsList[0].Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_Cost_Per_Email__c;
			// emailBalanceOnAccount = subsList[0].Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_PrePaid_Emails__c;
			emailBalanceOnAccount = String.valueOf(subsList[0].Zuora__CustomerAccount__r.eBroadcast_Available_Email_Balance__c);
			billingPlanName = subsList[0].Product_Rate_Plan_Information__r.Product_Rate_Plan__r.Name;
		} else { 
			// there is no current Zuora Subscription on EBC, then set as type to default / Pay As You Go. 
			
			List<Zuora__CustomerAccount__c> billAcctList = [select Id, Name
					, eBroadcast_Product_Access__c
					// , eBroadcast_Add_On_Access__c
					, eBroadcast_Available_Email_Balance__c
					, Contact__c
					, ClientType__c
				from Zuora__CustomerAccount__c
				where Contact__c = : thisUser.ContactId
					//and  Zuora__Status__c = 'Active'
				order by Zuora__Status__c asc, CreatedDate desc limit 1
				];
			
			// billing account should exist, otherwise keep those values as null
			if (billAcctList.size() != 0) 
			{
				emailBalanceOnAccount = String.valueOf(billAcctList[0].eBroadcast_Available_Email_Balance__c);
				
				// member or non member is defined by Billing Account.ClientType 
				// get product rate plan to get EBC_Cost_Per_Email
				// there should only be one ProductRatePlan, however just in case, we sort it to ensure consistency
				List<zqu__ProductRatePlan__c> prodRatePlanList = [select id, Name
							, EBC_Cost_Per_Email__c
							, EBC_SubscriptionType__c
							, EBC_PrePaid_Emails__c
						from zqu__ProductRatePlan__c
						where EBC_SubscriptionType__c = :DEFAULT_EBC_SUBSCRIPTION_TYPE // 'Pay-as-You-Go'
							and ( zqu__ZProduct__r.ProductAudience__c = : billAcctList[0].ClientType__c
								or zqu__ZProduct__r.ProductAudience__c = 'All' )
							and zqu__ZProduct__r.zqu__EffectiveStartDate__c <= TODAY
							and zqu__ZProduct__r.zqu__EffectiveEndDate__c >= TODAY
						order by zqu__ZProduct__r.zqu__Active__c, zqu__ZProduct__r.zqu__EffectiveEndDate__c DESC, zqu__ZProduct__r.ProductAudience__c DESC
						limit 1
						];
				billingPlanName = 'ProductRatePlan Not found';
				if (prodRatePlanList.size()>0) 
				{
					billingPlanRate = '$' + prodRatePlanList[0].EBC_Cost_Per_Email__c;
					billingPlanName = prodRatePlanList[0].Name;
				}
			} // end if billAcctList.size != 0
		}
	} // end of getEBCSubscriptionInformation
	
	
} // vfIECEBC_Dashboard