src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>Map the objects AGT from AIMS. This is a value equal to category.</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accommodation</fullName>
                </value>
                <value>
                    <fullName>Airline</fullName>
                </value>
                <value>
                    <fullName>Airline Supplier</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Equipment Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Cargo Agent</fullName>
                    <label>Freight Forwarder</label>
                </value>
                <value>
                    <fullName>General Public</fullName>
                </value>
                <value>
                    <fullName>General Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Governmental Institution</fullName>
                </value>
                <value>
                    <fullName>Holding Company</fullName>
                </value>
                <value>
                    <fullName>IATA</fullName>
                </value>
                <value>
                    <fullName>Infrastructure Partner</fullName>
                </value>
                <value>
                    <fullName>Internal Use</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Non-Airline Transportation</fullName>
                </value>
                <value>
                    <fullName>Recreational</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>IATA_Agency</fullName>
        <active>true</active>
        <description>The new record type for ALL Agencies with NEW data model - Use this for all Agencies</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AMS_Country_Specific_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>ANG_Minimum_RHC_Amount__c</fullName>
        <description>Defines a minimum RHC amount to be used in the RHC Amount calculation.</description>
        <inlineHelpText>Minimum RHC Amount</inlineHelpText>
        <label>Minimum RHC Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>AMS Country Specific Attributes</relationshipLabel>
        <relationshipName>AMS_Country_Specific_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only)
X-Handling Agents and Shipping Lines
J-Joint Vent</description>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AMS Country Specific Attribute</label>
    <nameField>
        <displayFormat>ACSA-{00000000}</displayFormat>
        <label>AMS Country Specific Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Country Specific Attributes</pluralLabel>
    <recordTypes>
        <fullName>Minimum_RHC_Amount</fullName>
        <active>true</active>
        <description>Record type to associate the Minimum RHC amount page layout.</description>
        <label>Minimum RHC Amount</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AMS_Settlement_System__c.object
<CustomObject>
    <fields>
        <fullName>ANG_RHC_Amount_Equals_FS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked all agencies belonging to this Operation (BSP) will have the RHC Amount equal to the sum of the financial securities provided</description>
        <inlineHelpText>If checked all agencies belonging to this Operation (BSP) will have the RHC Amount equal to the sum of the financial securities provided</inlineHelpText>
        <label>RHC Amount Equals FS</label>
        <type>Checkbox</type>
    </fields>
    <label>ISS Operation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ISS Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ANG_RHC_Information__c.object
<CustomObject>
    <fields>
        <fullName>ANG_RHC_Amount_Equals_FS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked the RHC amount will be equal to the total Financial Securities</description>
        <inlineHelpText>If checked the RHC amount will be equal to the total Financial Securities</inlineHelpText>
        <label>RHC Amount Equals FS</label>
        <type>Checkbox</type>
    </fields>
    <label>RHC Information</label>
    <nameField>
        <displayFormat>RHCI-{000000000}</displayFormat>
        <label>RHC Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RHC Information Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>AMS_Settlement_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BSP Billing environment</label>
        <referenceTo>AMS_Settlement_System__c</referenceTo>
        <relationshipLabel>IATA ISO Countries</relationshipLabel>
        <relationshipName>IATA_ISO_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ANG_Enable_NewGen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To enable the agency’s country to use the new accreditations model used in NewGen and Risk Event</description>
        <label>New Accr. Model &amp; Risk Events enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ISSP_CS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ISSP CS</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/operational_Calendar__c.object
<CustomObject>
    <description>used to host information on the ISS / ICH / ICCS calendars</description>
    <fields>
        <fullName>First_Day__c</fullName>
        <description>first day of the period</description>
        <label>Billing From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ISS_operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISS Operation</label>
        <referenceTo>AMS_Settlement_System__c</referenceTo>
        <relationshipLabel>Operational Calendars</relationshipLabel>
        <relationshipName>Operational_Calendars</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Day__c</fullName>
        <description>period last day</description>
        <label>Billing To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>frequency_code__c</fullName>
        <label>Remittance Frequency Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Operational Calendar</label>
    <nameField>
        <displayFormat>Calendar-{00000000}</displayFormat>
        <label>FDS Calendar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operational Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ANG_RHCHelperTest.cls
@isTest
private class ANG_RHCHelperTest {

	@testSetup static void setup() {

		Id devRecordTypeId = RecordTypeSingleton.getInstance().getRecordTypeId('AMS_Country_Specific_Attribute__c', 'Minimum_RHC_Amount');

		List<AMS_Settlement_System__c> bspList = new List<AMS_Settlement_System__c>();
		AMS_Settlement_System__c settlement = new AMS_Settlement_System__c(CurrencyIsoCode = 'USD', ANG_RHC_Amount_Equals_FS__c = true);
		bspList.add(settlement);
		AMS_Settlement_System__c settlement2 = new AMS_Settlement_System__c(CurrencyIsoCode = 'USD', ANG_RHC_Amount_Equals_FS__c = false);
		bspList.add(settlement2);
		insert bspList;

		list<String> listAirlineId = new list<String>();
		for (Profile profile: [SELECT Id FROM Profile WHERE Name LIKE 'ISS Portal Airline%']) {
			listAirlineId.add(profile.Id);
		}

		list<String> listAgencyId = new list<String>();
		for (Profile profile: [SELECT Id FROM Profile WHERE Name LIKE 'ISS Portal Agency%']) {
			listAgencyId.add(profile.Id);
		}

		List<ISSP_CS__c> listCs = new list<ISSP_CS__c>();
		listCs.add(new ISSP_CS__c(Name='ISS OperationalCalendar Airline Profil',Value__c=String.join(listAirlineId,',')));
		listCs.add(new ISSP_CS__c(Name='ISS OperationalCalendar Agency Profile',Value__c=String.join(listAgencyId,',')));
		insert listCs;

		Date operationDate = Date.today();

		//Calendars for BSP1
		List<Operational_Calendar__c> opCalanderList = new List<Operational_Calendar__c>();
		Operational_Calendar__c opCalendar1 = new Operational_Calendar__c(First_Day__c = operationDate.addDays(5), Frequency_code__c = 'W',
			ISS_operation__c = settlement.id, Last_day__c = operationDate.addDays(10));
		opCalanderList.add(opCalendar1);
		Operational_Calendar__c opCalendar2 = new Operational_Calendar__c(First_Day__c = operationDate.addDays(11), Frequency_code__c = 'W',
			ISS_operation__c = settlement.id, Last_day__c = operationDate.addDays(18));
		opCalanderList.add(opCalendar2);
		Operational_Calendar__c opCalendar3 = new Operational_Calendar__c(First_Day__c = operationDate.addDays(1), Frequency_code__c = 'D',
			ISS_operation__c = settlement.id, Last_day__c = operationDate.addDays(2));
		opCalanderList.add(opCalendar3);
		Operational_Calendar__c opCalendar4 = new Operational_Calendar__c(First_Day__c = operationDate.addDays(3), Frequency_code__c = 'D',
			ISS_operation__c = settlement.id, Last_day__c = operationDate.addDays(4));
		opCalanderList.add(opCalendar4);

		//Calendars for BSP2
		Operational_Calendar__c opCalendar5 = new Operational_Calendar__c(First_Day__c = operationDate.addDays(5), Frequency_code__c = 'W',
			ISS_operation__c = settlement2.id, Last_day__c = operationDate.addDays(10));
		opCalanderList.add(opCalendar5);
		Operational_Calendar__c opCalendar6 = new Operational_Calendar__c(First_Day__c = operationDate.addDays(11), Frequency_code__c = 'W',
			ISS_operation__c = settlement2.id, Last_day__c = operationDate.addDays(18));
		opCalanderList.add(opCalendar6);
		Operational_Calendar__c opCalendar7 = new Operational_Calendar__c(First_Day__c = operationDate.addDays(1), Frequency_code__c = 'D',
			ISS_operation__c = settlement2.id, Last_day__c = operationDate.addDays(2));
		opCalanderList.add(opCalendar7);
		Operational_Calendar__c opCalendar8 = new Operational_Calendar__c(First_Day__c = operationDate.addDays(3), Frequency_code__c = 'D',
			ISS_operation__c = settlement2.id, Last_day__c = operationDate.addDays(4));
		opCalanderList.add(opCalendar8);
		insert opCalanderList;

		List<IATA_ISO_Country__c> ctry = new List<IATA_ISO_Country__c>();
		ctry.add(new IATA_ISO_Country__c(Name = 'USA', ISO_Code__c = 'US', AMS_Settlement_System__c = settlement.id, ANG_Enable_NewGen__c = true));
		ctry.add(new IATA_ISO_Country__c(Name = 'WW', ISO_Code__c = 'WW', AMS_Settlement_System__c = settlement2.id, ANG_Enable_NewGen__c = true));
		insert ctry;

		AMS_Country_Specific_Attribute__c config = new AMS_Country_Specific_Attribute__c (
				RecordTypeId = devRecordTypeId, IATA_ISO_Country__c = ctry[1].id,
				ANG_Minimum_RHC_Amount__c = 10,CurrencyIsoCode = 'USD'  );

		insert config;

		Id accountAgencyRT = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');

		List<Account> accountList = new List<Account>();
		Account a1 = new Account(IATA_ISO_Country__c = ctry[0].id, RecordTypeId = accountAgencyRT, IATACode__c='1234562',
			Location_Type__c='HE',Name='Test2 Agency OK',Short_Name__c='Test1 Agency', Sector__c = 'Travel Agent',
			Location_Class__c = 'P', Remittance_frequency__c = 'W' );
		accountList.add(a1);

		Account a2 = new Account(IATA_ISO_Country__c = ctry[1].id, RecordTypeId = accountAgencyRT, IATACode__c='1234569',
			Location_Type__c='HE',Name='Test3 Agency OK',Short_Name__c='Test3 Agency', Sector__c = 'Travel Agent 3',
			Location_Class__c = 'P', Remittance_frequency__c = 'D' );
		accountList.add(a2);

		insert accountList;

	}


	static testMethod void rhcInfoInitialization() {

		Account a = [Select id FROM Account WHERE IATACode__c='1234562' limit 1];

		System.assertEquals(0, [SELECT Id FROM ANG_RHC_Information__c WHERE ANG_AccountId__c = :a.Id].size());

		Test.startTest();

		ANG_RHCHelper.createRHCInfo(new Set<Id>{a.Id}, false);

		Test.stopTest();

		System.assertEquals(1, [SELECT Id FROM ANG_RHC_Information__c WHERE ANG_AccountId__c = :a.Id].size());
	}


	static testMethod void rhcInfoInitialization2() {

		IATA_ISO_Country__c ctry2 = [SELECT id, Name FROM IATA_ISO_Country__c WHERE Name = 'WW' limit 1];

		Id devRecordTypeId = RecordTypeSingleton.getInstance().getRecordTypeId('AMS_Country_Specific_Attribute__c', 'Minimum_RHC_Amount');

		AMS_Country_Specific_Attribute__c config = new AMS_Country_Specific_Attribute__c( RecordTypeId = devRecordTypeId,
					 IATA_ISO_Country__c = ctry2.id, ANG_Minimum_RHC_Amount__c = 10);

		insert config;

		Account a = [Select id FROM Account WHERE IATACode__c='1234562' limit 1];

		System.assertEquals(0, [SELECT Id FROM ANG_RHC_Information__c WHERE ANG_AccountId__c = :a.Id].size());

		Test.startTest();

		ANG_RHCHelper.createRHCInfo(new Set<Id>{a.Id}, false);

		Test.stopTest();

		System.assertEquals(1, [SELECT Id FROM ANG_RHC_Information__c WHERE ANG_AccountId__c = :a.Id].size());
	}


	/**
	 * Test calculateRHCAmount method
	 */
	static testMethod void testRHCinformation_calculateRHCAmount() {

		Set<ID> accountIdSet = new Set<ID>();
		for(Account a : [Select id FROM Account])
			accountIdSet.add(a.ID);

		Test.startTest();

		ANG_RHCHelper.createRHCInfo(accountIdSet, false);

		List<ANG_RHC_Information__c> rhcinformationList =
				[SELECT id, ANG_CashCondition__c, ANG_AccountId__c,ANG_RHC_Amount_Equals_FS__c, ANG_Financial_Security__c,
					ANG_RME_Amount__c, ANG_RHC_Amount_Provisional__c, ANG_Exceeding_Financial_Security__c,ANG_RHC_Amount_Forecasted__c,
					CurrencyIsoCode, RHC_Amount_Equals_FS_Percent__c, ANG_Forecasted_RHC_Effective_date__c, ANG_Minimum_Financial_Security__c
				FROM ANG_RHC_Information__c];

		ANG_RHCHelper.calculateRHCAmount(rhcinformationList);

		Test.stopTest();

		List<ANG_RHC_Information__c> rhcUpdated = [SELECT Id, ANG_Forecasted_RHC_Effective_date__c, ANG_RHC_Amount_Forecasted__c, ANG_AccountId__r.IATACode__c
												  FROM ANG_RHC_Information__c];

		System.debug('__[ANG_RHCHelperTest - testRHCinformation_calculateRHCAmount] List<ANG_RHC_Information__c>:' +
			[SELECT Id, ANG_Forecasted_RHC_Effective_date__c, ANG_RHC_Amount_Forecasted__c FROM ANG_RHC_Information__c]);

		for(ANG_RHC_Information__c rhc : rhcUpdated){
			if(rhc.ANG_AccountId__r.IATACode__c == '1234562')
				System.assertEquals(Date.today().addDays(5), rhc.ANG_Forecasted_RHC_Effective_date__c);
			else if(rhc.ANG_AccountId__r.IATACode__c == '1234569')
				System.assertEquals(Date.today().addDays(1), rhc.ANG_Forecasted_RHC_Effective_date__c);

		}


	}
}