src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Identify_as_Key_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick this checkbox if Customer needs to be identified as a key customer</inlineHelpText>
        <label>Identify as Key Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key_Customer__c</fullName>
        <formula>IF( Identify_as_Key_Customer__c = True,IMAGE(&quot;/servlet/servlet.FileDownload?file=015200000011YZg&quot;,&quot;VIP Customers&quot;, 23, 23),&quot; &quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Key Customer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agency_Applied_Change_code__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agencies Applied Change codes</relationshipLabel>
        <relationshipName>Agencies_Applied_Change_codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this code is Active. Agency can only have one Active code in same time.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Change_Code__c</fullName>
        <label>Change Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFN</fullName>
                </value>
                <value>
                    <fullName>BSF</fullName>
                </value>
                <value>
                    <fullName>BSP</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CAS</fullName>
                </value>
                <value>
                    <fullName>CCA</fullName>
                </value>
                <value>
                    <fullName>CCF</fullName>
                </value>
                <value>
                    <fullName>CCR</fullName>
                </value>
                <value>
                    <fullName>CHC</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
                <value>
                    <fullName>CHG</fullName>
                </value>
                <value>
                    <fullName>CHI</fullName>
                </value>
                <value>
                    <fullName>CHJ</fullName>
                </value>
                <value>
                    <fullName>CHL</fullName>
                </value>
                <value>
                    <fullName>CHM</fullName>
                </value>
                <value>
                    <fullName>CHN</fullName>
                </value>
                <value>
                    <fullName>CHO</fullName>
                </value>
                <value>
                    <fullName>CHS</fullName>
                </value>
                <value>
                    <fullName>CHV</fullName>
                </value>
                <value>
                    <fullName>CLF</fullName>
                </value>
                <value>
                    <fullName>CLI</fullName>
                </value>
                <value>
                    <fullName>CLO</fullName>
                </value>
                <value>
                    <fullName>CLR</fullName>
                </value>
                <value>
                    <fullName>CMF</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                </value>
                <value>
                    <fullName>COR</fullName>
                </value>
                <value>
                    <fullName>CSF</fullName>
                </value>
                <value>
                    <fullName>CWD</fullName>
                </value>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>DFE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OSCAR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>In Case this Code has been applied during a Accreditaiton Request</inlineHelpText>
        <label>OSCAR</label>
        <referenceTo>AMS_OSCAR__c</referenceTo>
        <relationshipLabel>Agencies Applied Change codes</relationshipLabel>
        <relationshipName>Agencies_Applied_Change_codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Applied Change code</label>
    <nameField>
        <displayFormat>AACC-{000000}</displayFormat>
        <label>Change code details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies Applied Change codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AMS_OSCAR__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OSCARs</relationshipLabel>
        <relationshipName>OSCARs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Code__c</fullName>
        <label>Change Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DIS - Application Disapproved</fullName>
                </value>
                <value>
                    <fullName>NEW - New Application</fullName>
                </value>
                <value>
                    <fullName>FIN - Application Finalized</fullName>
                </value>
                <value>
                    <fullName>PCI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <formula>Account__r.IATACode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IATACode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Oscar Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted_Future Date</fullName>
                </value>
                <value>
                    <fullName>Accepted_Pending Agreement</fullName>
                </value>
                <value>
                    <fullName>Accepted_Pending BG</fullName>
                </value>
                <value>
                    <fullName>Accepted_Pending Docs</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed_ Not Accepted</fullName>
                </value>
                <value>
                    <fullName>Closed_Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed_Withdrawn</fullName>
                </value>
                <value>
                    <fullName>On Hold_External</fullName>
                </value>
                <value>
                    <fullName>On Hold_Internal</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Reopen</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Open - EDMC</fullName>
                </value>
                <value>
                    <fullName>Renewal not completed</fullName>
                </value>
                <value>
                    <fullName>Input requested</fullName>
                </value>
                <value>
                    <fullName>Pending Reconsideration</fullName>
                </value>
                <value>
                    <fullName>Closed_Disapproved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OSCAR</label>
    <nameField>
        <label>OSCAR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OSCARs</pluralLabel>
    <recordTypes>
        <fullName>NEW</fullName>
        <active>true</active>
        <label>NEW</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Person__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMS_Agents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person (AMS)</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons (AMS)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AMS_OSCAR_HightlightsPanelController.cls
public class AMS_OSCAR_HightlightsPanelController {

    public Boolean saveAction {get; set;}

    //person who submitted the OSCAR
    public AMS_Person__c submitter {get; set;}

    public String iataChangeCode {get; set;}

    public AMS_OSCAR__c theOSCAR {get; set;}

    public Case oscarCase {get; set;}

    public Id oscarId {get; set;}

    public Id caseId {get; set;}

    public AMS_OSCAR_HightlightsPanelController() {

        Id objectId = ApexPages.currentPage().getParameters().get('id');

        if (objectId == null) return;

        //is it an Oscar or a case?
        if (isObjectCase(objectId)) {

            this.oscarCase = fetchCaseFields(objectId, false);
            this.submitter = fetchPersonSubmiter(this.oscarCase.CreatedById);
            this.caseId = this.oscarCase.Id;

            if (this.oscarCase.OSCAR__c != null) {

                this.theOSCAR = fetchOscarFields(this.oscarCase.OSCAR__c);
                this.oscarId = this.theOSCAR.Id;
            }
        } else {

            this.theOSCAR = fetchOscarFields(objectId);
            this.oscarId = this.theOSCAR.Id;

            this.oscarCase = fetchCaseFields(objectId, true);
            this.caseId = this.oscarCase.Id;

            this.submitter = fetchPersonSubmiter(this.oscarCase.CreatedById);
        }

        if (this.oscarId != null) this.iataChangeCode = fetchActiveChangeCode(this.theOSCAR);
    }

    public void saveStatus() {
        try {
            update theOscar;
            this.saveAction = true;
        } catch(DmlException e) {
            /*** AMSU-37 ***/
            String e_message = e.getMessage();
            if(e_message.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                e_message = e_message.substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION, ', ': ');
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, e_message));
            } else {
                ApexPages.addMessages(e);
            }

            System.debug(loggingLevel.ERROR, '____ [cls AMS_OSCAR_HightlightsPanelController - saveStatus] error - ' + e.getMessage());
            this.theOSCAR = fetchOscarFields(this.oscarId);
        } catch(Exception e) {
            //DML Exceptions are sometimes displayed on the page
            if (e.getTypeName() != 'System.DmlException' || !ApexPages.hasMessages()) ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Couldn\'t save changes ' + e.getMessage()));
            System.debug(loggingLevel.ERROR, '____ [cls AMS_OSCAR_HightlightsPanelController - saveStatus] error - ' + e.getMessage());

            this.theOSCAR = fetchOscarFields(this.oscarId);
        }
    }

    public void cancelStatus() {
        return;
    }


    private AMS_OSCAR__c fetchOscarFields(ID oscarId) {

        AMS_OSCAR__c toReturn = null;

        List<AMS_OSCAR__c> oscars = [select Id, Account__c, Status__c, Account__r.IATA_ISO_Country__r.Name, Account__r.IATACode__c,
                                     Account__r.RecordType.Name, Account__r.Name,
                                     Account__r.Identify_as_Key_Customer__c, Account__r.Key_Customer__c,
                                     Owner.Name, CreatedDate from AMS_OSCAR__c where id = : oscarID LIMIT 1];

        if (!oscars.isEmpty()) toReturn = oscars.get(0);

        return toReturn;
    }

    private Id oSCARCaseRecordTypeID {
        get {
            if (oSCARCaseRecordTypeID == null) {
                oSCARCaseRecordTypeID = RecordTypeSingleton.getInstance().getRecordTypeId('Case', 'OSCAR_Communication');
            }
            return oSCARCaseRecordTypeID;
        }
        set;
    }

    private Case fetchCaseFields(ID objectId, Boolean isIdFromOscar) {

        Case toReturn = null;

        List<Case> cases = new List<Case>();

        if (isIdFromOscar) cases =  [SELECT Id, CaseNumber, CreatedBy.Name, CreatedById, CreatedDate, Subject, OSCAR__c FROM Case WHERE OSCAR__c = : objectId AND RecordTypeID = : oSCARCaseRecordTypeID AND ParentId = null LIMIT 1];
        else  cases = [SELECT Id, CaseNumber, CreatedBy.Name, CreatedById, CreatedDate, Subject, OSCAR__c FROM Case WHERE id = :objectId LIMIT 1];

        if (!cases.isEmpty()) toReturn = cases.get(0);

        return toReturn;

    }

    private boolean isObjectCase(Id objectToFind) {

        return AMS_Utils.findObjectNameFromRecordIdPrefix(objectToFind).equalsIgnoreCase('CASE');

    }


    public AMS_Person__c fetchPersonSubmiter(Id userId) {

        AMS_Person__c toReturn = null;

        List<AMS_Person__c> persons = [SELECT Id, Name FROM AMS_Person__c WHERE User__c = : userId LIMIT 1];

        if (!persons.isEmpty()) toReturn = persons.get(0);

        return toReturn;
    }

    private String fetchActiveChangeCode(AMS_OSCAR__c oscar) {

        String toReturn = null;

        List<Agency_Applied_Change_code__c> iataCCodeLst = [select Change_Code__c from Agency_Applied_Change_code__c where Account__c = :oscar.Account__c and Active__c = true ];

        if (!iataCCodeLst.isEmpty()) toReturn = iataCCodeLst.get(0).Change_Code__c;

        return toReturn;
    }
}