src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Currency_Center_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Airline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airline</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Currency Center Survey</relationshipLabel>
        <relationshipName>Currency_Center_Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Survey__c</fullName>
        <label>Month Survey</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Survey__c</fullName>
        <label>Year Survey</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Currency Center Survey</label>
    <nameField>
        <displayFormat>CCS-{0000000000}</displayFormat>
        <label>Currency Center Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency Center Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CurrencyCenter_MonthlySurveyNoticeBatch.cls
/**
 * @description This Class aims to implement a batch that sends a notification about Monthly Survey submission deadline for each Airline contact
 *
 *
 * @creation  2019-01-29
 * @author    José Cardoso
 */
global class CurrencyCenter_MonthlySurveyNoticeBatch implements Database.Batchable<sObject>, Schedulable{

	private String emailTemplate {get; set;}
	private Integer noticeOrder {get; set;}

	public CurrencyCenter_MonthlySurveyNoticeBatch(Integer reminderOrder){
		noticeOrder = reminderOrder;
		switch on reminderOrder {
			when 1 {
				emailTemplate = 'Currency_Center_Monthly_Survey_Notification_First';
			}
			when 2 {
				emailTemplate = 'Currency_Center_Monthly_Survey_Notification';
			}
			when 3 {
				emailTemplate = 'Currency_Center_Monthly_Survey_Notification_Last';
			}
			when else {
				throw new monthlySurveyNoticeBatchException('You must specify a reminderOrder between 1-3.');
			}
		}
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(ISSP_CurrencyCenterUtil.batchAirlineQuery);
	}

	global void execute(Database.BatchableContext BC, List<Account> scope){

		String year = String.valueOf(System.now().addMonths(-1).year());
		String month = String.valueOf(System.now().addMonths(-1).month());
		List<Currency_Center_Survey__c> existingCcsList = [SELECT Id, Airline__c FROM Currency_Center_Survey__c
															WHERE Survey__c = 'Monthly' AND Status__c = 'Draft'
																AND Year_Survey__c =:year AND Month_Survey__c =:month AND Airline__c in:scope
																AND RecordTypeId=:ISSP_CurrencyCenterUtil.rtIdMonthlySurvey];

		if(!existingCcsList.isEmpty()){
			ISSP_CurrencyCenterUtil.sendEmailsBatch(existingCcsList,'IATA Noreply',emailTemplate);
		}
	}

	global void finish(Database.BatchableContext BC){

	}

	global void execute(SchedulableContext ctx){
		CurrencyCenter_MonthlySurveyNoticeBatch b = new CurrencyCenter_MonthlySurveyNoticeBatch(noticeOrder);
		database.executeBatch(b);
	}

	private class monthlySurveyNoticeBatchException extends Exception{

	}

}