src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <defaultValue>&quot;Z001&quot;</defaultValue>
        <description>IEC - SAP payment term code to use when creates contracts</description>
        <label>Payment Terms</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profit_Center__c</fullName>
        <label>Profit Center</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DBP003</fullName>
                </value>
                <value>
                    <fullName>DBP004</fullName>
                </value>
                <value>
                    <fullName>DBP005</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <description>IEC - SAP sales office code</description>
        <label>Sales Office</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VAT_Number__c</fullName>
        <label>VAT Number 1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>VAT_Number__c</fullName>
        <formula>IF(NOT(ISBLANK(VAT_Country_Code__c)), VAT_Country_Code__c + Tax_1_ID__c, &apos;&apos;)</formula>
        <label>VAT Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IEC_SAP_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IEC SAP Invoices</relationshipLabel>
        <relationshipName>IEC_SAP_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_To__c</fullName>
        <label>Bill To</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country_ISO_Code__c</fullName>
        <label>Billing Country ISO Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Name__c</fullName>
        <label>Billing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zip__c</fullName>
        <label>Billing Zip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End</label>
        <summarizedField>IEC_SAP_Invoice_Item__c.Date_To__c</summarizedField>
        <summaryForeignKey>IEC_SAP_Invoice_Item__c.IEC_SAP_Invoice__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Contract_Start__c</fullName>
        <label>Contract Start</label>
        <summarizedField>IEC_SAP_Invoice_Item__c.Date_From__c</summarizedField>
        <summaryForeignKey>IEC_SAP_Invoice_Item__c.IEC_SAP_Invoice__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Customer_PO__c</fullName>
        <label>Customer PO</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dist_Chan__c</fullName>
        <defaultValue>$Setup.IEC_SAP_Settings__c.DistChan__c</defaultValue>
        <label>Dist Chan</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <defaultValue>$Setup.IEC_SAP_Settings__c.Division__c</defaultValue>
        <label>Division</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doc_Currency__c</fullName>
        <defaultValue>&quot;USD&quot;</defaultValue>
        <label>Doc Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Date__c</fullName>
        <label>PO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Code__c</fullName>
        <formula>IF(Pay_Method__c = &apos;Credit Card&apos;
	, &apos;1&apos;
	, IF(Pay_Method__c = &apos;ICH&apos;
		, &apos;I&apos;
		, IF(Pay_Method__c = &apos;Bank Transfer&apos;
			, &apos;T&apos;  
            ,IF(Pay_Method__c = &apos;BankTransfer&apos;
				, &apos;T&apos;
				, &apos;&apos;
            )
		)
	)
)</formula>
        <label>Payment Method Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <defaultValue>$Setup.IEC_SAP_Settings__c.SalesOffice__c</defaultValue>
        <label>Sales Office</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <defaultValue>$Setup.IEC_SAP_Settings__c.SalesOrg__c</defaultValue>
        <label>Sales Org</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <label>Shipping Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Country__c</fullName>
        <label>Shipping Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_State__c</fullName>
        <label>Shipping State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Zip__c</fullName>
        <label>Shipping Zip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text_Print__c</fullName>
        <label>Text Print</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Positive_Quantity__c</fullName>
        <description>Sum of all quantity items in related invoice items that has a Charge Amount value &gt; 0.

This is to avoid sending negative invoice items to SAP</description>
        <inlineHelpText>Sum of all quantity items in related invoice items that has a Charge Amount value &gt; 0.

This is to avoid sending negative invoice items to SAP</inlineHelpText>
        <label>Total Positive Quantity</label>
        <summarizedField>IEC_SAP_Invoice_Item__c.Quantity__c</summarizedField>
        <summaryFilterItems>
            <field>IEC_SAP_Invoice_Item__c.Charge_Amount__c</field>
            <operation>greaterOrEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>IEC_SAP_Invoice_Item__c.IEC_SAP_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <description>Sum of all related invoice item quantity</description>
        <inlineHelpText>Sum of all related invoice item quantity</inlineHelpText>
        <label>Total Quantity</label>
        <summarizedField>IEC_SAP_Invoice_Item__c.Quantity__c</summarizedField>
        <summaryForeignKey>IEC_SAP_Invoice_Item__c.IEC_SAP_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora_Invoice_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Zuora Invoice Number</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IEC SAP Invoice</label>
    <nameField>
        <label>Zuora Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IEC SAP Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IEC_SAP_Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>Adjusted_Charge_Amount__c</fullName>
        <description>If all invoice items are positive
    value=charged amount / quantity
else
    if (charged amount &gt;0)
      value = ( Invoice subtotal/ total quantity) 
  else 
       value = 0</description>
        <formula>IF(IEC_SAP_Invoice__r.Total_Positive_Quantity__c = IEC_SAP_Invoice__r.Total_Quantity__c
	, Charge_Amount__c  / Quantity__c
	, IF(Charge_Amount__c&gt;0,(IEC_SAP_Invoice__r.Subtotal__c / IEC_SAP_Invoice__r.Total_Positive_Quantity__c) ,0)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If all invoice items are positive
    value=charged amount / quantity
else
    if (charged amount &gt;0)
      value = ( Invoice subtotal/ total quantity) 
  else 
       value = 0</inlineHelpText>
        <label>Adjusted Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charge_Amount__c</fullName>
        <label>Charge Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_From__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_To__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IEC_SAP_Invoice__c</fullName>
        <label>IEC SAP Invoice</label>
        <referenceTo>IEC_SAP_Invoice__c</referenceTo>
        <relationshipLabel>IEC SAP Invoice Items</relationshipLabel>
        <relationshipName>IEC_SAP_Invoice_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Material_Description__c</fullName>
        <label>Material Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>IEC SAP Invoice Items</relationshipLabel>
        <relationshipName>IEC_SAP_Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profit_Center__c</fullName>
        <label>Profit Center</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price_Currency__c</fullName>
        <defaultValue>&quot;USD&quot;</defaultValue>
        <label>Unit Price Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>IEC SAP Invoice Item</label>
    <nameField>
        <label>Zuora Invoice Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IEC SAP Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <description>Used by the RCRM project to hold information about what division the product belongs to.</description>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IEC_SAP_DocType__c</fullName>
        <description>IEC - determine where to get contract type</description>
        <formula>IF(ISBLANK(IEC_Parent_Product__c), IEC_SAP_Contract_Type__c, IEC_Parent_Product__r.IEC_SAP_Contract_Type__c)</formula>
        <label>IEC SAP DocType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Manager_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Product Manager for the product. Needed as a lookup for the RCRM project, the picklist used before did not correspond.</description>
        <label>Product Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Contract_OrderReason__c</fullName>
        <formula>IF(ISBLANK(IEC_SAP_DocType__c), null, IF(CONTAINS(&apos;-ZC01-ZC02-ZC99-&apos;, IEC_SAP_DocType__c), &apos;Z01&apos;, null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Contract OrderReason</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IECSAPHelper.cls
/**
 * Provides helper methods to helper call SAP web service
 */
public with sharing class IECSAPHelper {

	private final static String EMPTY = '';

	// Message type: S Success, E Error, W Warning, I Info, A Abort
	public final static String RESPONSE_TYPE_SUCCESS = 'S';
	public final static String RESPONSE_TYPE_ERROR = 'E';
	public final static String RESPONSE_TYPE_WARNING = 'W';
	public final static String RESPONSE_TYPE_INFO = 'I';
	public final static String RESPONSE_TYPE_ABORT = 'A';

	public final static String RESPONSE_MESSAGE_CONTRACT_PREFIX = 'IATA Contract ';
	public final static String RESPONSE_MESSAGE_CONTRACT_SUFFIX = ' has been saved';
	public final static String RESPONSE_MESSAGE_BILLTO_PREFIX = 'Bill To:';
	public final static String RESPONSE_MESSAGE_BILLTO_SUFFIX = ' exists in system';

	// Payment method codes
	public final static String SAP_PAYMENT_METHOD_CODE_CREDITCARD = '1';
	public final static String SAP_PAYMENT_METHOD_CODE_ICH = 'I';
	public final static String SAP_PAYMENT_METHOD_CODE_BANKTRANSFER = 'T';

	/**
	 * Creates the header object required for the invoice creation SAP web service based on the Invoice, SAP Account, IsOneTimeCustomer flag, etc
	 */
	public static iataComXiSalesforceOtcWid5600Sales3.Header_element createHeaderForInvoiceSending(IEC_SAP_Invoice__c oSAPInvoice) {

		iataComXiSalesforceOtcWid5600Sales3.Header_element oHeader = new iataComXiSalesforceOtcWid5600Sales3.Header_element();

		/* Commented as part of ECOM-495: DEV- Modify contract interface for sales area
		oHeader.SalesOrg = oSAPInvoice.Sales_Org__c;
		oHeader.DistChan = oSAPInvoice.Dist_Chan__c;
		oHeader.Division = oSAPInvoice.Division__c;
		*/
		oHeader.SalesOffice = oSAPInvoice.Account__r.Sales_Office__c;
		oHeader.ContractNumber = EMPTY;
		oHeader.BillTo = oSAPInvoice.Bill_To__c;
		oHeader.ContactPerson = EMPTY;
		oHeader.ZuoraInv = oSAPInvoice.Zuora_Invoice_Number__c;
		oHeader.PODate = oSAPInvoice.PO_Date__c;
		oHeader.Name = oSAPInvoice.Billing_Name__c; // based on feedback from Tamer, it is the Contact's name
		// SAP integration test
		//oHeader.Name = EMPTY;
		oHeader.CustomerPO = oSAPInvoice.Customer_PO__c;
		oHeader.ContractStart = oSAPInvoice.Contract_Start__c;
		oHeader.ContractEnd = oSAPInvoice.Contract_End__c;
		oHeader.DocCurr = oSAPInvoice.Doc_Currency__c;
		oHeader.PayMethod = oSAPInvoice.Payment_Method_Code__c;
		oHeader.PayTerms = oSAPInvoice.Account__r.Payment_Term__c;
		oHeader.TextPrint = oSAPInvoice.Text_Print__c;

		if (!oSAPInvoice.IEC_SAP_Invoice_Items__r.isEmpty())
		{
			// Assumption is there will always be one invoice item under the any single invoice
			IEC_SAP_Invoice_Item__c oSAPInvoiceItem = oSAPInvoice.IEC_SAP_Invoice_Items__r[0];

			oHeader.DocType = oSAPInvoiceItem.Product__r.IEC_SAP_DocType__c;
			oHeader.EmpResp = oSAPInvoiceItem.Product__r.Product_Manager_lookup__r.EmployeeNumber;
			oHeader.OrderReason = oSAPInvoiceItem.Product__r.SAP_Contract_OrderReason__c;
		}
		else
		{
			oHeader.DocType = EMPTY;
			oHeader.EmpResp = EMPTY;
			oHeader.OrderReason = EMPTY;
		}

		return oHeader;
	}

	/**
	 * Creates the items element required for the invoice creation SAP web service
	 */
	public static iataComXiSalesforceOtcWid5600Sales3.Item_element[] createItemElementsForInvoiceSending(IEC_SAP_Invoice__c oSAPInvoice) {

		List<iataComXiSalesforceOtcWid5600Sales3.Item_element> lstItemElements = new List<iataComXiSalesforceOtcWid5600Sales3.Item_element>();

		// first check if the invoice is for an upgrade
		// (upgrades have a negative amount on an invoice item, and SAP just wants the adjusted charged amount)
		Boolean bInvoiceIsForUpgrade = (oSAPInvoice.Total_Positive_Quantity__c != oSAPInvoice.Total_Quantity__c);

		for(IEC_SAP_Invoice_Item__c oSAPInvoiceItem : oSAPInvoice.IEC_SAP_Invoice_Items__r) {

			// if the invoice is for an Upgrade, ignore negative Invoice items
			if (bInvoiceIsForUpgrade && oSAPInvoiceItem.Charge_Amount__c < 0)
				continue;

			iataComXiSalesforceOtcWid5600Sales3.Item_element item = new iataComXiSalesforceOtcWid5600Sales3.Item_element();

			item.Material = oSAPInvoiceItem.Material__c;
			item.MatDesc = oSAPInvoiceItem.Material_Description__c;
			item.PrftCtr = oSAPInvoiceItem.Profit_Center__c;
			item.Quantity = String.valueOf(oSAPInvoiceItem.Quantity__c);
			item.UnitPrice = String.valueOf(oSAPInvoiceItem.Adjusted_Charge_Amount__c); // send the Adjusted Charge Amount and not the Unit Price (hack for upgrades)
			item.UnitPriceCurr = oSAPInvoiceItem.Unit_Price_Currency__c;
			item.DateFrom = oSAPInvoiceItem.Date_From__c;
			item.DateTo = oSAPInvoiceItem.Date_To__c;

			lstItemElements.add(item);
		}

		return lstItemElements;
	}

	/**
	 * Creates the Address element required for the invoice creation SAP web service
	 */
	public static iataComXiSalesforceOtcWid5600Sales3.Address_element createAddressElementForInvoiceSending(IEC_SAP_Invoice__c oSAPInvoice) {

		iataComXiSalesforceOtcWid5600Sales3.Address_element oAddress = new iataComXiSalesforceOtcWid5600Sales3.Address_element();

		// Billing Address
		oAddress.BillingAddress = oSAPInvoice.Billing_Street__c;
		oAddress.BillingCity = oSAPInvoice.Billing_City__c;
		oAddress.BillingCountry = oSAPInvoice.Billing_Country_ISO_Code__c; //oSAPInvoice.Billing_Country__c;
		oAddress.BillingPostalCode = oSAPInvoice.Billing_Zip__c;
		// convert state name to state code (if needed)
		String sStateCode = null;
		if (String.isNotBlank(oSAPInvoice.Billing_State__c) && oSAPInvoice.Billing_State__c.length() == 2)
			sStateCode = oSAPInvoice.Billing_State__c.toUpperCase();
		else
			sStateCode = IECUtil.getStateCodeByNameAndCountryCode(oSAPInvoice.Billing_State__c, oSAPInvoice.Billing_Country_ISO_Code__c);
		oAddress.BillingState = String.isBlank(sStateCode) ? EMPTY : sStateCode;
		oAddress.VATRegId = oSAPInvoice.VAT_Number__c;

		// Shipping Address
		/* AS PER RELEASE 1: leave shipping fields empty
		oAddress.ShippingContactName = oSAPInvoice.Shipping_Contact__c;
		oAddress.ShippingAddress = oSAPInvoice.Shipping_Street__c;
		oAddress.ShippingCity = oSAPInvoice.Shipping_City__c;
		oAddress.ShippingCountry = oSAPInvoice.Shipping_Country__c;
		oAddress.ShippingPostalCode = oSAPInvoice.Shipping_Zip__c;
		// convert state name to state code (if needed)
		sStateCode = null;
		if (String.isNotBlank(oSAPInvoice.Shipping_State__c) && oSAPInvoice.Shipping_State__c.length() == 2)
			sStateCode = oSAPInvoice.Shipping_State__c.toUpperCase();
		else
			sStateCode = IECUtil.getStateCodeByNameAndCountryCode(oSAPInvoice.Shipping_State__c, oSAPInvoice.??????_Country_ISO_Code__c);

		oAddress.ShippingState = String.isBlank(sStateCode) ? null : sStateCode;
		*/
		oAddress.ShippingContactName = EMPTY;
		oAddress.ShippingAddress = EMPTY;
		oAddress.ShippingCity = EMPTY;
		oAddress.ShippingCountry = EMPTY;
		oAddress.ShippingPostalCode = EMPTY;
		oAddress.ShippingState = EMPTY;

		return oAddress;
	}
}