src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Role__c</fullName>
        <description>The roles covered by the account (e.g. Payment Provider)</description>
        <inlineHelpText>The roles covered by the account</inlineHelpText>
        <label>Account Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Payment Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email at Account level</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Role__c.object
<CustomObject>
    <description>Used to extend the role of any existing account type e.g. an airline that also acts as a payment provider. A record type should be created for each type of account role required.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Id to account record</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Role</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ICG_Account_Role_Detail__c.object
<CustomObject>
    <description>One Source Facilities</description>
    <fields>
        <fullName>Account_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Account_Role__c</description>
        <label>Link to Station Account</label>
        <referenceTo>Account_Role__c</referenceTo>
        <relationshipLabel>ONE Source Stations</relationshipLabel>
        <relationshipName>ICG_Account_Role_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City_FOR__c</fullName>
        <description>Formula to get the account business city . name</description>
        <formula>BLANKVALUE(Account_Role__r.Account__r.Business_City__r.Name, Account_Role__r.Account__r.Business_City_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Admin_Approver_Rejector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who has Approved or Rejected the station</description>
        <label>Company Admin Approver/Rejector</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ApprovedOrRejectedStations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_FOR__c</fullName>
        <description>Formula to get the account . name</description>
        <formula>Account_Role__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Name (Account)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_FOR__c</fullName>
        <description>Formula to get the IATA_ISO_Country__r.Name</description>
        <formula>Account_Role__r.Account__r.IATA_ISO_Country__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <description>Reason of the request was rejected</description>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Nr_FOR__c</fullName>
        <description>Displays the account business street</description>
        <formula>Account_Role__r.Account__r.Business_Street__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street + Nr</label>
        <type>Text</type>
    </fields>
    <label>OS Account Role Detail</label>
    <nameField>
        <label>ONE Source Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OS Account Role Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ICG_Capability_Assignment_Group__c.object
<CustomObject>
    <description>One Source certification / remote validation header where relevant data is stored</description>
    <fields>
        <fullName>CEIV_Scope_List__c</fullName>
        <description>Picklist of possible values for ceiv scope</description>
        <label>CEIV Scope</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Operational</fullName>
                </value>
                <value>
                    <fullName>Cargo_Facility_Operations</fullName>
                    <label>Cargo Facility Operations</label>
                </value>
                <value>
                    <fullName>Ramp_Operations</fullName>
                    <label>Ramp Operations</label>
                </value>
                <value>
                    <fullName>Administrative_And_Operational</fullName>
                    <isActive>false</isActive>
                    <label>Administrative and Operational</label>
                </value>
                <value>
                    <fullName>Cargo_Handling</fullName>
                    <isActive>false</isActive>
                    <label>Cargo Handling</label>
                </value>
                <value>
                    <fullName>Cargo_Handling_And_Ramp</fullName>
                    <isActive>false</isActive>
                    <label>Cargo Handling and Ramp</label>
                </value>
                <value>
                    <fullName>Ramp_Handling</fullName>
                    <isActive>false</isActive>
                    <label>Ramp Handling</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ICG_Account_Role_Detail__c</fullName>
        <description>Master detail to facility</description>
        <label>ONE Source Account Role Detail</label>
        <referenceTo>ICG_Account_Role_Detail__c</referenceTo>
        <relationshipLabel>ONE Source Capability Assignment Groups</relationshipLabel>
        <relationshipName>ICG_Capability_Assignment_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ICG_Certification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Certification</description>
        <label>ONE Source Certification</label>
        <referenceTo>ICG_Certification__c</referenceTo>
        <relationshipLabel>ONE Source Capability Assignment Groups</relationshipLabel>
        <relationshipName>ICG_Capability_Assignment_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFOC_Scope__c</fullName>
        <description>Multiselect to display the scope of SFOC records</description>
        <label>SFOC Scope</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Cargo</fullName>
                </value>
                <value>
                    <fullName>Dangerous Goods</fullName>
                </value>
                <value>
                    <fullName>Live Animals</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals</fullName>
                </value>
                <value>
                    <fullName>Perishables</fullName>
                </value>
                <value>
                    <fullName>Airmail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OS Capability Assignment Group</label>
    <nameField>
        <displayFormat>OSC-{0000000}</displayFormat>
        <label>ONE Source Capability Assignment Group</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OS Capability Assignment Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ICG_Certification__c.object
<CustomObject>
    <description>One Source Catalog of certifications</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>Field used to show in the UI</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OS Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OS Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ICG_Contact_Role_Detail__c.object
<CustomObject>
    <description>Function assigned to a contact towars a facility (ICG_Account_Role_Detail__c)</description>
    <label>ONE Source Contact Role Detail</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>ONE Source Contact Role Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ONE Source Contact Role Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fill this field if you are company admin of a specific Ops Hierarchy. This will determine the ops hierarchy that you belong to as company admin.</description>
        <label>Account Role</label>
        <referenceTo>Account_Role__c</referenceTo>
        <relationshipLabel>ONE Source Contact Role Details</relationshipLabel>
        <relationshipName>ICG_Contact_Role_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Admin_Approver_Rejector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who has Approved or Rejected the station</description>
        <label>Company Admin Approver/Rejector</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ApprovedOrRejectedContactRoleDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <description>Describes the contact id</description>
        <formula>CASESAFEID(Account_Contact_Role__r.Contact__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <description>Station Contact Email</description>
        <formula>Account_Contact_Role__r.Contact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <description>Station Contact Name</description>
        <formula>Account_Contact_Role__r.Contact__r.FirstName +&apos; &apos;+ Account_Contact_Role__r.Contact__r.LastName</formula>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Remove_Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Keep track of which user has requested the removal of a contact role detail.</description>
        <label>Contact Role Remove Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ICG_Contact_Role_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ICG_Account_Role_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship between the ICG Contact role detail, and the facility.</description>
        <label>ONE Source Account Role Detail</label>
        <referenceTo>ICG_Account_Role_Detail__c</referenceTo>
        <relationshipLabel>ONE Source Contact Role Details</relationshipLabel>
        <relationshipName>ICG_Contact_Role_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reject_Reason__c</fullName>
        <description>Reason of the request was rejected</description>
        <label>Reject Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/ICG_Notification__c.object
<CustomObject>
    <label>OS Notification</label>
    <description>One Source Account Role Detail Relationship</description>
    <nameField>
        <displayFormat>ICGNOTIF{000000}</displayFormat>
        <label>ONE Source Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OS Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <description>Describes the certification name</description>
        <formula>ICG_Certification__r.Name</formula>
        <label>Certification Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <description>Describes the contact email</description>
        <label>Contact Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <description>Describes the contact name</description>
        <label>Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ICG_Certification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Describes the certification linked</description>
        <label>ONE Source Certification</label>
        <referenceTo>ICG_Certification__c</referenceTo>
        <relationshipLabel>ONE Source Notifications</relationshipLabel>
        <relationshipName>ICG_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferable_Audit_Date__c</fullName>
        <description>Describes the date preferable for audit</description>
        <label>Preferable Audit Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/classes/CW_EmailTemplateData.cls
public without sharing class CW_EmailTemplateData {
	public String stationId {get; set;}
	public String notificationId {get; set;}
	public String contactRoleDetailId {get; set;}
	public String orderItemId {get; set;}
	public Boolean isRemove {get;set;}
	public Boolean isToIata {get;set;}
	public Boolean isCompanyAdmin {
		get{
			return stationId != null ? CW_Utilities.getUserRole(stationId) == CW_Utilities.COMPANY_ADMIN : false;
		}
		set;
	}
	List<ICG_Account_Role_Detail__c> station;
	List<ICG_Notification__c> notifications;
	List<ICG_Contact_Role_Detail__c> contactRoleDetail;
	List<OrderItem> orderItem;
	List<User> userRequestor;
	List<Account> accountDetail;
	public Boolean isPurchaseRemoteValidation {get;set;}
	List<ICG_Capability_Assignment_Group__c> ICGCapabilityAssignmentGroups{get; set;}

	public ICG_Notification__c getnotificationDetails(){
		if(notifications == null && notificationId != null){
			notifications = [SELECT Id, Certification_Name__c, Contact_Email__c, Contact_Name__c, Preferable_Audit_Date__c, ICG_Certification__r.Label__c FROM ICG_Notification__c WHERE Id = :notificationId LIMIT 1];
		}
		return listHasValues(notifications) ? notifications[0] : null;
	}

	public ICG_Account_Role_Detail__c getStationDetails(){
		if(station == null && stationId != null){
			station = [SELECT Id, Name, Company_FOR__c, Country_FOR__c, City_FOR__c, Street_Nr_FOR__c, CreatedById, Account_Role__c, Account_Role__r.Account__c, RecordType.DeveloperName, RecordType.Name, Company_Admin_Approver_Rejector__c, LastModifiedById, Reject_Reason__c FROM ICG_Account_Role_Detail__c WHERE Id = :stationId LIMIT 1];
		} 
		return listHasValues(station) ? station[0] : null;
	}

 
	public ICG_Contact_Role_Detail__c getContactRoleDetails(){
		if(contactRoleDetail == null && contactRoleDetailId != null){
			contactRoleDetail = [SELECT Id, CreatedById, ICG_Account_Role_Detail__c, Contact_Role_Remove_Requestor__c, ContactId__c, ICG_Account_Role_Detail__r.Account_Role__r.Account__c, Account_Role__r.Account__c, Company_Admin_Approver_Rejector__c, LastModifiedById, Reject_Reason__c FROM ICG_Contact_Role_Detail__c WHERE Id = :contactRoleDetailId LIMIT 1];
		} 
		return listHasValues(contactRoleDetail) ? contactRoleDetail[0] : null;
	}

	public List<ICG_Capability_Assignment_Group__c> getICGCapabilityAssignmentGroups(){
		if(ICGCapabilityAssignmentGroups == null && stationId != null){
			ICGCapabilityAssignmentGroups = new List<ICG_Capability_Assignment_Group__c>([SELECT Id, ICG_Certification__r.Name, ICG_Certification__r.Label__c, toLabel(CEIV_Scope_List__c), SFOC_Scope__c, CreatedDate FROM ICG_Capability_Assignment_Group__c WHERE ICG_Account_Role_Detail__c = :stationId AND ICG_Certification__c != null]);
		} 
		return listHasValues(ICGCapabilityAssignmentGroups) ? ICGCapabilityAssignmentGroups : new List<ICG_Capability_Assignment_Group__c>();
	}


	public OrderItem getOrderItemDetails(){
		if(orderItem == null && orderItemId != null){
			orderItem = [SELECT Id, OrderId, (Select Id FROM ICG_Capability_Assignment_Groups__r), CreatedById FROM OrderItem where Id =:orderItemId];
		} 
		return listHasValues(orderItem) ? orderItem[0] : null;
	}

	public Order getOrderDetails(){
		Order orderDetails;
		if(orderItem == null && orderItemId != null){
			orderDetails = [SELECT Id, OrderNumber FROM Order where Id =:getOrderItemDetails().OrderId LIMIT 1];
		} 
		return orderDetails;
	}


	public List<ICG_Contact_Role_Detail__c> getStationManagersContactRoleDetails(){
		return (stationId != null) ? CW_Utilities.getStationManagersContactRoleDetails(stationId) : new List<ICG_Contact_Role_Detail__c>();
	}

	public User getRequestedBy()
	{
		if(userRequestor == null){
			String requestorId;
			if(getContactRoleDetails() != null){
				requestorId = contactRoleDetail[0].Contact_Role_Remove_Requestor__c != null ? contactRoleDetail[0].Contact_Role_Remove_Requestor__c : contactRoleDetail[0].CreatedById;
			}
			else if(getOrderItemDetails() != null){
				requestorId = orderItem[0].CreatedById;
			}
			else if (getStationDetails() != null){
				requestorId = station[0].CreatedById;
			}

			userRequestor = queryUserById(requestorId);
		}
		
		return listHasValues(userRequestor) ? userRequestor[0] : null;
	}

	public String getRequestedByCompanyAddress()
	{
		String address='';
		User u = getRequestedBy();
		if (u != null){
			address = buildAddress(u);
		}

		return address;
	}

	public Account getAccountDetail()
	{
		if (getStationDetails() != null){
			accountDetail = [SELECT Id, TradeName__c,Legal_name__c,Phone,Email__c,Website, Category__c, Sector__c FROM Account WHERE Id = :station[0].Account_Role__r.Account__c LIMIT 1];
		}
		return listHasValues(accountDetail) ? accountDetail[0] : null;
	}

	public String getCommunityUrl(){
		return CW_Utilities.getCommunityUrlBase();
	}

	public String getCommunityUrlForResources(){
		return CW_Utilities.getCommunityUrlBase().removeEnd('s/');
	}

	public String getPrivateAreaUrl(){
		return CW_Utilities.getURLPage('URL_ICG_PrivateArea');
	}

	public String getFacilityPageUrl(){
		return CW_Utilities.getURLPage('URL_ICG_FacilityPage');
	}

	public String getOperationalHierarchyFromStation(){
		String opsHierarchy = getStationDetails() != null ? CW_Utilities.getOpsHierarchyNameFromStationId(station[0].Id) : 'N/A';
		return opsHierarchy;
	}

	public String getOperationalHierarchyFromCrd(){
		String opsHierarchy = 'N/A';
		if(getContactRoleDetails() != null){
			if(contactRoleDetail[0].ICG_Account_Role_Detail__c != null){
				return CW_Utilities.getOpsHierarchyNameFromStationId(contactRoleDetail[0].ICG_Account_Role_Detail__c);
			} 
			else if (contactRoleDetail[0].Account_Role__c != null) {
				return CW_Utilities.getOpsHierarchyNameFromAccountId(contactRoleDetail[0].Account_Role__r.Account__c);
			} 
		}
		return opsHierarchy;
	}

	public String getOperationalHierarchyFromCrdOrStation(){
		if(getOperationalHierarchyFromCrd() != 'N/A'){
			return getOperationalHierarchyFromCrd();
		}
		else {
			return getOperationalHierarchyFromStation();
		}
	}

	public String getOperationalHierarchyFromRequestor(){
		String opsHierarchy = getRequestedBy() != null ? CW_Utilities.getOpsHierarchyNameFromUserId(getRequestedBy().Id) : 'N/A';
		return opsHierarchy;
	}

	public String getOperationalHierarchyGroupFromRequestor(){
		String opsHierarchy = getRequestedBy() != null ? CW_Utilities.getOpsHierarchyGroupFromUserId(getRequestedBy().Id) : 'N/A';
		return opsHierarchy;
	}

	public List<ICG_Account_Role_Detail__c> getDuplicatedStations(){
		List<ICG_Account_Role_Detail__c> duplicatedStations;
		if (getStationDetails() != null){
			duplicatedStations = [SELECT Name, Status__c FROM ICG_Account_Role_Detail__c WHERE RecordType.DeveloperName =:station[0].RecordType.DeveloperName and Account_Role__c =:station[0].Account_Role__c and Id !=:station[0].Id];
		}
		return listHasValues(duplicatedStations) ? duplicatedStations : null;
	}

	private Boolean listHasValues(List<Object> listToCheck){
		return listToCheck != null && !listToCheck.isEmpty();
	}

	public String getApproveUrl(){
		String approveUrl = getPrivateAreaUrl();        
		if (isRemove == true){
			if(getContactRoleDetails() != null){
				approveUrl += '?approveRemoveContactRole='+contactRoleDetail[0].Id;
			}
		}else{
			if(getContactRoleDetails() != null){
				approveUrl += '?approveContactRole='+contactRoleDetail[0].Id;
			}
			else if (getStationDetails() != null){
				approveUrl += '?approveStation='+station[0].Id;
			}
		}
		return approveUrl;
	}

	public String getApprovalUrl(){		
		String approvalUrl = getPrivateAreaUrl(); 
		if(getContactRoleDetails() != null){
			approvalUrl += '#Pending%20User%20Approvals';
		}
		else if (getStationDetails() != null){
			approvalUrl += '#Pending%20Facility%20Approvals';
		}
		return approvalUrl;
	}

	public Contact getContactRoleDetailContact(){

		List<Contact> crdContact;
		if(getContactRoleDetails() != null){
			crdContact = queryContactById(contactRoleDetail[0].ContactId__c);
		}

		return listHasValues(crdContact) ? crdContact[0] : null;
	}
	
	public String getContactRoleDetailContactAccountAddress(){
		String address='';
		Contact c = getContactRoleDetailContact();
		if ( c != null){
		   address = buildAddress(c);
		}

		return address;
	}

	public String getRejectUrl(){
		String rejectUrl = getPrivateAreaUrl();

		if (isRemove == true){
			if(getContactRoleDetails() != null){
				rejectUrl += '?rejectRemoveContactRole='+contactRoleDetail[0].Id;
			}
		}else{
			if(getContactRoleDetails() != null){
				rejectUrl += '?rejectContactRole='+contactRoleDetail[0].Id;
			}
			else if (getStationDetails() != null){
				rejectUrl += '?rejectStation='+station[0].Id;
			}
		}

		return rejectUrl;
	}

	public String getStationUrl(){
		String url = isToIata == true ? CW_Utilities.getEnvironmentVariables().InternalRequestURL__c : getPrivateAreaUrl() + '/#ID:';
		if (getStationDetails() != null){
			url += String.valueOf(station[0].Id);
		}
		
		return url;
	}

	public String getPublicStationUrl(){
		String url = getFacilityPageUrl();
		if (getStationDetails() != null){
			url += '?eid='+station[0].Id;
		}
		return url;
	}

	public String getManageCompanyAdminsUrl(){
		String url = getPrivateAreaUrl();
		url += '#Company%20Admins';
		return url;
	}

	public String getIataManageRequest(){
		ICG_Environment_Variables__c environmentVariables = CW_Utilities.getEnvironmentVariables();
		String manageRequestUrl = environmentVariables.InternalRequestURL__c;
		if(getContactRoleDetails() != null){
			manageRequestUrl += String.valueOf(contactRoleDetail[0].Id);
		}
		else if (getStationDetails() != null){
			manageRequestUrl += String.valueOf(station[0].Id);
		}

		return manageRequestUrl;
	}

	public List<Contact> getCompanyAdminContacts(){
		if(contactRoleDetailId != null && getContactRoleDetails() != null){
			return contactRoleDetail[0].ICG_Account_Role_Detail__c != null ? CW_Utilities.getCompanyAdminContactsFromAccountId(contactRoleDetail[0].ICG_Account_Role_Detail__r.Account_Role__r.Account__c) : CW_Utilities.getCompanyAdminContactsFromAccountId(contactRoleDetail[0].Account_Role__r.Account__c);
		} 
		else if(stationId != null && getStationDetails() != null){
			return CW_Utilities.getCompanyAdminContactsFromAccountId(station[0].Account_Role__r.Account__c);
		} 
		else{
			return new List<Contact>();
		} 
	}
	
	public User getApprover (){
		List<User> approver;
		String approverId;
		if(getContactRoleDetails() != null){
			approverId = contactRoleDetail[0].Company_Admin_Approver_Rejector__c != null ? contactRoleDetail[0].Company_Admin_Approver_Rejector__c : contactRoleDetail[0].LastModifiedById;
		}
		else if (getStationDetails() != null){
			approverId = station[0].Company_Admin_Approver_Rejector__c != null ? station[0].Company_Admin_Approver_Rejector__c : station[0].LastModifiedById;
		}

		if(approverId != null){
			approver = queryUserById(approverId);
		}
		
		return listHasValues(approver) ? approver[0] : null;
	}

	public String getRejectReason (){
		String rejectReason;

		if(getContactRoleDetails() != null){
			rejectReason = contactRoleDetail[0].Reject_Reason__c != null ? contactRoleDetail[0].Reject_Reason__c : 'No Reason Provided';
		}
		else if (getStationDetails() != null){
			rejectReason = station[0].Reject_Reason__c != null ? station[0].Reject_Reason__c : 'No Reason Provided';
		}
		
		return rejectReason;
	}

	public String getApproverAddress()
	{
		String address='';
		User u = getApprover();
		if ( u != null){
		   address = buildAddress(u);
		}

		return address;
	}

	public String getContactRoleDetailUserAddress(){
		String address='';
		Contact c = getContactRoleDetailContact();
		if ( c != null){
			address = buildAddress(c);
		}

		return address;
	}

	public String getApproverOpsHierarchy()
	{
		String opsHierarchy='';
		User u = getApprover();
		if ( u != null && u.accountId != null){
			opsHierarchy = CW_Utilities.getOpsHierarchyNameFromAccountId(u.accountId);
		}

		return opsHierarchy; 
	}

	public String buildAddress(Object userOrContact){
		User u = userOrContact instanceOf User ? (User)userOrContact : null;
		Contact c = userOrContact instanceOf Contact ? (Contact)userOrContact : null;

		String address='';
		if( (u!= null && u.AccountId != null) || (c!= null && c.AccountId != null)){
			address += u!= null ? u.Account.Business_Street__c : c.Account.Business_Street__c;
			if(address != ''){
				address+=', ';
			}
			address += u!= null ? u.Account.Business_Postal_Code__c : c.Account.Business_Postal_Code__c;
			if(address != '' && !address.endsWith(', ')){
				address+=', ';
			}
			if(u != null){
				address +=  u.Account.Business_City__c != null ? u.Account.Business_City__r.Name : u.Account.Business_City_Name__c;
			}else{
				address +=  c.Account.Business_City__c != null ? c.Account.Business_City__r.Name : c.Account.Business_City_Name__c;
			}

			if(address != '' && !address.endsWith(', ')){
				address+=', ';
			}
			address += u!= null ? u.Account.IATA_ISO_Country__r.Name : c.Account.IATA_ISO_Country__r.Name;
			address = address.replaceAll('null, ','');
		}
		return address;
	}

	public String getRemoteValidationLink(){
		if(isPurchaseRemoteValidation == true){
			return getPurchaseRemoteValidationLink();
		} 
		else{
			return getOpenRemoteValidationAreaUrl();
		}
	}

	public String getOpenRemoteValidationAreaUrl(){
		return getPrivateAreaUrl() + '#Open%20Remote%20Validations';
	}

	public String getPurchaseRemoteValidationLink(){
		return getPrivateAreaUrl() + '#Purchase%20Remote%20Validation';
	}

	public String getScheduleAuditsUrl(){
		return getPrivateAreaUrl() + '#Schedule%20Audits';
	}

	public String getAccountToApproveUrl(){
		ICG_Environment_Variables__c environmentVariables = CW_Utilities.getEnvironmentVariables();
		String accountToApproveUrl = environmentVariables.InternalRequestURL__c;

		if (getStationDetails() != null){
			accountToApproveUrl += getAccountDetail() != null ? getAccountDetail().Id : ''; 
		}

		return accountToApproveUrl;
	}
	
	public List<User> queryUserById(String id){
		return [SELECT FirstName, LastName, Name, Email, Account.Name, AccountId, Account.Business_Street__c, Account.Business_Postal_Code__c, Account.Business_City__c, Account.Business_City__r.Name, Account.Business_City_Name__c, Account.IATA_ISO_Country__r.Name FROM User WHERE Id = :id LIMIT 1];
	}

	public List<Contact> queryContactById(String id){
		return [SELECT FirstName, LastName, Name, Email, Account.Name, AccountId, Account.Business_Street__c, Account.Business_Postal_Code__c, Account.Business_City__c, Account.Business_City__r.Name, Account.Business_City_Name__c, Account.IATA_ISO_Country__r.Name FROM Contact WHERE Id = :id LIMIT 1];
	}

}