src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Role__c</fullName>
        <description>The roles covered by the account (e.g. Payment Provider)</description>
        <inlineHelpText>The roles covered by the account</inlineHelpText>
        <label>Account Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Payment Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Contact_Role__c.object
<CustomObject>
    <description>Related to the Account Role, used to designate an existing contact, under the account, that acts as a primary contact for the associated type of account role.</description>
    <fields>
        <fullName>Account_Role__c</fullName>
        <description>Reference to the Account Role</description>
        <label>Account Role</label>
        <referenceTo>Account_Role__c</referenceTo>
        <relationshipLabel>Account Contacts Role</relationshipLabel>
        <relationshipName>Account_Contacts_Role</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the account referenced</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts Role</relationshipLabel>
        <relationshipName>Account_Contacts_Role</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Reference to the contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Contacts Role</relationshipLabel>
        <relationshipName>Account_Contacts_Role</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <description>Business context this detailed role will be related to</description>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Functional_Roles</valueSetName>
        </valueSet>
    </fields>
    <label>Account Contact Role</label>
    <nameField>
        <displayFormat>ACR-{000000000}</displayFormat>
        <label>Account Contact Role Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts Role</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Role__c.object
<CustomObject>
    <description>Used to extend the role of any existing account type e.g. an airline that also acts as a payment provider. A record type should be created for each type of account role required.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Id to account record</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <description>Business context this detailed role will be related to</description>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Functional_Roles</valueSetName>
        </valueSet>
    </fields>
    <label>Account Role</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AccountContactRole__e.object
<CustomObject>
    <description>Platform event definition to be used for ALL Account Contact Role record changes that require an integration with middleware.</description>
    <fields>
        <fullName>EventType__c</fullName>
        <description>The type of operation that resulted in the platform event being fired (Create, Update, Delete, Undelete).</description>
        <label>EventType</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>8 character, case insensitive, Salesforce record Id representing the record that was modified.</description>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <description>The name of the record type of the record that was changed.</description>
        <label>RecordType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Contact Role PE</label>
    <pluralLabel>Account Contact Roles PE</pluralLabel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <description>Transversal Object used to store data of different types of addresses.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>Address-{00000000}</displayFormat>
        <label>Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Address_Role__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is the Address to which this Address Role is associated.</description>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Addresses Role</relationshipLabel>
        <relationshipName>Addresses_Role</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Address Role</label>
    <nameField>
        <displayFormat>AR-{0000000}</displayFormat>
        <label>Address Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses Role</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Address_Role_Business_Context__c.object
<CustomObject>
    <fields>
        <fullName>Account_Activation_Context_Status__c</fullName>
        <description>Used to define the status of a flow</description>
        <label>Account Activation Context Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address_Role__c</fullName>
        <description>used to reference the address role record getting extended with the selected context (sales area equivalent in SAP)</description>
        <label>Address Role</label>
        <referenceTo>Address_Role__c</referenceTo>
        <relationshipName>Address_Role_Business_Process</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Address Role Business Context</label>
    <nameField>
        <displayFormat>ARBP-{0000000}</displayFormat>
        <label>Address Role Business Context Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Roles Business Context</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Functional_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>E&amp;F</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>One Source</fullName>
    </customValue>
    <customValue>
        <fullName>One Source</fullName>
    </customValue>
    <description>Functional Roles</description>
    <masterLabel>Functional Roles</masterLabel>
</GlobalValueSet>

src/classes/ContactSyncUtils.cls
/**
 * Created by LBERB on 22/10/2019.
 */

/**
 * Handle Contact (Contact, Account Contact Role, Address Role Business Context) synchronization logic to SAP/DMS
 */
public with sharing class ContactSyncUtils extends SObjectSyncUtils {

    public class ContactSyncException extends Exception {
    }

    private static Map<String, List<String>> FIELDS_TO_CHECK_ON_UPDATE = new Map<String, List<String>>{
            'Contact' => new List<String>{
                    'Title',
                    'FirstName',
                    'LastName',
                    'Phone',
                    'Email'
            },
            'Account_Contact_Role__c' => new List<String>{
                    'Functional_Role__c',
                    'Contact__c'
            },
            'Address_Role_Business_Context__c' => new List<String>{
                    'Account_Activation_Context_Status__c'
            }
    };

    public ContactSyncUtils() {
        this.fieldsToCheckOnUpdate.putAll(FIELDS_TO_CHECK_ON_UPDATE);
    }

    /**
     * Handle synchronize logic between Salesforce and SAP/DMS
     *
     * @param sobjIdsByAccountIds
     * @param eventType (Insert, Update, Delete, Undelete)
     */
    public void doSynchronisation(List<SObject> sObjects, String eventType) {
        System.debug('ContactSyncUtils.doSynchronisation() - ' + eventType);

        System.debug('sObjects.size() : ' + sObjects.size());
        System.debug('sObjects : ' + sObjects);
        if (sObjects.size() == 0) {
            return;
        }

        PlatformEventUtils.clear();

        System.debug('Processing data');
        Set<String> doneKeys = new Set<String>();
        String key;
        for (Account_Contact_Role__c accountContactRole : getACRFromSObjects(sObjects)) {
            // Only one platform event per Contact in a same Account
            key = accountContactRole.Contact__c + '|' + accountContactRole.Account__c;
            if(!doneKeys.contains(key)) {
                doneKeys.add(key);

                PlatformEventUtils.add(new AccountContactRole__e(
                        EventType__c = eventType,
                        RecordType__c = accountContactRole.RecordType.DeveloperName,
                        RecordId__c = accountContactRole.Id
                ));
            }
        }


        Boolean isFullSuccess = PlatformEventUtils.send();
    }


    /**
     * Get a list of Account Contact Role from the given @sObjects (Contact, Account Contact Role, Address Role Business Context)
     *
     * @param sObjects
     *
     * @return List of Account Contact Role
     */
    private List<Account_Contact_Role__c> getACRFromSObjects(List<SObject> sObjects){
        System.debug('getACRFromSObjects()');

        Set<Id> ids = new Set<Id>();

        String query = 'SELECT Id, RecordType.DeveloperName, Contact__c, Account_Role__r.Account__c';
        query += ' FROM Account_Contact_Role__c';
        query += ' WHERE ';

        // Context is observed by the current where clause
        switch on sObjects.get(0){
            when Contact contact {
                System.debug('from Contact');
                query += 'Contact__c';

                for (SObject sobj : sObjects) {
                    ids.add(sobj.Id);
                }
            }
            when Account_Contact_Role__c  accountContactRole {
                System.debug('from Account Contact Role');
                query += 'Id';

                for (SObject sobj : sObjects) {
                    ids.add(sobj.Id);
                }
            }
            when Address_Role_Business_Context__c addressRoleBusinessContext {
                System.debug('from Address Role Business Context');
                query += 'Account_Role__r.Account__c';

                for(Address_Role_Business_Context__c addressRoleBusinessContext : [
                        SELECT Address_Role__r.Address__r.Account__c
                        FROM Address_Role_Business_Context__c
                        WHERE Id IN :sObjects
                ]){
                    ids.add(addressRoleBusinessContext.Address_Role__r.Address__r.Account__c);
                }
            }
            when else {
                // TODO throw exception with Custom Label
                throw new ContactSyncException(String.format('This process does not support the SObject {0}', new List<String>{sObjects.get(0).getSObjectType().getDescribe().getName()}));
            }
        }

        query += ' IN :ids';

        query += ' ORDER BY Account_Role__r.Account__c DESC, Contact__c DESC, Id DESC';
        System.debug('query : ' + query);
        System.debug('ids : ' + ids);

        // Apply filter : only one platform event per Contact in a same Account
        List<Account_Contact_Role__c> accountContactRoles = new List<Account_Contact_Role__c>();

        Set<String> doneKeys = new Set<String>();
        String key;
        for (Account_Contact_Role__c accountContactRole : Database.query(query)) {
            key = accountContactRole.Contact__c + '|' + accountContactRole.Account_Role__r.Account__c;
            if(!doneKeys.contains(key)) {
                doneKeys.add(key);

                accountContactRoles.add(accountContactRole);
            }
        }

        return accountContactRoles;
    }
}