src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assessment_Performed_Date__c</fullName>
        <description>Used to copy the last one from the case IATA FINANCIAL REVIEW IFAP</description>
        <label>Last Assessment Performed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fin_statements_submission_deadline__c</fullName>
        <label>Fin. statements submission deadline</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financial_Review_Result__c</fullName>
        <description>Used to copy the last one from the case IATA FINANCIAL REVIEW IFAP</description>
        <label>Last Financial Review Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Financial_Review_Open_Cases__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Financial Review Open Cases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Financial_Assessment_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tell if the contact is define as Financial Assessment Contact.
IFAP Application.</description>
        <label>Financial Assessment Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>AIMS_Area_ID__c</fullName>
        <description>Area identifier used by AIMS</description>
        <inlineHelpText>Area identifier used by AIMS</inlineHelpText>
        <label>AIMS Area ID</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AIMS_Area_Name__c</fullName>
        <label>AIMS Country Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DownloadAgentsCtrlTest.cls
@isTest
private class DownloadAgentsCtrlTest {
       
       static testMethod void myUnitTest() {
       
        ID Hq  =Schema.SObjectType.Account.RecordTypeInfosByName.get('Airline Headquarters').RecordTypeId ;
        ID IFAPCaseID  =Schema.SObjectType.Case.RecordTypeInfosByName.get('IATA Financial Review').RecordTypeId ;
                
         IATA_ISO_Country__c isoCountry = new IATA_ISO_Country__c(name = 'suisse',ISO_Code__c ='SS',AIMS_Area_Name__c='suisse',AIMS_Area_ID__c= '1' );
         insert isoCountry;

                Account Hqrter = new Account(name ='IFAP ACCT',
                Fin_statements_submission_deadline__c= String.valueOF(date.today().Year()),
                    Has_Financial_Review_Open_Cases__c = false,
                                             industry = 'pluto',
                                             IATA_ISO_Country__c=isoCountry.id,
                                             recordtypeID = Hq,
                                             IATACode__c ='1234567',
                                             Type = 'IATA Cargo Agent',Status__c = 'Approved',    
                                             billingCountry = 'suisse',Location_Type__c = 'AO');
        insert Hqrter;
        
        
        Contact con = new Contact(firstName='Name',lastname ='bingo',email='bingo@asdf.it', accountID = Hqrter.id, Financial_Assessment_Contact__c = true);
        
        
                insert con;
                
        date dead = date.today().addDays(40);
        
        Case c = new Case(recordtypeID = IFAPCaseID,
        
                              Status = 'Assessment Performed',
                              Origin = 'asd',
                              IFAP_Area__c = 'asda',
                              Financial_Review_Type__c ='bla',
                              IFAP_Financial_Year__c =  String.valueOF(date.today().Year()),
                              Deadline_Date__c = dead,
                              contactid = con.id,
                              AccountId = Hqrter.id,
                              Assessment_Performed_Date__c = date.today(),
                              Financial_Review_Result__c = 'Satisfactory - No Action'                                                    
                              );
            
            insert c;
        
        PageReference pageRef = Page.DownloadAgents;
        Test.setCurrentPage(pageRef);
        
         ApexPages.currentPage().getParameters().put('agentStatus','Approved');
         ApexPages.currentPage().getParameters().put('agentType','IATA Cargo Agent');
         //ApexPages.currentPage().getParameters().put('country','suisse');
         ApexPages.currentPage().getParameters().put('ISOcountry',isoCountry.id);
         ApexPages.currentPage().getParameters().put('email','Available');
         ApexPages.currentPage().getParameters().put('exclClosedCases','false');
         ApexPages.currentPage().getParameters().put('exclOpenCases','false');
         ApexPages.currentPage().getParameters().put('targetFinancialYear','String.valueOF(date.today().Year())');
         ApexPages.currentPage().getParameters().put('yearend','--All--');
                 
        DownloadAgentsCtrl crtl = new DownloadAgentsCtrl();
        system.assertEquals(crtl.displayList.size(),1);
        
       }

}