src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region_formula__c</fullName>
        <description>Retrieves the Region from the selected item in the ISO Country lookup</description>
        <formula>TEXT(IATA_ISO_Country__r.Region__c)</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Statements</relationshipLabel>
        <relationshipName>Account_Statements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Remittance_Date__c</fullName>
        <label>Remittance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(
  Balance__c=0,
   $Label.ISSP_Fullpayment,
  IF(Balance__c&gt;0, $Label.ISSP_Pending, $Label.ISSP_Excess)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Account Statement</label>
    <nameField>
        <label>Account Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Notification_Template__c</fullName>
        <label>Notification Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ISSP_Notifications_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Set what trigger notification for which object and with a given template</description>
    <fields>
        <fullName>Notification_Template_Id__c</fullName>
        <description>The notification template Id to use for the notification</description>
        <label>Notification Template Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ISSP Notifications Trigger</label>
</CustomObject>

src/objects/Notification_template__c.object
<CustomObject>
    <fields>
        <fullName>Admins_Users__c</fullName>
        <label>Administrators/User</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrators</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Alert_Contact_By_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alert Contact By Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CriticalNotification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>wf : to check send email box.
notifications with this box checked will be first in the list of notification on the dashboard</description>
        <label>Critical notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DDS_Update_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EU Agent Consent Update Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_date__c</fullName>
        <label>Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expire_in_days__c</fullName>
        <label>Expire in (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Chinese (Simplified)</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazilian)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Notification_template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Notification template</label>
        <referenceTo>Notification_template__c</referenceTo>
        <relationshipLabel>Notification templates</relationshipLabel>
        <relationshipName>Notification_templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notification_color__c</fullName>
        <label>Notification color</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>#007FFF</fullName>
                </value>
                <value>
                    <fullName>#FF5E4D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification template</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notification template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Contact__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Enable_Notifications__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Activates the notification service for current application</description>
        <label>Enable Notifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Template__c</fullName>
        <label>Notification Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Terms_Acceptance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if terms and conditions have been accepted</description>
        <label>Terms Acceptance</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ISSP_AccountStatementsSchedule.cls
/**
 */
global class ISSP_AccountStatementsSchedule implements Schedulable {

    public static final Notification_template__c NOTIFICATION_TEMPLATE = [
        Select Type__c, Subject__c, Notification_color__c, Name, Message__c, Master_Notification_template__c, Language__c, Id, Expire_in_days__c, Due_date__c, DDS_Update_Request__c, Alert_Contact_By_Email__c, Admins_Users__c, CriticalNotification__c,
            (Select Type__c, Subject__c, Notification_color__c, Name, Message__c, Master_Notification_template__c, Language__c, Id, Expire_in_days__c, Due_date__c, DDS_Update_Request__c, Alert_Contact_By_Email__c, Admins_Users__c, CriticalNotification__c
            from Notification_templates__r)
        From Notification_template__c
        Where Id = :ISSP_Notifications_Trigger__c.getValues('Account Statements').Notification_Template_Id__c
        Limit 1
    ];

    public Integer elemsPerBatch;
    public String region;
    public Integer daysToRemittance;

    public ISSP_AccountStatementsSchedule () {
        this.elemsPerBatch = 1;
        this.region = '';
        this.daysToRemittance = 1;
    }

    public ISSP_AccountStatementsSchedule (String region, Integer daysToRemittance) {
        this.elemsPerBatch = 1;
        this.region = region;
        this.daysToRemittance = daysToRemittance;
    }

    global void execute(SchedulableContext ctx) {
        launchBatch();
    }

    public void launchBatch() {

        // date to filter the remmitance date
        // by default is today + 1 day (so TOMORROW) but it can be changed
        DateTime remittanceDate = Date.today().addDays(this.daysToRemittance);
        String remittanceDateStr = remittanceDate.formatGMT('yyyy-MM-dd');

        /**
            Find all contacts related to accounts
            with right to access to Account statements application in Portal
            and have accepted terms and conditions
        **/
        ISSP_NotificationBatch bc = new ISSP_NotificationBatch();
        bc.Query = 'SELECT ' + String.join(ISSP_NotificationUtilities.getAllContactFields(), ',')
        + ' FROM Contact '
        + ' WHERE Account.Status__c IN (\'Approved\',\'Changes Processed\',\'Listed\')'
        + ' AND AccountId in ('
        + '   Select Account__c'
        + '   From Account_Statement__c'
        + '   where Remittance_Date__c = ' + remittanceDateStr + ')'
        + ' And id in ('
        + '   Select contact__c'
        + '   From Portal_Application_Right__c'
        + '   Where Right__c = \'Access Granted\''
        + '   And Enable_Notifications__c = true'
        + '   And Portal_Application__r.Name =  \'' + ISSP_Ctrl_AccountStatements.APP_NAME + '\')';
        //+ '   And Terms_Acceptance__c = true'
        if ( this.region != null && this.region != '' ) {
        	bc.Query += '   And Account.Region_Formula__c =  \'' + this.region + '\'';
        }

        bc.NotificationTemplate = NOTIFICATION_TEMPLATE;
        bc.MessagesByGroupMap = null;
        bc.ContactGroupField = null;
        Database.executeBatch(bc, elemsPerBatch);
    }
}