src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ANG_IEP_Status__c</fullName>
        <description>To store HE easy pay status</description>
        <label>IEP HE Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No IEP Account</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Rejected by IEP Supplier</fullName>
                </value>
                <value>
                    <fullName>Closed – 2-year freeze period</fullName>
                </value>
                <value>
                    <fullName>Closed – 3-month freeze period</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Rejected by IATA compliance team</fullName>
                </value>
                <value>
                    <fullName>Declined by Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>Map the objects AGT from AIMS. This is a value equal to category.</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accommodation</fullName>
                </value>
                <value>
                    <fullName>Airline</fullName>
                </value>
                <value>
                    <fullName>Airline Supplier</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Equipment Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Cargo Agent</fullName>
                    <label>Freight Forwarder</label>
                </value>
                <value>
                    <fullName>General Public</fullName>
                </value>
                <value>
                    <fullName>General Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Governmental Institution</fullName>
                </value>
                <value>
                    <fullName>Holding Company</fullName>
                </value>
                <value>
                    <fullName>IATA</fullName>
                </value>
                <value>
                    <fullName>Infrastructure Partner</fullName>
                </value>
                <value>
                    <fullName>Internal Use</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Non-Airline Transportation</fullName>
                </value>
                <value>
                    <fullName>Recreational</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ANG_Enable_NewGen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To enable the agency’s country to use the new accreditations model used in NewGen and Risk Event</description>
        <label>New Accr. Model &amp; Risk Events enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ANG_Portal_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>EasyPay portal service that can be subscribed in the country.</description>
        <inlineHelpText>Enable this country for IATA EasyPay by selecting the EasyPay Portal Service corresponding to the Vendor that covers this country.</inlineHelpText>
        <label>IATA EasyPay Portal Service</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>IATA EasyPay Country Availability</relationshipLabel>
        <relationshipName>IATA_ISO_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <fields>
        <fullName>ANG_Accredited_Agents_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Service can only be subscribed by accredited agents.</description>
        <inlineHelpText>Restrict portal visibility to accredited Agents with Agency Status=Approved OR Changes processed OR Listed.</inlineHelpText>
        <label>Accredited Agents Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ANG_Restrict_by_Agency_Sector__c</fullName>
        <description>Permitted agency sector</description>
        <inlineHelpText>Restrict portal visibility to either Travel or Cargo Agents. Will be visible to Agents in both sectors if left empty.</inlineHelpText>
        <label>Restrict by Agency Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Travel Agent</fullName>
                </value>
                <value>
                    <fullName>Cargo Agent</fullName>
                </value>
                <value>
                    <fullName>Postal Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick if this is the application for the Agent type of customer.</inlineHelpText>
        <label>Agency</label>
        <type>Checkbox</type>
    </fields>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Mgmt_Report_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mgmt Report Team</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PortalServicesCtrlTest.cls
@isTest
public class PortalServicesCtrlTest {

    @testSetup
    static void setup() {

        Portal_Applications__c easyPay1 = new Portal_Applications__c (
                Name = ANG_ISSP_PortalServiceHelper.IATA_EASYPAY_EDENRED,
                ANG_Restrict_by_Agency_Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_Accredited_Agents_Only__c = false,
                Agency__c = true
            );

        Portal_Applications__c easyPay2 = new Portal_Applications__c (
                Name = ANG_ISSP_PortalServiceHelper.IATA_EASYPAY_MSTS,
                ANG_Restrict_by_Agency_Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_Accredited_Agents_Only__c = false,
                Agency__c = true
            );

        Portal_Applications__c easyPay3 = new Portal_Applications__c (
                Name = ANG_ISSP_PortalServiceHelper.IATA_EASYPAY_WEX,
                ANG_Restrict_by_Agency_Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_Accredited_Agents_Only__c = true,
                Agency__c = true
            );

        Portal_Applications__c serviceTest = new Portal_Applications__c (
                Name = 'serviceTest',
                ANG_Restrict_by_Agency_Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_Accredited_Agents_Only__c = false,
                Agency__c = true
            );

        Portal_Applications__c serviceTest2 = new Portal_Applications__c (
                Name = 'serviceTest2',
                ANG_Restrict_by_Agency_Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_Accredited_Agents_Only__c = false,
                Agency__c = true
            );

        insert new List<Portal_Applications__c>{easyPay1,easyPay2,easyPay3,serviceTest,serviceTest2};

        IATA_ISO_Country__c portugal = new IATA_ISO_Country__c (
                Name = 'Portugal_test',
                ISO_Code__c = 'PT',
                ANG_Portal_Service__c = easyPay1.id,
                ANG_Enable_NewGen__c = true
            );


        IATA_ISO_Country__c switzerland = new IATA_ISO_Country__c (
                Name = 'Switzerland_test',
                ISO_Code__c = 'CH',
                ANG_Portal_Service__c = easyPay2.id,
                ANG_Enable_NewGen__c = true
            );


        IATA_ISO_Country__c germany = new IATA_ISO_Country__c (
                Name = 'Germany_test',
                ISO_Code__c = 'DH',
                ANG_Portal_Service__c = easyPay3.id
            );

        IATA_ISO_Country__c spain = new IATA_ISO_Country__c (
                Name = 'Spain_test',
                ISO_Code__c = 'SP'
            );

        insert new List<IATA_ISO_Country__c>{portugal,switzerland,germany,spain};

        Account a = new Account (
                name = 'AccountTest',
                IATA_ISO_Country__c = portugal.id,
                Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_IEP_Status__c = ANG_ISSP_PortalServiceHelper.STATUS_OPEN,
                Location_type__c = 'HE',
                OwnerId = UserInfo.getUserId(),
                Location_Class__c = 'P'
            );

        Account a2 = new Account (
                name = 'AccountTest',
                IATA_ISO_Country__c = switzerland.id,
                Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_IEP_Status__c = ANG_ISSP_PortalServiceHelper.STATUS_NO_IEP_ACCOUNT,
                Location_type__c = 'HE',
                OwnerId = UserInfo.getUserId(),
                Location_Class__c = 'P'
            );

        Account a3 = new Account (
                name = 'AccountTest3',
                IATA_ISO_Country__c = germany.id,
                Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_IEP_Status__c = ANG_ISSP_PortalServiceHelper.STATUS_IN_PROGRESS,
                Location_type__c = 'AO',
                OwnerId = UserInfo.getUserId()
            );

        Account a4 = new Account (
                name = 'AccountTest4',
                IATA_ISO_Country__c = spain.id,
                Sector__c = ANG_ISSP_PortalServiceHelper.TRAVEL_AGENT,
                ANG_IEP_Status__c = ANG_ISSP_PortalServiceHelper.STATUS_NO_IEP_ACCOUNT,
                Location_type__c = 'HO',
                OwnerId = UserInfo.getUserId()
            );

        insert new List<Account>{a,a2,a3,a4};

        Contact c = new Contact (
                LastName = 'ContactTest',
                FirstName = 'Name',
                accountID = a.id
            );

        Contact c2 = new Contact (
                LastName = 'ContactTest2',
                FirstName = 'Name',
                accountId = a2.id
            );

        Contact c3 = new Contact (
                LastName = 'ContactTest3',
                FirstName = 'Name',
                accountId = a3.id
            );

        Contact c4 = new Contact (
                LastName = 'ContactTest4',
                FirstName = 'Name',
                accountId = a4.id
            );

        insert new List<Contact>{c,c2,c3,c4};

        Portal_Application_Right__c appRight = new Portal_Application_Right__c(
                Portal_Application__c = easyPay1.id,
                Right__c = 'Access Granted',
                Contact__c = c.Id
        );

        Portal_Application_Right__c appRight2 = new Portal_Application_Right__c(
                Portal_Application__c = easyPay2.id,
                Right__c = 'Access Granted',
                Contact__c = c2.Id
        );

        Portal_Application_Right__c appRight3 = new Portal_Application_Right__c(
                Portal_Application__c = easyPay3.id,
                Right__c = 'Access Requested',
                Contact__c = c3.Id
        );

        insert new List<Portal_Application_Right__c>{appRight,appRight2,appRight3};

    }


    @isTest
    public static void PortalServicesCtrlTest_getAccessGrantedServices() {

        Contact c = [select id from contact where lastName = 'ContactTest2'];

        //Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency User (Partner)']; 
        Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency Delegated Admin User']; 


        User testeUser1 = new User (
                Alias = 'newUser', 
                Email='newuser@testorg.com', 
                EmailEncodingKey='UTF-8', 
                LastName='Testing1', 
                LanguageLocaleKey='en_US', 
                ContactId = c.id,            
                LocaleSidKey='en_US',
                ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', 
                UserName='newuser@testorg.com',
                Mgmt_Report_Team__c = true
            );
        
        System.runAs(testeUser1) {
            Test.StartTest();

            List<Portal_Application_Right__c> lstResults = PortalServicesCtrl.getAccessGrantedServices();
            System.assertEquals(lstResults.size() > 0, true);

            Test.StopTest();
        }
    }

    @isTest
    public static void PortalServicesCtrlTest_getAccessRequestedServices() {
        Contact c = [select id from contact where lastName = 'ContactTest3'];

        //Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency User (Partner)']; 
        Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency Delegated Admin User']; 


        User testeUser1 = new User (
                Alias = 'newUser', 
                Email='newuser@testorg.com', 
                EmailEncodingKey='UTF-8', 
                LastName='Testing1', 
                LanguageLocaleKey='en_US', 
                ContactId = c.id,            
                LocaleSidKey='en_US',
                ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', 
                UserName='newuser@testorg.com',
                Mgmt_Report_Team__c = true
            );
        
        System.runAs(testeUser1) {
            Test.StartTest();

            List<Portal_Application_Right__c> lstResults = PortalServicesCtrl.getAccessRequestedServices();
            System.assertEquals(lstResults.size() > 0, true);

            Test.StopTest();
        }
    }

    @isTest
    public static void PortalServicesCtrlTest_getUserServicesList() {
        Contact c = [select id from contact where lastName = 'ContactTest'];

        //Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency User (Partner)']; 
        Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency Delegated Admin User']; 


        User testeUser1 = new User (
                Alias = 'newUser', 
                Email='newuser@testorg.com', 
                EmailEncodingKey='UTF-8', 
                LastName='Testing1', 
                LanguageLocaleKey='en_US', 
                ContactId = c.id,            
                LocaleSidKey='en_US',
                ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', 
                UserName='newuser@testorg.com',
                Mgmt_Report_Team__c = true
            );
        
        System.runAs(testeUser1) {
            Test.StartTest();

            PortalServicesCtrl.FilteringObject filteringObjectAux = new PortalServicesCtrl.FilteringObject();
            filteringObjectAux.searchText = '' + ANG_ISSP_PortalServiceHelper.IATA_EASYPAY_MSTS;

            String filteringObjectAuxStr = JSON.serialize(filteringObjectAux);


            List<Portal_Application_Right__c> lstResults = PortalServicesCtrl.getUserServicesList(filteringObjectAuxStr);
            System.assertEquals(lstResults.size() == 0, true);

            Test.StopTest();
        }
    }

    @isTest
    public static void PortalServicesCtrlTest_getFavoriteServicesList() {

        Contact c = [select id from contact where lastName = 'ContactTest'];

        //Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency User (Partner)']; 
        Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency Delegated Admin User']; 


        User testeUser1 = new User (
                Alias = 'newUser', 
                Email='newuser@testorg.com', 
                EmailEncodingKey='UTF-8', 
                LastName='Testing1', 
                LanguageLocaleKey='en_US', 
                ContactId = c.id,            
                LocaleSidKey='en_US',
                ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', 
                UserName='newuser@testorg.com',
                Mgmt_Report_Team__c = true
            );
        
        System.runAs(testeUser1) {
            Test.StartTest();

            List<Portal_Application_Right__c> lstResults = PortalServicesCtrl.getFavoriteServicesList();
            System.assertEquals(lstResults.size() > 0, true);

            Test.StopTest();
        }
    }

    @isTest
    public static void PortalServicesCtrlTest_getFavoriteServicesList_noRightsGiven() {

        Contact c = [select id from contact where lastName = 'ContactTest3'];

        //Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency User (Partner)']; 
        Profile p = [SELECT Id FROM Profile WHERE Name='ISS Portal Agency Delegated Admin User']; 


        List<Portal_Applications__c> lstApps = [SELECT Id from Portal_Applications__c];
        Database.delete(lstApps);

        User testeUser1 = new User (
                Alias = 'newUser', 
                Email='newuser@testorg.com', 
                EmailEncodingKey='UTF-8', 
                LastName='Testing1', 
                LanguageLocaleKey='en_US', 
                ContactId = c.id,
                LocaleSidKey='en_US',
                ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', 
                UserName='newuser@testorg.com',
                Mgmt_Report_Team__c = true
            );
        
        System.runAs(testeUser1) {
            Test.StartTest();

            List<Portal_Application_Right__c> lstResults = PortalServicesCtrl.getFavoriteServicesList();
            System.assertEquals(lstResults.size() == 0, true);

            Test.StopTest();
        }
    }

    @isTest
    public static void PortalServicesCtrlTest_goToOldPortalService() {
        Test.StartTest();

        PortalServicesCtrl.goToOldPortalService('');

        Test.StopTest();
        
    }


}