src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACLI_Status__c</fullName>
        <label>ACLI Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive Company</fullName>
                </value>
                <value>
                    <fullName>Active Company</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_code_secondary_flag__c</fullName>
        <label>Account code secondary flag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_Prefix__c</fullName>
        <label>Airline Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_designator__c</fullName>
        <description>Field used for the airline designator code e.g. BA</description>
        <label>IATA Designator</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IATA_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IATA Member Airline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ICAO_designator__c</fullName>
        <label>ICAO Designator</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_SITA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SITA Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Memmership_ARINC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership ARINC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Memmership_ATA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership ATA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name_on_AOC__c</fullName>
        <label>Name on AOC</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of__c</fullName>
        <label>Type of Operations code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>duplicate_flag_indicato__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Duplicate IATA Designator</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AcliStatusUpdateBatch.cls
global class AcliStatusUpdateBatch implements Database.Batchable<sObject>, Database.Stateful{
   
   global boolean StateOff {get;set;} 
   global  String backUp = AcliAccount.firstLineCSV();
   global String UserEmail {get;set;}   
   global boolean inctivateTheAirlines =false;  
    
global Database.QueryLocator start(Database.BatchableContext BC){

        StateOff = stateOFf == null?false:stateOff;
        set<string> acctFoundIDs = new set<string>();
    
        Document acliTxtFile = [SELECT Body FROM document where developername = 'AcliUniqueFile' ];
        string acliTxtFileString  = acliTxtFile.Body.tostring() ;
        
        integer max =0;
           string separator =  acliTxtFileString.contains('<br>') ?  '<br>' : '\\n';          
                for(String line : acliTxtFileString.split(separator)) {
                    max++;
                }
       
        AcliWrapper wrapperTmp =AcliParser.AcliParsingNotFound(acliTxtFileString,0,max,stateOFf);  

        if(wrapperTmp.AcliAccount.IsEmpty() 
                          ){
            inctivateTheAirlines =true;
        }
   // throw new transformationException(''+AcliParser.AcliParsingFound(acliTxtFileString  ,0,max,StateOff).acliAccount.values());
        if(inctivateTheAirlines) 
        for(acliAccount accL: AcliParser.AcliParsingFound(acliTxtFileString  ,0,max,StateOff).acliAccount.values()){
            if(accL.AcctID <> null)
                acctFoundIDs.add(accL.AcctID);
        }
       // throw new transformationException('' +acctFoundIDs.size());
       String Query =                'SELECT Id,name,IATACode__c,Name_on_AOC__c,'
                                   +' Airline_designator__c,ICAO_designator__c,'
                                   +' duplicate_flag_indicato__c,billingStreet,'
                                   +' billingCity,billingState,'
                                   +' billingCountry,billingPostalCode,'
                                   +' Membership_SITA__c,Memmership_ARINC__c,'
                                   +' IATA_Member__c,Memmership_ATA__c,Type_of__c,'
                                   +' Account_code_secondary_flag__c,Airline_Prefix__c,'
                                   +' IATA_ISO_Country__c,ACLI_Status__c,IATA_ISO_Country__r.ISO_Code__c'
                                   +' FROM account '
                                   +' WHERE '
                                   + 'id not IN: acctFoundIDs AND  recordtype.developername = \'iata_airline\' '
                                   ;
                                   
 //   list<account> accts =(list<account>) Database.query(query);
  //       throw new transformationException('' +accts );                           
       if(acctFoundIDs <> null && acctFoundIDs.size()>0)
            return Database.getQueryLocator(query);
         return Database.getQueryLocator('select id from account where name = \'Pompidur\'');
      }

   global void execute(Database.BatchableContext BC, List<sObject> scope){
          
           if(!scope.isEmpty()){    
                list<Account> Updates = new list<Account>();
                        
                  for(Sobject s : scope){   
                         
                         Account a = (Account)s;
                         //  throw new transformationException('' + a);               
                         Account cloned =a.clone(false,true,false,false);
                          backup +=AcliAccount.lineOfAcliFromACct(cloned);
                         a.ACLI_Status__c =  'Inactive Company';
                        Updates.add(a);
                  }
            if(!Updates.isEmpty())
                update Updates;
           }   
    }

   global void finish(Database.BatchableContext BC){
            
    
   if(inctivateTheAirlines){ 
     Blob b =blob.valueOf(backup );   
         Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();

         efa.setContentType('application/xml');   
         efa.setFileName('BackUpAcliACtive'+datetime.now()+'.txt');
         efa.setBody(b);
          
         String body = 'Please find attached the backUp';
         Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
        // Sets the 'BACK Up Accounts Pre Acli ' + dateTime.now()of the email
        email.setSubject('Acli Back Up STATUS ' + datetime.now());
        list<string> emails = new list<string>{'sfdcadmin@iata.org'};
        if(userEmail <> null)emails.add(userEmail);
        email.setToAddresses( emails);
        email.setPlainTextBody( body );
         Messaging.EmailFileAttachment[] attachements = new Messaging.EmailFileAttachment[]{} ;
         

        attachements.add(efa);
        
        email.setFileAttachments(attachements);

        // Sends the email
        Messaging.SendEmailResult [] r = 
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});  
  
    }  
   }        
            
            
            
            
            
   

}