src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ICCS_Product_Country__c.object
<CustomObject>
    <description>To be used by the ICCS Administrator to define a product availability by country.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to link the record to a ISO Country</description>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>ICCS Product Countries</relationshipLabel>
        <relationshipName>ICCS_Product_Countries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Product</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ICCS Product Countries</relationshipLabel>
        <relationshipName>ICCS_Product_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ICCS Product Country</label>
    <nameField>
        <displayFormat>CT-{000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICCS Product Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/trgEnsureUniqueProdCountryCurrTest.cls
/*
 *  @author: Constantin BUZDUGA, blue-infinity
 *  @description: This is a test class for the trgEnsureUniqueProductCountryCurrency trigger on the
 *  ICCS Product Currency object.
 *
 */

@isTest
private class trgEnsureUniqueProdCountryCurrTest {
	static testMethod void test() {
		// Create a new ISO Country
		IATA_ISO_Country__c country = new IATA_ISO_Country__c(Name = 'France', ISO_Code__c = 'FR');
		insert country;

		// Create a new Product
		Product2 p = new Product2(Name = 'Test prod', Family = 'ICCS');
		insert p;

		// Create a new ICCS Product Country for this product
		ICCS_Product_Country__c pct = new ICCS_Product_Country__c(Product__c = p.Id, Country__c = country.Id);
		insert pct;

		List<ICCS_Product_Country__c> lstProductCountries = [SELECT Id FROM ICCS_Product_Country__c];
		System.AssertEquals(1,lstProductCountries.size());

		// Create a new ICCS Product Country for the product with the same country as above, to test that
		// its insertion is blocked.
		try {
			pct = new ICCS_Product_Country__c(Product__c = p.Id, Country__c = country.Id);
			insert pct;
		} catch(Exception e) {}

		lstProductCountries = [SELECT Id FROM ICCS_Product_Country__c];
		System.AssertEquals(1,lstProductCountries.size()); // Check that the bank account was not inserted


	}
}