src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>Map the objects AGT from AIMS. This is a value equal to category.</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Top_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Top Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Connected_App_Roles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting defines the list of user roles that are available for each connected app: to be used on the Identity Community</description>
    <fields>
        <fullName>Connected_App_Provisioning_Name__c</fullName>
        <label>Connected App Provisioning Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Connected_App__c</fullName>
        <label>Connected App SSO Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PermissionSet_Provisioning__c</fullName>
        <label>PermissionSet Provisioning</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Permission_set_SSO__c</fullName>
        <label>PermissionSet SSO</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>TextArea</type>
    </fields>
    <label>Connected App Roles</label>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ANG_Portal_Service_Role__c</fullName>
        <description>Selected service portal role</description>
        <label>Portal Service Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ANG_PortalApplicationRightTest.cls
@isTest
private class ANG_PortalApplicationRightTest {
	
	static {
		//initilize static variables
	}

	@testSetup static void createData() {

		Account acc = ISSP_ObjectFactory.createNewAccount();  		

		acc.Location_Type__c = 'HO';
		acc.Location_Class__c = 'P';				

		insert acc;

		Account acc2 = ISSP_ObjectFactory.createNewAccount();
		acc2.Location_Type__c = 'BR';
		acc2.Location_Class__c = 'P';
		acc2.ParentId = acc.id;
		acc2.Top_Parent__c = acc.id;

		Account acc3 = ISSP_ObjectFactory.createNewAccount();

		insert new List<Account>{acc2, acc3};
		
		Contact contact = ISSP_ObjectFactory.createNewContact();
		Contact contact2 = ISSP_ObjectFactory.createNewContact();
		Contact contact3 = ISSP_ObjectFactory.createNewContact();
		contact.AccountId = acc.Id;
		contact2.AccountId = acc2.Id;
		contact3.AccountId = acc3.Id;

		insert new List<Contact>{contact, contact2, contact3};

		Portal_Applications__c app = new Portal_Applications__c(Name = 'IATA EasyPay - Tester');
		Portal_Applications__c app2 = new Portal_Applications__c(Name = 'IATA EasyPay');
		
		insert new List<Portal_Applications__c>{app, app2};

		ConnectedApplication capp;

		System.runAs([SELECT Id FROM User WHERE Id = :UserInfo.getUserId()][0]){

			capp = UserProvisioning.ConnectorTestUtil.createConnectedApp('ANG Provisioning App');

			PermissionSet ang_ssoapp = new PermissionSet(
				Name = 'ANG_SSOApp'
				, Label = 'ANG_SSOApp'
			);

			PermissionSet ang_provapp = new PermissionSet(
				Name = 'ANG_ProvApp'
				, Label = 'ANG_ProvApp'
			);

			insert new List<PermissionSet>{ang_ssoapp, ang_provapp};
			
			insert new User(
				Alias = 'dsfsdfds', 
				Email = contact.email, 
				Emailencodingkey = 'UTF-8', 
				Firstname = contact.firstName, 
				Lastname = contact.lastname, 
				Languagelocalekey = 'en_US', 
				Localesidkey = 'en_US', 
				ContactId = contact.Id,
				Timezonesidkey = 'Asia/Dubai',
				Username = contact.email+'dfgdf',
				PortalRole = 'Manager',
				CommunityNickname = contact.email.substring(0, contact.email.indexOf('@'))+Datetime.now().formatLong().substring(10,15),
				ProfileId = ISSP_Constant.TEST_User_ProfileID,
				IsActive = true
			);

			Connected_App_Roles__c car = new Connected_App_Roles__c(
				Name = 'ANG Test'
				, Connected_App__c = 'IATA EasyPay - Tester'
				, Permission_set_SSO__c = 'ANG_SSOApp'
				, PermissionSet_Provisioning__c = 'ANG_ProvApp'
				, Provisioning_Id__c = capp.Id
				, Connected_App_Provisioning_Name__c = capp.Name
				, Role__c = 'Tester'
				, Min_Users_With_Role__c = 0
			);

			Connected_App_Roles__c car2 = new Connected_App_Roles__c(
				Name = 'ANG Test2',
				Connected_App__c = 'IATA EasyPay',
				Permission_set_SSO__c = 'IATA EasyPay',
				Role__c = 'IEP Admin',
				Min_Users_With_Role__c = 1
			);

			Connected_App_Roles__c car3 = new Connected_App_Roles__c(
				Name = 'ANG Test3',
				Connected_App__c = 'IATA EasyPay',
				Permission_set_SSO__c = 'IATA EasyPay',
				Role__c = 'Wallet Gone',
				Min_Users_With_Role__c = 1
			);		

			insert new List<Connected_App_Roles__c>{car, car2, car3};
		}

		Portal_Application_Right__c par = new Portal_Application_Right__c(
			Contact__c = contact.Id, 
			Portal_Application__c = app.Id,
			Right__c = 'Access Requested',
			ANG_Portal_Service_Role__c = 'Tester'
		);

		Portal_Application_Right__c par2 = new Portal_Application_Right__c(
			Contact__c = contact.Id, 
			Portal_Application__c = app2.Id,
			Right__c = 'Access Requested',
			ANG_Portal_Service_Role__c = 'IEP Admin'
		);

		Portal_Application_Right__c par3 = new Portal_Application_Right__c(
			Contact__c = contact2.Id, 
			Portal_Application__c = app2.Id,
			Right__c = 'Access Granted',
			ANG_Portal_Service_Role__c = 'IEP Admin'
		);

		Portal_Application_Right__c par4 = new Portal_Application_Right__c(
			Contact__c = contact3.Id, 
			Portal_Application__c = app2.Id,
			Right__c = 'Access Granted',
			ANG_Portal_Service_Role__c = 'Wallet Gone'
		);

		insert new List<Portal_Application_Right__c>{par, par2, par3, par4};
	}
	
	static testMethod void test_grantingAccess() {
		Portal_Application_Right__c par = [SELECT Id, Contact__c FROM Portal_Application_Right__c WHERE ANG_Portal_Service_Role__c = 'Tester'];

		Integer provAssignments = [SELECT Id FROM PermissionSetAssignment WHERE PermissionSet.Name = 'ANG_ProvApp' AND AssigneeId IN (SELECT Id FROM User WHERE ContactId = :par.Contact__c)].size();
		System.assertEquals(1, provAssignments);

		Test.startTest();

		par.Right__c = 'Access Granted';
		update par;

		Test.stopTest();

		User u = [SELECT Id FROM User WHERE ContactId = :par.Contact__c];

		Integer ssoAssignments = [SELECT Id FROM PermissionSetAssignment WHERE PermissionSet.Name = 'ANG_SSOApp' AND AssigneeId IN (SELECT Id FROM User WHERE ContactId = :par.Contact__c)].size();
		System.assertEquals(1, ssoAssignments);
	}
	
	static testMethod void test_removingAccess() {
		Portal_Application_Right__c par = [SELECT Id, Contact__c FROM Portal_Application_Right__c WHERE ANG_Portal_Service_Role__c = 'Tester'];
		par.Right__c = 'Access Granted';
		update par;

		Test.startTest();

		delete par;

		Test.stopTest();

		User u = [SELECT Id FROM User WHERE ContactId = :par.Contact__c];

		Integer assignments = [SELECT Id FROM PermissionSetAssignment WHERE PermissionSet.Name in ('ANG_ProvApp', 'ANG_SSOApp') AND AssigneeId IN (SELECT Id FROM User WHERE ContactId = :par.Contact__c)].size();
		System.assertEquals(0, assignments);
	}
	
	static testMethod void test_denyingAccess() {
		Portal_Application_Right__c par = [SELECT Id, Contact__c FROM Portal_Application_Right__c WHERE ANG_Portal_Service_Role__c = 'Tester'];

		par.Right__c = 'Access Granted';
		update par;

		Test.startTest();

		par.Right__c = 'Access Denied';
		update par;

		Test.stopTest();

		User u = [SELECT Id FROM User WHERE ContactId = :par.Contact__c];

		Integer assignments = [SELECT Id FROM PermissionSetAssignment WHERE PermissionSet.Name in ('ANG_ProvApp', 'ANG_SSOApp') AND AssigneeId IN (SELECT Id FROM User WHERE ContactId = :par.Contact__c)].size();
		System.assertEquals(0, assignments);
	}
	
	static testMethod void test_failProvisioning() {
		UserProvisioningRequest request = [SELECT Id, SalesforceUserId, AppName, State FROM UserProvisioningRequest];

		Test.startTest();

		request.State = 'Failed';
		update request;

		Test.stopTest();

		List<Portal_Application_Right__c> parList = [SELECT Id, Contact__c FROM Portal_Application_Right__c WHERE ANG_Portal_Service_Role__c = 'Tester'];
		System.debug(loggingLevel.ERROR, '____ [cls ANG_PortalApplicationRightTest - test_failProvisioning] parList - ' + parList);
		System.assert(parList.isEmpty());
	}

	static testMethod void test_checkMinimumUsersAllowedUpdateAndDelete() {
		Portal_Application_Right__c par = [SELECT Id, Contact__c FROM Portal_Application_Right__c WHERE ANG_Portal_Service_Role__c = 'IEP Admin' AND Right__c = 'Access Requested'];

		Test.startTest();

		par.Right__c = 'Access Denied';

		try {
			update par;	
			System.assert(true);
		} catch(Exception e) {
			System.assert(false);
		}

		try {
			delete par;	
			System.assert(true);
		} catch(Exception e) {
			System.assert(false);
		}

		Test.stopTest();
	}

	static testMethod void test_checkMinimumUsersAllowedUpdateAndDelete2() {
		Portal_Application_Right__c par = [SELECT Id, Contact__c FROM Portal_Application_Right__c WHERE ANG_Portal_Service_Role__c = 'Wallet Gone'];
		par.Right__c = 'Access Granted';
		update par;

		Test.startTest();

		par.Right__c = 'Access Denied';

		try {
			update par;	
			System.assert(false);
		} catch(Exception e) {
			System.assert(e.getMessage().contains(Label.ANG_ISSP_Min_Users_With_Role_Error_Msg));
		}

		try {
			delete par;	
			System.assert(false);
		} catch(Exception e) {
			System.assert(e.getMessage().contains(Label.ANG_ISSP_Min_Users_With_Role_Error_Msg));
		}

		Test.stopTest();
	}

	static testMethod void test_checkMinimumUsersAllowedUpdateAndDelete3() {
		Portal_Application_Right__c par = [SELECT Id, Contact__c FROM Portal_Application_Right__c WHERE ANG_Portal_Service_Role__c = 'IEP Admin' AND Right__c = 'Access Granted'];

		Test.startTest();

		par.Right__c = 'Access Denied';

		try {
			update par;	
			System.assert(false);
		} catch(Exception e) {
			System.assert(e.getMessage().contains(Label.ANG_ISSP_Min_Users_With_Role_Error_Msg));
		}

		try {
			delete par;	
			System.assert(false);
		} catch(Exception e) {
			System.assert(e.getMessage().contains(Label.ANG_ISSP_Min_Users_With_Role_Error_Msg));
		}

		Test.stopTest();
	}
}