src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Check_Digit__c</fullName>
        <label>Check Digit</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Accreditation__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>Accreditation (GDP Reference Table)</relationshipLabel>
        <relationshipName>Accreditation2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>GDP_Reference_Table__c</referenceTo>
        <relationshipLabel>Accreditation</relationshipLabel>
        <relationshipName>Accreditation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accreditation</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Accreditation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accreditation</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CAC_and_GAD_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Excluded_CAC_Location_Classes__c</fullName>
        <description>Excluded codes for CAC Agency class</description>
        <label>Excluded CAC Location Classes</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Excluded_GAD_Location_Classes__c</fullName>
        <description>Excluded codes for CAC Agency class</description>
        <label>Excluded GAD Location Classes</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CAC and GAD Settings</label>
</CustomObject>

src/objects/GDP_Products_Account_View__c.object
<CustomObject>
    <fields>
        <fullName>Check_Digit__c</fullName>
        <label>Check Digit</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_Code__c</fullName>
        <externalId>true</externalId>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Accreditation_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to GDP Accreditation</inlineHelpText>
        <label>Related Accreditation</label>
        <referenceTo>Accreditation__c</referenceTo>
        <relationshipLabel>GDP Products - Accounts View</relationshipLabel>
        <relationshipName>GDP_Products_Accounts_View</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GDP Products - Account View</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP Products - Accounts View</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <description>Used for GDP Live Applications</description>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Reference_Table__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <label>Table</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>GDP Reference Table</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP References Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ID_Card__c.object
<CustomObject>
    <description>ID Cards information
two record types:
1- AIMS (default) contains AIMS data (SFDC is the master data)
2- WebStar contains WebStar data (WebStar is master data)</description>
    <fields>
        <fullName>GDP_Products_Account_View__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GDP Products - Account View</label>
        <referenceTo>GDP_Products_Account_View__c</referenceTo>
        <relationshipLabel>ID Cards</relationshipLabel>
        <relationshipName>ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <label>Valid From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To_Date__c</fullName>
        <label>Valid To Date</label>
        <type>Date</type>
    </fields>
    <label>ID Card</label>
    <nameField>
        <displayFormat>IDC-{000000000}</displayFormat>
        <label>ID Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ID Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IEC_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the IEC project</description>
    <label>IEC Settings</label>
</CustomObject>

src/classes/vfIECCACFreeTest.cls
@isTest
private class vfIECCACFreeTest {
	
	@isTest static void vfIECCACFreeTest() {
		List<ID_Card__c> listIDCard = new List<ID_Card__c>(); 
		ID_Card__c oIDCard = IECTestUtil.createSampleIDCard('John', 'Doe', '55780005', 'test', '55780005', 'Valid ID Card');
        oIDCard.Valid_To_Date__c = Date.today().addYears(1);
        oIDCard.Valid_From_Date__c = Date.today();
        listIDCard.add(oIDCard);

        oIDCard = IECTestUtil.createSampleIDCard('John', 'Doe', '5578000523', 'test', '12312312', 'Valid ID Card');
        listIDCard.add(oIDCard);
        insert listIDCard;
        GDP_Reference_Table__c oRefAgencyStatus = IECTestUtil.createSampleGDPReferenceTableEntry('4', 'Valid');
        insert oRefAgencyStatus;

        GDP_Reference_Table__c oAgencyPassengerClass =  IECTestUtil.createSampleGDPReferenceTableEntry('P', 'Passenger');
        oAgencyPassengerClass.Code__c = 'P';
        oAgencyPassengerClass.Name = 'Passenger';
        oAgencyPassengerClass.System__c = 'Global';
        oAgencyPassengerClass.Table__c = 'ORGCLASS';
        insert oAgencyPassengerClass;

        GDP_Products_Account_View__c gdp = new GDP_Products_Account_View__c(IATA_Code__c = '5578000', Check_Digit__c = '5');
		insert gdp;

		GDP_Products_Account_View__c gdp2 = new GDP_Products_Account_View__c(IATA_Code__c = '1231231', Check_Digit__c = '5');
		insert gdp2;

		GDP_Products_Account_View__c gdp3 = new GDP_Products_Account_View__c(IATA_Code__c = '12312312321', Check_Digit__c = '5');
		insert gdp3;

		Accreditation__c oAccreditation1 = IECTestUtil.CreateSampleAccreditation(null, gdp, 'GDP');
        oAccreditation1.Status__c = oRefAgencyStatus.Id;
        oAccreditation1.Class__c = oAgencyPassengerClass.Id;
        insert oAccreditation1;

        gdp.Related_Accreditation_Class__c = oAccreditation1.Id;
        update gdp;

		CAC_and_GAD_Settings__c CacGadSettings = new CAC_and_GAD_Settings__c();
        CacGadSettings.Name = 'Excluded Values';
        CacGadSettings.Excluded_CAC_Location_Classes__c = 'A;I;L;Q;R;U;Y;Z';
        CacGadSettings.Excluded_GAD_Location_Classes__c = 'A;I;L;Q;R;U;Y;Z;C;X';
        insert CacGadSettings;

		
		IEC_Settings__c iecSettings = IEC_Settings__c.getOrgDefaults();
		vfIECCACFree cont = new vfIECCACFree();
		//has account 7 digis
		cont.sValidationCode = '1231231';
		cont.validateCode();
		//error account 7 digis
		cont.sValidationCode = '1231232';
		cont.validateCode();
		cont.sValidationCode = '12312312';
		cont.validateCode();
		cont.sValidationCode = '55780005';
		cont.validateCode();
		cont.sValidationCode = '12312312321';
		cont.validateCode();
		//exists idcard 10 digits
		cont.sValidationCode = '5578000523';		
		cont.validateCode();
		//don't 10 digis
		cont.sValidationCode = '1231231231';		
		cont.validateCode();
		cont.pageLoad();
		cont.sValidationCode = '123123123214214';
		cont.iRECAPTCHACount = 21;
		cont.validateCode();
		//error code with letter
		cont.sValidationCode = '1231231d';
		cont.whichcountry= 'CN';
		cont.validateCode();


	}	
}