src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ANG_Accreditation_Model__c</fullName>
        <description>To store Accreditation Model selected by the agency.</description>
        <label>Accreditation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Accreditation_Models</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ANG_IsNewGenAgency__c</fullName>
        <description>To show information to analyst. To simplify triggers and classes.</description>
        <formula>(IATA_ISO_Country__r.ANG_Enable_NewGen__c  &amp;&amp;  OR(TEXT(Location_Class__c) = &apos;P&apos;, TEXT(Location_Class__c) = &apos;D&apos;)) || (IATA_ISO_Country__r.Enable_NewGen_Pilot__c &amp;&amp; OR(TEXT(Location_Type__c) = &apos;HE&apos;, TEXT(Location_Type__c) = &apos;AE&apos;, TEXT(Location_Type__c) = &apos;GE&apos;) &amp;&amp; TEXT(Location_Class__c) = &apos;D&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is New Gen Agency</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ANG_PCI_compliance_expiry_date__c</fullName>
        <description>PCI compliance expiry date</description>
        <label>PCI compliance expiry date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_PCI_compliant__c</fullName>
        <description>Determines if an agency is PCI Compliant</description>
        <label>Is PCI compliant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Nil CC</fullName>
                </value>
                <value>
                    <fullName>Corporate Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_name__c</fullName>
        <description>Field used for the legal name of the airlines and the travel agents</description>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>Map the objects AGT from AIMS. This is a value equal to category.</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_formula__c</fullName>
        <description>Retrieves the Region from the selected item in the ISO Country lookup</description>
        <formula>TEXT(IATA_ISO_Country__r.Region__c)</formula>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BSP_CASS_Payment_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BSP/CASS Payment contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Assessment_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tell if the contact is define as Financial Assessment Contact.
IFAP Application.</description>
        <label>Financial Assessment Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_BSPLink_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New BSPLink Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Portal_Status__c</fullName>
        <label>User Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved User</fullName>
                </value>
                <value>
                    <fullName>Approved Admin</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Regional Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SalesforceSupportEmails__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Support members to receive error email messages</description>
    <fields>
        <fullName>Support_Email__c</fullName>
        <description>[Deprecated] - This field is not to be used.
To send emails use only - Support_User_Id__c</description>
        <label>Support Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Salesforce Support Emails</label>
</CustomObject>

src/globalValueSets/ANG_Accreditation_Models.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Legacy</fullName>
    </customValue>
    <customValue>
        <fullName>Cashless</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Multicountry</fullName>
    </customValue>
    <customValue>
        <fullName>CNS Endorsement</fullName>
    </customValue>
    <masterLabel>Accreditation Models</masterLabel>
</GlobalValueSet>

src/classes/ANG_PCIComplianceRenewalBatch.cls
global class ANG_PCIComplianceRenewalBatch implements Database.Batchable<Account>, Database.Stateful {

	//Batch will run every day and create a pci renewal OSCAR for each account with PCI expiry date expiring in 90 days

	private static final String AGENCYRTID = AMS_Utils.RECTYPE_IATAAGENCY;
	private static final String OSCARCOMMRTID = AMS_Utils.RECTYPE_OSCARCOMM;
	private static final Set<String> ACTIVE_ACC_STATUS = new Set<String>{AMS_Utils.ACC_S9_APPROVED, AMS_Utils.ACC_S8_CHANGESPROCESSED, AMS_Utils.ACC_S7_UNDERREVIEW, 
																		AMS_Utils.ACC_S6_CASHWITHCOMMISSION, AMS_Utils.ACC_S5_CASHNOCOMMISSION, AMS_Utils.ACC_S4_LISTED, 'Review'};

	private Date triggerRenewalDate;
	private Integer daysBeforeExpiry;

	private List<String> errors = new List<String>();
	private List<String> agenciesWithoutContact = new List<String>();

		
	global ANG_PCIComplianceRenewalBatch() {
		
	}

	// allows the batch to be run manually using a custom date to trigger the renewal
	global ANG_PCIComplianceRenewalBatch(Integer customDaysBeforeExpiry) {
		this.daysBeforeExpiry = customDaysBeforeExpiry;
	}
	
	global Iterable<Account> start(Database.BatchableContext BC) {

		triggerRenewalDate = Date.today().addDays(daysBeforeExpiry != null ? daysBeforeExpiry : 90);

	    String query = 'SELECT Id, Name, IataCode__c, BillingCountry, Region_formula__c,ANG_Accreditation_Model__c, Legal_name__c, '+
	    	'(SELECT Id, Name, Email, Preferred_Language__c, BSP_CASS_Payment_contact__c, Financial_Assessment_Contact__c, User_Portal_Status__c, New_BSPLink_Contact__c, AccountId '+
	    		'FROM Contacts WHERE Status__c = \'Active\' AND (User_Portal_Status__c = \'Approved Admin\' OR Financial_Assessment_Contact__c = true OR BSP_CASS_Payment_contact__c = true)) '+
	    	'FROM Account '+
	    	'WHERE RecordTypeId = :AGENCYRTID '+
	    	'AND Is_PCI_compliant__c = \'Yes\' '+
	    	'AND ANG_IsNewGenAgency__c = true '+
	    	'AND ANG_PCI_compliance_expiry_date__c = :triggerRenewalDate '+
	    	'AND Location_Class__c IN (\'P\',\'D\') '+
	    	'AND Status__c IN :ACTIVE_ACC_STATUS '+
	    	'AND Id NOT IN (SELECT AccountId FROM Case WHERE RecordTypeId = :OSCARCOMMRTID '+
	    		'AND Reason1__c = \'FoP Management\' AND IsClosed = false)';
	    	
    	return (Iterable<Account>) Database.getQueryLocator(query);
  	}

   	global void execute(Database.BatchableContext BC, List<Account> scope) {
   		Map<Id,List<Contact>> contactsPerAcc = new Map<Id,List<Contact>>();
   		List<Account> accsToProcess = new List<Account>();
   		List<String> iataCodesAndNames = new List<String>();
	
		try{
			for (Account acc : scope){
				if (!acc.contacts.isEmpty()){
					iataCodesAndNames.add(acc.IataCode__c+' - '+acc.Name);			
					accsToProcess.add(acc);		
					contactsPerAcc.put(acc.Id, new List<Contact>(acc.contacts));				
				} else {
					agenciesWithoutContact.add (acc.IataCode__c+' - '+acc.Name);
				}
			}
			List<Case> fopCases = ANG_OscarProcessHelper.createPCIComplianceOscars(accsToProcess, contactsPerAcc, contactsPerAcc.keySet(), AMS_Utils.ANG_FOP_AUTOMATIC_RENEWAL);
		}catch(Exception e){
			errors.add('Error running batch for Accounts with Iata code(s): '+String.join(iataCodesAndNames,',')+' - '+e.getMessage()+' - '+e.getStackTraceString());
		}
	}
	
	global void finish(Database.BatchableContext BC) {

		if(!errors.isEmpty() || !agenciesWithoutContact.isEmpty()){
			String errorMsg;
			String noContactAgents;
			if (!errors.isEmpty())
				errorMsg = String.join(errors,'\n\n');
			if (!agenciesWithoutContact.isEmpty())
				noContactAgents = +String.join(agenciesWithoutContact,'\n');

			//send email w/ errors to support
			List<String> emailAddresses = new List<String>();
			for (SalesforceSupportEmails__c supportEmail: SalesforceSupportEmails__c.getAll().values()){ 
                emailAddresses.add(supportEmail.Support_Email__c);
                //add more email addresses if needed
            }

            if (!emailAddresses.isEmpty()){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(emailAddresses);    
                mail.setSubject('ANG_PCIComplianceRenewalBatch Completed With Issues - End time: '+ System.now());
                mail.setSenderDisplayName('Batch Processing Completed');
                mail.setPlainTextBody('Batch Process has been completed with issues. Some OSCARs were not created due to the following issues: \n\n\tUNEXPECTED ERRORS:\n\n'
                 +errorMsg+'\n\n-------------------\n\n\tAGENTS WITHOUT VALID CONTACTS:\n\n'+noContactAgents);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
            }

			System.debug('[ANG_PCIComplianceRenewalBatch] ERRORS: '+errorMsg);
			System.debug('[ANG_PCIComplianceRenewalBatch] AGENTS WITHOUT CONTACTS: '+noContactAgents);
		}
		
	}
	
}