src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ANG_CashCondition__c</fullName>
        <formula>IF(ANG_FA_Opt_out__c,true,
   IF(ISPICKVAL(ANG_Accreditation_Model__c, &apos;Cashless&apos;) ||ISPICKVAL(Top_Parent__r.ANG_Accreditation_Model__c, &apos;Cashless&apos;),false,
      IF(ISPICKVAL(Location_Type__c ,&apos;HE&apos;), ANG_HE_CashCondition__c,Top_Parent__r.ANG_HE_CashCondition__c)
   ))</formula>
        <inlineHelpText>Indicates that the RHC Amount is equal to the Guaranteed Amount. Will be enforced only if the agency has a FS</inlineHelpText>
        <label>Cash Condition equal to FS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ANG_RHC_Information__c.object
<CustomObject>
    <fields>
        <fullName>ANG_AccountId__c</fullName>
        <description>Holds the id of the account to wich the RHC record is related.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RHC Information</relationshipLabel>
        <relationshipName>RHC_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ANG_CashCondition__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Reports the cash conditions of the account. This information is filled by the account trigger and should no be updated manually. It&apos;s used on the calculation of RHC Amount and Forecasted RHC Amount</description>
        <label>Cash Conditions Equal to FS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ANG_Exceeding_Financial_Security__c</fullName>
        <description>Helper field: reports the amount of FS provided over the minimum</description>
        <formula>IF(ANG_Minimum_Financial_Security__c  &gt;= 0 , ANG_Financial_Security__c - ANG_Minimum_Financial_Security__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Exceeding FS Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ANG_Financial_Security__c</fullName>
        <description>The total FS provided by the agent. This field is calculated in a trigger, based on the converted amount of the Financial Security Records on the Account.</description>
        <label>Total FS Provided</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ANG_RHC_Amount_Forecasted__c</fullName>
        <description>Holds the information regarding what is the expected RHC Amount if the user clicks on the button &quot;Confirm Forecasted RHC&quot;</description>
        <label>Forecasted RHC Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ANG_RHC_Amount_Provisional__c</fullName>
        <description>Expected RHC Amount calculated by RME. The agent can request a new calculation via a button on the layout. The information comes from an external system and should not be updated manually.</description>
        <label>Amount At Risk</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ANG_RHC_Amount__c</fullName>
        <description>The current RHC Amount for the agent</description>
        <inlineHelpText>Help text for the RHC Amount</inlineHelpText>
        <label>RHC Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ANG_RME_Amount__c</fullName>
        <description>The last approved value calculated from RME.</description>
        <label>Confirmed RME Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>RHC Information</label>
    <nameField>
        <displayFormat>RHCI-{000000000}</displayFormat>
        <label>RHC Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RHC Information Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ANG_RHCHelper.cls
public class ANG_RHCHelper {


	/*public static void calculateRHCAmount(List<Account> accounts) {
		calculateRHCAmount([SELECT Id, ANG_CashCondition__c, ANG_Financial_Security__c, ANG_RHC_Amount__c, ANG_RHC_Amount_Forecasted__c, ANG_RME_Amount__c, ANG_Exceeding_Financial_Security__c, ANG_RHC_Amount_Provisional__c FROM ANG_RHC_Information__c WHERE ANG_AccountId__c IN :accounts]);
	}*/
	
	public static void calculateRHCAmount(List<ANG_RHC_Information__c> rhcInfo) {
		//calculates RHC and forescasted RHC amount based on business rules. this is not done on a formula field, because terminated accounts should not have the value changed
		for(ANG_RHC_Information__c rhc : rhcInfo){

			if(rhc.ANG_CashCondition__c && rhc.ANG_Financial_Security__c > 0){
				rhc.ANG_RHC_Amount__c = rhc.ANG_Financial_Security__c;
				rhc.ANG_RHC_Amount_Forecasted__c = rhc.ANG_Financial_Security__c;
			}else{
				Decimal fsAmount = rhc.ANG_Financial_Security__c == null ? 0 : rhc.ANG_Financial_Security__c;
				Decimal rmeAmount = rhc.ANG_RME_Amount__c == null ? 0 : rhc.ANG_RME_Amount__c;
				Decimal provisionalRHC = rhc.ANG_RHC_Amount_Provisional__c == null ? 0 : rhc.ANG_RHC_Amount_Provisional__c;
				Decimal exceedingFS = rhc.ANG_Exceeding_Financial_Security__c == null ? 0 : rhc.ANG_Exceeding_Financial_Security__c;

				if (fsAmount > (rmeAmount + exceedingFS)) rhc.ANG_RHC_Amount__c = fsAmount;
				else rhc.ANG_RHC_Amount__c = rmeAmount + exceedingFS;


				if (fsAmount > (provisionalRHC + exceedingFS)) rhc.ANG_RHC_Amount_Forecasted__c = fsAmount;
				else rhc.ANG_RHC_Amount_Forecasted__c = provisionalRHC + exceedingFS;
			}
		}
	}
}