src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Objective__c.object
<CustomObject>
    <description>Object created for the AME objectives reporting project. 
Object used to store objectives that can be independent, related to other objectives or related to an account</description>
    <fields>
        <fullName>AM_Level_of_importance__c</fullName>
        <description>Field to be used for Account Issues and Priorities RT, to represent the level of importance of the item, from the accounts point of view.</description>
        <label>Level of Importance</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account an objective may be related to</description>
        <inlineHelpText>Please search for the account this objective is related to. Only Airline HQ accounts are available in the search</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Airline Headquarters, Agency, Airline Headquarters, Airline Branch, General Sales Agent Headquarters, Others</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Objectives</relationshipLabel>
        <relationshipName>Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the objective</description>
        <inlineHelpText>There is no automation between the Status and the Progress value. You should manually set a status if you want to flag the objective somehow for filtering or reporting purposes.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aborted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed without intervention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of scope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At risk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Area objectives decomposed to meet objectives at an Account level</description>
        <label>4. Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>License_Cost_Center__c</fullName>
        <inlineHelpText>The IATA cost center that is paying for your Salesforce.com license.</inlineHelpText>
        <label>License Cost Center</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AMP_IssuesAndprioritiesExtensionTest.cls
@isTest
private class AMP_IssuesAndprioritiesExtensionTest
{
	@isTest
	static void testIssuesAndPrioritiesListing()
	{
		// TODO: run this as a test User
		Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
		User testUser = New User(
			// Username = 'test.username@test.com',
			// Email = 'test.username@test.com',
			// ProfileId = testProfile.Id

			Alias = 'standt', Email='standarduser@testorg.com',
			EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
			LocaleSidKey='en_US', ProfileId = testProfile.Id,
			TimeZoneSidKey='America/Los_Angeles', UserName='test.username@test.com',
			License_Cost_Center__c = 'ISF005CH01'
		);

		System.runAs(testUser) {

			Id accountRecordTypeId = [SELECT Id FROM RecordType WHERE Name ='Airline Headquarters'].Id;
			Account a = new Account(name='testAccount', RecordTypeId=accountRecordTypeId);
			insert a;

			Id objectiveRecordTypeId = [SELECT Id FROM RecordType WHERE Name ='Account Issues and Priorities'].Id;

			Objective__c o = new Objective__c();
			o.Account__c = a.Id;
			o.RecordTypeId = objectiveRecordTypeId;
			o.Name = 'testObjective';
			o.Status__c = 'Not Started';
			o.AM_Level_of_importance__c = 'Medium';
			insert o;

			ApexPages.currentPage().getParameters().put('id',a.id);
			ApexPages.StandardController stdController = new ApexPages.StandardController(a);
			AMP_IssuesAndPrioritiesExtension issuesAndPrioritiesExtension  = new AMP_IssuesAndPrioritiesExtension(stdController);

			List<Objective__c> lsIssuesAndPriorities =  issuesAndPrioritiesExtension.getIssuesAndPriorities();
			String s = issuesAndPrioritiesExtension.getRecordName();
			s = issuesAndPrioritiesExtension.getRecordId();
			s = issuesAndPrioritiesExtension.getJSONIssuesAndPriorities();
			// for coverage go through the void functions
			issuesAndPrioritiesExtension.sortByName();
			issuesAndPrioritiesExtension.sortByDescription();
			issuesAndPrioritiesExtension.sortByDetails();
			issuesAndPrioritiesExtension.sortByLocal();
			issuesAndPrioritiesExtension.sortByRegional();
			issuesAndPrioritiesExtension.sortByGlobal();
			issuesAndPrioritiesExtension.sortByPublic();
			issuesAndPrioritiesExtension.sortByCanIATASupport();
			issuesAndPrioritiesExtension.sortByIssueWithIATA();
			issuesAndPrioritiesExtension.sortByStatus();
			issuesAndPrioritiesExtension.sortByLevelOfImportance();

			issuesAndPrioritiesExtension.newLine();
			issuesAndPrioritiesExtension.EditLine();
			issuesAndPrioritiesExtension.SaveLine();
			issuesAndPrioritiesExtension.CancelEdit();
			issuesAndPrioritiesExtension.IdConcerned = o.Id;
			issuesAndPrioritiesExtension.DeleteLine();

			PageReference pr = issuesAndPrioritiesExtension.saveList();
			System.assertEquals(1,lsIssuesAndPriorities.size());
			try {
				o.Id = 'fakeId';
				issuesAndPrioritiesExtension.saveList();
			} catch(Exception e) {
				return;
			}
			System.assert(false, 'There should be and Exception thrown');
		}
	}
}