src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_ISO_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Class__c</fullName>
        <description>Map the objects AGT from AIMS. This is a value equal to category.</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Location Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Field used to determine the Location Type of travel agents (used in Americas)</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>EB</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>HE</fullName>
                </value>
                <value>
                    <fullName>HO</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>WH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>China &amp; North Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East &amp; North Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Russia &amp; CIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IATA_Agency</fullName>
        <active>true</active>
        <description>The new record type for ALL Agencies with NEW data model - Use this for all Agencies</description>
        <label>Agency</label>
    </recordTypes>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agency_Applied_Change_code__c.object
<CustomObject>
    <fields>
        <fullName>Outstanding_Amount__c</fullName>
        <description>Value to be displayed at Outstanding Amount column on eBulletin report</description>
        <inlineHelpText>Value to be displayed at Outstanding Amount column on eBulletin report</inlineHelpText>
        <label>Outstanding Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agency Applied Change code</label>
    <nameField>
        <displayFormat>AACC-{000000}</displayFormat>
        <label>Change code details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies Applied Change codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PSG_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>maintained by FDS Governance</inlineHelpText>
        <label>PSG Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PaConf_Representative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PAConf Representative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code_Numeric__c</fullName>
        <label>ISO Code (Numeric)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Africa &amp; Middle East</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Asia &amp; Pacific</fullName>
                </value>
                <value>
                    <fullName>China &amp; North Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Services_Rendered__c.object
<CustomObject>
    <fields>
        <fullName>Services_Rendered_Status__c</fullName>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Rendered_Type__c</fullName>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CASS Participation</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>BSP Participation</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>BSP via IBCS</fullName>
                </value>
                <value>
                    <fullName>CASS Export via GSSA</fullName>
                </value>
                <value>
                    <fullName>CASS Export Direct Participation</fullName>
                </value>
                <value>
                    <fullName>CASS Import Direct Participation</fullName>
                </value>
                <value>
                    <fullName>CASS Import via GHA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Rendered_to_Airline__c</fullName>
        <label>Consumer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Airline Headquarters, Airline Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rendered</relationshipLabel>
        <relationshipName>Services_Rendered_md</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Services Rendered</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rendered</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AMS_MajorDefaultCommunicationTest.cls
@isTest
private class AMS_MajorDefaultCommunicationTest {

	@testSetup static void setup() {
		IATA_ISO_Country__c country = new IATA_ISO_Country__c();
		country.Name = 'Portugal';
		country.ISO_Code__c = 'PT';
		country.ISO_Code_Numeric__c = 11;
		insert country;

		Account airline = new Account();
		airline.Name = 'Airline';
		airline.RecordTypeId = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline');
		airline.IATA_ISO_Country__c = country.Id;

		Account agency = new Account();
		agency.Name = 'Agency';
		agency.RecordTypeId = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Agency');
		agency.IATACode__c = '24125';
		agency.Location_Type__c = 'HO';
		agency.Location_Class__c = 'P';
		agency.IATA_ISO_Country__c = country.Id;
		insert new List<Account> {airline, agency};

		Contact airlineContact1 = new Contact();
		airlineContact1.FirstName = 'FirstName';
		airlineContact1.LastName = 'LastName';
		airlineContact1.Email = 'test@mail.com';
		airlineContact1.Status__c = 'Active';
		airlineContact1.AccountId = airline.Id;
		airlineContact1.PSG_Member__c = true;
		airlineContact1.PaConf_Representative__c = true; 

		Contact airlineContact2 = new Contact();
		airlineContact2.FirstName = 'FirstName2';
		airlineContact2.LastName = 'LastName2';
		airlineContact2.Email = 'test2@mail.com';
		airlineContact2.Status__c = 'Active';
		airlineContact2.AccountId = airline.Id;
		airlineContact2.PSG_Member__c = true;
		airlineContact2.PaConf_Representative__c = true; 

		Contact agencyContact = new Contact();
		agencyContact.FirstName = 'FirstName';
		agencyContact.LastName = 'LastName';
		agencyContact.Email = 'mail@test.com';
		agencyContact.AccountId = agency.Id;
		insert new List<Contact> {airlineContact1, airlineContact2, agencyContact};

		Case cse = new Case();
		cse.RecordTypeId = RecordTypeSingleton.getInstance().getRecordTypeId('Case', 'SIDRA');
		cse.AccountId = agency.Id;
		cse.ContactId = agencyContact.Id;
		cse.Region__c = 'Europe';
		cse.BSPCountry__c = 'Portugal';
		cse.BSP_CASS__c = 'BSP';
		cse.IATAcode__c = '24125';
		cse.Subject = 'Major Default';
		cse.Short_Payment_Amount__c = 200000000.00;
		cse.Outstanding_Amount__c = 100;
		insert cse;

		Services_Rendered__c service = new Services_Rendered__c();
		service.Services_Rendered_to_Airline__c = airline.Id;
		service.Services_Rendered_Status__c  = 'Active';
		service.Services_Rendered_Type__c  = 'BSP Participation';
		insert service;
	}
	
	@isTest static void testDefaultNotification() {
		User admin = [SELECT Id, ProfileId FROM User WHERE Id <> :UserInfo.getUserId() AND ProfileId = :UserInfo.getProfileId() AND IsActive = true LIMIT 1];

		//Avoid MIXED_DML_OPERATION on setup and non-setup objects exception
		System.runAs(admin) {
			Group g = [SELECT Id FROM Group WHERE DeveloperName = 'AMS_Agency_Default_Notification'];
			GroupMember gm = new GroupMember();
			gm.GroupId = g.Id;
			gm.UserOrGroupId = UserInfo.getUserId();
			insert gm;

			Contact c = [SELECT Id, FirstName, LastName, Email FROM Contact WHERE Email = 'test2@mail.com'];
			User u = ISSP_WS_Utilities.createUser(c.FirstName, c.LastName, c.email, 'OtherCompany', c.Id, false);
        	u.FederationIdentifier = String.valueOf(c.Id).substring(0, 15);
        	u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'ISS Portal Airline Delegated Admin User'].Id;
        	insert u;
		}

		Test.startTest();
		Case cse = [SELECT Id, AccountId FROM Case];
		Agency_Applied_Change_code__c cc = new Agency_Applied_Change_code__c();
		cc.Account__c = cse.AccountId;
		cc.SIDRA_Case__c = cse.Id;
		cc.Change_Code__c = 'DEF';
		insert cc;

		Test.stopTest();
	}
	

}