src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACLI_Status__c</fullName>
        <label>ACLI Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive Company</fullName>
                </value>
                <value>
                    <fullName>Active Company</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Airline_Prefix__c</fullName>
        <label>Airline Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_designator__c</fullName>
        <description>Field used for the airline designator code e.g. BA</description>
        <label>IATA Designator</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BIETA_Bilateral_Date__c</fullName>
        <label>BIETA Bilateral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIETA_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BIETA Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BIETA_One_way_Electronic_Issuing_Airline__c</fullName>
        <label>BIETA One way Electronic Issuing Airline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIETA_One_way_Electronic_Participating__c</fullName>
        <label>BIETA One way Electronic Participating</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIETA_One_way_Intermodal_Issuing_Airline__c</fullName>
        <label>BIETA One way Intermodal Issuing Airline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BIETA_One_way_Intermodal_Participating__c</fullName>
        <label>BIETA One way Intermodal Participating</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IATACode__c</fullName>
        <label>IATA Code</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo_File_ID__c</fullName>
        <label>Logo File ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Cargo__c</fullName>
        <label>MITA IATA Interline Cargo</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_IATA_Interline_Passenger__c</fullName>
        <label>MITA IATA Interline Passenger</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MITA Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MITA_One_way_Pass_Issuing_Airline__c</fullName>
        <label>MITA One way Pass. Issuing Airline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MITA_One_way_Pass_Participating__c</fullName>
        <label>MITA One way Pass. Participating</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Membership_status__c</fullName>
        <description>Field used to specify the membership status</description>
        <label>IATA Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IATA member</fullName>
                </value>
                <value>
                    <fullName>Non-IATA member</fullName>
                </value>
                <value>
                    <fullName>Ex-IATA Member</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IATA_Airline</fullName>
        <active>true</active>
        <description>The new record type for ALL Airlines, IATA members and non members - Headquaters Account - with NEW data model - Use this for all Airlines HQ</description>
        <label>Airline Headquarters</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Airline_Designator__c</fullName>
        <formula>Account.Airline_designator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Airline Designator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MITA_Contact_Type__c</fullName>
        <label>MITA Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Interline Passenger Agreement Manager</fullName>
                </value>
                <value>
                    <fullName>Passenger Protection Agreement</fullName>
                </value>
                <value>
                    <fullName>Interline Airline Generic Contact</fullName>
                </value>
                <value>
                    <fullName>Interline Cargo Agreement Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MITA_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MITA Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Template__c</fullName>
        <label>Notification Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Portal_Status__c</fullName>
        <label>User Portal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved User</fullName>
                </value>
                <value>
                    <fullName>Approved Admin</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Regional Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ISSP_Notifications_Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Set what trigger notification for which object and with a given template</description>
    <fields>
        <fullName>Notification_Template_Id__c</fullName>
        <description>The notification template Id to use for the notification</description>
        <label>Notification Template Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ISSP Notifications Trigger</label>
</CustomObject>

src/objects/MITA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Airline_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airline 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Airline Headquarters</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MITA Agreements (Account)</relationshipLabel>
        <relationshipName>MITA_Agreements_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Describes the situtation of the agreement</description>
        <formula>IF(ISNULL(Cancellation_processed_date__c),
  IF(ISNULL(Agreement_processed_date__c),
    &apos;Pending Approval&apos;,
    IF(Effective_date__c &lt;= TODAY(),
      &apos;Active&apos;,
      &apos;Not Active Yet&apos;
    )
  ),
  IF(OR(ISPICKVAL(Cancellation_Reason__c,&apos;Rejected by Airline 1&apos;),ISPICKVAL(Cancellation_Reason__c,&apos;Rejected by Airline 2&apos;)),
    &apos;Rejected&apos;,
    IF(Cancellation_date__c &lt;= TODAY(),
      &apos;Withdrawn&apos;,
      &apos;Pending Withdrawal&apos;
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Possible values are:
 - Not Active Yet,
 - Active
 - Pending Approval
 - Withdrawn
- Pending Withdrawal
- Rejected</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>MITA Agreement</label>
    <nameField>
        <displayFormat>MA-{YYYY}{MM}-{0000}</displayFormat>
        <label>MITA Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MITA Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{0000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Notification_template__c.object
<CustomObject>
    <fields>
        <fullName>Admins_Users__c</fullName>
        <label>Administrators/User</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrators</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Identifier__c</fullName>
        <description>Unique identifier used internally so the template can be found on code in all environments</description>
        <externalId>true</externalId>
        <label>Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <label>Notification template</label>
    <nameField>
        <displayFormat>NT-{0000}</displayFormat>
        <label>Notification template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MITA_AgreementTriggerHandlerTest.cls
@isTest
public class MITA_AgreementTriggerHandlerTest {

	private static Id RT_AIRLINE = RecordTypeSingleton.getInstance().getRecordTypeId('Account', 'IATA_Airline');
	private static Account airline1;
	private static Account airline2;
	private static Contact contact1;
	private static Contact contact2;

	@TestSetup
	public static void setup(){

		Notification_Template__c template1 = new Notification_template__c (
			Subject__c = MITA_AgreementTriggerHandler.TEMPLATE_REQUESTED,
			Message__c = 'Some message',
			Admins_Users__c = 'User',
			Identifier__c = 'notification'
		);
		Notification_Template__c template2 = new Notification_template__c (
			Subject__c = MITA_AgreementTriggerHandler.TEMPLATE_APPROVED,
			Message__c = 'Some message',
			Admins_Users__c = 'User',
			Identifier__c = 'notification'
		);
		Notification_Template__c template3 = new Notification_template__c (
			Subject__c = MITA_AgreementTriggerHandler.TEMPLATE_REJECTED,
			Message__c = 'Some message',
			Admins_Users__c = 'User',
			Identifier__c = 'notification'
		);
		Notification_Template__c template4 = new Notification_template__c (
			Subject__c = MITA_AgreementTriggerHandler.TEMPLATE_WITHDRAWN,
			Message__c = 'Some message',
			Admins_Users__c = 'User',
			Identifier__c = 'notification'
		);
		insert new list<Notification_Template__c>{template1, template2, template3, template4};

		insert new list<ISSP_Notifications_Trigger__c>{
			new ISSP_Notifications_Trigger__c (
				Name = MITA_AgreementTriggerHandler.TEMPLATE_REQUESTED,
				Notification_Template_Id__c = template1.Id
			),
			new ISSP_Notifications_Trigger__c (
				Name = MITA_AgreementTriggerHandler.TEMPLATE_APPROVED,
				Notification_Template_Id__c = template2.Id
			),
			new ISSP_Notifications_Trigger__c (
				Name = MITA_AgreementTriggerHandler.TEMPLATE_REJECTED,
				Notification_Template_Id__c = template3.Id
			),
			new ISSP_Notifications_Trigger__c (
				Name = MITA_AgreementTriggerHandler.TEMPLATE_WITHDRAWN,
				Notification_Template_Id__c = template4.Id
			)
		};

		airline1 = new Account(
			RecordTypeId = RT_AIRLINE,
			Name='MyAirline1',
			ACLI_Status__c = 'Active Company',
			MITA_Member__c = true,
			BIETA_Member__c = true,
			Airline_designator__c = 'AA',
			IATACode__c = '111',
			Airline_Prefix__c = '111',
			MITA_IATA_Interline_Passenger__c = Date.today(),
			MITA_IATA_Interline_Cargo__c = Date.today(),
			MITA_One_way_Pass_Issuing_Airline__c = Date.today(),
			MITA_One_way_Pass_Participating__c = Date.today(),
			BIETA_Bilateral_Date__c = Date.today(),
			BIETA_One_way_Electronic_Issuing_Airline__c = Date.today(),
			BIETA_One_way_Electronic_Participating__c = Date.today(),
			BIETA_One_way_Intermodal_Issuing_Airline__c = Date.today(),
			BIETA_One_way_Intermodal_Participating__c = Date.today()
		);

		airline2 = new Account(
			RecordTypeId = RT_AIRLINE,
			Name='MyAirline2',
			ACLI_Status__c = 'Active Company',
			MITA_Member__c = true,
			BIETA_Member__c = true,
			Airline_designator__c = 'BB',
			IATACode__c = '222',
			Airline_Prefix__c = '222',
			MITA_IATA_Interline_Passenger__c = Date.today(),
			MITA_IATA_Interline_Cargo__c = Date.today(),
			MITA_One_way_Pass_Issuing_Airline__c = Date.today(),
			MITA_One_way_Pass_Participating__c = Date.today(),
			BIETA_Bilateral_Date__c = Date.today(),
			BIETA_One_way_Electronic_Issuing_Airline__c = Date.today(),
			BIETA_One_way_Electronic_Participating__c = Date.today(),
			BIETA_One_way_Intermodal_Issuing_Airline__c = Date.today(),
			BIETA_One_way_Intermodal_Participating__c = Date.today()
		);

		insert new list<Account>{airline1,airline2};

		contact1 = new Contact (
			AccountId = airline1.Id,
			FirstName = 'first1',
			LastName = 'last1',
			Email = 'test1email@test.com',
			Phone = '123456789',
			Status__c = 'Active',
			MITA_Contact__c = true,
			User_Portal_Status__c = 'Administrator',
			MITA_Contact_Type__c = IA_util.GENERIC_CONTACT
		);
		contact2 = new Contact (
			AccountId = airline2.Id,
			FirstName = 'first2',
			LastName = 'last2',
			Email = 'test2email@test.com',
			Phone = '123456789',
			Status__c = 'Active',
			MITA_Contact__c = true,
			User_Portal_Status__c = 'Administrator',
			MITA_Contact_Type__c = IA_util.CARGO_MANAGER
		);
		insert new list<Contact>{contact1,contact2};
	}

	private static void queryRecords() {
		for ( Account account: [
				SELECT Name, Airline_Prefix__c, Airline_designator__c, IATAcode__c, Membership_status__c, MITA_Member__c, BIETA_Member__c, Logo_File_ID__c,
				MITA_IATA_Interline_Passenger__c, MITA_IATA_Interline_Cargo__c, MITA_One_way_Pass_Issuing_Airline__c, MITA_One_way_Pass_Participating__c,
				BIETA_Bilateral_Date__c, BIETA_One_way_Electronic_Issuing_Airline__c, BIETA_One_way_Electronic_Participating__c, BIETA_One_way_Intermodal_Issuing_Airline__c,
				BIETA_One_way_Intermodal_Participating__c
				FROM Account])
		{
			if (account.Name == 'MyAirline1') airline1 = account;
			if (account.Name == 'MyAirline2') airline2 = account;
		}
		for ( Contact contact: [
				SELECT Id, RecordTypeId, AccountId, FirstName, LastName, Email, Phone, Status__c, MITA_Contact_Type__c
				FROM Contact])
		{
			if (contact.Email == 'test1email@test.com') contact1 = contact;
			if (contact.Email == 'test2email@test.com') contact2 = contact;
		}
	}

	static testMethod void testRequestNotification(){
		queryRecords();

		MITA_Agreement__c agreement = new MITA_Agreement__c(
			Airline_1__c = airline1.Id,
			Airline_2__c = airline2.Id,
			MITAorBIETA__c = IA_util.MITA,
			Agreement_Type__c = IA_util.TYPE_PAX,
			Created_date__c = Date.today(),
			Agreement_processed_date__c = Date.today(),
			Effective_date__c = Date.today()
		);

		Test.StartTest();
		insert agreement;
		Test.stopTest();

		list<Notification__c> listNotification = [SELECT Id, Subject__c, Contact__c FROM Notification__c ORDER BY CreatedDate DESC LIMIT 1];
		System.assertEquals(1, listNotification.size());
		System.assertEquals(MITA_AgreementTriggerHandler.TEMPLATE_REQUESTED, listNotification[0].Subject__c);
		System.assertEquals(contact2.Id, listNotification[0].Contact__c);
	}

	static TestMethod void testApprovalNotification(){
		queryRecords();

		MITA_Agreement__c agreement = new MITA_Agreement__c(
			Airline_1__c = airline1.Id,
			Airline_2__c = airline2.Id,
			MITAorBIETA__c = IA_util.MITA,
			Agreement_Type__c = IA_util.TYPE_PAX,
			Created_date__c = Date.today(),
			Agreement_processed_date__c = Date.today(),
			Effective_date__c = null,
			Cancellation_date__c = null
		);
		insert agreement;

		Test.StartTest();
		agreement.Effective_date__c = Date.today();
		update agreement;
		Test.stopTest();

		list<Notification__c> listNotification = [SELECT Id, Subject__c, Contact__c
			FROM Notification__c
			WHERE Subject__c = :MITA_AgreementTriggerHandler.TEMPLATE_APPROVED
			ORDER BY CreatedDate DESC LIMIT 1];
		System.assertEquals(1, listNotification.size());
		System.assertEquals(MITA_AgreementTriggerHandler.TEMPLATE_APPROVED, listNotification[0].Subject__c);
		System.assertEquals(contact1.Id, listNotification[0].Contact__c);
	}

	static testMethod void testRejectNotification(){
		queryRecords();

		MITA_Agreement__c agreement = new MITA_Agreement__c(
			Airline_1__c = airline1.Id,
			Airline_2__c = airline2.Id,
			MITAorBIETA__c = IA_util.MITA,
			Agreement_Type__c = IA_util.TYPE_PAX,
			Created_date__c = Date.today(),
			Agreement_processed_date__c = Date.today()
		);
		insert agreement;

		Test.StartTest();
		agreement.Cancellation_date__c = Date.today();
		agreement.Cancellation_Reason__c = 'Rejected by Airline 2';
		update agreement;
		Test.stopTest();

		list<Notification__c> listNotification = [SELECT Id, Subject__c, Contact__c
			FROM Notification__c
			WHERE Subject__c = :MITA_AgreementTriggerHandler.TEMPLATE_REJECTED
			ORDER BY CreatedDate DESC LIMIT 1];
		System.assertEquals(1, listNotification.size(), listNotification);
		System.assertEquals(MITA_AgreementTriggerHandler.TEMPLATE_REJECTED, listNotification[0].Subject__c);
		System.assertEquals(contact1.Id, listNotification[0].Contact__c);
	}

	static testMethod void testWithdrawNotification1(){
		queryRecords();

		MITA_Agreement__c agreement = new MITA_Agreement__c(
			Airline_1__c = airline1.Id,
			Airline_2__c = airline2.Id,
			MITAorBIETA__c = IA_util.MITA,
			Agreement_Type__c = IA_util.TYPE_PAX,
			Created_date__c = Date.today(),
			Agreement_processed_date__c = Date.today()
		);
		insert agreement;

		Test.StartTest();
		agreement.Cancellation_date__c = Date.today();
		agreement.Cancellation_Reason__c = 'Airline 1 leaves agreement';
		update agreement;
		Test.stopTest();

		list<Notification__c> listNotification = [SELECT Id, Subject__c, Contact__c
			FROM Notification__c
			WHERE Subject__c = :MITA_AgreementTriggerHandler.TEMPLATE_WITHDRAWN
			ORDER BY CreatedDate DESC LIMIT 1];
		System.assertEquals(1, listNotification.size(), listNotification);
		System.assertEquals(MITA_AgreementTriggerHandler.TEMPLATE_WITHDRAWN, listNotification[0].Subject__c);
		System.assertEquals(contact2.Id, listNotification[0].Contact__c);
	}

	static testMethod void testWithdrawNotification2(){
		queryRecords();

		MITA_Agreement__c agreement = new MITA_Agreement__c(
			Airline_1__c = airline1.Id,
			Airline_2__c = airline2.Id,
			MITAorBIETA__c = IA_util.MITA,
			Agreement_Type__c = IA_util.TYPE_PAX,
			Created_date__c = Date.today(),
			Agreement_processed_date__c = Date.today()
		);
		insert agreement;

		Test.StartTest();
		agreement.Cancellation_date__c = Date.today();
		agreement.Cancellation_Reason__c = 'Airline 2 leaves agreement';
		update agreement;
		Test.stopTest();

		list<Notification__c> listNotification = [SELECT Id, Subject__c, Contact__c
			FROM Notification__c
			WHERE Subject__c = :MITA_AgreementTriggerHandler.TEMPLATE_WITHDRAWN
			ORDER BY CreatedDate DESC LIMIT 1];
		System.assertEquals(1, listNotification.size(), listNotification);
		System.assertEquals(MITA_AgreementTriggerHandler.TEMPLATE_WITHDRAWN, listNotification[0].Subject__c);
		System.assertEquals(contact1.Id, listNotification[0].Contact__c);
	}
}