src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>ARC registered</fullName>
                </value>
                <value>
                    <fullName>Cash basis/no commission</fullName>
                </value>
                <value>
                    <fullName>Cash basis/with commission</fullName>
                </value>
                <value>
                    <fullName>Changes processed</fullName>
                </value>
                <value>
                    <fullName>Endorsed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>New application pending</fullName>
                </value>
                <value>
                    <fullName>No longer a customer</fullName>
                </value>
                <value>
                    <fullName>Not accreditated</fullName>
                </value>
                <value>
                    <fullName>Not in operation</fullName>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under review</fullName>
                </value>
                <value>
                    <fullName>Unregisterable STP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Amazon_Cred__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Dev_Configuration__c</fullName>
        <label>Dev Configuration</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prod_Configuration__c</fullName>
        <label>Prod Configuration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Amazon Cred</label>
</CustomObject>

src/objects/AWSKey__c.object
<CustomObject>
    <description>Store keys used to communicate with Amazon Web Services</description>
    <fields>
        <fullName>AWS_ENDPOINT_URL__c</fullName>
        <defaultValue>&quot;http://s3.awsamazon.com&quot;</defaultValue>
        <description>Specific endpoint url to use to connect stored in this bucket/crednetials</description>
        <label>AWS EndPoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>Define the bucket to use with this credential key</description>
        <externalId>true</externalId>
        <inlineHelpText>Define the bucket to use with this credential key</inlineHelpText>
        <label>Bucket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAS_Access_Point__c</fullName>
        <inlineHelpText>URL access point as http(s)://IP:PORT</inlineHelpText>
        <label>IAS Access Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAS_configuration_name__c</fullName>
        <defaultValue>&quot;iata.ini&quot;</defaultValue>
        <inlineHelpText>enter the nameof IAS configuratuon file to load for this access</inlineHelpText>
        <label>IAS configuration name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>AWS Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IATA_Code__c</fullName>
        <formula>Account.IATACode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IATA Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VER_Number__c</fullName>
        <label>VER Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ID_Card__c.object
<CustomObject>
    <description>ID Cards information
two record types:
1- AIMS (default) contains AIMS data (SFDC is the master data)
2- WebStar contains WebStar data (WebStar is master data)</description>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_Card_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Latest ID Card Application</label>
        <referenceTo>ID_Card_Application__c</referenceTo>
        <relationshipLabel>ID Cards</relationshipLabel>
        <relationshipName>ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VER_Number__c</fullName>
        <label>VER Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>ID Card</label>
    <nameField>
        <displayFormat>IDC-{000000000}</displayFormat>
        <label>ID Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ID Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ID_Card_Application__c.object
<CustomObject>
    <description>Object that holds information on the application of a new/renew/reissue/replacement ID Card</description>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IATA_Code__c</fullName>
        <label>IATA Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ID Card</label>
        <referenceTo>ID_Card__c</referenceTo>
        <relationshipLabel>ID Card Applications</relationshipLabel>
        <relationshipName>ID_Card_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_application__c</fullName>
        <label>Type of application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Replacement</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reissue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VER_Number__c</fullName>
        <externalId>true</externalId>
        <label>VER#</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>ID Card Application</label>
    <nameField>
        <displayFormat>IDCA-{00000}</displayFormat>
        <label>ID Card Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ID Card Applications</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Record type for all cards on non key account</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>License_Cost_Center__c</fullName>
        <inlineHelpText>The IATA cost center that is paying for your Salesforce.com license.</inlineHelpText>
        <label>License Cost Center</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/trgIDCard_Case_BeforeUpdateTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class trgIDCard_Case_BeforeUpdateTest
{
    private static IDCardTestData testData;
    private static List<Contact> relatedContact;
    private static List<Case> relatedCase;
    
    TestMethod static void testTrgIDCard_Case_BeforeUpdate()
    {
        
        Amazon_Cred__c amc = new Amazon_Cred__c(Name = 'IdCard', Dev_Configuration__c = 'IdCardDev', Prod_Configuration__c = 'IdCardProd');
        insert amc;

        AWSKey__c awsk_dev = new AWSKey__c(Name = 'IdCardDev', Key__c = 'asd', Secret__c = 'asd',  IAS_configuration_name__c = 'asd', IAS_Access_Point__c = 'asd', Bucket__c = 'asd', AWS_ENDPOINT_URL__c = 'https://asd.com');
        AWSKey__c awsk_prd = new AWSKey__c(Name = 'IdCardProd', Key__c = 'asd', Secret__c = 'asd',  IAS_configuration_name__c = 'asd', IAS_Access_Point__c = 'asd', Bucket__c = 'asd', AWS_ENDPOINT_URL__c = 'https://asd.com');
        insert awsk_dev;
        insert awsk_prd;
        

        
        TransformationHelper.trgAccountISSP_AfterBeforInsertDeleteUpdateUndelete = true;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'sasa', Email='abciuhgrtydfmmnd@iata.org', 
        EmailEncodingKey='UTF-8', LastName='Saso', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, License_Cost_Center__c='ITO005CH01',
        TimeZoneSidKey='America/Los_Angeles', UserName='abciuhgrtydfmmnd@iata.org');
        insert u;
        
        testData = new IDCardTestData();
        
            List<ID_Card_Application__c> idCardAppToInsert = new List<ID_Card_Application__c>();
            
            idCardAppToInsert.add(testData.IDCards_IDCardApplications[3]);        
            
            insert idCardAppToInsert;
            
            Contact contactId1 = IDCardUtil.CreateContactWhenNewCardIsApproved(idCardAppToInsert[0]);   
            
            
            IDCardUtil.CreateIDCardApplicationCase(idCardAppToInsert[0], testData.IDCard_Accounts[0]);
            System.debug('*-*-*-*-*-*-*-*-*- IdCardApplication ' + idCardAppToInsert[0].Id);
            System.debug('*-*-*-*-*-*-*-*-*- Account ' + testData.IDCard_Accounts[0]);
            relatedCase = [SELECT ID_Card_Status__c FROM Case];
            System.debug('*-*-*-*-*-*-*-*-*- ' + relatedCase);
            
            relatedCase[0].ID_Card_Status__c = IDCardUtil.CASECARDSTATUS_PENDING_MNG_APPROVAL;
            update relatedCase[0];
            relatedCase[0].ID_Card_Status__c = IDCardUtil.CASECARDSTATUS_APPROVED;
            update relatedCase[0];
            
            relatedContact = [SELECT Id, LastName, FirstName, VER_Number__c, IATA_Code__c, Account.RecordType.Name, Account.Status__c, Date_of_Birth__c FROM Contact WHERE Id =:contactId1.id];  
            
            List<ID_Card__c> idCardToInsert = new List<ID_Card__c>();          
            idCardToInsert.add(IDCardUtil.CreateIDCardObjectFromApplication(idCardAppToInsert[0], relatedContact[0]));            
            insert idCardToInsert;
            
            idCardAppToInsert[0].Type_of_application__c = IDCardUtil.APPLICATIONTYPE_REISSUE;
            update idCardAppToInsert;
            relatedCase[0].OwnerId = u.Id;
            update relatedCase;
            
        Test.startTest();
            System.runAs(u)
            {
                relatedCase = [SELECT ID_Card_Status__c FROM Case];
                
                relatedCase[0].ID_Card_Status__c = IDCardUtil.CASECARDSTATUS_REJECTED;
                update relatedCase;
            }
            
        Test.stopTest();
    }
}