src/objects/Accreditation__c.object
<CustomObject>
    <fields>
        <fullName>AMS_GDP_Key__c</fullName>
        <externalId>true</externalId>
        <label>AMS_GDP_Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Accreditation</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Accreditation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accreditation</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agency_Authorization__c.object
<CustomObject>
    <description>Object is used to store agency Authorization such as BSPLink authorization</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Authorizations</relationshipLabel>
        <relationshipName>Agency_Authorizations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Agency Authorization</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Agency Authorization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Authorizations</pluralLabel>
    <recordTypes>
        <fullName>FormOfPayment</fullName>
        <active>true</active>
        <label>Form Of Payment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Account_Role__c.object
<CustomObject>
    <description>Object that represents a connection between an Account another entity. This other entity can be a Person, a Contact or another Account. This will replace the Agency Employee and Agency Ownership + Owner structure.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The main Account on this object. This Account will be connect with another Account, a Person or a Contact</description>
        <inlineHelpText>The main Account on this object. This Account will be connect with another Account, a Person or a Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Owners</relationshipLabel>
        <relationshipName>AMS_Account_Roles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AMS Account Role</label>
    <nameField>
        <displayFormat>AAR-{00000000}</displayFormat>
        <label>AMS Account Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Account Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Address__c.object
<CustomObject>
    <description>AMS Address</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses (AMS)</relationshipLabel>
        <relationshipName>Addresses_AMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address (AMS)</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses (AMS)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Agency_Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AMS Agency Affiliations</relationshipLabel>
        <relationshipName>AMS_Agency_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AMS Agency Affiliation</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>AMS Agency Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Agency Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AMS_Agency_Airport__c.object
<CustomObject>
    <description>Junction object to relate Airport with Agency.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Airports (AMS)</relationshipLabel>
        <relationshipName>Agency_Airports_AMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Airport (AMS)</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>Agency Airport (AMS) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Airports (AMS)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AMS_Agency_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Profiles</relationshipLabel>
        <relationshipName>Agency_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Profile</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Agency Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Inspection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Inspections_AMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inspection (AMS)</label>
    <nameField>
        <displayFormat>INS-{0000000}</displayFormat>
        <label>Inspection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections (AMS)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AMS_Territory__c.object
<CustomObject>
    <description>This object is a child of the Appointment, it represents a limitation on the permission of selling tickets. The appointments are limited to their territories (if any).</description>
    <fields>
        <fullName>Appointment__c</fullName>
        <description>Related Appointment(AMS)</description>
        <label>Appointment (AMS)</label>
        <referenceTo>AMS_Inspection__c</referenceTo>
        <relationshipLabel>AMS Territories</relationshipLabel>
        <relationshipName>AMS_Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AMS Territory</label>
    <nameField>
        <displayFormat>Territory-{000000}</displayFormat>
        <label>Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GDP_Address__c.object
<CustomObject>
    <fields>
        <fullName>GDP_Geo_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GDP Geo Detail</label>
        <referenceTo>GDP_Geo_Detail__c</referenceTo>
        <relationshipLabel>GDP Addresses</relationshipLabel>
        <relationshipName>GDP_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>GDP Addresses</relationshipLabel>
        <relationshipName>GDP_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IATA_ISO_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IATA ISO State</label>
        <referenceTo>IATA_ISO_State__c</referenceTo>
        <relationshipLabel>GDP Addresses</relationshipLabel>
        <relationshipName>GDP_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Continent__c</fullName>
        <formula>GDP_Geo_Detail__r.Sub_Continent__c</formula>
        <label>Sub Continent</label>
        <type>Text</type>
    </fields>
    <label>GDP Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>GDP Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDP Addresses</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Agency_Profile_Specialization__c.object
<CustomObject>
    <fields>
        <fullName>AMS_GDP_Key__c</fullName>
        <externalId>true</externalId>
        <label>AMS GDP Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GDP Agency Profile and Specialization</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>GDP Agency Profile and Specialization Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDP Agency Profiles and Specializations</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Geo_Detail__c.object
<CustomObject>
    <description>Used to define and store geological locations (identified by location specific IDs and filtered out by sub continent) of GDP Agencies</description>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <description>Related IATA ISO Country</description>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipName>IEC_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sub_Continent__c</fullName>
        <description>Used to filter out Geo Details by sub continents</description>
        <label>Sub Continent</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_ID__c</fullName>
        <description>Used as location ID for GDP Agencies</description>
        <externalId>true</externalId>
        <inlineHelpText>Please enter the Country ISO Code this is used for external system mapping(External ID)</inlineHelpText>
        <label>System ID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>GDP Geo Detail</label>
    <nameField>
        <label>GDP Geo Detail</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP Geo Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GDP_Products_Account_View__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Continent__c</fullName>
        <formula>Related_GDP_Address__r.Sub_Continent__c</formula>
        <label>Sub Continent</label>
        <type>Text</type>
    </fields>
    <label>GDP Products - Account View</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP Products - Accounts View</pluralLabel>
    <recordTypes>
        <fullName>GDP</fullName>
        <active>true</active>
        <description>Used for GDP Live Applications</description>
        <label>GDP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Reference_Table__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External ID used for Data loading from external system</inlineHelpText>
        <label>System ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>GDP Reference Table</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP References Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <description>International country code (ISO)</description>
        <externalId>true</externalId>
        <inlineHelpText>International country code</inlineHelpText>
        <label>ISO Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>International_dialing_code_ISD__c</fullName>
        <label>International dialing code ISD</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IATA_ISO_State__c.object
<CustomObject>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>IATA ISO States</relationshipLabel>
        <relationshipName>IATA_ISO_States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <externalId>true</externalId>
        <label>ISO Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IATA ISO State</label>
    <nameField>
        <label>ISO State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ams2gdp_Selector.cls
public class ams2gdp_Selector
{
	public static Map<String, String> getCountryNameById(Set<String> countryIds)
	{
		Map<String, String> result = new Map<String, String>();
		if(countryIds.size() > 0)
		{
			for(IATA_ISO_Country__c isoCountry : [SELECT Id, Name FROM IATA_ISO_Country__c WHERE Id IN :countryIds])
				result.put(isoCountry.Id, isoCountry.Name);

		}
		return result;
	}

	public static Map<String, String> getCountryIdByName(Set<String> countryNames)
	{
		Map<String, String> result = new Map<String, String>();
		if(countryNames.size() > 0)
		{
			for(IATA_ISO_Country__c isoCountry : [SELECT Id, Name FROM IATA_ISO_Country__c WHERE Name IN :countryNames])
				result.put(isoCountry.Name, isoCountry.Id);

		}
		return result;
	}

	public static Map<String, String> getStateNameById(Set<String> stateIds)
	{
		Map<String, String> result = new Map<String, String>();
		if(stateIds.size() > 0)
		{
			for(IATA_ISO_State__c isoState : [SELECT Id, Name FROM IATA_ISO_State__c WHERE Id IN :stateIds])
				result.put(isoState.Id, isoState.Name);

		}
		return result;
	}

	public static Map<String, String> getStateIdByName(Set<String> stateNames)
	{
		Map<String, String> result = new Map<String, String>();
		if(stateNames.size() > 0)
		{
			for(IATA_ISO_State__c isoState : [SELECT Id, Name FROM IATA_ISO_State__c WHERE Name IN :stateNames])
			       result.put(isoState.Name, isoState.Id);

		}
		return result;
	}

	public static Map<String, String> getGeoDetailsByCountry(Set<String> countryIds)
	{
		Map<String, String> result = new Map<String, String>();

		for(GDP_Geo_Detail__c geo : [SELECT ID, IATA_ISO_Country__c, Sub_Continent__c, System_ID__c FROM GDP_Geo_Detail__c WHERE IATA_ISO_Country__c IN :countryIds])
			result.put(geo.IATA_ISO_Country__c, geo.Id);


		return result;
	}

	/*public static List<String> getAMS_InspectionIdsByAccountIds(List<String> accountIds)
	{
		List<String> result = new List<String>();
		for(AMS_Inspection__c item:[SELECT Id FROM AMS_Inspection__c WHERE Account__c IN:accountIds])
			result.add(item.Id);

		return result;
	}*/

	public static List<String> getAMS_TerritoryIdsByAccountIds(List<String> accountIds)
	{
		List<String> result = new List<String>();
		for(AMS_Territory__c item:[SELECT Id FROM AMS_Territory__c WHERE Appointment__r.Account__c IN:accountIds])
		   result.add(item.Id);


		return result;
	}

	public static List<String> getAMS_AddressIdsByAccountIds(List<String> accountIds)
	{
		List<String> result = new List<String>();
		for(AMS_Address__c item:[SELECT Id FROM AMS_Address__c WHERE Account__c IN:accountIds])
			result.add(item.Id);

		return result;
	}

	public static List<String> getAMS_Agency_AffiliationIdsByAccountIds(List<String> accountIds)
	{
		List<String> result = new List<String>();
		for(AMS_Agency_Affiliation__c item:[SELECT Id FROM AMS_Agency_Affiliation__c WHERE Account__c IN:accountIds])
		    result.add(item.Id);

		return result;
	}

	public static List<String> getAMS_Account_RoleIdsByAccountIds(List<String> accountIds)
	{
		List<String> result = new List<String>();
		for(AMS_Account_Role__c item:[SELECT Id FROM AMS_Account_Role__c WHERE Account__c IN:accountIds])
		    result.add(item.Id);


		return result;
	}

	public static List<String> getAMS_Agency_AirportIdsByAccountIds(List<String> accountIds)
	{
		List<String> result = new List<String>();
		for(AMS_Agency_Airport__c item:[SELECT Id FROM AMS_Agency_Airport__c WHERE Account__c IN:accountIds])
		result.add(item.Id);


		return result;
	}

	public static List<String> getAMS_Agency_ProfileIdsByAccountIds(List<String> accountIds)
	{
		List<String> result = new List<String>();
		for(AMS_Agency_Profile__c item:[SELECT Id FROM AMS_Agency_Profile__c WHERE Account__c IN:accountIds])
		result.add(item.Id);

		return result;
	}


	//Ex CA=>1|514;450;819 ... will be an entry for Canada
	public static Map<String, String> getPhoneCodesByCountry()
	{
		Map<String, String> result = new Map<String, String>(); /*, Phone_Area_Codes__c*/
		for(IATA_ISO_Country__c c : [SELECT ISO_Code__c, International_dialing_code_ISD__c	 FROM IATA_ISO_Country__c ORDER BY Name])
		{ result.put(c.ISO_Code__c,c.International_dialing_code_ISD__c/*+':'+c.Phone_Area_Codes__c*/);}

		return result;
	}


	public static Map<String, String> getGDP_Products_Account_View_By_Account(Set<String> accountIds)
	{
		Map<String, String> result = new Map<String, String>();
		if(accountIds !=null && accountIds.size() >0)
		{
			for(GDP_Products_Account_View__c prod : [SELECT Id, AMS_GDP_Key__c FROM GDP_Products_Account_View__c WHERE AMS_GDP_Key__c IN :accountIds])
			result.put(prod.AMS_GDP_Key__c, prod.Id);
		}

		return result;
	}

	public static Map<String, String> getGDP_AddressByAccount(Set<String> accountIds)
	{
		Map<String, String> result = new Map<String, String>();
		for(GDP_Address__c item:[SELECT Id, Related_Account__c FROM GDP_Address__c WHERE Related_Account__c IN:accountIds AND Address_Type__c = 'Location' AND RecordType.Name='GDP'])
		{	result.put(item.Related_Account__c,item.Id);}

		return result;
	}

	public static Map<String, String> getGDP_PhoneByAccount(Set<String> accountIds)
	{
		Map<String, String> result = new Map<String, String>();
		for(GDP_Phone__c item:[SELECT Id, Related_Account__c FROM GDP_Phone__c WHERE Related_Account__c IN:accountIds AND Phone_Type__c='Phone 1' AND RecordType.Name='GDP'])
		{
			result.put(item.Related_Account__c,item.Id);
		}

		return result;
	}

	public static Map<String, String> getAccreditationByAccount(Set<String> accountIds)
	{
		Map<String, String> result = new Map<String, String>();
		for(Accreditation__c item:[SELECT Id, Related_Account__c FROM Accreditation__c WHERE Related_Account__c IN:accountIds AND RecordType.Name='GDP'])
		{
			result.put(item.Related_Account__c,item.Id);
		}

		return result;
	}

	public static Map<String, String> getAppointmentByAccount(Set<String> accountIds)
	{
		Map<String, String> result = new Map<String, String>();
		for(AMS_Inspection__c item:[SELECT Id, Account__c, Airline_Code__c FROM AMS_Inspection__c WHERE Account__c IN : accountIds])
		{
			result.put(item.Account__c,item.Airline_Code__c);
		}

		return result;
	}

	public static List<String> getAMS_Agency_AuthorizationByAccountIds(List<String> accountIds)
	{
		List<String> result = new List<String>();
		for(Agency_Authorization__c item:[SELECT Id, Account__c FROM Agency_Authorization__c WHERE Account__c IN:accountIds AND RecordType.Name='FormOfPayment'])
		{
			result.add(item.Id);
		}

		return result;
	}

	public static AMS_GDP_Batch__c getBatchInfo(String batchName)
	{
		List<AMS_GDP_Batch__c> batches =  [
			SELECT Id, Batch_Name__c, Last_Sync_End_Date__c, Last_Sync_Start_Date__c, Failed_Records__c FROM AMS_GDP_Batch__c WHERE Batch_Name__c = :batchName LIMIT 1
		];
		return (batches.size() >0)? batches[0] : null;
	}

	public static Map<String, GDP_Reference_Table__c> getGDPReferenceTableByCode(Set<String> codes)
	{
		Map<String, GDP_Reference_Table__c> result = new Map<String, GDP_Reference_Table__c>();

		for(GDP_Reference_Table__c tbl : [SELECT Id, Code__c FROM GDP_Reference_Table__c WHERE Code__c IN : codes])	result.put(tbl.Code__c, tbl);

		return result;
	}

	public static Map<String, GDP_Reference_Table__c> getGDPReferenceTableByCodeAndTable(Set<String> codes, String table)
	{
		Map<String, GDP_Reference_Table__c> result = new Map<String, GDP_Reference_Table__c>();

		for(GDP_Reference_Table__c tbl : [SELECT Id, Code__c, Table__c, Definition__c FROM GDP_Reference_Table__c WHERE Code__c IN : codes AND Table__c = :table])
			result.put(tbl.Code__c, tbl);

		return result;
	}


	// public static Map<String, GDP_Reference_Table__c> getGDPReferenceTablebyDefinitionAndTable(Set<String> definitions, String table)
	// {
	// 	Map<String, GDP_Reference_Table__c> result = new Map<String, GDP_Reference_Table__c>();
	//
	// 	for(GDP_Reference_Table__c tbl : [SELECT Id, Code__c, Table__c, Definition__c FROM GDP_Reference_Table__c WHERE Definition__c IN : definitions AND Table__c = :table])
	// 		result.put(tbl.Definition__c, tbl);
	//
	// 	return result;
	// }

	public static Map<String, GDP_Reference_Table__c> getGDPReferenceTablebyDescriptionAndTable(Set<String> names, String table)
	{
		Map<String, GDP_Reference_Table__c> result = new Map<String, GDP_Reference_Table__c>();

		for(GDP_Reference_Table__c tbl : [SELECT Id, Code__c, Table__c, Name FROM GDP_Reference_Table__c WHERE Name IN : names AND Table__c = :table])
			result.put(tbl.Name, tbl);

		return result;
	}

	// public static Map<String, GDP_Reference_Table__c> getGDPReferenceTablebyDefinitionAndTable(Set<String> definitions, String table, String sys)
	// {
	// 	Map<String, GDP_Reference_Table__c> result = new Map<String, GDP_Reference_Table__c>();
	//
	// 	for(GDP_Reference_Table__c tbl : [SELECT Id, Code__c, Table__c, Definition__c FROM GDP_Reference_Table__c WHERE Definition__c IN : definitions AND Table__c = :table AND System__c = :sys])
	// 		result.put(tbl.Definition__c, tbl);
	//
	// 	return result;
	// }

	public static Map<String, GDP_Reference_Table__c> getGDPReferenceTablebyDescriptionAndTable(Set<String> descriptions, String table, String sys)
	{
		Map<String, GDP_Reference_Table__c> result = new Map<String, GDP_Reference_Table__c>();

		for(GDP_Reference_Table__c tbl : [SELECT Id, Code__c, Table__c, Definition__c FROM GDP_Reference_Table__c WHERE Name IN : descriptions AND Table__c = :table AND System__c = :sys])
			result.put(tbl.Definition__c, tbl);

		return result;
	}


	public static Map<String,GDP_Reference_Table__c> getGDPReferenceTableByCodeandTable1(Set<String> codes)
	{
		Map<String,GDP_Reference_Table__c> result = new Map<String,GDP_Reference_Table__c>();

		for(GDP_Reference_Table__c table : [SELECT Id, Code__c, Table__c FROM GDP_Reference_Table__c WHERE Code__c IN : codes])
			result.put(table.Table__c+table.Code__c, table);

			return result;
	}

	public static Map<String, GDP_Agency_Profile_Specialization__c> getGDPbyAccount(Set<Id> accountsSet)
	{

		Map<String, GDP_Agency_Profile_Specialization__c> result= new Map<String, GDP_Agency_Profile_Specialization__c> ();

		for(GDP_Agency_Profile_Specialization__c gdprecord: [SELECT AMS_GDP_Key__c, Related_Account__c FROM GDP_Agency_Profile_Specialization__c WHERE Related_Account__c IN: accountsSet])
			result.put(gdprecord.Related_Account__c,gdprecord);


		return result;
	}
}