src/objects/Agents__c.object
<CustomObject>
    <description>Used for the automatic assignment of cases in SCE. Developed by Salesforce Professional Services.</description>
    <fields>
        <fullName>Logged_on__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the agent logged on?</inlineHelpText>
        <label>Logged on</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum_case_workload__c</fullName>
        <defaultValue>6</defaultValue>
        <inlineHelpText>Maximum number of cases for this user</inlineHelpText>
        <label>Maximum case workload</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agent</label>
    <nameField>
        <label>Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auto_Queue__c.object
<CustomObject>
    <description>Used for the automatic assignment of cases in SCE. Developed by Salesforce Professional Services.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Represents if the queue is active</description>
        <inlineHelpText>Is auto assignment currently active for this queue</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Auto Queue</label>
    <nameField>
        <label>Auto Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auto Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SalesforceSupportEmails__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Support members to receive error email messages</description>
    <fields>
        <fullName>Support_Email__c</fullName>
        <description>[Deprecated] - This field is not to be used.
To send emails use only - Support_User_Id__c</description>
        <label>Support Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Salesforce Support Emails</label>
</CustomObject>

src/objects/Skill__c.object
<CustomObject>
    <description>Used for the automatic assignment of cases in SCE. Developed by Salesforce Professional Services.</description>
    <fields>
        <fullName>Auto_queue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the parent Auto Queue</description>
        <label>Auto queue</label>
        <referenceTo>Auto_Queue__c</referenceTo>
        <relationshipLabel>Skills</relationshipLabel>
        <relationshipName>Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill_Types__c</fullName>
        <description>Id of the parent Skill Type</description>
        <label>Skill Types</label>
        <referenceTo>Skill_Types__c</referenceTo>
        <relationshipName>Skill</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Skill_Assignment__c.object
<CustomObject>
    <description>Used for the automatic assignment of cases in SCE. Developed by Salesforce Professional Services.</description>
    <fields>
        <fullName>Agents__c</fullName>
        <description>Related Agent</description>
        <label>Agents</label>
        <referenceTo>Agents__c</referenceTo>
        <relationshipName>R00NS0000000M2FWMA0</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Represents the priority of the skill. Can be '0', '1', '2', '3'</description>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <description>Related Skill</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Skills</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipName>R00NS0000000M2FPMA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skill Assignment</label>
    <nameField>
        <displayFormat>SA{0000000}</displayFormat>
        <label>Skill Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Skill_Types__c.object
<CustomObject>
    <description>Used for the automatic assignment of cases in SCE. Developed by Salesforce Professional Services.</description>
    <fields>
        <fullName>Case_Location__c</fullName>
        <label>Case Location</label>
        <length>225</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skill_Weight__c</fullName>
        <label>Skill Weight</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Skill Type</label>
    <nameField>
        <label>Skill Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Settings__c.object
<CustomObject>
    <description>Used for the automatic assignment of cases in SCE. Developed by Salesforce Professional Services.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Currently active settings - this will inactivate all other system setting options</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_on_Error__c</fullName>
        <description>Use this field to define the email addresses to which error messages generated by the IATA Auto Assignment should be sent.</description>
        <inlineHelpText>Use ; to separate the email addresses.</inlineHelpText>
        <label>Email on Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Progress_Case_Workload_Weighting__c</fullName>
        <label>In Progress Case Workload Weighting</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Case_Workload_Weighting__c</fullName>
        <label>Open Case Workload Weighting</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill_P1_Weighting__c</fullName>
        <label>Skill P1 Weighting</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill_P2_Weighting__c</fullName>
        <label>Skill P2 Weighting</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill_P3_Weighting__c</fullName>
        <label>Skill P3 Weighting</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Active__c</controllingField>
            <picklistValues>
                <fullName>On</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Workload_Weight__c</fullName>
        <label>Workload Weight</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>System Settings</label>
    <nameField>
        <label>System Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AutoAssignmentEngineSFTest.cls
@isTest
private class AutoAssignmentEngineSFTest {

    public static testmethod void test()
    {
    
        SalesforceSupportEmails__c supemails = new SalesforceSupportEmails__c(Name = 'SupUser', Support_Email__c=UserInfo.getUserEmail());
        insert supemails;
        
        System_Settings__c sysset = new System_Settings__c(Name='Europe', Active__c=true, Status__c= 'On', Workload_Weight__c=0.2,Skill_P3_Weighting__c=2.00, Skill_P2_Weighting__c=1.00, Skill_P1_Weighting__c=0.10, Open_Case_Workload_Weighting__c=1.00, In_Progress_Case_Workload_Weighting__c=0.25, Email_on_Error__c = 'test@org.com;test2@org.com');
        insert sysset;
        
        // Turn off all Auto Queues
        Auto_Queue__c[] aQueues=[select id, Active__c from Auto_Queue__c where Active__c=true];
        for (Auto_Queue__c aq:aQueues)
            aq.Active__c=false;
        update  aQueues;
        
        Group g= [select Id, Name from Group where Type = 'Queue' limit 1];
        Auto_Queue__c AQ=new Auto_Queue__c(Active__c=true);
        AQ.Name=g.Name;
        insert AQ;
        Case c=new Case(Subject='test 1', OwnerId=g.Id,Status='Open');
        insert c;
        
        List<Case> casesToAssign = AutoAssignmentEngineSF.getPendingCases();
       // system.assertEquals(casesToAssign.size(), 1);
        test.startTest();
        // 1) Log off all agents
        Agents__c[] aAgent=[select id, Logged_on__c from Agents__c];
        for (Agents__c a:aAgent)
            a.Logged_on__c=false;
        update aAgent;
        
        system.debug('RESULT ====>'+AutoAssignmentEngineSF.assignCase(c.id));
        Case assignCase = [SELECT Id, OwnerId From Case Where Id = :c.id limit 1];
        //No agents available so case should remain in queue
        system.assertEquals(assignCase.OwnerId, g.Id);
        
        // 2) Create an agent with 0 Max Workload
        Agents__c ag=new Agents__c(Logged_on__c =true,Name='Test',Maximum_case_workload__c=0,User__c=UserInfo.getUserId());
        insert ag;
        Case c1=new Case(Subject='test', OwnerId=UserInfo.getUserId(),Status='Open');
        Case c2=new Case(Subject='test', OwnerId=UserInfo.getUserId(),Status='In Progress');
        Case c3=new Case(Subject='', OwnerId=UserInfo.getUserId(),Status='In Progress');
        List<Case> cases = new List<Case>{c1,c2,c3};
        insert cases;
        
        // 3) Create Skills
        Skill_Types__c st=new Skill_Types__c(Name='Subject', Skill_Weight__c=1,Case_Location__c='Subject' );
        insert st;
        Skill__c s1=new Skill__c(Name='test', Skill_Types__c=st.id);
        insert s1;
        Skill__c  s2=new Skill__c(Name='test 1', Skill_Types__c=st.id);
        insert s2;
    
        // 4) Create Skill Assignment
        Skill_Assignment__c sa=new Skill_Assignment__c(Priority__c='1', Skills__c=s1.Id,Agents__c=ag.id); 
        insert sa;
        
        // Assign Case (Test Max workload limit)
        system.debug('RESULT ====>'+AutoAssignmentEngineSF.assignCase(c.id));
        assignCase = [SELECT Id, OwnerId From Case Where Id = :c.id limit 1];
        
        //Available agents are at max workload, so case remains in queue
        system.assertEquals(assignCase.OwnerId, g.Id);
        
        //5) Update agent Max Workload but not skill
        ag.Maximum_case_workload__c=10;
        update ag;
        
        system.debug('RESULT ====>'+AutoAssignmentEngineSF.assignCase(c.id));
        assignCase = [SELECT Id, OwnerId From Case Where Id = :c.id limit 1];
        
        //No agent has skills for this case. Case remains in queue.
        system.assertEquals(assignCase.OwnerId, g.Id);
        
        // Test with skills
        sa=new Skill_Assignment__c(Priority__c='1', Skills__c=s2.Id,Agents__c=ag.id); 
        insert sa;
        
        system.debug('RESULT ====>'+AutoAssignmentEngineSF.assignCase(c.id));
        assignCase = [SELECT Id, OwnerId From Case Where Id = :c.id limit 1];
        
        //Case assigned to user
        system.assertEquals(assignCase.OwnerId, UserInfo.getUserId());
        
        //--------------------
        // 6) Duplicate Case
        //--------------------
        c=new Case(Subject='test 1', OwnerId=g.Id,Status='Open');
        insert c;
        
        system.debug('RESULT ====>'+AutoAssignmentEngineSF.assignCase(c.id));
        assignCase = [SELECT Id, OwnerId From Case Where Id = :c.id limit 1];
        
        //duplicate case also gets assigned
        system.assertEquals(assignCase.OwnerId, UserInfo.getUserId());
        
        
        AutoAssignmentEngineSF batch = new AutoAssignmentEngineSF();
        Database.executeBatch(batch, 1);
        
        string jobId = System.schedule('AutoAssignmentEngineSchedulerTest',
               '0 0 0 15 3 ? 2022', 
        new AutoAssignmentEngineScheduler ());
        
                test.stopTest();

    }
    
}