src/objects/Agents__c.object
<CustomObject>
    <description>Used for the automatic assignment of cases in SCE. Developed by Salesforce Professional Services.</description>
    <fields>
        <fullName>Log_on_picklist__c</fullName>
        <label>Log on picklist</label>
        <picklist>
            <picklistValues>
                <fullName>Log on</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Logged_on__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the agent logged on?</inlineHelpText>
        <label>Logged on</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_next_case__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For the agent, indicates that the next case should be assigned to them</inlineHelpText>
        <label>Request next case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agent</label>
    <nameField>
        <label>Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill_Types__c.object
<CustomObject>
    <description>Used for the automatic assignment of cases in SCE. Developed by Salesforce Professional Services.</description>
    <fields>
        <fullName>Case_Location__c</fullName>
        <label>Case Location</label>
        <length>225</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Skill Type</label>
    <nameField>
        <label>Skill Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgentStatusExtensionTest.cls
@isTest
private class AgentStatusExtensionTest {

	@isTest
	static void test() {
		TestUtilities.setupDefaultSystemSettings();
		TestUtilities.setupSkillType('Priority', 'Priority');
		Skill_Types__c aSkillType = [Select name, Case_Location__c from Skill_Types__c where Case_Location__c = : 'Priority' and Name = : 'Priority' limit 1];
		TestUtilities.setupSkill(aSkillType.id, 'Low');

		// Create agent
		Agents__c agent = new Agents__c(Name = 'Test User', User__c = UserInfo.getUserId());
		insert agent;

		PageReference ref = new PageReference(Page.Agent_Status_Page.getUrl());
		Test.setCurrentPage(ref);
		AgentStatusExtension con = new AgentStatusExtension();
		system.assertEquals(con.save(), ref);

		con.agent.Request_next_case__c = true;
		con.save();

		con.agent.Log_on_picklist__c = 'Log on';
		con.save();
		system.assertEquals(con.agent.Logged_on__c, true);

		con.agent.Log_on_picklist__c = 'Log off';
		con.save();
		system.assertEquals(con.agent.Logged_on__c, false);
	}

}