src/objects/Agency_Applied_Change_code__c.object
<CustomObject>
    <fields>
        <fullName>Change_Code__c</fullName>
        <label>Change Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFN</fullName>
                </value>
                <value>
                    <fullName>BSF</fullName>
                </value>
                <value>
                    <fullName>BSP</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CAS</fullName>
                </value>
                <value>
                    <fullName>CCA</fullName>
                </value>
                <value>
                    <fullName>CCF</fullName>
                </value>
                <value>
                    <fullName>CCR</fullName>
                </value>
                <value>
                    <fullName>CHC</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
                <value>
                    <fullName>CHG</fullName>
                </value>
                <value>
                    <fullName>CHI</fullName>
                </value>
                <value>
                    <fullName>CHJ</fullName>
                </value>
                <value>
                    <fullName>CHL</fullName>
                </value>
                <value>
                    <fullName>CHM</fullName>
                </value>
                <value>
                    <fullName>CHN</fullName>
                </value>
                <value>
                    <fullName>CHO</fullName>
                </value>
                <value>
                    <fullName>CHS</fullName>
                </value>
                <value>
                    <fullName>CHV</fullName>
                </value>
                <value>
                    <fullName>CLF</fullName>
                </value>
                <value>
                    <fullName>CLI</fullName>
                </value>
                <value>
                    <fullName>CLO</fullName>
                </value>
                <value>
                    <fullName>CLR</fullName>
                </value>
                <value>
                    <fullName>CMF</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                </value>
                <value>
                    <fullName>COR</fullName>
                </value>
                <value>
                    <fullName>CSF</fullName>
                </value>
                <value>
                    <fullName>CWD</fullName>
                </value>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>DFE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IEPPayload__c</fullName>
        <formula>IF(OR(Account__r.ANG_IEP_Status_FF__c = &apos;No IEP Account&apos;, ISBLANK(Account__r.ANG_IEP_Status_FF__c)) , null, 
IF(AND(ISPICKVAL(Change_Code__c,&apos;IEP&apos;),OR(ISPICKVAL(Account__r.Location_Type__c,&apos;HO&apos;),ISPICKVAL(Account__r.Location_Type__c,&apos;AO&apos;),ISPICKVAL(Account__r.Location_Type__c,&apos;HE&apos;))),Account__r.IATACode__c,IF(AND(ISPICKVAL(Change_Code__c,&apos;FIN&apos;),NOT(OR(ISPICKVAL(Account__r.Location_Type__c,&apos;HO&apos;),ISPICKVAL(Account__r.Location_Type__c,&apos;AO&apos;),ISPICKVAL(Account__r.Location_Type__c,&apos;HE&apos;)))),Account__r.IATACode__c,IF(NOT(OR(ISPICKVAL(Change_Code__c,&apos;FIN&apos;),ISPICKVAL(Change_Code__c , &apos;IEP&apos;))),Account__r.IATACode__c,null))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IEPPayload</label>
        <type>Text</type>
    </fields>
    <label>Agency Applied Change code</label>
    <nameField>
        <displayFormat>AACC-{000000}</displayFormat>
        <label>Change code details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agencies Applied Change codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ANG_CalloutMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Newgen ISS Callout Mapping</description>
    <fields>
        <fullName>CalloutClass__c</fullName>
        <description>Callout Class Implementation</description>
        <label>Callout Class</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Code__c</fullName>
        <label>Change_Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Newgen ISS Callout Mapping</label>
</CustomObject>

src/classes/ANG_IEP_CalloutHelper.cls
public  with sharing class ANG_IEP_CalloutHelper {
	
	public static final Integer STATUSOKLOWER  = 199;
	public static final Integer STATUSOKHIGHER = 300;

    @InvocableMethod(label='Create a payload to be sent to mulesoft' description='Create a payload to be sent to mulesoft')
    public static void invokeCustomImpl(List<Agency_Applied_Change_code__c> objList) {

		List<ANG_CalloutMapping__c> calloutMappingList = ANG_CalloutMapping__c.getall().values();

		Map<String,ANG_CalloutMapping__c> changeCodeList = new Map<String,ANG_CalloutMapping__c>();

		for(ANG_CalloutMapping__c item: calloutMappingList){
			for(Agency_Applied_Change_code__c obj: objList)
				if(item.Change_code__c == obj.Change_Code__c && obj.IEPPayload__c != null)
					changeCodeList.put(obj.IEPPayload__c ,item);
		}


		System.debug('Custom Setting values:' + changeCodeList);

		Set<String> changeCodesIATACodes = changeCodeList.keySet();

		for(String item: changeCodesIATACodes){

			invokeChangeCodeImpl(changeCodeList.get(item),item);

		}
		
	}


	public static void invokeChangeCodeImpl(ANG_CalloutMapping__c calloutMapping, Object obj){

		// Get the Type corresponding to the class name
		Type t = Type.forName(calloutMapping.CalloutClass__c);

		ANG_CalloutHelperInt callout = (ANG_CalloutHelperInt)t.newInstance();

		callout.doCallOut(obj, calloutMapping);
	}

}