src/objects/Amazon_Cred__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Dev_Configuration__c</fullName>
        <label>Dev Configuration</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prod_Configuration__c</fullName>
        <label>Prod Configuration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Amazon Cred</label>
</CustomObject>

src/objects/AWSKey__c.object
<CustomObject>
    <description>Store keys used to communicate with Amazon Web Services</description>
    <fields>
        <fullName>AWS_ENDPOINT_URL__c</fullName>
        <defaultValue>&quot;http://s3.awsamazon.com&quot;</defaultValue>
        <description>Specific endpoint url to use to connect stored in this bucket/crednetials</description>
        <label>AWS EndPoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>Define the bucket to use with this credential key</description>
        <externalId>true</externalId>
        <inlineHelpText>Define the bucket to use with this credential key</inlineHelpText>
        <label>Bucket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAS_Access_Point__c</fullName>
        <inlineHelpText>URL access point as http(s)://IP:PORT</inlineHelpText>
        <label>IAS Access Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAS_configuration_name__c</fullName>
        <defaultValue>&quot;iata.ini&quot;</defaultValue>
        <inlineHelpText>enter the nameof IAS configuratuon file to load for this access</inlineHelpText>
        <label>IAS configuration name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>AWS Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Assessment_Result__c.object
<CustomObject>
    <description>This object was created to contain the financial assessment results provided by CMC (IATA Financial Assessment Portal project)</description>
    <label>Financial Assessment Result</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Assessment Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AmazonResultsCtrlTest.cls
@IsTest
public class AmazonResultsCtrlTest {

	public  static void loadCredentials() {
				IfapToolManagerTest.beforeTest();

		Amazon_Cred__c Amazon_Cred =  new Amazon_Cred__c(name = 'IFAP', Prod_Configuration__c = 'adevconf' , Dev_Configuration__c = 'adevconf');
		insert Amazon_Cred;

		list<AWSKey__c> AWS_KEYs = new list<AWSKey__c>{
			new AWSKey__c(
				name = 'adevconf',
				Key__c = 'asd',
				Secret__c = 'asd',
				IAS_configuration_name__c = 'asdas',
				IAS_Access_Point__c = 'asd',
				Bucket__c = 'asd',
				AWS_ENDPOINT_URL__c = 'asd')
		};
		insert AWS_KEYs;
	}

	private static testMethod void testControllerError() {

		Case cse = new Case();

		Test.startTest();
		try {
			ApexPages.StandardController stdController = new ApexPages.StandardController(cse);
			AmazonResultsCtrl controller = new AmazonResultsCtrl(stdController);
			System.assert(false, 'should throw a transformationException ');

		} catch ( Exception e) {
			System.assert(true, 'should throw a transformationException ');
		}
		Test.stopTest();
	}

	private static testMethod void testControllerCaseNotArchived() {

		loadCredentials();

		Case cse = new Case();
		insert cse;

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(cse);
		AmazonResultsCtrl controller = new AmazonResultsCtrl(stdController);
		Test.stopTest();
	}

	private static testMethod void testControllerCaseArchived_Ok() {
		loadCredentials();

		Case cse = new Case();
		cse.Financial_Results_Archived_Date__c = Date.today();
		insert cse;

		ENZ__FTPAttachment__c attach = new ENZ__FTPAttachment__c(
			Financial_Assessment_Result__c = cse.Id
		);

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(cse);
		AmazonResultsCtrl controller = new AmazonResultsCtrl(stdController);
		AmazonResultsCtrl.getExpiringLinkIfap('/test/path/filename');
		System.assert(true,controller.docs.size() > 0);
		Test.stopTest();
	}

}