src/objects/Amazon_Cred__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Dev_Configuration__c</fullName>
        <label>Dev Configuration</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prod_Configuration__c</fullName>
        <label>Prod Configuration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Amazon Cred</label>
</CustomObject>

src/objects/AWSKey__c.object
<CustomObject>
    <description>Store keys used to communicate with Amazon Web Services</description>
    <fields>
        <fullName>AWS_ENDPOINT_URL__c</fullName>
        <defaultValue>&quot;http://s3.awsamazon.com&quot;</defaultValue>
        <description>Specific endpoint url to use to connect stored in this bucket/crednetials</description>
        <label>AWS EndPoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>Define the bucket to use with this credential key</description>
        <externalId>true</externalId>
        <inlineHelpText>Define the bucket to use with this credential key</inlineHelpText>
        <label>Bucket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAS_Access_Point__c</fullName>
        <inlineHelpText>URL access point as http(s)://IP:PORT</inlineHelpText>
        <label>IAS Access Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IAS_configuration_name__c</fullName>
        <defaultValue>&quot;iata.ini&quot;</defaultValue>
        <inlineHelpText>enter the nameof IAS configuratuon file to load for this access</inlineHelpText>
        <label>IAS configuration name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>AWS Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AcliJavaToolTest.cls
@isTest
private class AcliJavaToolTest {

	static void loadData() {
		Amazon_Cred__c Amazon_Cred =  new Amazon_Cred__c(name = 'ACLI', Prod_Configuration__c = 'aprodconf' , Dev_Configuration__c = 'adevconf');
		insert Amazon_Cred;

		list<AWSKey__c> AWS_KEYs = new list<AWSKey__c>{
			new AWSKey__c(name = 'aprodconf',
				Key__c = 'asd',
				Secret__c = 'asd',
				IAS_configuration_name__c = 'asdas',
				IAS_Access_Point__c = 'asd',
				Bucket__c = 'asd',
				AWS_ENDPOINT_URL__c = 'asd'),
			new AWSKey__c(name = 'adevconf' ,
				Key__c = 'asd',
				Secret__c = 'asd',
				IAS_configuration_name__c = 'asdas',
				IAS_Access_Point__c = 'asd',
				Bucket__c = 'asd',
				AWS_ENDPOINT_URL__c = 'asd')
		};

		insert AWS_KEYs;
	}

	static testMethod void testGetFile_Error() {
		loadData();

		Test.StartTest();
		AcliJavaTool.Response response = AcliJavaTool.getFile();
		String responseStr = response.toString();
		Test.StopTest();

		System.assert(response.success == false);
		System.assert(responseStr.startsWith('ERROR'));
	}

	static testMethod void testGetFile_Success() {
		loadData();

		String testResponse = '{"success":true,"content":"file content","code":"","message":""}';

		Test.StartTest();
		AcliJavaTool.testJsonResults = testResponse;
		AcliJavaTool.Response response = AcliJavaTool.getFile();
		String responseStr = response.toString();
		Test.StopTest();

		System.assert(response.success == true);
		System.assert(response.content == 'file content');
		System.assert(responseStr.startsWith('SUCCESS'));
	}

	static testMethod void testDeleteFile_Error() {
		loadData();

		Test.StartTest();
		AcliJavaTool.Response response = AcliJavaTool.deleteFile();
		String responseStr = response.toString();
		Test.StopTest();

		System.assert(response.success == false);
		System.assert(responseStr.startsWith('ERROR'));
	}

	static testMethod void testDeleteFile_Success() {
		loadData();

		String testResponse = '{"success":true,"content":"","code":"","message":""}';

		Test.StartTest();
		AcliJavaTool.testJsonResults = testResponse;
		AcliJavaTool.Response response = AcliJavaTool.deleteFile();
		String responseStr = response.toString();
		Test.StopTest();

		System.assert(response.success == true);
		System.assert(responseStr.startsWith('SUCCESS'));
	}

}