src/objects/AMS_Accreditation_Contact__c.object
<CustomObject>
    <description>Used to capture Agency contacts listed in the online Accreditation application process</description>
    <fields>
        <fullName>AMS_Pax_Accreditation_Form__c</fullName>
        <label>AMS Online Accreditation Form</label>
        <referenceTo>AMS_Pax_Accreditation_Form__c</referenceTo>
        <relationshipLabel>Agency Contacts &amp; Stakeholders</relationshipLabel>
        <relationshipName>AMS_Accreditation_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AMS Accreditation Contact</label>
    <nameField>
        <label>AMS Accreditation Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AMS Accreditation Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AMS_Pax_Accreditation_Form__c.object
<CustomObject>
    <description>Capture PAX &amp; Cargo accreditation application details from the CS Portal.</description>
    <label>AMS Online Accreditation</label>
    <nameField>
        <displayFormat>AMS-ACCREDIT-{000000}</displayFormat>
        <label>Pax Accreditation Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Online Accreditations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.history/src/classes/ANG_AnnualRevRoHelper_20180507102552.cls
public with sharing class ANG_AnnualRevRoHelper {
	public ANG_AnnualRevRoCurrentAccount ca {get; set;}
	public AMS_Pax_Accreditation_Form__c newForm {
		get {return this.ca.fw.newForm;}
		set;
	}
	public Account currentAccount {
		get {return this.ca.account;}
		set;
	}


	public ANG_AnnualRevRoHelper(ANG_AnnualRevRoCurrentAccount ca) {
		this.ca = ca;
	}


	public List<AMS_Accreditation_Contact__c> getPreviousOwners() {
		return this.ca.fw.previousOwners;
	}

	public List<AMS_Accreditation_Contact__c> getCurrentOwners() {
		return this.ca.fw.currentOwners;
	}

	public List<AMS_Accreditation_Contact__c> getPreviousCompanies() {
		return this.ca.fw.previousCompanies;
	}

	public List<AMS_Accreditation_Contact__c> getCurrentCompanies() {
		return this.ca.fw.currentCompanies;
	}
}