src/objects/AMS_Settlement_System__c.object
<CustomObject>
    <label>ISS Operation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ISS Operations</pluralLabel>
    <recordTypes>
        <fullName>BSP</fullName>
        <active>true</active>
        <label>BSP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ANG_BSP_Attributes__c.object
<CustomObject>
    <description>Object that stores the possible remittance frequency options for each Location Class by IATA ISO Country</description>
    <fields>
        <fullName>Amount_At_Risk_From_USD__c</fullName>
        <description>Amount at risk: FROM threshold. Used to determine in which tier the agency fall</description>
        <label>Amount At Risk - From (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_At_Risk_Multiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <description>In the formula used to calculate RHC, it indicates How many time the Amount At Risk should be multiplied</description>
        <inlineHelpText>In the formula used to calculate RHC, it indicates How many time the Amount At Risk should be multiplied. Default value: 1</inlineHelpText>
        <label>Amount At Risk Multiplier</label>
        <precision>10</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_At_Risk_To_USD__c</fullName>
        <description>Amount at risk: TO threshold. Used to determine in which tier the agency fall</description>
        <label>Amount At Risk - To (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BSP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BSP</label>
        <referenceTo>AMS_Settlement_System__c</referenceTo>
        <relationshipLabel>BSP Attributes</relationshipLabel>
        <relationshipName>BSP_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class_Type__c</fullName>
        <description>Location Class of the Account</description>
        <inlineHelpText>C-Cargo
D-Domestic
E-External Registrars
G-General Sales Agents
K-CATO
M-Members &amp; Airlines Sales Offices
N-NISI
O-SATO
P-Passenger
S-SSI
T-TIDS
V-Travel Service Intermediaries-TSI (USA Only) 
X-Handling Agents and Shipping Lines
J-Joint Vent</inlineHelpText>
        <label>Class Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>K</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>Q</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FS_Percentage__c</fullName>
        <description>Percentage of Financial Security</description>
        <label>% of Financial Security</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ISO_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISO State</label>
        <referenceTo>IATA_ISO_State__c</referenceTo>
        <relationshipLabel>BSP Attributes</relationshipLabel>
        <relationshipName>BSP_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Limit_Cash_Condition__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has Limit Cash Condition?</description>
        <label>Limit Cash Condition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_FA_Points__c</fullName>
        <description>Max Financial Assessment Points</description>
        <label>Max FA Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_FA_Points__c</fullName>
        <label>Min FA Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup field to theh BSP Attribute field (AMS Operation Code)</description>
        <label>Operation</label>
        <referenceTo>AMS_Operation__c</referenceTo>
        <relationshipLabel>BSP Attributes</relationshipLabel>
        <relationshipName>BSP_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RHC_Amnt_Calc_Type__c</fullName>
        <description>Remittance Holding Capacity Amount Calculation Type</description>
        <label>RHC Amount Calculation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Fixed Percentage</fullName>
                </value>
                <value>
                    <fullName>Tier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remittance_Frequency__c</fullName>
        <description>Account&apos;s Remittance Frequency</description>
        <label>Remittance Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Remittance_Frequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remittances_Per_Year__c</fullName>
        <description>Number of remittances per year to compute the most frequence value.</description>
        <formula>IF(BSP__r.Name &lt;&gt; &apos;BSP-CN&apos;, 

CASE( (TEXT(Remittance_Frequency__c)) , 

&apos;M&apos; , 12, 
&apos;F&apos; , 24, 
&apos;R&apos; , 48, 
&apos;V&apos; , 52, 
&apos;S&apos; , 73, 
&apos;B&apos; , 96, 
&apos;T&apos;, 105,
&apos;W&apos; , 48, 
&apos;D&apos; , 0, 
0) 

, CASE( (TEXT(Remittance_Frequency__c)), 
&apos;M&apos; , 12, 
&apos;F&apos; , 24, 
&apos;R&apos; , 48, 
&apos;V&apos; , 52, 
&apos;S&apos; , 73, 
&apos;B&apos; , 96,
&apos;T&apos;, 105, 
&apos;W&apos; , 48, 
&apos;D&apos;, 300, 
0) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remittances Per Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Risk_Status__c</fullName>
        <label>Risk Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ANG_Risk_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier_RHC_Formula_Deduct_USD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used in Tier RHC: Indicates the amount to deduct from the formula</description>
        <inlineHelpText>Used in Tier RHC: Indicates the amount to deduct from the formula. Default value: 0</inlineHelpText>
        <label>Tier RHC Formula. Deduct (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tier_RHC_Formula_TopUp_USD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used in Tier RHC: Indicates the amount to add to the formula</description>
        <inlineHelpText>Used in Tier RHC: Indicates the amount to add to the formula. Default value: 0</inlineHelpText>
        <label>Tier RHC Formula TopUp (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tier_RHC_Formula__c</fullName>
        <formula>IF(text(RHC_Amnt_Calc_Type__c)=&apos;Tier&apos;,
  IF(Tier_RHC_Formula_TopUp_USD__c&gt;0, text(Tier_RHC_Formula_TopUp_USD__c) &amp; &apos; + &apos;, &apos;&apos;)
  &amp; text(Amount_At_Risk_Multiplier__c)
  &amp; &apos; x ( [Amount At Risk]&apos; 
  &amp; IF(Tier_RHC_Formula_Deduct_USD__c &gt;0, &apos; - &apos; &amp; text(Tier_RHC_Formula_Deduct_USD__c), &apos;&apos;)
  &amp; &apos; )&apos;
,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tier RHC Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>The tier used in tiered RHC calculation</description>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <description>Unique identifier on the object to ensure no duplicates.</description>
        <externalId>true</externalId>
        <label>UniqueKey</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>BSP Attributes</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSP Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/ANG_Remittance_Frequency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Fortnightly</fullName>
    </customValue>
    <customValue>
        <fullName>Every 10 days</fullName>
    </customValue>
    <customValue>
        <fullName>4 times per month</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Every 3 days</fullName>
    </customValue>
    <customValue>
        <fullName>Every 5 days</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Daily (China)</fullName>
    </customValue>
    <masterLabel>Remittance Frequency</masterLabel>
</GlobalValueSet>

src/globalValueSets/ANG_Risk_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <masterLabel>Risk Status</masterLabel>
</GlobalValueSet>

src/classes/BSPAttributesSingleton.cls
/**
 * Singleton class that contains BSP Attributes
 */
public class BSPAttributesSingleton {
	// private static variable referencing the class
	private static BSPAttributesSingleton instance = null;
	// variable that contains the list of Attributes for each BSP required
	private Map<id, Map<String, ANG_BSP_Attributes__c>> BSPAttributes;

	/**
	 * Private constructor
	 * @return
	 */
	private BSPAttributesSingleton(set<id> setBSPId, set<string> setRTNames){
		BSPAttributes = new map<id, Map<String, ANG_BSP_Attributes__c>>();

		string sQuery = 'select id, recordtype.DeveloperName, FS_Percentage__c, Amount_At_Risk_From_USD__c, Amount_At_Risk_Multiplier__c, Amount_At_Risk_To_USD__c' +
						'  , BSP__c, Class_Type__c, ISO_State__c, Limit_Cash_Condition__c, Max_FA_Points__c, Min_FA_Points__c, Operation__c, Remittance_Frequency__c' +
						'  , Remittances_Per_Year__c, RHC_Amnt_Calc_Type__c, Risk_Status__c, Tier__c, Tier_RHC_Formula__c, Tier_RHC_Formula_Deduct_USD__c, Tier_RHC_Formula_TopUp_USD__c, UniqueKey__c ' +
						'  , bsp__r.name	 ' +
						'  from ANG_BSP_Attributes__c';
						
		if(setBSPId!=null && setRTNames!=null)
			sQuery += ' where BSP__c IN :setBSPId and recordtype.developername IN :setRTNames';
		else{
			if(setBSPId!=null)
				sQuery += ' where BSP__c IN :setBSPId';
			if(setRTNames!=null)
				sQuery += ' where recordtype.developername IN :setRTNames';
		}

		for(ANG_BSP_Attributes__c attr : database.query(sQuery)){
			// checks if the BSP is already mapped
			if(!BSPAttributes.containsKey(attr.BSP__c)){
				// puts a new entry for the BSP and instantiates the map that will contain the corresponding attributes records
				BSPAttributes.put(attr.BSP__c, new Map<String, ANG_BSP_Attributes__c>());
			}
			// fills the maps of the attributes per BSP
			BSPAttributes.get(attr.BSP__c).put(attr.UniqueKey__c, attr);
		}
	}

	/**
	 * Method that returns the instance of BSPAttributesSingleton
	 * @param setBSPId is the set of BSP Ids for which is required to get the attributes
	 * @param setRecordtypes is the set of recordtypes (developername) of the attributed to retrieve
	 * @return instance of the singleton matching the BSP and Recordtypes received in input
	 */
	public static BSPAttributesSingleton getInstance(set<id> setBSPId, set<string> setRTNames){
		if(instance == null) instance = new BSPAttributesSingleton(setBSPId, setRTNames);
		return instance;
	}

	/**
	 * Method that returns the instance of BSPAttributesSingleton
	 * @return instance of the singleton with all BSP and all Recordtypes. Note that this can retrieve thousands of records
	 */
	public static BSPAttributesSingleton getInstance(){
		if(instance == null) instance = new BSPAttributesSingleton(null, null);
		return instance;
	}

	/**
	 * Method that returns the instance of BSPAttributesSingleton
	 * @param setBSPId is the set of BSP Ids for which is required to get the attributes
	 * @return instance of the singleton matching the BSPIds received. All Recordtypes are returned
	 */
	public static BSPAttributesSingleton getInstance(set<id> setBSPId){
		if(instance == null) instance = new BSPAttributesSingleton(setBSPId, null);
		return instance;
	}

	/**
	 * Method that returns the record type object
	 * @param BSPId the ID of the BSP
	 * @param AttrUniqueId 	  the unique ID of the attribute to get
	 * @return 		the full ANG_BSP_Attributes__c record
	 */
	public ANG_BSP_Attributes__c getSingleBSPAttributeByUniqueId(id BSPId, String AttrUniqueId){
		if(!BSPAttributes.containsKey(BSPId)) return null;

		return BSPAttributes.get(BSPId).get(AttrUniqueId);
	}

	/**
	 * Method that returns a list of attributes for a specified BSP
	 * @param  BSPId the ID of the BSP
	 * @return       the list of ANG_BSP_Attributes__c for the passed BSP
	 */
	public List<ANG_BSP_Attributes__c> getAllBSPAttributes(id BSPId){
		if(!BSPAttributes.containsKey(BSPId)) return new List<ANG_BSP_Attributes__c>();

		return BSPAttributes.get(BSPId).values();
	}

	/**
	 * Method that returns a list of attributes for a specified BSP matching a specific recortype requested
	 * @param  BSPId the ID of the BSP
	 * @param  RTNames the Names of the recordtype to retrieve
	 * @return       the list of ANG_BSP_Attributes__c for the passed BSP mathching the RTs received
	 */
	public List<ANG_BSP_Attributes__c> getAllBSPAttributesByRecordtype(id BSPId, set<string> RTNames){
		list<ANG_BSP_Attributes__c> lsToReturn = new list<ANG_BSP_Attributes__c>();
		if(!BSPAttributes.containsKey(BSPId)) return lsToReturn;

		for(ANG_BSP_Attributes__c attr:BSPAttributes.get(BSPId).values()){
			if(RTNames.contains(attr.recordtype.developername))
				lsToReturn.add(attr);
		}
		return lsToReturn;
	}

	/**
	 * Method that returns the map of attributes (where the index is the UniqueKey of the record)
	 * @param  BSPId the ID of the BSP
	 * @return       the map of attributes
	 */
	public map<string, ANG_BSP_Attributes__c> getFullBSPMap(id BSPId){
		if(BSPAttributes.containsKey(BSPId)) return BSPAttributes.get(BSPId);
		else return new map<string, ANG_BSP_Attributes__c>();
	}
}