src/objects/AMS_Accreditation_Country_CheckList__c.object
<CustomObject>
    <description>Used to display Country HO &amp; Branch requirements for the online accreditation application process</description>
    <fields>
        <fullName>IATA_ISO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related ISO Country</description>
        <label>IATA ISO Country</label>
        <referenceTo>IATA_ISO_Country__c</referenceTo>
        <relationshipLabel>AMS Accreditation Country Checklists</relationshipLabel>
        <relationshipName>AMS_Accreditation_Country_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>Values must correspond to Sector on Account</description>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Travel Agent</fullName>
                </value>
                <value>
                    <fullName>Cargo Agent</fullName>
                </value>
                <value>
                    <fullName>Travel Agent - International</fullName>
                </value>
                <value>
                    <fullName>Travel Agent - Domestic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AMS Accreditation Country Checklist</label>
    <nameField>
        <displayFormat>AMS-CHECKLIST-{0000}</displayFormat>
        <label>AMS Accreditation Country Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Accreditation Country Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMS_Accreditation_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>AMS_Accreditation_Country_CheckList__c</fullName>
        <label>AMS Accreditation Country Requirement</label>
        <referenceTo>AMS_Accreditation_Country_CheckList__c</referenceTo>
        <relationshipLabel>Accreditation Requirements</relationshipLabel>
        <relationshipName>AMS_Accreditation_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AMS Accreditation Requirement</label>
    <nameField>
        <label>AMS Accreditation Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AMS Accreditation Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IATA_ISO_Country__c.object
<CustomObject>
    <description>Contain a list of countries with their ISO country code and their Region</description>
    <label>IATA ISO Country</label>
    <nameField>
        <label>ISO Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IATA ISO Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ISSP_ModelA_Onboarding.cls
public with sharing class ISSP_ModelA_Onboarding {
	
	public Case onBoardingOSCARCase {get; private set;}
	public AMS_Accreditation_Country_CheckList__c countryChecklist {get; private set;}
	public List<AMS_Accreditation_Requirement__c> countryRequirementsList {get; private set;}

	public ISSP_ModelA_Onboarding() {
		fetchOnBoardingOSCARCase();
		fetchCountryRequirementsList();
	}

	private void fetchOnBoardingOSCARCase() {
		if (ApexPages.currentPage().getParameters().containsKey('caseId')) {
			this.onBoardingOSCARCase = [SELECT Id, BSPCountry__c FROM Case WHERE Id = :ApexPages.currentPage().getParameters().get('caseId')];
		}
	}

	private void fetchCountryRequirementsList() {
		if (this.onBoardingOSCARCase != null) {
			//ONLY ONE CHCKLIST FOR TRAVEL AGENT??
			this.countryChecklist = [SELECT Id, IATA_ISO_Country__c FROM AMS_Accreditation_Country_CheckList__c WHERE IATA_ISO_Country__c = :this.onBoardingOSCARCase.BSPCountry__c AND Operation__c = 'Travel Agent'];
			if (this.countryChecklist != null) {
				this.countryRequirementsList = [SELECT Id FROM AMS_Accreditation_Requirement__c WHERE AMS_Accreditation_Requirement__c = this.countryChecklist.Id];
			}
		}
	}
}