src/objects/AMS_Agencies_relationhip__c.object
<CustomObject>
    <label>AMS Agencies relationship</label>
    <nameField>
        <displayFormat>AAR-{0000000}</displayFormat>
        <label>AMS Agencies parentship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMS Agencies relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Connected_App_Roles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting defines the list of user roles that are available for each connected app: to be used on the Identity Community</description>
    <fields>
        <fullName>Connected_App__c</fullName>
        <label>Connected App SSO Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Default_User_Role__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default user Role to be used on the portal. Role assigned by default to be stored in the Portal Service Access Object</description>
        <label>Default User Role</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>TextArea</type>
    </fields>
    <label>Connected App Roles</label>
</CustomObject>

src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ANG_Portal_Service_Role__c</fullName>
        <description>Selected service portal role</description>
        <label>Portal Service Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Contact__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <formula>Contact__r.Account.ParentId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ANG_ISSP_IEPMailRecipientsUtils.cls
public class ANG_ISSP_IEPMailRecipientsUtils {

	// NOTE: The set accountIDs needs the 15 digit ids.
	// Returns Users by account.
	public static Map<String, Set<Id>> getRecipients(Set<Id> accountIDs, Set<String> roles) {
		return getRecipients(accountIDs, roles, null, 'A');
	}

	public static Map<String, Set<Id>> getRecipientsPortalServices(Set<Id> accountIDs, Set<String> portalServices) {
		return getRecipients(accountIDs, null, portalServices, 'B');
	}

	public static Map<String, Set<Id>> getRecipientsPortalServices(Set<Id> accountIDs, Set<Id> portalServices) {
		Set <String> portalServicesIdsStringSet = (Set <String>)JSON.deserialize(JSON.serialize(portalServices), Set <String>.class);
		return getRecipients(accountIDs, null, portalServicesIdsStringSet, 'C');
	}

	public static Map<String, Set<Id>> getRecipients(Set<Id> accountIDs, Set<String> roles, Set<String> portalServices, String type) {
		Map<Id, String> topParents = new Map<Id, String>();

		Map<Id, List<AMS_Agencies_relationhip__c>> hier = AMS_HierarchyHelper.getAccountsHierarchies(accountIDs);

		Set<id> accountIDsSet = new Set<id>();

		for(String accountId : accountIDs) {
			List<AMS_Agencies_relationhip__c> amsl = hier.get(accountId);
			accountIDsSet.add(accountId);
			topParents.put(accountId, String.valueOf(accountId).substring(0, 15));

			for (AMS_Agencies_relationhip__c ams : amsl) {
				if(ams.Child_Account__c != null) {
					accountIDsSet.add(ams.Child_Account__c);
					topParents.put(ams.Child_Account__c, String.valueOf(accountId).substring(0, 15));
				}
				if(ams.Parent_Account__c != null) {
					accountIDsSet.add(ams.Parent_Account__c);
					topParents.put(ams.Parent_Account__c, String.valueOf(accountId).substring(0, 15));
				}
			}
		}

		List<Portal_Application_Right__c> parList2;

		if(type == 'A') {
			parList2 = [Select Account__c,
							   Contact__c
						  From Portal_Application_Right__c
						 Where ANG_Portal_Service_Role__c in : roles
						   And right__c = 'Access Granted'
						   And contact__r.accountId in : accountIDsSet
						   And contact__r.isEmailBounced = false];
		} else if (type == 'C') {
			parList2 = [Select Account__c,
							   Contact__c
						  From Portal_Application_Right__c
						 Where Portal_Application__c in : portalServices
						   And right__c = 'Access Granted'
						   And contact__r.accountId in : accountIDsSet
						   And contact__r.isEmailBounced = false];
		} else {
			parList2 = [Select Account__c,
							   Contact__c
						  From Portal_Application_Right__c
						 Where Portal_Application__r.name in : portalServices
						   And right__c = 'Access Granted'
						   And contact__r.accountId in : accountIDsSet
						   And contact__r.isEmailBounced = false];
		}

		// Set with all contacts per account
		Map<Id, Set<Id>> IEP_accountIDs = new Map<Id, Set<Id>>();

		for(Portal_Application_Right__c p : parList2) {
			Set<ID> contactIDs = IEP_accountIDs.get(p.Account__c);
			if(null == contactIDs)
				contactIDs = new Set<ID>();
			contactIDs.add(p.Contact__c);
			IEP_accountIDs.put(p.Account__c, contactIDs);
		}

		// Get the users by account
		Map<String, Set<Id>> accIdToUserIdMapIep = new map<String, Set<ID>>();

		for(Id key : IEP_accountIDs.keySet()) {
			Set<Id> userIDsAux = new Set<id>();

			if(type == 'A') {
				userIDsAux.addAll(PortalServiceAccessTriggerHandler.getPortalIepUsers(IEP_accountIDs.get(key)));
			} else {
				// In type B We get the contacts instead of the users
				userIDsAux.addAll(IEP_accountIDs.get(key));
			}

			Set<Id> userIDs = accIdToUserIdMapIep.get(topParents.get(key));

			if(null == userIDs)
				userIDs = new Set<ID>();

			userIDs.addAll(userIDsAux);

			accIdToUserIdMapIep.put(topParents.get(key), userIDs);
		}

		return accIdToUserIdMapIep;
	}

	public enum IEPRoleEnum {
		DEFAULT_USER_ROLE,
		MANAGE_USER_ACCESS
	}

	public static Set<String> getIEPDefaultRoles() {
		return dynamicIEPRoles(IEPRoleEnum.DEFAULT_USER_ROLE);
	}

	public static Set<String> getIEPRolesManageUserAccess() {
		return dynamicIEPRoles(IEPRoleEnum.MANAGE_USER_ACCESS);
	}

	private static Set<String> dynamicIEPRoles(IEPRoleEnum paramCode) {
		Set<String> iepVendors = AMS_Utils.IEP_VENDORS;

		String query = 'SELECT Role__c FROM Connected_App_Roles__c WHERE Connected_App__c IN :iepVendors ';

		switch on paramCode {
			when DEFAULT_USER_ROLE {
				query += 'AND Default_User_Role__c = true';
			}

			when MANAGE_USER_ACCESS {
				query += 'AND Manage_User_Access__c = true';
			}
		}

		Set<String> roles = new Set<String>();

		for(Connected_App_Roles__c r: Database.query(query)) {
			roles.add(r.Role__c);
		}

		return roles;
	}
}