src/objects/ANG_RHC_Information__c.object
<CustomObject>
    <fields>
        <fullName>ANG_AccountId__c</fullName>
        <description>Holds the id of the account to wich the RHC record is related.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RHC Information</relationshipLabel>
        <relationshipName>RHC_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ANG_CashCondition__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Reports the cash conditions of the account. This information is filled by the account trigger and should no be updated manually. It&apos;s used on the calculation of RHC Amount and Forecasted RHC Amount</description>
        <label>Cash Conditions Equal to FS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ANG_Exceeding_Financial_Security__c</fullName>
        <description>Helper field: reports the amount of FS provided over the minimum</description>
        <formula>IF(ANG_Minimum_Financial_Security__c  &gt;= 0 , ANG_Financial_Security__c - ANG_Minimum_Financial_Security__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Exceeding FS Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ANG_Financial_Security__c</fullName>
        <description>The total FS provided by the agent. This field is calculated in a trigger, based on the converted amount of the Financial Security Records on the Account.</description>
        <label>Total FS Provided</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ANG_Provisional_RHC_Last_Update__c</fullName>
        <description>The date of the Provisional RHC Amount last update. This information comes from an external system and should not be updated manually.</description>
        <label>Amount At Risk Last Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ANG_RHC_Amount_Provisional__c</fullName>
        <description>Expected RHC Amount calculated by RME. The agent can request a new calculation via a button on the layout. The information comes from an external system and should not be updated manually.</description>
        <label>Amount At Risk</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ANG_RME_Amount__c</fullName>
        <description>The last approved value calculated from RME.</description>
        <label>Confirmed RME Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>RHC Information</label>
    <nameField>
        <displayFormat>RHCI-{000000000}</displayFormat>
        <label>RHC Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RHC Information Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ANG_RequestProvisionalRHCCtrl.cls
public with sharing class ANG_RequestProvisionalRHCCtrl {

	private static final Set<String> FORECAST_REQUIRED_FIELDS = new Set<String>{'ANG_CashCondition__c','ANG_AccountId__c',
        'ANG_Financial_Security__c', 'ANG_RME_Amount__c','ANG_RHC_Amount_Provisional__c','ANG_Exceeding_Financial_Security__c'};

    private String objId;

    private Decimal requestedProvisionalRHCAmount;
    private Date requestedProvisionalRHCAmountLastUpdate;

    private static DescribeSObjectResult sObjDesc{
        get{
            if(sObjDesc==null){
                sObjDesc = ANG_RHC_Information__c.SObjectType.getDescribe();
            }

            return sObjDesc;
        }
        set;
    }

    private static List<Schema.FieldSetMember> fieldsSet{
        get{
            if(fieldsSet == null){
                fieldsSet = Schema.SObjectType.ANG_RHC_Information__c.fieldSets.Request_Provisional.getFields();
            }

            return fieldsSet;
        }
        set;
    } 

    public List<FieldWrapper> displayFields{get; set;}
    
    private Set<String> fieldsToQuery{
        get{
            if(fieldsToQuery == null){
                fieldsToQuery = new Set<String>();
                for(Schema.SObjectField soF:  sObjDesc.fields.getMap().values()){
                    for(Schema.FieldSetMember fieldToShow : fieldsSet){
                        if(soF.getDescribe().getName() == fieldToShow.getFieldPath()){
                            if(displayFields == null){
                                displayFields = new List<FieldWrapper>();
                            }
                            displayFields.add(new FieldWrapper(soF.getDescribe().getName(),soF.getDescribe().getLabel()));
                            fieldsToQuery.add(soF.getDescribe().getName());
                        }
                    }
                }
                fieldsToQuery.addAll(FORECAST_REQUIRED_FIELDS);
            }
            return fieldsToQuery;
        }
        private set;
    }

    public boolean hasChanged{get;set;}
    public boolean buttonAlreadyPushed{get;set;}

    public ANG_RHC_Information__c rhc{get;set;}

    public void requestProvisionalRHC(){ 
		
		buttonAlreadyPushed= true;
		ANG_RME_Alert_Service.WebserviceResult result = ANG_RME_Alert_Service.requestProvisionalRHCAux(rhc.ANG_AccountId__c, false,false);

        if(Test.isRunningTest()){
            result.isSuccess = true;
            ANG_RME_Alert_Service.RHCMessage message = result.getResultMessage();
            message.provisionalRHC = 200;
        }

        if(result.isSuccess){

            System.debug('[ANG_RequestProvisionalRHCCtrl] - Result from webservice is:'+result);

            rhc.ANG_RHC_Amount_Provisional__c = result.getResultMessage().provisionalRHC;
            rhc.ANG_Provisional_RHC_Last_Update__c = System.today();

            if( rhc.ANG_RHC_Amount_Provisional__c <> requestedProvisionalRHCAmount ||
                rhc.ANG_Provisional_RHC_Last_Update__c <> requestedProvisionalRHCAmountLastUpdate
            ){
                
                hasChanged = true;
                
                requestedProvisionalRHCAmount = rhc.ANG_RHC_Amount_Provisional__c;
                requestedProvisionalRHCAmountLastUpdate = rhc.ANG_Provisional_RHC_Last_Update__c;
                
                rhc.ANG_RME_Amount__c = rhc.ANG_RHC_Amount_Provisional__c;

            }else{
                this.hasChanged = false;
            }
        }else{ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR,result.description));}

    }

    public void save(){
        
        if(canUpdateRHC()){
            update rhc;
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.INFO,'Provisional RHC Amount saved on record.'));
        }

    }

    private boolean canUpdateRHC(){

        // check if current user is Admin
        Profile profile = [Select id, Name from Profile where Id = :UserInfo.getProfileId()];
        boolean isAdminUser = profile.Name.startsWithIgnoreCase('System Administrator');
        
        boolean toBlockUpdate = !isAdminUser && rhc.ANG_CashCondition__c && ( rhc.ANG_Financial_Security__c == 0 || rhc.ANG_Financial_Security__c == null);

        if(toBlockUpdate){
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR,'Provisional RHC cannot be enforced as RHC amount because the agent has cash condition equal to FS. If the agent has no valid FS, please contact your administrator'));
            return false;
        }

        return true;
    }

    private void queryRHC(){
        this.rhc = Database.query('SELECT Id,Name,'+String.join(new List<String>(fieldsToQuery),',') +' FROM ANG_RHC_Information__c WHERE Id = :objId LIMIT 1');
    }

    public ANG_RequestProvisionalRHCCtrl() {
        this.objId = ApexPages.currentPage().getParameters().get('Id'); 
        this.rhc = Database.query('SELECT Id,'+String.join(new List<String>(fieldsToQuery),',') +' FROM ANG_RHC_Information__c WHERE Id = :objId LIMIT 1');

        requestedProvisionalRHCAmount = rhc.ANG_RHC_Amount_Provisional__c;
        requestedProvisionalRHCAmountLastUpdate = rhc.ANG_Provisional_RHC_Last_Update__c;
    }

    public class FieldWrapper{
        public String name {get; set;} 
        public String label {get; set;} 

        public FieldWrapper(String name, String label){
            this.name = name;
            this.label = label;
        }

    }

}