src/objects/CAC_Subscription_Credit__c.object
<CustomObject>
    <description>Hold all the CAC Subscription Credits</description>
    <fields>
        <fullName>CAC_Subscription_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription Detail against which the credit is applied</description>
        <inlineHelpText>Subscription Detail against which the credit is applied</inlineHelpText>
        <label>CAC Subscription Detail</label>
        <referenceTo>CAC_Subscription_Detail__c</referenceTo>
        <relationshipLabel>CAC Subscription Credits</relationshipLabel>
        <relationshipName>CAC_Subscription_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <description>Credit Applied up on the consumption</description>
        <inlineHelpText>Credit Applied up on the consumption</inlineHelpText>
        <label>Credit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date of when the credit has been applied</description>
        <inlineHelpText>Date of when the credit has been applied</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CAC Subscription Credit</label>
    <nameField>
        <displayFormat>CT-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAC Subscription Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CAC_Subscription_Detail__c.object
<CustomObject>
    <description>Will hold the CAC WebService Subscription Details</description>
    <fields>
        <fullName>Credit__c</fullName>
        <description>Credit amount applicable on the usage consumed</description>
        <inlineHelpText>Credit amount applicable on the usage consumed</inlineHelpText>
        <label>Credit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_API_Call_Per_Month__c</fullName>
        <description>Maximum Calls per Month will limit the number of calls performed during the month, the number is managed inside the mysql database</description>
        <inlineHelpText>Maximum Calls per Month will limit the number of calls performed during the month, the counter is managed inside the mysql database</inlineHelpText>
        <label>Max API Call Per Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Activation_Date__c</fullName>
        <description>Date used in the generation of the service Token, the token is generated every time the date is changed</description>
        <inlineHelpText>Date used in the generation of the service Token, the token is generated every time the date is changed</inlineHelpText>
        <label>Service Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Specification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Specification that will be responsible to generate the JSON response to the customer</description>
        <inlineHelpText>Service Specification that will be responsible to generate the JSON response to the customer</inlineHelpText>
        <label>Service Specification</label>
        <referenceTo>GDP_File_Description__c</referenceTo>
        <relationshipLabel>CAC Subscription Details</relationshipLabel>
        <relationshipName>CAC_Subscription_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Token__c</fullName>
        <description>Service Token used by the IATA customer to identify itself during the mysql validation</description>
        <inlineHelpText>Service Token used by the IATA customer to identify itself during the mysql validation</inlineHelpText>
        <label>Service Token</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Zuora Subscription Lookup Id may be lost during amendment</description>
        <inlineHelpText>The Zuora Subscription</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>CAC Subscription Details</relationshipLabel>
        <relationshipName>CAC_Subscription_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CAC Subscription Detail</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CAC Subscription Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IEC_Compiled_Usage_Tracker__c.object
<CustomObject>
    <description>Object used by the compiling process of &quot;live&quot; usage tracking.</description>
    <fields>
        <fullName>CAC_Subscription_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CAC Subscription Detail</label>
        <referenceTo>CAC_Subscription_Detail__c</referenceTo>
        <relationshipLabel>IEC Compiled Usage Tracker</relationshipLabel>
        <relationshipName>IEC_Compiled_Usage_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Counter__c</fullName>
        <description>Compiled value of usage</description>
        <inlineHelpText>Compiled value of usage</inlineHelpText>
        <label>Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>The date for which the usage is compiled</description>
        <inlineHelpText>The date for which the usage is compiled</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Max_API_Call_Per_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Maximum API Calls Per Month allowed</description>
        <inlineHelpText>Maximum API Calls Per Month allowed</inlineHelpText>
        <label>Max API Call Per Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_Application__c</fullName>
        <description>The application for which the usage is compiled</description>
        <inlineHelpText>The application for which the usage is compiled</inlineHelpText>
        <label>Related Application</label>
        <picklist>
            <picklistValues>
                <fullName>CACFREE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CACPRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CACSWS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CACEWS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Validation_Result__c</fullName>
        <label>Validation Result</label>
        <picklist>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Validation_Type__c</fullName>
        <label>Validation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IEC Compiled Usage Tracker</label>
    <nameField>
        <displayFormat>IEC-CUT-{0000000}</displayFormat>
        <label>IEC Compiled Usage Tracler Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IEC Compiled Usage Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Category__c.object
<CustomObject>
    <description>Contains the main product categories and their related information to be displayed on the product viewer page, and some extra configurations used for browsing products and rate plans.</description>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Information__c.object
<CustomObject>
    <description>Represents the Product Information in Salesforce, this Product level is configurable and linked to a parent (Product Category) and can have multiple Rate Plan information as Children</description>
    <fields>
        <fullName>Product_Audience__c</fullName>
        <label>Product Audience</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>IATA Employee</fullName>
                </value>
                <value>
                    <fullName>Strategic Member</fullName>
                </value>
                <value>
                    <fullName>Member Airline</fullName>
                </value>
                <value>
                    <fullName>Non Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Information</label>
    <nameField>
        <label>Product Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan_Information__c.object
<CustomObject>
    <description>Contains the main Rate Plans information to be displayed on the product browsing page UI</description>
    <label>Product Rate Plan Information</label>
    <nameField>
        <label>Product Rate Plan Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fixingUpdate/objects/zqu__ZProduct__c.object
<CustomObject>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/vfIEC_CACWMonthlyConsumptionTest.cls
/**
* @author Mathieu Beausoleil
* @date 2016
* @group CACW
* @description This is the Test class to test the Visual force contoller extension vfIEC_CACWMonthlyConsumption
* SeeAllData notation is required to be able to use Zuora WSDL
*
* Change logs:
*  - 20160420-sl: disable test method testHistoryFall2015. 
*    Reason: validation error in trgCACSubscriptionCredit.trigger: 11
*    Error Message: 'No direct action is allowed on the credit, please use the Apply Credit Interface!' 
*
*/
@isTest (seeAllData=true)
private class vfIEC_CACWMonthlyConsumptionTest {
    private static Product_Category__c oProductCategory;
    private static Product_Information__c oProductInfo;
    private static zqu__ZProduct__c oProduct;
    private static zqu__ProductRatePlan__c oProductRatePlan;
    private static zqu__ProductRatePlanCharge__c oProductRatePlanCharge;
    private static Product_Rate_Plan_Information__c oProductRatePlanInfo;
    private static Zuora__Subscription__c subscription;
    private static Zuora__SubscriptionProductCharge__c subscriptionCharge;

    private static IECCustomer currentCustomer;
    
    private static CAC_Subscription_Detail__c CAC_SubscriptionDetail ;


    /*******************************************************************************************************
    * @description Initialize data requied to have a subscription and related records required to run test
    */    
    static void Init() {
        System.debug('Unit Test: Start: Init');
        oProductCategory = IECTestUtil.CreateSampleProductCategory(IECConstants.ProductCategory_SF_CACWEB, true);
        insert oProductCategory;
        
        oProduct = IECTestUtil.CreateSampleProduct('PTST');
        insert oProduct;
        
        oProductInfo = IECTestUtil.CreateSampleProductInfo('PITST', oProductCategory, oProduct);
        oProductInfo.Product_Audience__c = IECConstants.ProductInformationAudience_DEFAULT;
        insert oProductInfo;
        
        oProductRatePlan = IECTestUtil.CreateSampleProductRatePlan('PRPTST', false, oProduct);
        insert oProductRatePlan;
        
        oProductRatePlanCharge = IECTestUtil.CreateSampleProductRatePlanCharge(oProductRatePlan, 'CHARGETEST', 1);
        insert oProductRatePlanCharge;
        
        oProductRatePlanInfo = IECTestUtil.CreateSampleProductRatePlanInfo('PCRPTST', false, oProductRatePlan, oProductInfo);
        insert oProductRatePlanInfo;
        
        currentCustomer = IECCustomer.getCurrentIECCustomer();
        
        // create dummy subscription
        subscription = IECTestUtil.createSampleSubscription(currentCustomer.RelatedAccount.Id, currentCustomer.RelatedBillingAccount.Id, 'Subs 01', Date.newInstance(2015, 12, 31));
        subscription.Zuora__Status__c='Active';
        subscription.Product_Rate_Plan_Information__c = oProductRatePlanInfo.Id;
        insert subscription;
        
        // create dummy subscription charge
        subscriptionCharge = IECTestUtil.createSampleSubscriptionCharge(subscription.Id, Date.newInstance(2014, 12, 31), oProduct, oProductRatePlan);
        insert subscriptionCharge;
        
        // Create dummy CAC Subscription Detail
        CAC_SubscriptionDetail = 
            new CAC_Subscription_Detail__c(Name=subscription.Name
                                          ,Subscription__c=subscription.Id
                                          ,Service_Activation_Date__c=Date.newInstance(2015, 1, 1)
                                          ,Max_API_Call_Per_Month__c=30
                                          ,Status__c='Active'
                                          /*Service_Specification__c=*/
                                          /*,Service_Token__c=*/);
        Insert CAC_SubscriptionDetail;
            
        
        System.debug('Unit Test: Finish: Init');
    }
    
    
    
    // SL Note-20160420: temporary disabled as this fails
    //static testMethod 
    void testHistoryFall2015() {
        //Set current page to GSSDetail File
        PageReference pgRef = Page.IEC_CACWHistory;
        pgRef.getParameters().put(IECConstants.PARAM_SUBSCRIPTION_NAME, IECUtil.EncryptEncodeParameter('Subs 01'));
        pgRef.getParameters().put(IECConstants.PARAM_PRODUCT_CODE, IECUtil.EncryptEncodeParameter(IECConstants.ProductCategory_SF_CACWEB));
        Test.setCurrentPage(pgRef);
        
        User usr = IECTestUtil.createSampleGuestUserAndLogin();
        System.runAs(usr) {
            
            Test.startTest();
            //Arrange                
            // setup data
            Init();

            // triggers the Product Access creation
            update subscription;

            List<IEC_Compiled_Usage_Tracker__c> compiled = new List<IEC_Compiled_Usage_Tracker__c>{
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 10, Date__c = Date.newInstance(2015, 12, 15), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent'),
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 1, Date__c = Date.newInstance(2015, 11, 15), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent'),
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 40, Date__c = Date.newInstance(2015, 10, 15), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent'),
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 45, Date__c = Date.newInstance(2015, 9, 15), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent')
            };

            insert compiled;

            List<CAC_Subscription_Credit__c> credits = new List<CAC_Subscription_Credit__c>{
                new CAC_Subscription_Credit__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Credit__c = 1000, Date__c = Date.newInstance(2015, 09, 13))
            };

            insert credits;
                
            Test.stopTest();

            //Instantiate Controller

            vfIEC_CACW iecCacWebController = new vfIEC_CACW();
            vfIEC_CACWMonthlyConsumption MyExtension = new vfIEC_CACWMonthlyConsumption(iecCacWebController);
            MyExtension.segment = 'Monthly';
            MyExtension.startDate = Date.newInstance(2015, 08, 01);
            MyExtension.endDate = Date.newInstance(2015, 12, 31);
            
            System.assertEquals('Monthly', MyExtension.segment);

            vfIEC_CACWMonthlyConsumption.CACWebAPIPeriodConsumption r;

            r = MyExtension.PeriodConsumptionHistory[0];
            System.assertEquals(Date.newInstance(2015, 12, 31), r.periodEndDate);
            System.assertEquals('2015-12-31', r.periodEndDateText);
            System.assertEquals(Date.newInstance(2015, 12, 1), r.periodStartDate);
            System.assertEquals('2015-12-01', r.periodStartDateText);
            System.assertEquals(30, r.APICallsForPeriodAllowed);
            System.assertEquals(10, r.APICallsForPeriodConsumed);
            System.assertEquals(20, r.APICallsForPeriodLeft);
            System.assertEquals(33, r.APICallsUsedPercentage);
            System.assertEquals(0, r.Credits);
            System.assertEquals(11, r.ProjectedConsumptionAtEndOfMonth);
            System.assertEquals((r.APICallsForPeriodAllowed + r.Credits), r.TotalAllowed);
            System.assertEquals('Daily', r.detailSegment);

            r = MyExtension.PeriodConsumptionHistory[1];
            System.assertEquals(Date.newInstance(2015, 11, 30), r.periodEndDate);
            System.assertEquals('2015-11-30', r.periodEndDateText);
            System.assertEquals(Date.newInstance(2015, 11, 1), r.periodStartDate);
            System.assertEquals('2015-11-01', r.periodStartDateText);
            System.assertEquals(30, r.APICallsForPeriodAllowed);
            System.assertEquals(1, r.APICallsForPeriodConsumed);
            System.assertEquals(29, r.APICallsForPeriodLeft);
            System.assertEquals(3, r.APICallsUsedPercentage);
            System.assertEquals(0, r.Credits);
            System.assertEquals(1, r.ProjectedConsumptionAtEndOfMonth);
            System.assertEquals((r.APICallsForPeriodAllowed + r.Credits), r.TotalAllowed);
            System.assertEquals('Daily', r.detailSegment);

            r = MyExtension.PeriodConsumptionHistory[2];
            System.assertEquals(Date.newInstance(2015, 10, 31), r.periodEndDate);
            System.assertEquals('2015-10-31', r.periodEndDateText);
            System.assertEquals(Date.newInstance(2015, 10, 1), r.periodStartDate);
            System.assertEquals('2015-10-01', r.periodStartDateText);
            System.assertEquals(30, r.APICallsForPeriodAllowed);
            System.assertEquals(40, r.APICallsForPeriodConsumed);
            System.assertEquals(-10, r.APICallsForPeriodLeft);
            System.assertEquals(133, r.APICallsUsedPercentage);
            System.assertEquals(0, r.Credits);
            System.assertEquals(40, r.ProjectedConsumptionAtEndOfMonth);
            System.assertEquals((r.APICallsForPeriodAllowed + r.Credits), r.TotalAllowed);
            System.assertEquals('Daily', r.detailSegment);

            r = MyExtension.PeriodConsumptionHistory[3];
            System.assertEquals(Date.newInstance(2015, 09, 30), r.periodEndDate);
            System.assertEquals('2015-09-30', r.periodEndDateText);
            System.assertEquals(Date.newInstance(2015, 09, 1), r.periodStartDate);
            System.assertEquals('2015-09-01', r.periodStartDateText);
            System.assertEquals(30, r.APICallsForPeriodAllowed);
            System.assertEquals(45, r.APICallsForPeriodConsumed);
            System.assertEquals(985, r.APICallsForPeriodLeft);
            System.assertEquals(150, r.APICallsUsedPercentage);
            System.assertEquals(1000, r.Credits);
            System.assertEquals(45, r.ProjectedConsumptionAtEndOfMonth);
            Boolean showRecommendation = r.showRecommendation;
            Boolean showRecommendationMonthlyAllowed = r.showRecommendationMonthlyAllowed;
            System.assertEquals((r.APICallsForPeriodAllowed + r.Credits), r.TotalAllowed);
            System.assertEquals('Daily', r.detailSegment);

            System.debug(subscription);
            System.debug(MyExtension.aPeriodConsumption);
            System.debug(MyExtension.PeriodConsumptionHistory);
        }
        System.debug('Unit Test: Finish: TestIEC_CACWKey');
        
    }
    
    static testMethod void testHistoryDaily() {
        //Set current page to GSSDetail File
        PageReference pgRef = Page.IEC_CACWHistory;
        pgRef.getParameters().put(IECConstants.PARAM_SUBSCRIPTION_NAME, IECUtil.EncryptEncodeParameter('Subs 01'));
        pgRef.getParameters().put(IECConstants.PARAM_PRODUCT_CODE, IECUtil.EncryptEncodeParameter(IECConstants.ProductCategory_SF_CACWEB));
        Test.setCurrentPage(pgRef);
        
        User usr = IECTestUtil.createSampleGuestUserAndLogin();
        System.runAs(usr) {
            
            Test.startTest();
            //Arrange                
            // setup data
            Init();

            // triggers the Product Access creation
            update subscription;

            List<IEC_Compiled_Usage_Tracker__c> compiled = new List<IEC_Compiled_Usage_Tracker__c>{
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 5, Date__c = Date.newInstance(2015, 12, 31), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent'),
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 4, Date__c = Date.newInstance(2015, 12, 30), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent'),
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 3, Date__c = Date.newInstance(2015, 12, 29), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent')
            };

            insert compiled;

            Test.stopTest();

            //Instantiate Controller

            vfIEC_CACW iecCacWebController = new vfIEC_CACW();
            vfIEC_CACWMonthlyConsumption MyExtension = new vfIEC_CACWMonthlyConsumption(iecCacWebController);
            MyExtension.segment = 'Daily';
            MyExtension.startDate = Date.newInstance(2015, 12, 01);
            MyExtension.endDate = Date.newInstance(2015, 12, 31);
            
            System.assertEquals('Daily', MyExtension.segment);

            vfIEC_CACWMonthlyConsumption.CACWebAPIPeriodConsumption r;

            System.assertEquals(31, MyExtension.PeriodConsumptionHistory.size());

            System.assertEquals(MyExtension.startDate, MyExtension.aPeriodConsumption.periodStartDate);
            System.assertEquals(MyExtension.endDate, MyExtension.aPeriodConsumption.periodEndDate);
            System.assertEquals(12, MyExtension.aPeriodConsumption.APICallsForPeriodConsumed);

            r = MyExtension.PeriodConsumptionHistory[0];
            System.assertEquals(Date.newInstance(2015, 12, 31), r.periodEndDate);
            System.assertEquals('2015-12-31', r.periodEndDateText);
            System.assertEquals(r.periodEndDate, r.periodStartDate);
            System.assertEquals(r.periodEndDateText, r.periodStartDateText);
            System.assertEquals(5, r.APICallsForPeriodConsumed);
            System.assertEquals(null, r.detailSegment);

            r = MyExtension.PeriodConsumptionHistory[1];
            System.assertEquals(Date.newInstance(2015, 12, 30), r.periodEndDate);
            System.assertEquals('2015-12-30', r.periodEndDateText);
            System.assertEquals(r.periodEndDate, r.periodStartDate);
            System.assertEquals(r.periodEndDateText, r.periodStartDateText);
            System.assertEquals(4, r.APICallsForPeriodConsumed);
            System.assertEquals(null, r.detailSegment);

            r = MyExtension.PeriodConsumptionHistory[2];
            System.assertEquals(Date.newInstance(2015, 12, 29), r.periodEndDate);
            System.assertEquals('2015-12-29', r.periodEndDateText);
            System.assertEquals(r.periodEndDate, r.periodStartDate);
            System.assertEquals(r.periodEndDateText, r.periodStartDateText);
            System.assertEquals(3, r.APICallsForPeriodConsumed);
            System.assertEquals(null, r.detailSegment);

            r = MyExtension.PeriodConsumptionHistory[30];
            System.assertEquals(Date.newInstance(2015, 12, 1), r.periodEndDate);
            System.assertEquals('2015-12-01', r.periodEndDateText);
            System.assertEquals(r.periodEndDate, r.periodStartDate);
            System.assertEquals(r.periodEndDateText, r.periodStartDateText);
            System.assertEquals(0, r.APICallsForPeriodConsumed);
            System.assertEquals(null, r.detailSegment);
        }    
    }
    
    static testMethod void testHistoryYearly() {
        //Set current page to GSSDetail File
        PageReference pgRef = Page.IEC_CACWHistory;
        pgRef.getParameters().put(IECConstants.PARAM_SUBSCRIPTION_NAME, IECUtil.EncryptEncodeParameter('Subs 01'));
        pgRef.getParameters().put(IECConstants.PARAM_PRODUCT_CODE, IECUtil.EncryptEncodeParameter(IECConstants.ProductCategory_SF_CACWEB));
        Test.setCurrentPage(pgRef);
        
        User usr = IECTestUtil.createSampleGuestUserAndLogin();
        System.runAs(usr) {
            
            Test.startTest();
            //Arrange                
            // setup data
            Init();

            // triggers the Product Access creation
            update subscription;

            List<IEC_Compiled_Usage_Tracker__c> compiled = new List<IEC_Compiled_Usage_Tracker__c>{
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 5, Date__c = Date.newInstance(2015, 12, 31), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent'),
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 4, Date__c = Date.newInstance(2014, 12, 30), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent'),
                new IEC_Compiled_Usage_Tracker__c(CAC_Subscription_Detail__c = CAC_SubscriptionDetail.Id, Counter__c = 3, Date__c = Date.newInstance(2013, 12, 29), Related_Application__c = 'CACSWS', Validation_Result__c = 'Success', Validation_Type__c = 'Agent')
            };

            insert compiled;

            Test.stopTest();

            //Instantiate Controller

            vfIEC_CACW iecCacWebController = new vfIEC_CACW();
            vfIEC_CACWMonthlyConsumption MyExtension = new vfIEC_CACWMonthlyConsumption(iecCacWebController);
            MyExtension.segment = 'Yearly';
            MyExtension.startDate = Date.newInstance(2014, 01, 01);
            MyExtension.endDate = Date.newInstance(2015, 12, 31);
            
            System.assertEquals('Yearly', MyExtension.segment);

            vfIEC_CACWMonthlyConsumption.CACWebAPIPeriodConsumption r;

            System.assertEquals(2, MyExtension.PeriodConsumptionHistory.size());

            System.assertEquals(MyExtension.startDate, MyExtension.aPeriodConsumption.periodStartDate);
            System.assertEquals(MyExtension.endDate, MyExtension.aPeriodConsumption.periodEndDate);
            System.assertEquals(9, MyExtension.aPeriodConsumption.APICallsForPeriodConsumed);

            r = MyExtension.PeriodConsumptionHistory[0];
            System.assertEquals(Date.newInstance(2015, 12, 31), r.periodEndDate);
            System.assertEquals('2015-12-31', r.periodEndDateText);
            System.assertEquals(Date.newInstance(2015, 01, 01), r.periodStartDate);
            System.assertEquals('2015-01-01', r.periodStartDateText);
            System.assertEquals(5, r.APICallsForPeriodConsumed);
            System.assertEquals('Monthly', r.detailSegment);

            r = MyExtension.PeriodConsumptionHistory[1];
            System.assertEquals(Date.newInstance(2014, 12, 31), r.periodEndDate);
            System.assertEquals('2014-12-31', r.periodEndDateText);
            System.assertEquals(Date.newInstance(2014, 01, 01), r.periodStartDate);
            System.assertEquals('2014-01-01', r.periodStartDateText);
            System.assertEquals(4, r.APICallsForPeriodConsumed);
            System.assertEquals('Monthly', r.detailSegment);
        }    
    }
}