src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Generate_Members_Completed_On__c</fullName>
        <description>IEC - Timestamp indicating when generation of campaign members is complete</description>
        <label>Generate Members Completed On</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Campaign_Member_Product__c.object
<CustomObject>
    <description>IEC - products ordered by customer for a given Campaign</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <description>IEC - parent campaign</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Members and Products</relationshipLabel>
        <relationshipName>Campaign_Members_and_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>IEC - technical field to avoid duplicates</description>
        <label>Key</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Campaign Member and Product</label>
    <nameField>
        <displayFormat>CMP-{00000000}</displayFormat>
        <label>Member Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Members and Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <description>Technical field to perform upserts</description>
        <externalId>true</externalId>
        <label>Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/OrderItem_Batch.cls
global class OrderItem_Batch implements Database.Batchable<sObject>
{
	public String action;
	public String query;
	public Id campaignId;


	global OrderItem_Batch(String a)
	{
		action = a;
	}

	global Database.QueryLocator start(Database.BatchableContext BC)
	{
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope)
	{
		if(action == 'GenerateCampaignMembersAndProducts')
		{
			List<OrderItem> items = (List<OrderItem>) scope;

			//-- Generate Campaign Members
			List<CampaignMember> cmGenerated = CampaignMember_Svc.generateCampaignMembers(campaignId, items);

			//-- Generate CampaignMeber Products
			List<Campaign_Member_Product__c> cmpGenerated = CampaignMemberProduct_Svc.generateCampaignMemberProducts(campaignId, items);
		}
	}

	global void finish(Database.BatchableContext BC)
	{
		if(action == 'GenerateCampaignMembersAndProducts')
		{
			//-- Cleanup potential duplicates
			List<AggregateResult> duplicates = [SELECT COUNT(Id) nb, Key__c
				FROM Campaign_Member_Product__c
				WHERE Campaign__c = :campaignId
				GROUP BY Key__c
				HAVING (COUNT(Id) > 1)
			];
			Set<String> duplicateKeys = new Set<String>();
			for (AggregateResult ar : duplicates)
				duplicateKeys.add((String) ar.get('Key__c'));

			if(duplicateKeys.size() > 0) CampaignMemberProduct_Svc.removeDuplicates(duplicateKeys);

			//-- Update Campaign flag to notified the batch job is completed
			Campaign c = new Campaign(
				Id = campaignId,
				Generate_Members_Completed_On__c = Datetime.now()
			);
			update c;

			//-- Send notification email
			//if(!Test.isRunningTest())
			{
				Id templateId = (!Test.isRunningTest())? (Id) Utility.getTextSetting('TPL_GENERATE_CAMPAIGN_MEMBER_COMPLETED') : [SELECT Id FROM EmailTemplate  LIMIT 1].Id;

				Mail_DTO mail = new Mail_DTO();
					mail.whatId = campaignId;
					mail.templateId = templateId;
					mail.recipients = new List<String>{UserInfo.getUserEmail()};

				Utility.sendBulkEmails(new List<Mail_DTO>{mail});
			}
		}
	}
}