src/objects/Comment__c.object
<CustomObject>
    <description>Object created for the AME objectives reporting project. 
Object to store comments related to objectives, or independent comments that we can report on.</description>
    <fields>
        <fullName>Is_incomplete__c</fullName>
        <description>As there is a VR that prevents a comment to be of no kind. If no kind specify we know that is an incomplete one, and (CreatedDate =  LastModifiedDate)</description>
        <formula>IF(((Divisional_News__c = FALSE) &amp;&amp; (Country_News__c = FALSE) &amp;&amp; (Achievement__c = FALSE)) &amp;&amp;  (CreatedDate =  LastModifiedDate), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is incomplete</label>
        <type>Checkbox</type>
    </fields>
    <label>News</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>News Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DeleteIncompletedCommentsScheduler.cls
global class DeleteIncompletedCommentsScheduler implements Schedulable {

	global void execute(SchedulableContext SC) {
		launchProcess();
	}

	public void launchProcess() {
		try {
			list<Comment__c> listComment = [Select Id From Comment__c where Is_incomplete__c = true];
			//and CreatedDate <= YESTERDAY
			System.debug('*** ' + listComment);
			delete listComment;

		} catch (Exception e) {
			System.debug('ERROR DeleteIncompletedCommentsScheduler: ' + e.getMessage());
			TransformationHelper.sendEmailSupport('FATAL: DeleteIncompletedCommentsScheduler in function launchProcess()  ' ,'STACKTRACE   ' + e.getStackTraceString()  + '  '  + e.getMessage());
		}
	}

}