src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is to track employees that are no longer with the account (dismissed, left, died) and for which we do not have updated information on employer.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Left Company / Relocated</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/EBC_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Scheduled_Date__c</fullName>
        <description>The scheduled date of the campaign</description>
        <inlineHelpText>The scheduled date of the campaign</inlineHelpText>
        <label>Scheduled Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of the campaign</description>
        <inlineHelpText>The current status of the campaign</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                    <default>true</default>
                    <label>DRAFT</label>
                </value>
                <value>
                    <fullName>PENDING_APPROVAL</fullName>
                </value>
                <value>
                    <fullName>APPROVED</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>STARTED</fullName>
                </value>
                <value>
                    <fullName>SENT</fullName>
                </value>
                <value>
                    <fullName>DELETED</fullName>
                </value>
                <value>
                    <fullName>EMAIL RECOVER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EBC Campaign</label>
    <nameField>
        <label>eBroadcast Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBC Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/vfIECEBC_CampaignList.cls
public class vfIECEBC_CampaignList {
    class Controller_Exception extends Exception{}
    public List<EBC_Campaign__c> campaigns {
        get {
            User u = [Select ContactId, Contact.AccountId from User where id =: Userinfo.getUserid()];
            
	        if (campaigns == null) campaigns = [Select Id, Name, Status__c, Scheduled_Date__c, Owner.Name From EBC_Campaign__c WHERE Account__c = :u.Contact.AccountId ORDER BY LastModifiedDate];
            return campaigns;
        }
        private set;
    }
    public Integer getCampaignsCount() {
        return [Select count() From EBC_Campaign__c];
    }
    
    public vfIECEBC_CampaignList() {
    }
}