src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <fields>
        <fullName>GDPR_PrivacyStatement__c</fullName>
        <description>URL to privacy statement (document or web page) for each service</description>
        <label>GDPR_PrivacyStatement</label>
        <type>Url</type>
    </fields>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IATA_ServiceList_CTRL.cls
global without sharing class IATA_ServiceList_CTRL {
    
    @AuraEnabled
    global static List<Portal_Application_Right__c> getUserPortalServices(){
        String contactId = null;
        String userId = UserInfo.getUserId();

        User userAux = [SELECT Id, ContactId FROM User WHERE Id = :userId];
        if(userAux != null && userAux.ContactId != null){contactId = userAux.ContactId;}
        
        
        if(contactId == null || contactId == ''){return null;}
        
        List<Portal_Application_Right__c> lstApps = [SELECT Id,Portal_Application__c,Portal_Application__r.Name,
                                                     Portal_Application__r.GDPR_PrivacyStatement__c
                                                     FROM Portal_Application_Right__c WHERE Contact__c = :contactId AND Right__c = 'Access Granted'];
        return lstApps;
    }

}