src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EBC_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated billing account</description>
        <inlineHelpText>Associated billing account</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>EBC Preferences</relationshipLabel>
        <relationshipName>eBroadcast_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_From_Name__c</fullName>
        <description>The From Name that will be set by default on a new campaign</description>
        <inlineHelpText>The From Name that will be set by default on a new campaign</inlineHelpText>
        <label>Default From Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Google_Analytics_Tracker__c</fullName>
        <description>Default Google Analytics account for the current account</description>
        <inlineHelpText>Default Google Analytics account for the current account</inlineHelpText>
        <label>Default Google Analytics Tracker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Account_Status__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send an email with the monthly account status to the primary contact email</description>
        <inlineHelpText>Send an email with the monthly account status to the primary contact email</inlineHelpText>
        <label>Monthly Account Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_On_Send__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send an email notification to primary contact email when campaign is sent</description>
        <inlineHelpText>Send an email notification to primary contact email when campaign is sent</inlineHelpText>
        <label>Notify On Send</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrimaryContact_Address__c</fullName>
        <description>The address of the primary contact</description>
        <inlineHelpText>The address of the primary contact</inlineHelpText>
        <label>Primary Contact Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PrimaryContact_Company__c</fullName>
        <description>The company name for which the primary contact is working for</description>
        <inlineHelpText>The company name for which the primary contact is working for</inlineHelpText>
        <label>Primary Contact Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryContact_Email__c</fullName>
        <description>The email address fo the primary contact</description>
        <inlineHelpText>The email address fo the primary contact</inlineHelpText>
        <label>Primary Contact Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PrimaryContact_Job_Title__c</fullName>
        <description>The job title of the primary contact</description>
        <inlineHelpText>The job title of the primary contact</inlineHelpText>
        <label>Primary Contact Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryContact_Name__c</fullName>
        <description>The name of the primary contact</description>
        <inlineHelpText>The name of the primary contact</inlineHelpText>
        <label>Primary Contact Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryContact_Phone__c</fullName>
        <description>The phone number of the primary contact</description>
        <inlineHelpText>The phone number of the primary contact</inlineHelpText>
        <label>Primary Contact Phone</label>
        <type>Phone</type>
    </fields>
    <label>EBC Preference</label>
    <nameField>
        <label>eBroadcast Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBC Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>EBC_Cost_Per_Email__c</fullName>
        <description>Numeric value representing the the cost per e-mail in eBroadcast,, i.e. $0.20 / e-mail</description>
        <inlineHelpText>Numeric value representing the the cost per e-mail in eBroadcast, i.e. $0.20 / e-mail</inlineHelpText>
        <label>EBC Cost per Email</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBC_Currency_Cost_Per_Email__c</fullName>
        <description>The Currency formatted value of the Cost per Email</description>
        <formula>VALUE(EBC_Cost_Per_Email__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Currency formatted value of the Cost per Email</inlineHelpText>
        <label>EBC Currency Cost Per Email</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EBC_PrePaid_Emails__c</fullName>
        <description>This field stores the initial number of email credits per rate plan.</description>
        <inlineHelpText>This field stores the initial number of email credits per rate plan.</inlineHelpText>
        <label>EBC PrePaid Emails</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBC_SubscriptionType__c</fullName>
        <description>Identifies the type of eBroadcast subscription that represents the rate plan.</description>
        <inlineHelpText>Identifies the type of eBroadcast subscription that represents the rate plan.</inlineHelpText>
        <label>EBC Subscription Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Description__c</fullName>
        <description>The Description of the Rate Plan.</description>
        <inlineHelpText>The Description of the Rate Plan.</inlineHelpText>
        <label>Description</label>
        <length>25535</length>
        <type>LongTextArea</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eBroadcast_Email_Balance__c</fullName>
        <label>eBroadcast Email Balance</label>
        <summarizedField>EBC_Activity__c.Total_Count__c</summarizedField>
        <summaryForeignKey>EBC_Activity__c.Related_Billing_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>eBroadcast_Trusted_Sender__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Zuora is pre-authorized to send eBroadcast Campaigns without requiring any approval</description>
        <inlineHelpText>Is this Zuora is pre-authorized to send eBroadcast Campaigns without requiring any approval</inlineHelpText>
        <label>eBroadcast Trusted Sender</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/vfIECEBC.cls
public class vfIECEBC {
    public static User usr = [Select ContactId, Contact.AccountId from User where id = :Userinfo.getUserid()];
    public static Zuora__CustomerAccount__c billingAccount {
        get {
            if (billingAccount == null) {
                billingAccount = [Select Id, eBroadcast_Trusted_Sender__c, eBroadcast_Email_Balance__c, Zuora__Account__c  from Zuora__CustomerAccount__c where Contact__c = :usr.ContactId LIMIT 1];
            }
            
            return billingAccount;
        }
        private set;
    }
    public static EBC_Preference__c pref {
        get {
            if (pref == null) {
                System.debug(billingAccount);
                
                pref = [
                    Select Id, Default_From_Name__c, Default_Google_Analytics_Tracker__c,
                        Monthly_Account_Status__c, Notify_On_Send__c, PrimaryContact_Address__c,
                        PrimaryContact_Company__c, PrimaryContact_Email__c,
                        PrimaryContact_Job_Title__c, PrimaryContact_Name__c, PrimaryContact_Phone__c
                    From EBC_Preference__c
                    Where Billing_Account__c = :billingAccount.Id
                    LIMIT 1
                ];
            }
            return pref;
        }
        private set;
    }
    
    public static Zuora__Subscription__c subscription {
        get {
            if (subscription == null) {
                List<Zuora__Subscription__c> subsList = [SELECT Id, Name
                                                         	 , Zuora__AutoRenew__c
	                                                         , Zuora__SubscriptionEndDate__c
	                                                         , Zuora__NextRenewalDate__c
                                                             , Product_Rate_Plan_Information__r.Product_Rate_Plan__c
                                                             , Product_Rate_Plan_Information__r.Product_Rate_Plan__r.Id
                                                             , Product_Rate_Plan_Information__r.Product_Rate_Plan__r.Name
                                                             , Product_Rate_Plan_Information__r.Product_Rate_Plan__r.zqu__Description__c
                                                             , Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_SubscriptionType__c
                                                             , Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_Cost_Per_Email__c
                                                             , Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_Currency_Cost_Per_Email__c
                                                             , Product_Rate_Plan_Information__r.Product_Rate_Plan__r.EBC_PrePaid_Emails__c
                                                         FROM Zuora__Subscription__c
                                                         WhERE (Zuora__CustomerAccount__c = :billingAccount.Id) 
                                                             AND (
                                                                 (Zuora__SubscriptionEndDate__c >=  TODAY) 
                                                                 OR (Zuora__SubscriptionEndDate__c = NULL)
                                                             )
                                                             AND (Zuora__SubscriptionStartDate__c <=  TODAY) 
                                                             AND (Zuora__Status__c = 'Active')
                                                             AND (Product_Rate_Plan_Information__r.Related_Product_Information__r.Related_Product_Category__r.Name = :IECConstants.ProductCategory_SF_EBROADCAST)
                                                         ORDER BY Zuora__Status__c ASC
                                                             , Zuora__SubscriptionEndDate__c DESC NULLS FIRST
                                                             , Zuora__SubscriptionStartDate__c DESC
                                                         LIMIT 1
                                                        ];
                if (subsList.size() > 0) {
                    subscription = subsList[0];
                }
            }
            
            return subscription;
        }
        set;
    }
    
    /*
    public static vfIECSubscriptionInfo subscriptionInfo {
    	get {
    		if (subscriptionInfo == null) {
		        subscriptionInfo = new vfIECSubscriptionInfo(); 
		        subscriptionInfo.loggedCustomer = IECCustomer.getCurrentIECCustomer();
		        subscriptionInfo.sApplicationName = sProductCode;
    		}

    		return subscriptionInfo;
    	}
    	set;
    }
*/    
    public static zqu__ProductRatePlan__c  productRatePlan {
        get { 
            if (productRatePlan == null) { 
                //System.debug(subscriptionInfo.oSubscription.Product_Rate_Plan_Information__r.Product_Rate_Plan__c);
	        	//productRatePlan = [Select Id, Name, EBC_SubscriptionType__c, EBC_Currency_Cost_Per_Email__c, EBC_PrePaid_Emails__c From zqu__ProductRatePlan__c  Where Id = :subscriptionInfo.oSubscription.Product_Rate_Plan_Information__r.Product_Rate_Plan__c];
	        	productRatePlan = subscription.Product_Rate_Plan_Information__r.Product_Rate_Plan__r;
            }
            
            return productRatePlan;
        }
        set;
    }
    /*
    public vfIECSubscriptionInfo ctrSubsInfo  {
    	get {
    		return subscriptionInfo;
    	}
    }*/

	public static String sProductCode {
		get {
			return IECConstants.ProductCategory_SF_EBROADCAST;
		}
	}
    /*
    public Pagereference pageLoad() {
        if (String.isBlank(UserInfo.getSessionId())) {
            Pagereference prLogin = Page.IECLogin;
            prLogin.getParameters().put(IECConstants.PARAM_RETURN_URL, IECUtil.EncryptEncodeParameter(ApexPages.currentPage().getUrl()));
            prLogin.getParameters().put(IECConstants.PARAM_WARNING_MSG, IECUtil.EncryptEncodeParameter(Label.IEC_Warning_Must_Login));
            prLogin.setRedirect(true);
            return prLogin;
        } else {
            
        }
        throw new Controller_Exception('Session ID: ' + UserInfo.getSessionId());
        
        
        return null;
        // first check if the user is logged in
        try {
            if (IECUserManager.isUserLoggedIn() == false) {
                Pagereference prLogin = Page.IECLogin;
                prLogin.getParameters().put(IECConstants.PARAM_RETURN_URL, IECUtil.EncryptEncodeParameter(ApexPages.currentPage().getUrl()));
                prLogin.getParameters().put(IECConstants.PARAM_WARNING_MSG, IECUtil.EncryptEncodeParameter(Label.IEC_Warning_Must_Login));
                prLogin.setRedirect(true);
                return prLogin;
            } else {
                // Validate Logged in user profile and ensure profile is complete
                validUserProfile();
                
                // Make sure to validate user access to application subscription
                ctrSubsInfo.validateAccess(new Set<String>{IECConstants.ProductCategory_SF_EBROADCAST}); 
                System.debug(ctrSubsInfo.hasPageAccess); 
                
                // if no access, redirect to the unauthorized page

		        if (!ctrSubsInfo.hasPageAccess) return Page.IECUnauthorized;
			}
        }
        catch(Exception ex) {
            addErrorMessage(ex.getMessage() + '<br />' + ex.getStackTraceString());
        }

        return null;
    }
*/
}