src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ISSP_CS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ISSP CS</label>
</CustomObject>

src/objects/ISSP_NonTD_Report__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ISSP_ICCS_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted_Date__c</fullName>
        <label>Posted Date</label>
        <type>Date</type>
    </fields>
    <label>ISSP NonTD  Report</label>
    <nameField>
        <displayFormat>NonTD_Rep-{00000}</displayFormat>
        <label>ISSP NonTD Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ISSP NonTD Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Contact__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ISSP_UserTriggerHandler_Test.cls
@isTest
private class ISSP_UserTriggerHandler_Test {

    static testMethod void myUnitTest() {
        //ISSP_ObjectFactory.fiilIncludedFields();
    	String profileId = [SELECT Id FROM Profile WHERE Name = 'ISS Portal DPC' LIMIT 1].Id;
    	//Account acc = (Account)ISSP_ObjectFactory.createSObject('Account',false,4);
    	Account acc = ISSP_ObjectFactory.createNewAccount();
		insert acc;
		//Contact contact = (Contact)ISSP_ObjectFactory.createSObject('Contact',false,1);
		Contact contact = ISSP_ObjectFactory.createNewContact();
        contact.Email = 'test2@test.test';
        contact.AccountId = acc.Id;
        insert contact;

        User newUser = new User(alias = 'dsfsdfds', 
	                            email = contact.email, 
	                            emailencodingkey = 'UTF-8', 
	                            firstname = contact.firstName, 
	                            lastname = contact.lastname, 
	                            languagelocalekey = 'en_US', 
	                            localesidkey = 'en_US', 
	                            contactId = contact.Id,
	                            timezonesidkey = 'Asia/Dubai',
	                            username = contact.email+'dfgdf',
	                            PortalRole = 'Manager',
	                            CommunityNickname = contact.email.substring(0, contact.email.indexOf('@'))+Datetime.now().formatLong().substring(10,15),
	                            ProfileId = profileId,
	                            IsActive = true);
    	insert newUser;

    	Map<Id, String> conEmailMap = new Map<Id, String>();
    	conEmailMap.put(contact.Id, contact.Email);
    	Map<Id, String> conFirstNameMap = new Map<Id, String>();
    	conFirstNameMap.put(contact.Id, contact.Firstname);
    	Map<Id, String> conLastNameMap = new Map<Id, String>();
    	conLastNameMap.put(contact.Id, contact.Lastname);
    	Set<Id> conEmailIdSet = new Set<Id>();
    	conEmailIdSet.add(contact.Id);

    	PortalServiceAccessTriggerHandler.avoidAppTrigger = true;
    	Portal_Applications__c app = new Portal_Applications__c(Name = 'SIS'); 
        insert app;
        Portal_Application_Right__c appRight = new Portal_Application_Right__c(Contact__c = contact.Id, Portal_Application__c = app.Id, Right__c = 'Access Granted');
        insert appRight;
        PortalServiceAccessTriggerHandler.avoidAppTrigger = false;

        ISSP_CS__c cs = new ISSP_CS__c();
        cs.Name='SIS_WebService_ON';
     	insert cs;

    	System.runAs (newUser){
    		Test.startTest();
	    	newUser.email = 'test1234@test.test';
	    	update newUser;	    	

	    	ISSP_UserTriggerHandler.changeEmailFromContact(conEmailMap, conFirstNameMap, conLastNameMap, conEmailIdSet);
	    	ISSP_UserTriggerHandler.updateSIS_permissionSet(conEmailIdSet, conEmailIdSet);

	    	PermissionSet ps = new PermissionSet();
		    ps.Name = 'Test';
		    ps.Label = 'Test';
		    insert ps;

	    	PermissionSetAssignment psa = new PermissionSetAssignment();
		    psa.AssigneeId = UserInfo.getUserId();
		    psa.PermissionSetId = ps.Id;
		    insert psa;
	    	
	    	Set<Id> emptySet = new Set<Id>();
	    	ISSP_UserTriggerHandler.updateUserPermissionSet('Test', conEmailIdSet, conEmailIdSet);
	    	ISSP_UserTriggerHandler.deleteTwoFactor(conEmailIdSet);
	    	ISSP_UserTriggerHandler.updateFederation(conLastNameMap);
	    	ISSP_UserTriggerHandler.updateUserPermissionSet('Test', conEmailIdSet, emptySet);	    	

	    	Test.stopTest();
    	}

    	ISSP_NonTD_Report__c report = new ISSP_NonTD_Report__c();
        report.Posted_Date__c = System.Today();
        report.Account__c = acc.Id;
        insert report;

    	/*ISSP_NonTD_Report__Share newReportShare = new ISSP_NonTD_Report__Share();
		newReportShare.AccessLevel = 'Read';
		newReportShare.ParentId = report.Id;
		newReportShare.UserOrGroupId = newUser.Id;
		insert newReportShare;*/

		ISSP_UserTriggerHandler.addNonTdReportSharing(conEmailIdSet);
    	ISSP_UserTriggerHandler.removeNonTdReportSharing(conEmailIdSet);

    	String thisUsername = [SELECT Id, Email, Username FROM User WHERE Id = :newUser.Id].Username;
    	system.assertEquals(thisUsername, 'test1234.test.test@partner.iata.org');
    }
}