src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Country_of_publication__c</fullName>
        <inlineHelpText>This field serves to identify which countries are concerned with the document; It does not apply filtering to those countries</inlineHelpText>
        <label>Country of publication</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All - Globally</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bonaire</fullName>
                </value>
                <value>
                    <fullName>Bosnia &amp; Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>British Virgin Islands</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Category__c</fullName>
        <label>Document Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accreditation</fullName>
                </value>
                <value>
                    <fullName>Bulletins and News</fullName>
                </value>
                <value>
                    <fullName>Calendars</fullName>
                </value>
                <value>
                    <fullName>Forms and Procedures</fullName>
                </value>
                <value>
                    <fullName>Products and Services</fullName>
                </value>
                <value>
                    <fullName>Resolutions</fullName>
                </value>
                <value>
                    <fullName>Taxation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/ISSP_CS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ISSP CS</label>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ISSP_ctrl_ContentDisplay.cls
public class ISSP_ctrl_ContentDisplay{
    
    public List<ContentVersion> ContentVersion_Lst {get;set;}
    public ContentVersion ConVer{get;set;}
    public String csHost {get;set;}
    //CNS
    public String communityName{ get{ return ApexPages.currentPage().getParameters().get('CommunityName'); }set;}

    public ISSP_ctrl_ContentDisplay(){
    
        string ContentVersionId= Apexpages.currentPage().getParameters().get('id');
        ISSP_CS__c cs = ISSP_CS__c.getInstance('Host');
        String csHost = cs.value__c;
        ContentVersion_Lst =new List<ContentVersion>([select id, Title, Description, FileType,OwnerId,Owner.Name, VersionNumber ,ContentUrl,
                                                         TagCsv ,ContentDocumentId , Country_of_publication__c , Document_Category__c ,ContentSize
                                                   From ContentVersion 
                                                   Where IsLatest = true 
                                                   And ContentDocumentId =: ContentVersionId]);
                                                   
        if(ContentVersion_Lst  != null && ContentVersion_Lst .size() > 0){
            ConVer = ContentVersion_Lst  [0];
        }
    }


}