src/objects/Contact__c.object
<CustomObject>
    <label>Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/One_Id_App_Config_Detail__c.object
<CustomObject>
    <fields>
        <fullName>One_Id_Service_Provider_Config__c</fullName>
        <label>One Id Service Provider Config</label>
        <referenceTo>One_Id_Service_Provider_Config__c</referenceTo>
        <relationshipLabel>One Id App Config Details</relationshipLabel>
        <relationshipName>One_Id_App_Config_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PermissionSet_Provisioning__c</fullName>
        <label>PermissionSet Provisioning</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermissionSet_SSO__c</fullName>
        <label>PermissionSet SSO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>One Id App Config Detail</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>OneId  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>One Id App Config Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/One_Id_Service_Provider_Config__c.object
<CustomObject>
    <fields>
        <fullName>App_Picture_Url__c</fullName>
        <label>App Picture Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Upgrade_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>License Upgrade Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Portal Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Bundle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Bundle</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>notEqual</operation>
                <valueField>One_Id_Service_Provider_Config__c.Id</valueField>
            </filterItems>
            <filterItems>
                <field>One_Id_Service_Provider_Config__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>One_Id_Service_Provider_Config__c</referenceTo>
        <relationshipLabel>One Id Service Providers Config</relationshipLabel>
        <relationshipName>One_Id_Service_Providers_Config</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Provider_Name__c</fullName>
        <label>Service Provider Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>One Id Service Provider Config</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>One Id Service Provider Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>One Id Service Providers Config</pluralLabel>
    <recordTypes>
        <fullName>Service_Bundle</fullName>
        <active>true</active>
        <label>Service Bundle</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Contact__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Invoice_Type__c</fullName>
        <inlineHelpText>Please choose at least one invoice type to give rights</inlineHelpText>
        <label>Invoice Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cass Invoices</fullName>
                </value>
                <value>
                    <fullName>Passenger Invoices</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technical_Provisioning_Status__c</fullName>
        <label>Technical Provisioning Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>IATA Access Granted</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>External Access Granted</fullName>
                </value>
                <value>
                    <fullName>External Access Denied</fullName>
                </value>
                <value>
                    <fullName>IATA Access Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Biller_Direct</fullName>
        <active>true</active>
        <label>Biller Direct</label>
    </recordTypes>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Provisioning_Type__c</fullName>
        <label>Provisioning Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WebService</fullName>
                </value>
                <value>
                    <fullName>SCIM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SCIM_App_Name__c</fullName>
        <description>Name of Salesforce Connected SCIM App Name</description>
        <label>SCIM App Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SAP_Account__c.object
<CustomObject>
    <description>Represents an account on SAP</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SAP Accounts</relationshipLabel>
        <relationshipName>SAP_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SAP_Account_type__c</fullName>
        <description>Represents the type of SAP Invoice type:  Cass Invoices, Passenger Invoices, Invoices, e-Commerce</description>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cass Invoices</fullName>
                </value>
                <value>
                    <fullName>Passenger Invoices</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>e-Commerce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <label>SAP ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SAP Account</label>
    <nameField>
        <displayFormat>SAP-{0000}</displayFormat>
        <label>Internal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SCIM_Prov_Connector__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>FYI_Email__c</fullName>
        <label>FYI Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Processor_Email__c</fullName>
        <label>Processor Email</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>SCIM Prov Connector</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SIS_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SIS Team</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ISSP_Portal_Application_RightTest.cls
@isTest
public class ISSP_Portal_Application_RightTest {

	public static testMethod void myUnitTest_1bis() {
		Portal_Applications__c apptest = new Portal_Applications__c(Name = 'SIS'); 
	    insert apptest;
	}
	
	public static testMethod void myUnitTest_1() {
		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
		thisUser.SIS_Team__c = true;
    	update thisUser;
    	thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
    	system.runAs(thisUser){
			ISSP_ObjectFactory.fiilIncludedFields();
			PermissionSet newPermSet = new PermissionSet(Name = 'ISS_Portal_Permission_Set_SIS_users');
			//Account acc = (Account)ISSP_ObjectFactory.createSObject('Account',false,4);
			Account acc = ISSP_ObjectFactory.createNewAccount();
			insert acc;
			//Contact contact = (Contact)ISSP_ObjectFactory.createSObject('Contact',false,1);
			Contact contact = ISSP_ObjectFactory.createNewContact();
	        contact.AccountId = acc.Id;
	        insert contact;
	        User newUser = new User(alias = 'dsfsdfds', 
		                            email = contact.email, 
		                            emailencodingkey = 'UTF-8', 
		                            firstname = contact.firstName, 
		                            lastname = contact.lastname, 
		                            languagelocalekey = 'en_US', 
		                            localesidkey = 'en_US', 
		                            contactId = contact.Id,
		                            timezonesidkey = 'Asia/Dubai',
		                            username = contact.email+'dfgdf',
		                            PortalRole = 'Manager',
		                            CommunityNickname = contact.email.substring(0, contact.email.indexOf('@'))+Datetime.now().formatLong().substring(10,15),
		                            ProfileId = ISSP_Constant.TEST_User_ProfileID,
		                            IsActive = true);
	    	insert newUser;
			Portal_Applications__c app = new Portal_Applications__c(Name = 'SIS'); 
	        insert app;

	        Portal_Application_Right__c appRight = new Portal_Application_Right__c();
	        appRight.Portal_Application__c = app.Id;
	        appRight.Right__c = 'Access Granted';
	        appRight.Contact__c = contact.Id;
	        insert appRight;
	        appRight.Right__c = 'Access Denied';
	        update appRight;
	        appRight.Right__c = 'Access Granted';
	        update appRight;
        }
	}
	
	public static testMethod void ISSP_Portal_Application_RightTest() {
		User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    	system.runAs(thisUser){
			RecordType rt = [select Id from RecordType where developerName=:'Biller_Direct'];
			//ISSP_ObjectFactory.fiilIncludedFields();
			
			Account acc = ISSP_ObjectFactory.createNewAccount();  
	            //(Account)ISSP_ObjectFactory.createSObject('Account',false,4);
			insert acc;
			
			SAP_Account__c sap = new SAP_Account__c();
	            //(SAP_Account__c)ISSP_ObjectFactory.createSObject('SAP_Account__c',false,3);
			sap.SAP_Account_type__c = 'test';
			sap.Account__c = acc.Id;
			sap.SAP_Id__c = '1234';
			insert sap;
			
			Contact contact = ISSP_ObjectFactory.createNewContact();
	            //(Contact)ISSP_ObjectFactory.createSObject('Contact',false,1);
	         contact.AccountId = acc.Id;
	         insert contact;
	         
	         User newUser = new User(alias = 'dsfsdfds', 
		                            email = contact.email, 
		                            emailencodingkey = 'UTF-8', 
		                            firstname = contact.firstName, 
		                            lastname = contact.lastname, 
		                            languagelocalekey = 'en_US', 
		                            localesidkey = 'en_US', 
		                            contactId = contact.Id,
		                            timezonesidkey = 'Asia/Dubai',
		                            username = contact.email+'dfgdf',
		                            PortalRole = 'Manager',
		                            CommunityNickname = contact.email.substring(0, contact.email.indexOf('@'))+Datetime.now().formatLong().substring(10,15),
		                            ProfileId = ISSP_Constant.TEST_User_ProfileID,
		                            IsActive = true);
	    	insert newUser;
    	

         	Portal_Applications__c app = new Portal_Applications__c(Name = 'Biller Direct'); 
        	insert app;
			//Portal_Application_Right__c par = (Portal_Application_Right__c)ISSP_ObjectFactory.createSObject('Portal_Application_Right__c',false,2);
			Portal_Application_Right__c par = new Portal_Application_Right__c();
	        par.Contact__c = contact.Id;
	        par.Portal_Application__c = app.Id;
	        par.Right__c = 'Access Granted';
	        par.RecordTypeId = rt.Id;
	        par.Invoice_Type__c = 'test';
	        insert par;
         }
         
	}

	public static testMethod void IFGUnitTest() {
		////////////////////////////////
  		// Configurations SET
  		////////////////////////////////
  		SCIM_Prov_Connector__c conf = new SCIM_Prov_Connector__c();
  		conf.Name = 'Test';
  		conf.FYI_Email__c = 'manuel.conde@rightitservices.com';
  		conf.Processor_Email__c = 'manuel.conde@rightitservices.com';
  		conf.SetupOwnerId=UserInfo.getOrganizationId();
  		insert conf;

  		System.debug('basto1p - testConfigObjsInit SCIM_Prov_Connector__c conf='+conf);

  		Id recTypeId = OneIdProvisioningDAO.AppRecordTypesConfig.get('One_Id_Service_Provider_Config__c').get('Service_Bundle');

  		One_Id_Service_Provider_Config__c oi = new One_Id_Service_Provider_Config__c(
  			Service_Provider_Name__c = SCIMServProvManager.PRE_PROD_SRV_PROV,
  			License_Upgrade_Required__c= true,
  			Profile_Id__c='a1',
  			Description__c='qualquer',
  			Is_Active__c = true,
  			Portal_Visible__c = false,
  			RecordTypeid = recTypeId,
  			App_Picture_Url__c='oi');
  		insert oi;

  		System.debug('basto1p - testConfigObjsInit One_Id_Service_Provider_Config__c oi='+oi);

  		One_Id_Service_Provider_Config__c rr =
  		new One_Id_Service_Provider_Config__c (
  			Service_Provider_Name__c = SCIMServProvManager.PRE_PROD_SRV_PROV,
  			Is_Active__c = true,
  			Portal_Visible__c = false,
  			RecordTypeid = recTypeId,
  			Service_Bundle__c=oi.id);
  		insert rr;

  		System.debug('basto1p - testConfigObjsInit One_Id_Service_Provider_Config__c rr='+rr);

  		List<PermissionSet> psIds = [SELECT Id,name FROM PermissionSet LIMIT 5];

  		One_Id_App_Config_Detail__c r =
  		new One_Id_App_Config_Detail__c (
  			One_Id_Service_Provider_Config__c=rr.id,
  			PermissionSet_SSO__c = psIds[0].name,
  			PermissionSet_Provisioning__c = psIds[01].name );
  		insert r;

  		System.debug('basto1p - testConfigObjsInit One_Id_App_Config_Detail__c r='+r);

  		/////////////////////////////////////////////////////////////

  		Account newAccount = ISSP_ObjectFactory.CreateNewAccount();
  		insert newAccount;

  		Contact newContact = ISSP_ObjectFactory.CreateNewContact();
  		newContact.AccountId = newAccount.id;
  		insert newContact;

  		User newPortalUser = ISSP_ObjectFactory.createPortalUser(newContact);

		//Portal_Applications__c app = [SELECT Id,Name,Provisioning_Type__c FROM Portal_Applications__c WHERE Name =:'IFG Production' LIMIT 1];

		Portal_Applications__c app = new Portal_Applications__c(Name = 'IFG Pre-Production', Provisioning_Type__c = 'SCIM', SCIM_App_Name__c = SCIMServProvManager.PRE_PROD_SRV_PROV);
		insert app;

		system.runAs(newPortalUser){

			Portal_Application_Right__c par = new Portal_Application_Right__c();
			par.Contact__c = newContact.Id;
			par.Portal_Application__c = app.Id;
			par.Right__c = 'Access Granted';
			par.Technical_Provisioning_Status__c = 'IATA Access Granted';
			insert par;
			par.Right__c = SCIMServProvManager.IATA_STS_ACCESS_DENIED;
			update par;
            par.Right__c = SCIMServProvManager.IATA_STS_ACCESS_GRANTED;
			update par;
		}
		

	}
}