src/objects/Contact_Role_Service_Access__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Account_Contact_Role__c</referenceTo>
        <relationshipLabel>Contact Role Service Accesses</relationshipLabel>
        <relationshipName>Contact_Role_Service_Accesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Contact Role Service Accesses</relationshipLabel>
        <relationshipName>Contact_Role_Service_Accesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <description>use to uniquely identify a record and to prevent duplicates</description>
        <label>UniqueKey</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Contact Role Service Access</label>
    <nameField>
        <displayFormat>CRSA-{000000}</displayFormat>
        <label>Contact Role Service Access Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Role Service Accesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>IATA services airlines can subscribe for</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactRoleServiceAccessTriggerHandler.cls
public with sharing class ContactRoleServiceAccessTriggerHandler {

    public void OnBeforeInsert(List<Contact_Role_Service_Access__c> newObjects) {
        for(Contact_Role_Service_Access__c newObject : newObjects) {
            newObject.UniqueKey__c = String.ValueOf(newObject.Service__c).left(15) + '_' + String.valueOf(newObject.Contact_Role__c).left(15);
        }
    }

    public void OnBeforeUpdate(List<Contact_Role_Service_Access__c> oldObjects, List<Contact_Role_Service_Access__c> updatedObjects, Map<Id, Contact_Role_Service_Access__c> oldMap) {
        for(Contact_Role_Service_Access__c newObject : updatedObjects) {
            Contact_Role_Service_Access__c oldObject = oldMap.get(newObject.Id);
            if((oldObject.Service__c != newObject.Service__c) || (oldObject.Contact_Role__c != newObject.Contact_Role__c)) {
                newObject.UniqueKey__c = String.ValueOf(newObject.Service__c).left(15) + '_' + String.valueOf(newObject.Contact_Role__c).left(15);
            }
        }
    }

}