src/objects/EBC_Email_Exclusion__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>The Email Address to opt out</description>
        <externalId>true</externalId>
        <inlineHelpText>The Email Address to opt out</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>EBC Email Exclusion</label>
    <nameField>
        <label>EBC Exclusion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBC Email Exclusions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDP_Products_Account_View__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>GDP Products - Account View</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GDP Products - Accounts View</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ID_Card__c.object
<CustomObject>
    <description>ID Cards information
two record types:
1- AIMS (default) contains AIMS data (SFDC is the master data)
2- WebStar contains WebStar data (WebStar is master data)</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>GDP_Products_Account_View__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GDP Products - Account View</label>
        <referenceTo>GDP_Products_Account_View__c</referenceTo>
        <relationshipLabel>ID Cards</relationshipLabel>
        <relationshipName>ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_on_ID_Card__c</fullName>
        <label>Name on ID Card</label>
        <length>22</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ID Card</label>
    <nameField>
        <displayFormat>IDC-{000000000}</displayFormat>
        <label>ID Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ID Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SchdlIECEBCEmailExclusionRelationTest.cls
@isTest
private class SchdlIECEBCEmailExclusionRelationTest {

    static testMethod void testBatch() {

        EBC_Email_Exclusion__c ee1 = new EBC_Email_Exclusion__c();
        ee1.Is_Relation_Created__c = true;
        ee1.Email__c = 'email@ebc.com';
        insert ee1;

        EBC_Email_Exclusion__c ee2 = new EBC_Email_Exclusion__c();
        ee2.Is_Relation_Created__c = true;
        ee2.Email__c = 'card@ebc.com';
        insert ee2;

        GDP_Products_Account_View__c gav = new GDP_Products_Account_View__c();
        gav.Email_Address__c = 'email@ebc.com';
        insert gav;

        ID_Card__c idc = new ID_Card__c();
        idc.Email__c = 'card@ebc.com';
        idc.Name_on_ID_Card__c = 'name on card';
        insert idc;

        Test.startTest();

        SchdlIECEBCEmailExclusionRelation obj1 = new SchdlIECEBCEmailExclusionRelation();
        DataBase.executeBatch(obj1);

        SchdlIECEBCEmailExclusionRelation sh1 = new SchdlIECEBCEmailExclusionRelation();
        String sch = '0 0 23 * * ?'; system.schedule('Test', sch, sh1);

        Test.stopTest();

    }
}