src/objects/EBC_Activity__c.object
<CustomObject>
    <description>This custom object contains all history of e-mail credit transactions per campain on eBroadcast - how many e-mails credits were sent out (expensed), how many credits were adjusted, how many credits were received.</description>
    <fields>
        <fullName>Activity_Date_Time__c</fullName>
        <description>This fields logs the date and time when the activity on the account took place.</description>
        <inlineHelpText>This fields logs the date and time when the activity on the account took place.</inlineHelpText>
        <label>Activity Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <description>This field sets the type of activity performed on the e-mail credit.</description>
        <inlineHelpText>This field sets the type of activity performed on the e-mail credit.</inlineHelpText>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EBC_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EBC Campaign</label>
        <referenceTo>EBC_Campaign__c</referenceTo>
        <relationshipLabel>EBC Activities</relationshipLabel>
        <relationshipName>EBC_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Billing_Account__c</fullName>
        <description>This field links the EBC Activity to the Billing Account.</description>
        <label>Related Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>EBC Activities</relationshipLabel>
        <relationshipName>EBC_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Count__c</fullName>
        <description>This field contains the number of credits sent, credited or adjusted.</description>
        <inlineHelpText>This field contains the number of credits sent, credited or adjusted.</inlineHelpText>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EBC Activity</label>
    <nameField>
        <label>EBC Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBC Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EBC_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Billing Account that pay for that campaign</description>
        <inlineHelpText>The Billing Account that pay for that campaign</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>EBC Campaigns</relationshipLabel>
        <relationshipName>EBC_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EBC Campaign</label>
    <nameField>
        <label>eBroadcast Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBC Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EBC_Email_Exclusion__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Event Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Campaign</label>
        <referenceTo>EBC_Campaign__c</referenceTo>
        <relationshipLabel>EBC Email Exclusions</relationshipLabel>
        <relationshipName>EBC_Email_Exclusions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of exclusion</description>
        <inlineHelpText>Type of exclusion</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>OPTOUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HARDBOUNCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LISTDETECTIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>EBC Email Exclusion</label>
    <nameField>
        <label>EBC Exclusion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EBC Email Exclusions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EBC_Email_Exclusion_TriggerHandler.cls
public class EBC_Email_Exclusion_TriggerHandler {
    // http://help.marketingcloud.com/en/documentation/exacttarget/interactions/email_messages/email_send_error_codes/
    public static Boolean isEmailExclusionGenerateCredit(EBC_Email_Exclusion__c ee) {
        if (ee.Type__c == 'HARDBOUNCE') return true;
        if (ee.Type__c == 'LISTDETECTIVE') return true;

        return false;
    }
    public static void creditHardBounce(List<EBC_Email_Exclusion__c> ees) {
        
        List<Id> campaignsId = new List<Id>();
        
        for(EBC_Email_Exclusion__c ee : ees) {
            if (!isEmailExclusionGenerateCredit(ee)) continue;
            campaignsId.add(ee.Source_Campaign__c);
        }
        
        if (campaignsId.size() == 0) return ;
        
        Map<Id, EBC_Campaign__c> campaigns = new Map<Id, EBC_Campaign__c>([Select Id, Billing_Account__c From EBC_Campaign__c Where Id in :campaignsId]);
        
        Map<Id, EBC_Activity__c> campaignActivity = new Map<Id, EBC_Activity__c>();
        
        for(EBC_Email_Exclusion__c ee : ees) {
            if (!isEmailExclusionGenerateCredit(ee)) continue;
            
            EBC_Activity__c a;
            if (campaignActivity.containsKey(ee.Source_Campaign__c)) {
                a = campaignActivity.get(ee.Source_Campaign__c);
            } else {
                a = new EBC_Activity__c(
                    name = ee.Type__c,
                    Activity_Date_Time__c = ee.Event_Date__c,
                    Activity_Type__c = 'Adjustment',
                    EBC_Campaign__c = ee.Source_Campaign__c,
                    Total_Count__c = 0,
                    Related_Billing_Account__c = campaigns.get(ee.Source_Campaign__c).Billing_Account__c,
	                Reason__c = ee.Type__c
                );
            }
            
            a.Total_Count__c++;
            
            campaignActivity.put(ee.Source_Campaign__c, a);
        }
        
        if (campaignActivity.size() == 0) return ;
        insert campaignActivity.values();
    }
}