src/objects/IATA_Process_Orchestrator__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case Associated</description>
        <label>Associated Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>IATA Processes Orchestrator</relationshipLabel>
        <relationshipName>IATA_Processes_Orchestrator</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IATA_Orchestrator_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to IATA Process Orchestrator</description>
        <label>IATA Orchestrator Process</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IATA_Process_Orchestrator__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Orchestrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IATA_Process_Orchestrator__c</referenceTo>
        <relationshipLabel>IATA Orchestrator Processes</relationshipLabel>
        <relationshipName>IATA_Orchestrator_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <description>This field is the overall status of all stages</description>
        <label>Overall Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Step_Name__c</fullName>
        <description>Holds the name of a given step in a Business Process Name</description>
        <label>Process Step Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status about process</description>
        <formula>IF( Total_Actions_Pending_Customer__c &gt; 0 , &apos;Pending Customer&apos;, 
IF( Total_Actions_Failed__c &gt; 0, &apos;Fail&apos;,
IF( Total_Actions_Completed__c = Total_Number_of_Actions__c, &apos;Completed&apos;, 
IF( OR(Total_Actions_Progressing__c &gt; 0, Total_Actions_Completed__c &gt; 0), &apos;Progressing&apos;, &apos;Not Started&apos;))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>IATA Process Orchestrator</label>
    <nameField>
        <displayFormat>IO-{000000}</displayFormat>
        <label>IATA Process Orchestrator No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IATA Processes Orchestrator</pluralLabel>
    <recordTypes>
        <fullName>Orchestrator</fullName>
        <active>true</active>
        <description>Record Type to hold IATA Orchestrator Process</description>
        <label>Orchestrator</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IATA_Process_Orchestrator_Step_Action__c.object
<CustomObject>
    <fields>
        <fullName>Action_name__c</fullName>
        <label>Action name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Associated_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>IATA Process Orchestrator Step Actions</relationshipLabel>
        <relationshipName>IATA_Process_Orchestrator_Step_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IATA_Process_Orchestrator__c</fullName>
        <label>IATA Process Orchestrator</label>
        <referenceTo>IATA_Process_Orchestrator__c</referenceTo>
        <relationshipLabel>IATA Process Orchestrator Step Actions</relationshipLabel>
        <relationshipName>IATA_Process_Orchestrator_Step_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Stage_Status</valueSetName>
        </valueSet>
    </fields>
    <label>IATA Process Orchestrator Step Action</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>IATA Process Orchestrator Step Action Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IATA Process Orchestrator Step Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Stage_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Progressing</fullName>
    </customValue>
    <customValue>
        <fullName>Fail</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Customer</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Stage Status</masterLabel>
</GlobalValueSet>

src/classes/ISSP_AMC_OrchestratorHandler_Test.cls
@isTest
public class ISSP_AMC_OrchestratorHandler_Test {

	@isTest static void testOrchestrator() {

		ISSP_AMC_ParticipationFactory.createcustomSetting(true);
		ISSP_AMC_ParticipationFactory.createLocationIdentifierRequirements(true);
		//ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true, 'Off-line Point', false);

		User myUser = [select Id from User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

		Test.StartTest();
		System.runAs(myUser){

			User portalUser = ISSP_AMC_ParticipationFactory.portalSetup();

			System.runAs(portalUser){

				PageReference pageRef = Page.ISSP_AMC_Location_Identifier;
				Test.setCurrentPageReference(pageRef);
				pageRef.getParameters().put('participationId',
						ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true,
								'Off-line Point', false).Id);
				ISSP_AMC_Location_Identifier controller = new ISSP_AMC_Location_Identifier();
				controller.step = 'Submit';
				controller.saveParticipation();

				IATA_Process_Orchestrator__c orchestrator = new IATA_Process_Orchestrator__c();
				orchestrator.associated_case__c = controller.participation.case__c;
				orchestrator.RecordTypeId = [SELECT Id,Name FROM RecordType WHERE Name='Orchestrator'][0].Id;
				//orchestrator.Process_Step_Name__c = 'TESTE 1';
				insert orchestrator;

				IATA_Process_Orchestrator__c orchestratorSon = createOrchSon(controller, orchestrator);

				IATA_Process_Orchestrator_Step_Action__c action = createActionpOrch(orchestratorSon,'Completed');


				List<IATA_Process_Orchestrator__c> oneOrchestratorList = [SELECT Status__c, IATA_Orchestrator_Process__r.Overall_Status__c, IATA_Orchestrator_Process__c
																		  FROM IATA_Process_Orchestrator__c 
																		  WHERE id =: orchestrator.Id];


				Test.stopTest();

				/*Test.startTest();
				action2.Status__c = 'Fail';
				update action2;
				Test.stopTest();

				System.assertEquals(oneOrchestrator.IATA_Orchestrator_Process__r.Overall_Status__c, 'Fail');*/
			}
		}
	}

	@isTest static void testOrchestratorSec() {

		ISSP_AMC_ParticipationFactory.createcustomSetting(true);
		ISSP_AMC_ParticipationFactory.createLocationIdentifierRequirements(true);
		//ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true, 'Off-line Point', false);

		User myUser = [select Id from User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

		Test.StartTest();
		System.runAs(myUser){

			User portalUser = ISSP_AMC_ParticipationFactory.portalSetup();

			System.runAs(portalUser){

				PageReference pageRef = Page.ISSP_AMC_Location_Identifier;
				Test.setCurrentPageReference(pageRef);
				pageRef.getParameters().put('participationId',
						ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true,
								'Off-line Point', false).Id);
				ISSP_AMC_Location_Identifier controller = new ISSP_AMC_Location_Identifier();
				controller.step = 'Submit';
				controller.saveParticipation();

				IATA_Process_Orchestrator__c orchestrator = new IATA_Process_Orchestrator__c();
				orchestrator.associated_case__c = controller.participation.case__c;
				orchestrator.RecordTypeId = [SELECT Id,Name FROM RecordType WHERE Name='Orchestrator'][0].Id;
				//orchestrator.Process_Step_Name__c = 'TESTE 1';
				insert orchestrator;

				IATA_Process_Orchestrator__c orchestratorSon = createOrchSon(controller, orchestrator);

				//IATA_Process_Orchestrator_Step_Action__c action = createActionpOrch(orchestratorSon,'Completed');
				//actionList.add(action);

				//IATA_Process_Orchestrator_Step_Action__c action2 = createActionpOrch(orchestratorSon,'Pending Customer');

				//IATA_Process_Orchestrator_Step_Action__c action3 = createActionpOrch(orchestratorSon,'Fail');

				IATA_Process_Orchestrator_Step_Action__c action4 = createActionpOrch(orchestratorSon,'Progressing');

				//IATA_Process_Orchestrator_Step_Action__c action5 = createActionpOrch(orchestratorSon,'Not Applicable');


				List<IATA_Process_Orchestrator__c> oneOrchestratorList = [SELECT Status__c, IATA_Orchestrator_Process__r.Overall_Status__c, IATA_Orchestrator_Process__c
						FROM IATA_Process_Orchestrator__c
						WHERE id =: orchestrator.Id];


				Test.stopTest();

				/*Test.startTest();
				action2.Status__c = 'Fail';
				update action2;
				Test.stopTest();

				System.assertEquals(oneOrchestrator.IATA_Orchestrator_Process__r.Overall_Status__c, 'Fail');*/
			}
		}
	}

	@isTest static void testOrchestratorT() {

		ISSP_AMC_ParticipationFactory.createcustomSetting(true);
		ISSP_AMC_ParticipationFactory.createLocationIdentifierRequirements(true);
		//ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true, 'Off-line Point', false);

		User myUser = [select Id from User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

		Test.StartTest();
		System.runAs(myUser){

			User portalUser = ISSP_AMC_ParticipationFactory.portalSetup();

			System.runAs(portalUser){

				PageReference pageRef = Page.ISSP_AMC_Location_Identifier;
				Test.setCurrentPageReference(pageRef);
				pageRef.getParameters().put('participationId',
						ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true,
								'Off-line Point', false).Id);
				ISSP_AMC_Location_Identifier controller = new ISSP_AMC_Location_Identifier();
				controller.step = 'Submit';
				controller.saveParticipation();

				IATA_Process_Orchestrator__c orchestrator = new IATA_Process_Orchestrator__c();
				orchestrator.associated_case__c = controller.participation.case__c;
				orchestrator.RecordTypeId = [SELECT Id,Name FROM RecordType WHERE Name='Orchestrator'][0].Id;
				//orchestrator.Process_Step_Name__c = 'TESTE 1';
				insert orchestrator;

				IATA_Process_Orchestrator__c orchestratorSon = createOrchSon(controller, orchestrator);

				//IATA_Process_Orchestrator_Step_Action__c action = createActionpOrch(orchestratorSon,'Completed');
				//actionList.add(action);

				//IATA_Process_Orchestrator_Step_Action__c action2 = createActionpOrch(orchestratorSon,'Pending Customer');

				//IATA_Process_Orchestrator_Step_Action__c action3 = createActionpOrch(orchestratorSon,'Fail');

				IATA_Process_Orchestrator_Step_Action__c action4 = createActionpOrch(orchestratorSon,'Pending Customer');

				//IATA_Process_Orchestrator_Step_Action__c action5 = createActionpOrch(orchestratorSon,'Not Applicable');


				List<IATA_Process_Orchestrator__c> oneOrchestratorList = [SELECT Status__c, IATA_Orchestrator_Process__r.Overall_Status__c, IATA_Orchestrator_Process__c
						FROM IATA_Process_Orchestrator__c
						WHERE id =: orchestrator.Id];


				Test.stopTest();

				/*Test.startTest();
				action2.Status__c = 'Fail';
				update action2;
				Test.stopTest();

				System.assertEquals(oneOrchestrator.IATA_Orchestrator_Process__r.Overall_Status__c, 'Fail');*/
			}
		}
	}

	@isTest static void testOrchestratorF() {

		ISSP_AMC_ParticipationFactory.createcustomSetting(true);
		ISSP_AMC_ParticipationFactory.createLocationIdentifierRequirements(true);
		//ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true, 'Off-line Point', false);

		User myUser = [select Id from User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

		Test.StartTest();
		System.runAs(myUser){

			User portalUser = ISSP_AMC_ParticipationFactory.portalSetup();

			System.runAs(portalUser){

				PageReference pageRef = Page.ISSP_AMC_Location_Identifier;
				Test.setCurrentPageReference(pageRef);
				pageRef.getParameters().put('participationId',
						ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true,
								'Off-line Point', false).Id);
				ISSP_AMC_Location_Identifier controller = new ISSP_AMC_Location_Identifier();
				controller.step = 'Submit';
				controller.saveParticipation();

				IATA_Process_Orchestrator__c orchestrator = new IATA_Process_Orchestrator__c();
				orchestrator.associated_case__c = controller.participation.case__c;
				orchestrator.RecordTypeId = [SELECT Id,Name FROM RecordType WHERE Name='Orchestrator'][0].Id;
				//orchestrator.Process_Step_Name__c = 'TESTE 1';
				insert orchestrator;

				IATA_Process_Orchestrator__c orchestratorSon = createOrchSon(controller, orchestrator);

				IATA_Process_Orchestrator_Step_Action__c action3 = createActionpOrch(orchestratorSon,'Fail');

				List<IATA_Process_Orchestrator__c> oneOrchestratorList = [SELECT Status__c, IATA_Orchestrator_Process__r.Overall_Status__c, IATA_Orchestrator_Process__c
						FROM IATA_Process_Orchestrator__c
						WHERE id =: orchestrator.Id];


				Test.stopTest();

				/*Test.startTest();
				action2.Status__c = 'Fail';
				update action2;
				Test.stopTest();

				System.assertEquals(oneOrchestrator.IATA_Orchestrator_Process__r.Overall_Status__c, 'Fail');*/
			}
		}
	}

	@isTest static void testOrchestratorFF() {

		ISSP_AMC_ParticipationFactory.createcustomSetting(true);
		ISSP_AMC_ParticipationFactory.createLocationIdentifierRequirements(true);
		//ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true, 'Off-line Point', false);

		User myUser = [select Id from User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

		Test.StartTest();
		System.runAs(myUser){

			User portalUser = ISSP_AMC_ParticipationFactory.portalSetup();

			System.runAs(portalUser){

				PageReference pageRef = Page.ISSP_AMC_Location_Identifier;
				Test.setCurrentPageReference(pageRef);
				pageRef.getParameters().put('participationId',
						ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true,
								'Off-line Point', false).Id);
				ISSP_AMC_Location_Identifier controller = new ISSP_AMC_Location_Identifier();
				controller.step = 'Submit';
				controller.saveParticipation();

				IATA_Process_Orchestrator__c orchestrator = new IATA_Process_Orchestrator__c();
				orchestrator.associated_case__c = controller.participation.case__c;
				orchestrator.RecordTypeId = [SELECT Id,Name FROM RecordType WHERE Name='Orchestrator'][0].Id;
				//orchestrator.Process_Step_Name__c = 'TESTE 1';
				insert orchestrator;

				IATA_Process_Orchestrator__c orchestratorSon = createOrchSon(controller, orchestrator);

				IATA_Process_Orchestrator_Step_Action__c action5 = createActionpOrch(orchestratorSon,'Not Applicable');


				List<IATA_Process_Orchestrator__c> oneOrchestratorList = [SELECT Status__c, IATA_Orchestrator_Process__r.Overall_Status__c, IATA_Orchestrator_Process__c
						FROM IATA_Process_Orchestrator__c
						WHERE id =: orchestrator.Id];


				Test.stopTest();

				/*Test.startTest();
				action2.Status__c = 'Fail';
				update action2;
				Test.stopTest();

				System.assertEquals(oneOrchestrator.IATA_Orchestrator_Process__r.Overall_Status__c, 'Fail');*/
			}
		}
	}

	@isTest static void testOrchestratorSS() {

		ISSP_AMC_ParticipationFactory.createcustomSetting(true);
		ISSP_AMC_ParticipationFactory.createLocationIdentifierRequirements(true);
		//ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true, 'Off-line Point', false);

		User myUser = [select Id from User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

		Test.StartTest();
		System.runAs(myUser){

			User portalUser = ISSP_AMC_ParticipationFactory.portalSetup();

			System.runAs(portalUser){

				PageReference pageRef = Page.ISSP_AMC_Location_Identifier;
				Test.setCurrentPageReference(pageRef);
				pageRef.getParameters().put('participationId',
						ISSP_AMC_ParticipationFactory.createLocationIdentifierParticipation('ParName', true,
								'Off-line Point', false).Id);
				ISSP_AMC_Location_Identifier controller = new ISSP_AMC_Location_Identifier();
				controller.step = 'Submit';
				controller.saveParticipation();

				IATA_Process_Orchestrator__c orchestrator = new IATA_Process_Orchestrator__c();
				orchestrator.associated_case__c = controller.participation.case__c;
				orchestrator.RecordTypeId = [SELECT Id,Name FROM RecordType WHERE Name='Orchestrator'][0].Id;
				//orchestrator.Process_Step_Name__c = 'TESTE 1';
				insert orchestrator;

				IATA_Process_Orchestrator__c orchestratorSon = createOrchSon(controller, orchestrator);

				IATA_Process_Orchestrator_Step_Action__c action5 = createActionpOrch(orchestratorSon,'Not Started');


				List<IATA_Process_Orchestrator__c> oneOrchestratorList = [SELECT Status__c, IATA_Orchestrator_Process__r.Overall_Status__c, IATA_Orchestrator_Process__c
						FROM IATA_Process_Orchestrator__c
						WHERE id =: orchestrator.Id];


				Test.stopTest();

				/*Test.startTest();
				action2.Status__c = 'Fail';
				update action2;
				Test.stopTest();

				System.assertEquals(oneOrchestrator.IATA_Orchestrator_Process__r.Overall_Status__c, 'Fail');*/
			}
		}
	}

	public static IATA_Process_Orchestrator_Step_Action__c createActionpOrch(IATA_Process_Orchestrator__c orch, String status) {
		IATA_Process_Orchestrator_Step_Action__c orchStepAction = new IATA_Process_Orchestrator_Step_Action__c();
		orchStepAction.Status__c = status;
		orchStepAction.IATA_Process_Orchestrator__c = orch.Id;
		orchStepAction.Action_name__c = 'Scheduled Airlines';
		insert orchStepAction;
		return orchStepAction;
	}

	public static IATA_Process_Orchestrator__c createOrchSon(ISSP_AMC_Location_Identifier controller,IATA_Process_Orchestrator__c orchestrator) {
		IATA_Process_Orchestrator__c orchestratorSon = new IATA_Process_Orchestrator__c();
		orchestratorSon.associated_case__c = controller.participation.case__c;
		orchestratorSon.RecordTypeId = [SELECT Id,Name FROM RecordType WHERE Name='IATA Process Step'][0].Id;
		orchestratorSon.IATA_Orchestrator_Process__c = orchestrator.Id;
		orchestratorSon.Process_Step_Name__c = 'TESTE Son 1';
		insert orchestratorSon;
		return orchestratorSon;
	}
}