src/objects/IEC_ZuoraPricing2SAP_Tracking__c.object
<CustomObject>
    <description>Track Zuora prices sent to SAP</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for discount</description>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <description>Currency for pricing</description>
        <label>Currency</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerType__c</fullName>
        <description>Type of customer for pricing</description>
        <label>Customer Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndingUnit__c</fullName>
        <description>Ending unit of range</description>
        <label>Ending Unit</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsFreeShipping__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is free shipping discount</description>
        <label>Is Free Shipping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPreSale__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is pre-sales discount</description>
        <label>Is Pre Sale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region for discount</description>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartingUnit__c</fullName>
        <description>Starting unit of range</description>
        <label>Starting Unit</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <label>ZuoraPricing2SAP Price</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>IEC ZuoraPricing2SAP Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZuoraPricing2SAP Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ZProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ZProduct</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>ZProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveEndDate__c</fullName>
        <description>The Effective End Date of the Product.</description>
        <inlineHelpText>The Effective End Date of the Product.</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveStartDate__c</fullName>
        <description>The Effective Start Date of the Product.</description>
        <inlineHelpText>The Effective Start Date of the Product.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Couponcode__c</fullName>
        <label>Coupon code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerType__c</fullName>
        <label>CustomerType</label>
        <picklist>
            <picklistValues>
                <fullName>Member Airline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited Training Schools (ATS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited Training Center (ATC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Agents (Platinum)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Agents (Gold)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Agents (Genric)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Partners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IATA Employees (work related reason)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IATA Employee (commercial purposes)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IATA Training &amp; Development Institute</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsFreeShipping__c</fullName>
        <label>IsFreeShipping</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsPreSale__c</fullName>
        <label>IsPreSale</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Africa &amp; Middle East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia &amp; Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China &amp; North Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveEndDate__c</fullName>
        <description>The Effective End Date of the Rate Plan.</description>
        <inlineHelpText>The Effective End Date of the Rate Plan.</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveStartDate__c</fullName>
        <description>The Effective Start Date of the Rate Plan.</description>
        <inlineHelpText>The Effective Start Date of the Rate Plan.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>ZRatePlan_CouponCode__c</fullName>
        <formula>zqu__ProductRatePlan__r.Couponcode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ZRatePlan_CouponCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Model__c</fullName>
        <description>The Model of the Rate Plan Charge.</description>
        <inlineHelpText>The Model of the Rate Plan Charge.</inlineHelpText>
        <label>Model</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flat Fee</fullName>
                </value>
                <value>
                    <fullName>Per Unit</fullName>
                </value>
                <value>
                    <fullName>Volume</fullName>
                </value>
                <value>
                    <fullName>Tiered</fullName>
                </value>
                <value>
                    <fullName>Overage</fullName>
                </value>
                <value>
                    <fullName>Tiered with Overage</fullName>
                </value>
                <value>
                    <fullName>Discount-Fixed Amount</fullName>
                </value>
                <value>
                    <fullName>Discount-Percentage</fullName>
                </value>
                <value>
                    <fullName>Flat Fee Pricing</fullName>
                </value>
                <value>
                    <fullName>Per Unit Pricing</fullName>
                </value>
                <value>
                    <fullName>Overage Pricing</fullName>
                </value>
                <value>
                    <fullName>Tiered Pricing</fullName>
                </value>
                <value>
                    <fullName>Tiered with Overage Pricing</fullName>
                </value>
                <value>
                    <fullName>Volume Pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Type__c</fullName>
        <description>The Type of the Rate Plan Charge.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanChargeTier__c.object
<CustomObject>
   
    <fields>
        <fullName>zqu__Currency__c</fullName>
        <label>Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__EndingUnit__c</fullName>
        <label>EndingUnit</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlanCharge__c</fullName>
        <label>Product Rate Plan Charge</label>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Product RatePlan Charge Tier</relationshipLabel>
        <relationshipName>Product_RatePlan_Charge_Tier</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__StartingUnit__c</fullName>
        <label>StartingUnit</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <label>Product RatePlan Charge Tier</label>
    <nameField>
        <label>Tier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product RatePlan Charge Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IEC_ZuoraPricing2SAP_Batch.cls
global class IEC_ZuoraPricing2SAP_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful
{
    //****************************************************************************************************
    //  Batch to send Zuora pricing to SAP
    //****************************************************************************************************
    public static final String processingStep1 = 'Track changes';
    public static final String processingStep2 = 'Send to SAP';
    String strProcessingStep;
    Map<Id, Product2> mapZProductId_Product;


    // constructor - used to specify step to execute
    global IEC_ZuoraPricing2SAP_Batch(String strRequestStep)
    {
        strProcessingStep = strRequestStep;
    }



    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        if (strProcessingStep == processingStep1)
        {
            // get products to track Zuora pricing
            mapZProductId_Product = new IEC_ZuoraPricing2SAP_Svc().getTrackingProduct();
            
            // query Zuora pricing to track
            return Database.getQueryLocator([select Id, CurrencyIsoCode, IsDeleted
                      , LastModifiedDate
                      , zqu__Deleted__c
                      , zqu__Currency__c
                      , zqu__StartingUnit__c
                      , zqu__EndingUnit__c
                      , zqu__Price__c
                      , zqu__ProductRatePlanCharge__c
                      , zqu__ProductRatePlanCharge__r.LastModifiedDate
                      , zqu__ProductRatePlanCharge__r.zqu__Deleted__c
                      , zqu__ProductRatePlanCharge__r.zqu__Model__c
                      , zqu__ProductRatePlanCharge__r.zqu__Type__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.LastModifiedDate
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__Deleted__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__EffectiveStartDate__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__EffectiveEndDate__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.CustomerType__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.Couponcode__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.Country__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.Region__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.IsFreeShipping__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.IsPreSale__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__ZProduct__c
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__ZProduct__r.LastModifiedDate
                      , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__ZProduct__r.zqu__Deleted__c
                      from zqu__ProductRatePlanChargeTier__c
                      where zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__ZProduct__c in :mapZProductId_Product.keySet()
                        and zqu__ProductRatePlanCharge__r.zqu__Type__c in ('One-Time', 'Recurring')
                        and ZRatePlan_CouponCode__c = null
                        and zqu__ProductRatePlanCharge__r.zqu__Model__c in ('Per Unit', 'Per Unit Pricing', 'Volume', 'Volume Pricing'
                                                                          , 'Discount-Fixed Amount', 'Discount-Percentage')
                      order by zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__ZProduct__c
                             , zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__c
                             , zqu__ProductRatePlanCharge__c
                             , zqu__Tier__c
                      ALL ROWS]);
        }
        else if (strProcessingStep == processingStep2)
        {
            // should order tracked data by operation to send the deletion first to prevent possible conflicts on SAP
            return Database.getQueryLocator([select Operation__c, Material_Number__c, CustomerType__c, Currency__c
                                                  , Pricing_Type__c, EffectiveFrom__c, EffectiveTo__c
                                                  , StartingUnit__c, EndingUnit__c, AmountOrPercentage__c
                                             from IEC_ZuoraPricing2SAP_Tracking__c
                                             where SendingTimestamp__c = null
                                             order by Operation__c, Material_Number__c, Id]);
        }
        else
            // when batch was wrongly invoked
            return Database.getQueryLocator([select Id from Product2 where Id = null]);
    }


    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        IEC_ZuoraPricing2SAP_Svc svc = new IEC_ZuoraPricing2SAP_Svc();
        // save changed pricing information to tracking table 
        if (strProcessingStep == processingStep1 && scope.size() > 0)
            svc.trackPricing((List<zqu__ProductRatePlanChargeTier__c>)scope, mapZProductId_Product);
        // send pricing information to SAP
        else if (strProcessingStep == processingStep2 && scope.size() > 0)
            svc.sendPricing((List<IEC_ZuoraPricing2SAP_Tracking__c>)scope);
    }


    global void finish(Database.BatchableContext BC) 
    {
        // send pricing to SAP after tracking changes
        if (strProcessingStep == processingStep1)
            Database.executeBatch(new IEC_ZuoraPricing2SAP_Batch(processingStep2), 2000);
        // send notification to support after sending pricing to SAP
        else if (strProcessingStep == processingStep2 && Boolean.valueOf(Utility.getTextSetting('ZuoraPricing2SAP Notify Job Completion')))
            TransformationHelper.sendEmailSupport('Zuora Pricing 2 SAP', 'Job complete at ' + system.now().format('yyyy-MM-dd HH:mm:ss'));
    }
}