src/objects/IEC_Event_Release__c.object
<CustomObject>
    <description>IEC - Contain releases (versions of renewal) for event subscriptions</description>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <description>IEC - Type of customer to query subscribed customers for renewal</description>
        <label>Customer Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accredited Training Center (ATC)</fullName>
                </value>
                <value>
                    <fullName>Accredited Training Schools (ATS)</fullName>
                </value>
                <value>
                    <fullName>IATA Employee (commercial purposes)</fullName>
                </value>
                <value>
                    <fullName>IATA Employees (work related reason)</fullName>
                </value>
                <value>
                    <fullName>IATA Training &amp; Development Institute</fullName>
                </value>
                <value>
                    <fullName>Member Airline</fullName>
                </value>
                <value>
                    <fullName>Non-member</fullName>
                </value>
                <value>
                    <fullName>Sales Agents (Genric)</fullName>
                </value>
                <value>
                    <fullName>Sales Agents (Gold)</fullName>
                </value>
                <value>
                    <fullName>Sales Agents (Platinum)</fullName>
                </value>
                <value>
                    <fullName>Strategic Partners</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IEC - Latest version of product subscribed to auto-renew</description>
        <label>Product Last Version</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>IEC Event Releases (Product Last Version)</relationshipLabel>
        <relationshipName>IEC_Event_Releases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Material_Number__c</fullName>
        <description>IEC - SAP material number of the product subscribed to auto-renew</description>
        <formula>Left( Product__r.SAP_Material_Number__c,4 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nb_Customer__c</fullName>
        <description>IEC - Number of customers eligible to auto-renew</description>
        <label># Customers</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processing_Message__c</fullName>
        <description>IEC - Message to inform user the processing step</description>
        <formula>IF( Sales_Amout__c&gt;0,&apos;&apos;,&apos;BATCH JOB IN PROGRESS TO GENERATE ORDERS&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <description>IEC - Message to inform user the processing step</description>
        <label>Processing Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Last_Version__c</fullName>
        <description>IEC - SAP material number of the latest version of product subscribed to auto-renew</description>
        <formula>Last_Version__r.SAP_Material_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Last Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <description>IEC - SAP material number of product to renew</description>
        <formula>IF(ISBLANK( Swapped_Product__c ),  Last_Version__r.SAP_Material_Number__c ,  Swapped_Product__r.SAP_Material_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IEC - Subscribed product to auto-renew</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>IEC Event Releases</relationshipLabel>
        <relationshipName>IEC_Event_Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Released__c</fullName>
        <defaultValue>false</defaultValue>
        <description>IEC - Indicate if event for auto-renew is released</description>
        <label>Released</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Amout__c</fullName>
        <description>IEC - Sales amount for the event</description>
        <label>Sales Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Quantity__c</fullName>
        <description>IEC - Total quantity needed for the event</description>
        <label>Sales Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Swapped_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IEC - Product that replaces the product subscribed to auto-renew</description>
        <label>Swapped Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>IEC Event Releases (Swapped Product)</relationshipLabel>
        <relationshipName>IEC_Event_Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IEC Event Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IEC Event Releases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IEC_EventRelease_Sel.cls
public without sharing class IEC_EventRelease_Sel extends Selector {
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
			IEC_Event_Release__c.Id,
			IEC_Event_Release__c.Name,
			IEC_Event_Release__c.Nb_Customer__c,
			IEC_Event_Release__c.Product__c,
			IEC_Event_Release__c.Material_Number__c,
			IEC_Event_Release__c.Last_Version__c,
			IEC_Event_Release__c.Product_Last_Version__c,
			IEC_Event_Release__c.Swapped_Product__c,
			IEC_Event_Release__c.Product_Number__c,
			IEC_Event_Release__c.Released__c,
			IEC_Event_Release__c.Customer_Type__c,
			IEC_Event_Release__c.Processing_Status__c,
			IEC_Event_Release__c.Sales_Amout__c,
			IEC_Event_Release__c.Sales_Quantity__c,
			IEC_Event_Release__c.Processing_Message__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return IEC_Event_Release__c.sObjectType;
	}

	public map<Id,IEC_Event_Release__c> getEventReleaseById(set<Id> releaseIds){
		String query = String.format(
			'SELECT {0}  ' +
			'FROM {1} ' +
			'WHERE Id IN :releaseIds ' ,
			new List<String>{
				String.join(getDefaultFields(), ', '),
				getSObjectType().getDescribe().getName()
			}
		);

		return new map<Id,IEC_Event_Release__c>((List<IEC_Event_Release__c>)Database.query(query));
	}
}