src/objects/Individual.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Individual email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <description>Timestamp to store when access token of GDPR portal was last generated. It controls the 1h session validity</description>
        <label>Timestamp</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Token used during access control of the GDPR portal</description>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GDPR_Logout_CTRL_Test.cls
@isTest
public with sharing class GDPR_Logout_CTRL_Test {
	
	@isTest
	static void killTokenTest() {
		String token = 'test';

		Boolean k = GDPR_Logout_CTRL.killToken('fakeId');

        Individual indiv = new Individual(FirstName = 'fred', LastName = 'dev', Email__c = 'fred.dev@test.com', Token__c = token, Timestamp__c = String.valueOf(System.now().getTime()));
        INSERT indiv;

		Boolean killT = GDPR_Logout_CTRL.killToken(indiv.Id);
	}
}