src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <fields>
        <fullName>Auto_grant_Account_Role__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if the Account Role is automatically granted when the first user is granted access to this service and also removed when the last user is denied access to the service.</description>
        <label>Auto grant Account Role?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <label>Functional Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Functional_Roles</valueSetName>
        </valueSet>
    </fields>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Functional_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>E&amp;F</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>One Source</fullName>
    </customValue>
    <customValue>
        <fullName>One Source</fullName>
    </customValue>
    <description>Functional Roles</description>
    <masterLabel>Functional Roles</masterLabel>
</GlobalValueSet>

src/classes/PortalApplicationSelector.cls
public class PortalApplicationSelector {
	public static List<Portal_Applications__c> selectIdByName(Set<String> nameSet){
		return [SELECT Id FROM Portal_Applications__c WHERE Name IN :nameSet];
	}

	public static List<Portal_Applications__c> selectAutoGrantAccountRoleByFunctionalRole(Set<String> functionalRoleNameSet){
		return [SELECT Id, Auto_grant_Account_Role__c FROM Portal_Applications__c WHERE Functional_Role__c IN :functionalRoleNameSet];
	}
}