src/objects/Portal_Application_Right__c.object
<CustomObject>
    <description>Link object between contact and Portal Application</description>
    <label>Portal Service Access</label>
    <nameField>
        <displayFormat>APPR-{00000}</displayFormat>
        <label>Portal Application Right Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Service Access</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Case_creation_record_type__c</fullName>
        <label>Case creation record type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Application__c</fullName>
        <label>Portal Application</label>
        <referenceTo>Portal_Applications__c</referenceTo>
        <relationshipLabel>Portal Application Rights</relationshipLabel>
        <relationshipName>Portal_Application_Rights</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Restricted_App__c</fullName>
        <formula>Portal_Application__r.Restricted_App__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Restricted App</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <label>Right</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Access Requested</fullName>
                    <default>true</default>
                    <label>Access Requested</label>
                </value>
                <value>
                    <fullName>Access Granted</fullName>
                </value>
                <value>
                    <fullName>Access Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pending Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Portal_Applications__c.object
<CustomObject>
    <description>Will contain the list of applications accessible trough the portal</description>
    <fields>
        <fullName>Agency__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick if this is the application for the Agent type of customer.</inlineHelpText>
        <label>Agency</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Aplication_Start_Icon__c</fullName>
        <formula>HYPERLINK( Application_URL__c ,  IMAGE( &quot;https://confluence.sakaiproject.org/download/attachments/32735262/start-button.png?api=v2&quot; ,  Name,32,32), &quot;_self&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aplication Start Icon</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_URL__c</fullName>
        <label>Application URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Application_icon_URL__c</fullName>
        <defaultValue>&quot;http://greencyprus.net/wp-content/uploads/image/question%20mark.jpg&quot;</defaultValue>
        <description>URL to the Application icon</description>
        <label>Application icon URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Application_icon__c</fullName>
        <formula>IMAGE( Application_icon_URL__c ,  Name, 64, 64 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application icon</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_creation_record_type__c</fullName>
        <label>Case creation record type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirm_Box__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirm Box</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Confirm_Text__c</fullName>
        <label>Confirm Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>GSSA__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Make portal service available to all GSSA customers (Partner users belonging to Account of record type &apos;General Sales Agent Headquarters / Branch WITH 3-letter IATA code)</inlineHelpText>
        <label>GSSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_on_Homepage__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If check the application will not be visible on the user homepage</inlineHelpText>
        <label>Hide on Homepage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ICH_Airline__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick if this is the application for the ICH Airline type of customer.</inlineHelpText>
        <label>ICH Airline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Window__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Window</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Not_ICH_Airline__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick if this is the application for the Airline non-ICH type of customer.</inlineHelpText>
        <label>Not ICH Airline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_type_for_App_Rigth__c</fullName>
        <defaultValue>&quot;012w0000000QC2Z&quot;</defaultValue>
        <inlineHelpText>The id of the Record type to open when creating a new service access request</inlineHelpText>
        <label>Record type for App Rigth</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requestable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate if  application That can be requested</description>
        <label>Requestable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Restricted_App__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Restricted App</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Description__c</fullName>
        <formula>IF( NOT(ISNULL(Service_Description_List_A__c))  , Service_Description_List_A__c,
				IF(NOT(ISNULL(Service_Description_List_B__c)), Service_Description_List_B__c, 
							&quot;&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TD_Access_Level__c</fullName>
        <label>TD Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TD_Included_Dashboards__c</fullName>
        <label>TD Included Dashboards</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ISSP_TD_1</fullName>
                </value>
                <value>
                    <fullName>ISSP_TD_2</fullName>
                </value>
                <value>
                    <fullName>ISSP_TD_3</fullName>
                </value>
                <value>
                    <fullName>ISSP_TD_4</fullName>
                </value>
                <value>
                    <fullName>ISSP_TD_5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TD_Included_Reports__c</fullName>
        <label>TD Included Reports</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Past Settlements</fullName>
                </value>
                <value>
                    <fullName>Settlement Calendars</fullName>
                </value>
                <value>
                    <fullName>Forecast Data</fullName>
                </value>
                <value>
                    <fullName>Historical Data</fullName>
                </value>
                <value>
                    <fullName>Incoming Funds</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Non TD Reports</fullName>
                </value>
                <value>
                    <fullName>ICCS Settlement</fullName>
                </value>
                <value>
                    <fullName>TIP Reports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <formula>IF(AND(Name = &quot;ID Card Online Platform&quot;, $User.ANG_Sector__c = &quot;Airline&quot;),
			false,
IF(OR(
    Name = &quot;IFG Production&quot;, Name = &quot;IFG Sandbox&quot;),
    $User.IFG_Account_Member__c,
				IF(
								AND(Name = &quot;ID Card Online Platform&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;AS&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;GU&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;MP&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;PW&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;UP&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;US&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;PR&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;VI&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;MH&quot;,
                    $User.ANG_Customer_Country_ISO__c &lt;&gt; &quot;FM&quot;),
                true,
                IF( AND(Name = &quot;IATAN Online Services&quot;,
                    OR($User.ANG_Customer_Country_ISO__c = &quot;AS&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;GU&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;MP&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;PW&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;UP&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;US&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;PR&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;VI&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;MH&quot;,
                    $User.ANG_Customer_Country_ISO__c = &quot;FM&quot;)),
                true,
    OR(
        AND(Agency__c = true,
            $User.Customer_type__c=&quot;Agency&quot;,
            NOT(Name = &quot;Access BOP&quot;),
            NOT(Name = &quot;Payment Link&quot;),
	    NOT(Name = &quot;ID Card Online Platform&quot;),
            NOT(Name = &quot;IATAN Online Services&quot;)),
        AND(VisibleCNS__c= true, 
            $User.Customer_type__c=&quot;CNS Agency&quot;), 
        AND(Not_ICH_Airline__c = true,
            Name != &quot;Payment Link&quot;, 
            CONTAINS($User.Customer_type__c,&quot;Airline&quot;), 
            NOT(CONTAINS($User.Customer_type__c,&quot;ICH&quot;))), 
        AND(ICH_Airline__c = true, 
            Name != &quot;Payment Link&quot;, 
            CONTAINS($User.Customer_type__c,&quot;Airline&quot;), 
            CONTAINS($User.Customer_type__c,&quot;ICH&quot;)), 
        AND(GSSA__c = true, 
            CONTAINS($User.Customer_type__c,&quot;GSSA&quot;)), 
        AND(Name = &quot;Resource Center&quot;, 
            CONTAINS($UserRole.Name ,&quot;General Public&quot;)), 
        AND(Others__c = true, 
            CONTAINS($User.Contact_Account_Record_Type__c  ,&quot;Others&quot;)), 
        AND(Name = &quot;Payment Link&quot;,
            NOT($User.Customer_type__c=&quot;CNS Agency&quot;),
            NOT($User.ANG_Category__c=&quot;IATAN Passenger Sales Agent (USA Only)&quot;),
            NOT($User.ANG_Category__c=&quot;Travel Service Intermediaries-TSI (USA Only)&quot;)),
            AND(Name = &quot;Webstar&quot;,
            OR($User.ANG_Category__c=&quot;IATAN Passenger Sales Agent (USA Only)&quot;,
            $User.ANG_Category__c=&quot;Travel Service Intermediaries-TSI (USA Only)&quot;)),
        AND(Name = &quot;Paypal&quot;,
            $User.CNS_Account_or_Agency__c),
        AND(Name = &quot;Resource Center&quot;, 
            NOT($User.Customer_type__c=&quot;CNS Agency&quot;),
            NOT(CONTAINS($User.Customer_type__c,&quot;Airline&quot;))),
        AND(Name = &quot;Transparency in Payments (TIP)&quot;,
            ($User.Is_TIP_User__c)),
        AND(Name = &quot;Access BOP&quot;,
            $User.ANG_Customer_Country_ISO__c = &quot;CN&quot;),
            AND(Name = &quot;IATA Accreditation &amp; Changes&quot;,
            NOT($User.CNS_Account_or_Agency__c),
            NOT($User.ANG_Sector__c=&quot;Cargo Agent&quot;))
))
))
)</formula>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Portal Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TreasuryDashboardCtrl.cls
public without sharing class TreasuryDashboardCtrl {

	public static String POWERBI_ACCESS_TOKEN = 'PowerBIaccessToken';
	public static String POWERBI_EXPIERS_ON = 'PowerBIexpiersOn';
	public static String POWERBI_REFRESH_TOKEN = 'PowerBIrefreshToken';

	public class UserInformation {
		@AuraEnabled
		public User user {get; set;}
		@AuraEnabled
		public Boolean hasTwoFactor {get; set;}
		@AuraEnabled
		public Boolean isStandardUser {get; set;}
		@AuraEnabled
		public Boolean isPremiumUser {get; set;}
		@AuraEnabled
		public Portal_Applications__c tdPremium {get; set;}
	}


	@AuraEnabled
	public static PowerBI_Config__c getPowerBICredentials(String configurationName) {
		return PowerBiCtrl.getPowerBICredentials(configurationName);
	}


	@AuraEnabled
	public static PowerBiCtrl.ReportDetails getReportConfigDetails(String reportName) {
		return PowerBiCtrl.getReportConfigDetails(reportName);
	}


	@AuraEnabled
	public static UserInformation getUserInformation() {

		UserInformation userInfoToReturn = new UserInformation();
		userInfoToReturn.user = null;
		userInfoToReturn.hasTwoFactor = false;
		userInfoToReturn.isStandardUser = false;
		userInfoToReturn.isPremiumUser = false;
		userInfoToReturn.tdPremium = null;

		List<User> users = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];


		List <Portal_Applications__c> tdServicePremiumList = [SELECT Id, Name, Agency__c, Aplication_Start_Icon__c, Application_icon__c,
				Application_icon_URL__c, Application_URL__c, Case_creation_record_type__c, Confirm_Box__c,
				Confirm_Text__c, Description__c, GSSA__c, Hide_on_Homepage__c,
				ICH_Airline__c, New_Window__c, Not_ICH_Airline__c, Record_type_for_App_Rigth__c,
				Requestable__c, Restricted_App__c, Visible__c, Service_Description__c, TD_Access_Level__c
		FROM Portal_Applications__c
		WHERE Name = 'Treasury Dashboard - Premium'];

		if(! tdServicePremiumList.isEmpty()) {
			userInfoToReturn.tdPremium =  tdServicePremiumList[0];
		}

		if(! users.isEmpty()) {
			//get user
			userInfoToReturn.user = users[0];

			//get two factor
			List<TwoFactorInfo> twoFactors = [SELECT UserId, Type FROM TwoFactorInfo where userID = :users[0].Id];
			if (twoFactors.isEmpty()) {

				//user does not have two factor

			} else {

				userInfoToReturn.hasTwoFactor = true;

			}

			/* Check for Bypass_TD_2FA permission set
			This permission set is used for automation testing user to bypass the 2FA check on Treasury Dashboard page.
			 */
			List<String> resultList = hasBypass2FA(new List<String>{users[0].Id});
			if(! resultList.isEmpty()) {
				if('true'.equals(resultList[0])) {
					userInfoToReturn.hasTwoFactor = true;
				}
			}

			//get is standard user
			List <Portal_Application_Right__c> accessList = [
					SELECT Id, Portal_Application__r.TD_Access_Level__c,
							Portal_Application__r.TD_Included_Dashboards__c,
							Portal_Application__r.TD_Included_Reports__c
					FROM Portal_Application_Right__c
					WHERE Contact__c = :users[0] .ContactId
					AND Portal_Application__r.Name LIKE 'Treasury Dashboard%'
					AND Right__c = 'Access Granted'
			];
			//TreasuryDashboard access not granted
			if (accessList.isEmpty()) {

				//no Standard Dashboard access

			} else {//access granted

				userInfoToReturn.isStandardUser = true;

				if (accessList[0].Portal_Application__r.TD_Included_Dashboards__c != null) {
					List<String> dashboardAccess = accessList[0].Portal_Application__r.TD_Included_Dashboards__c.split(';');
					for (String thisDashboard : dashboardAccess) {

						if (thisDashboard == 'ISSP_TD_5') {
							userInfoToReturn.isStandardUser = false;
							userInfoToReturn.isPremiumUser = true;
							break;

						}
					}

				}


			}

		}

		return userInfoToReturn;

	}


	@AuraEnabled
	public static String premiumAccessRequest(String applicationId, String contactId) {
		return requestTreasuryDashboardPremium(applicationId, contactId);
	}


	@RemoteAction
	public static String requestTreasuryDashboardPremium (String applicationId, String contactId){
		insert new Portal_Application_Right__c(Contact__c = contactId,Portal_Application__c = applicationId,Right__c = 'Access Requested');
		return 'ok';
	}

	@AuraEnabled
	public static String getCaseRecordTypeId() {
		String caseRecordTypeId = '';

		ISSP_Record_Type_Mgmt__c rtMgmt =  ISSP_Record_Type_Mgmt__c.getValues('Treasury Dashboard');
		if (rtMgmt != null){
			if (rtMgmt.Record_Type_Name__c != null){
				caseRecordTypeId = RecordTypeSingleton.getInstance().getRecordTypeId('Case', rtMgmt.Record_Type_Name__c);
			}
		}

		return caseRecordTypeId;
	}


	@AuraEnabled
	public static PowerBiCtrl.OAuthResult getAccessToken(PowerBI_Config__c conf) {
		Integer refreshSecondsToExpire = 360;
		return PowerBiCtrl.retrieveAccessToken(conf, POWERBI_ACCESS_TOKEN, POWERBI_EXPIERS_ON, POWERBI_REFRESH_TOKEN, refreshSecondsToExpire);
	}

	@AuraEnabled
	public static PowerBiCtrl.DatasetDetailResult getDataset(String accessToken, String datasetId, PowerBI_Config__c conf) {
		return PowerBiCtrl.getDataset(accessToken, datasetId, conf);
	}

	@AuraEnabled
	public static PowerBiCtrl.ReportDetailResult getReportsDetails(String accessToken, String reportId, PowerBI_Config__c conf) {
		return PowerBiCtrl.getReportsDetails(accessToken, reportId, conf);
	}


	@AuraEnabled
	public static PowerBiCtrl.EmbedTokenResult getEmbedToken(String accessToken, String userId, String groupId, String reportId, String datasetId, PowerBI_Config__c conf) {
		Integer refreshMinutesToExpire = 10;
		return PowerBiCtrl.retrieveEmbedToken(accessToken, userId, groupId, reportId, datasetId, conf, refreshMinutesToExpire);
	}


	/*
	This method is used in Accept Terms and 2FA 2 login flow and Treasury Dashboard page for bypassing 2FA for users
	that have Bypass_TD_2FA permission set assigned.
	 */
	@InvocableMethod
	public static List<String> hasBypass2FA(List<String> userId) {
		List<String> resultList = new List<String>();
		List<PermissionSetAssignment> permissionsList = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId = :userId[0] AND PermissionSet.Name = 'Bypass_TD_2FA'];
		if(! permissionsList.isEmpty()) {
			resultList.add('true');
		}else{
			resultList.add('false');
		}

		return resultList;
	}




}