src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Display_to_Direct_Sales__c</fullName>
        <formula>AND(OR(AND(OR(SAP_Status_Code__c = &quot;A&quot;, SAP_Status_Code__c = &quot;Z4&quot;)
, OR(OR(Is_Electronic_Product__c = true, TEXT(Inventory_Status__c) = &quot;In stock&quot;, Is_Electronic_Product__c = true, TEXT(Inventory_Status__c) = &quot;Available Now&quot;), 
AND(
OR(TEXT(Inventory_Status__c) = &quot;Out of stock&quot;, TEXT(Inventory_Status__c) = &quot;Coming Soon&quot;), 
NOT(ISBLANK(Expected_Availability_Date__c))))
, Post_to_Ecommerce_Date__c &lt;= TODAY()
, Direct_Sales__c = true)
, AND(OR(SAP_Status_Code__c = &apos;I&apos;, SAP_Status_Code__c = &apos;Z3&apos;, Effective_To__c &lt; TODAY())
, Is_Electronic_Product__c = false
, TEXT(Inventory_Status__c) = &quot;In stock&quot;
, NOT(ISBLANK(Post_to_Ecommerce_Date__c))))
, NOT(ISBLANK(SAP_Material_Number__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display to Direct Sales</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_to_ECommerce__c</fullName>
        <formula>AND(
OR(SAP_Status_Code__c = &quot;A&quot;, SAP_Status_Code__c = &quot;Z4&quot;), 
OR(
Is_Electronic_Product__c = true, 
OR(TEXT(Inventory_Status__c) = &quot;In stock&quot;, TEXT(Inventory_Status__c) = &quot;Available Now&quot;), 
AND(
OR(TEXT(Inventory_Status__c) = &quot;Coming Soon&quot;, TEXT(Inventory_Status__c) = &quot;Out of stock&quot;), 
NOT(ISBLANK(Expected_Availability_Date__c))
)
),
Post_to_Ecommerce_Date__c &lt;= TODAY(),
NOT(ISBLANK(SAP_Material_Number__c)),
IF( (IEC_Parent_Product__c &lt;&gt; null &amp;&amp; IEC_Parent_Product__r.IEC_Product_Information__c &lt;&gt; null || IEC_Product_Information__c &lt;&gt; null), Sell_through_eCommerce__c, true)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display to eCommerce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Edition__c</fullName>
        <label>Edition #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_From__c</fullName>
        <label>Effective From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Availability_Date__c</fullName>
        <description>Value is depending on Availability = Out of stock</description>
        <label>Expected Availability Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IATA_ORG_Group__c</fullName>
        <description>This field is used for IATA.ORG Integration to group products</description>
        <label>IATA.ORG Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>20 Year Passenger Forecast</fullName>
                </value>
                <value>
                    <fullName>A4A-IATA Reservations Interline Procedures (AIRIMP)</fullName>
                </value>
                <value>
                    <fullName>Aircraft Reliability Guidelines</fullName>
                </value>
                <value>
                    <fullName>Airline Coding Directory</fullName>
                </value>
                <value>
                    <fullName>Airline Industry Freight Forecast</fullName>
                </value>
                <value>
                    <fullName>Airline Operational Cost Management Guidelines</fullName>
                </value>
                <value>
                    <fullName>Airlines Magazine Subscription</fullName>
                    <label>Airlines. Magazine Subscription</label>
                </value>
                <value>
                    <fullName>Airline Sustainability Reporting Handbook</fullName>
                </value>
                <value>
                    <fullName>Airport Development Reference Manual</fullName>
                </value>
                <value>
                    <fullName>Airport Handling Manual</fullName>
                </value>
                <value>
                    <fullName>Aviation Charges Intelligence Center (ACIC)</fullName>
                </value>
                <value>
                    <fullName>Aviation Cyber Security Toolkit</fullName>
                </value>
                <value>
                    <fullName>Baggage ID</fullName>
                </value>
                <value>
                    <fullName>Baggage Reference Manual</fullName>
                </value>
                <value>
                    <fullName>Cabin Safety Guide</fullName>
                </value>
                <value>
                    <fullName>Cargo Agency Conference Resolution Manual</fullName>
                </value>
                <value>
                    <fullName>Cargo Claims and Loss Prevention Handbook</fullName>
                </value>
                <value>
                    <fullName>Cargo Country Statistics</fullName>
                </value>
                <value>
                    <fullName>Cargo Interchange Message Procedures (Cargo-IMP)</fullName>
                </value>
                <value>
                    <fullName>Cargo Services Conference Resolution</fullName>
                </value>
                <value>
                    <fullName>Cargo Tariff Coordinating Conference Resolutions Manuals</fullName>
                </value>
                <value>
                    <fullName>Cargo-XML Toolkit</fullName>
                </value>
                <value>
                    <fullName>City Code Directory</fullName>
                </value>
                <value>
                    <fullName>Dangerous Goods Regulations ES</fullName>
                </value>
                <value>
                    <fullName>DGR Compliance Kits - Combos</fullName>
                </value>
                <value>
                    <fullName>DGR Data eList Products</fullName>
                </value>
                <value>
                    <fullName>DGR Handling Labels</fullName>
                </value>
                <value>
                    <fullName>DGR Hazard Labels</fullName>
                </value>
                <value>
                    <fullName>DGR Limited- Excepted Labels</fullName>
                </value>
                <value>
                    <fullName>DGR Posters</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IEC_OrderBy__c</fullName>
        <label>IATA.ORG Order By</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IEC_Sample_Link__c</fullName>
        <description>Field used for IATA.ord integration</description>
        <label>IATA.ORG Sample Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>As detailed in the IATA business plan model</description>
        <label>Line Of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>BIS</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>FSS</fullName>
                </value>
                <value>
                    <fullName>GDP</fullName>
                </value>
                <value>
                    <fullName>Publications</fullName>
                </value>
                <value>
                    <fullName>Strategic Partnerships</fullName>
                </value>
                <value>
                    <fullName>T &amp; T</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Media__c</fullName>
        <label>Media</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Book and CD-ROM</fullName>
                </value>
                <value>
                    <fullName>Book and WEB Download</fullName>
                </value>
                <value>
                    <fullName>CD-ROM LAN</fullName>
                </value>
                <value>
                    <fullName>Chart</fullName>
                </value>
                <value>
                    <fullName>Data File</fullName>
                </value>
                <value>
                    <fullName>Email Service</fullName>
                </value>
                <value>
                    <fullName>Excel Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Forms</fullName>
                </value>
                <value>
                    <fullName>Memory Stick</fullName>
                </value>
                <value>
                    <fullName>Software Application</fullName>
                </value>
                <value>
                    <fullName>WEB Application</fullName>
                </value>
                <value>
                    <fullName>WEB Download</fullName>
                </value>
                <value>
                    <fullName>WEB Seminar</fullName>
                </value>
                <value>
                    <fullName>GR Airline pseudo code</fullName>
                </value>
                <value>
                    <fullName>Binder</fullName>
                </value>
                <value>
                    <fullName>Book</fullName>
                </value>
                <value>
                    <fullName>Brochure</fullName>
                </value>
                <value>
                    <fullName>Calendar</fullName>
                </value>
                <value>
                    <fullName>Card</fullName>
                </value>
                <value>
                    <fullName>CD-ROM</fullName>
                </value>
                <value>
                    <fullName>Disk</fullName>
                </value>
                <value>
                    <fullName>DVD</fullName>
                </value>
                <value>
                    <fullName>Folder</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Labels</fullName>
                </value>
                <value>
                    <fullName>Magazine</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>PDF</fullName>
                </value>
                <value>
                    <fullName>Poster</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Refinement_Language__c</fullName>
        <description>Ecommerce site Refinement Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Multilingual</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Material_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Product Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>IATA.org Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Short_Title__c</fullName>
        <label>Short Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SFDC_ProductCatalog.cls
/****************************************************************************************************
    Created by David D 2016/02
        SOAP web service to be called by iata.org to get product catalog
****************************************************************************************************/
@RestResource(urlMapping = '/ProductCatalog/*')
global class SFDC_ProductCatalog {
	global class Error {
		String Code;
		String Message;
		global Error(String c, String m) {
			Code = c;
			Message = m;
		}
	}

	global class ProductCatalog {
		List<Error> Errors;
		List<ProductGroup> ProductGroup;
		Integer NB_Products; //Number of products founded
		Integer NB_Pages; // Number of available pages if some limit is specified
		Integer PageNumber; //Specified Page Number
		Integer PageSize; // Specified limit
	}

	global class ProductGroup {
		String PageTitle;
		String PageURL;

		List<ProductInfo> ProductInfo;
	}

	global class ProductInfo {
		String 	ProductTitle;
		String 	ProductName;
		String 	ProductNumber;
		String 	ProductEdition;
		String 	ProductDescription;
		String 	ProductNotes;
		Decimal ProductPrice;
		String 	ProductLink;
		String 	ProductLanguage;
		String 	ProductCategory;
		String 	ProductMedia;
		Date 	ProductAvailabilityDate;
		String 	ProductSampleLink;
		Integer ProductOrder;
		String 	PageAreaOfActivityLevel;
		String 	PageContentTypes;
		Boolean UseOnIATA;
	}

	@HttpGet
	global static ProductCatalog getProducts() {
		Map<String, String> params = RestContext.request.params;

		ProductCatalog response = new ProductCatalog();
		response.Errors = new List<Error>();


		Product_Sel pSelector = new Product_Sel();
		String searchCondition = 'SAP_Material_Number__c != null AND (Display_to_ECommerce__c = true OR Display_to_Direct_Sales__c = true) '; // Basic filter

		//-- If Date filter is specified
		if (params.containsKey('date')) {
			String strDate = params.get('date');
			if (isValidDate(strDate)) {
				Date dt = Date.valueOf(strDate);
				searchCondition += ' AND LastModifiedDate >= ' + DateTime.newInstance(dt.year(), dt.month(), dt.day(), 23, 59, 59).format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
			} else {
				response.Errors.add(new Error('INVALID_DATE', 'The Date parameter specified is invalid. The valid date format is yyyy-mm-dd'));
			}
		}

		//-- If limit is specified
		if (params.containsKey('limit')) {
			String strLimit = params.get('limit');
			if (isValidInteger(strLimit)) {
				response.PageSize = Integer.valueOf(strLimit);

				//-- If page number is specified
				if (params.containsKey('page')) {
					String strPageNumber = params.get('page');
					if (isValidInteger(strPageNumber)) {
						response.PageNumber =  Integer.valueOf(strPageNumber);
					} else {
						response.Errors.add(new Error('INVALID_INTEGER', 'The Page number parameter specified is invalid. You must specified an integer'));
					}
				} else {
					//-- Page 1 is the default page
					response.PageNumber = 1;
				}
			} else {
				response.Errors.add(new Error('INVALID_INTEGER', 'The Limit parameter specified is invalid. You must specified an integer'));
			}
		}

		//-- Validate there is no error
		if (response.Errors.size() == 0) {
			//-- No Error
			response.Errors = null;

			//-- Perform query
			List<ProductGroup> groups = new List<ProductGroup>();

			Integer queryLimit = response.PageSize;
			Integer queryOffset = (response.PageNumber >= 1) ? (response.PageNumber - 1) * response.PageSize : 0;

			//-- Available products
			List<Product2> products = pSelector.getProducts(searchCondition, 'Name', queryLimit, queryOffset);

			//-- Products Price
			Set<String> productNumbers = new Set<String>();
			for (Product2 p : products)
				productNumbers.add(p.SAP_Material_Number__c);

			Map<String, PriceInfo_DTO> productPrices =  pSelector.getProductPriceInfo(productNumbers, null, null, null, true);

			//-- Group Products
			Map<String, List<Product2>> productsByGroup = new Map<String, List<Product2>>();
			for (Product2 p : products) {
				String g = (p.IATA_ORG_Group__c != null) ? p.IATA_ORG_Group__c : '-';
				List<Product2> tmp = (productsByGroup.containsKey(g))
				                     ?	productsByGroup.get(g)
				                     : 	new List<Product2>();
				tmp.add(p);
				productsByGroup.put(g, tmp);
			}

			//-- Build Response
			for (String groupName : productsByGroup.keySet()) {
				List<Product2> prods = productsByGroup.get(groupName);

				ProductGroup pg = new ProductGroup();
				pg.PageTitle = groupName;
				pg.PageURL = '/' + groupName.toLowerCase().replace(' ', '-') + '.aspx';

				pg.ProductInfo = new List<ProductInfo>();
				for (Product2 p : productsByGroup.get(groupName)) {
					pg.ProductInfo.add(formatToProductInfo(p, productPrices.get(p.SAP_Material_Number__c)));
				}

				groups.add(pg);
			}

			response.ProductGroup = groups;

			List<Product2> availableProducts = pSelector.getProducts(searchCondition, 'Name', null, null);

			response.NB_Products = availableProducts.size();

			if (response.PageSize != null) {
				response.NB_Pages = Integer.valueOf(Math.round(response.NB_Products / response.PageSize));
			}

		}

		return response;
	}

	private static ProductInfo formatToProductInfo(Product2 p, PriceInfo_DTO price) {
		ProductInfo ws = new ProductInfo();
		ws.ProductTitle 			= p.Short_Title__c;
		ws.ProductName 				= p.Name;
		ws.ProductNumber 			= p.SAP_Material_Number__c;
		ws.ProductEdition 			= p.Edition__c;
		ws.ProductDescription 		= p.Short_Description__c;
		ws.ProductNotes 			= p.Notes__c;
		ws.ProductLink 				= '/IEC_ProductDetails?id=' + p.SAP_Material_Number__c;
		ws.ProductLanguage 			= p.Refinement_Language__c;
		ws.ProductCategory 			= p.Line_of_Business__c;
		ws.ProductMedia 			= p.Media__c;
		//ws.ProductAvailabilityDate 	= p.Effective_From__c;
		ws.ProductAvailabilityDate 	= p.Expected_Availability_Date__c;
		ws.ProductSampleLink 		= p.IEC_Sample_Link__c;
		ws.ProductOrder 			= Integer.valueOf(p.IEC_OrderBy__c);
		ws.PageAreaOfActivityLevel	= p.IEC_Page_Areas_of_Activity__c;
		ws.PageContentTypes 		= p.IEC_Page_Content_Types__c;
		ws.UseOnIATA 				= p.IEC_Use_on_IATA_org__c;

		if (price != null) {
			ws.ProductPrice = Order_Svc.getRegularPrice(price, 1);
		}

		return ws;
	}

	private static Boolean isValidDate(String sDate) {
		try {
			Date dt = Date.valueOf(sDate);
			return true;
		} catch (Exception e) {
			return false;
		}
	}

	private static Boolean isValidInteger(String sInteger) {
		try {
			Integer i = Integer.valueOf(sInteger);
			return true;
		} catch (Exception e) {
			return false;
		}
	}

}