src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Display_Ecom_Topic__c</fullName>
        <label>Ecommerce Site Topic</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Mega_Menu__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Airline Distribution</fullName>
                </value>
                <value>
                    <fullName>Airport Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Cargo</fullName>
                </value>
                <value>
                    <fullName>Dangerous-Goods</fullName>
                </value>
                <value>
                    <fullName>Economics-and-Traffic-Results</fullName>
                </value>
                <value>
                    <fullName>Finance-and-Accounting</fullName>
                </value>
                <value>
                    <fullName>Ground Operations</fullName>
                </value>
                <value>
                    <fullName>Legal-and-Regulatory</fullName>
                </value>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Passenger</fullName>
                </value>
                <value>
                    <fullName>Safety</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Coding</fullName>
                </value>
                <value>
                    <fullName>Directories</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environment</fullName>
                </value>
                <value>
                    <fullName>Exchange-Rates</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Forecasts-and-Statistic</fullName>
                </value>
                <value>
                    <fullName>Law-and-Regulations</fullName>
                </value>
                <value>
                    <fullName>Regulations</fullName>
                </value>
                <value>
                    <fullName>Safety-and-Operations</fullName>
                </value>
                <value>
                    <fullName>Scheduling</fullName>
                </value>
                <value>
                    <fullName>Standards-and-Recommended-Practices</fullName>
                </value>
                <value>
                    <fullName>Tax-Data</fullName>
                </value>
                <value>
                    <fullName>Travel-Agency-Data</fullName>
                </value>
                <value>
                    <fullName>User-Charges</fullName>
                </value>
                <value>
                    <fullName>Baggage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IATA_ORG_Group__c</fullName>
        <description>This field is used for IATA.ORG Integration to group products</description>
        <label>IATA.ORG Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>20 Year Passenger Forecast</fullName>
                </value>
                <value>
                    <fullName>A4A-IATA Reservations Interline Procedures (AIRIMP)</fullName>
                </value>
                <value>
                    <fullName>Aircraft Reliability Guidelines</fullName>
                </value>
                <value>
                    <fullName>Airline Coding Directory</fullName>
                </value>
                <value>
                    <fullName>Airline Industry Freight Forecast</fullName>
                </value>
                <value>
                    <fullName>Airline Operational Cost Management Guidelines</fullName>
                </value>
                <value>
                    <fullName>Airlines Magazine Subscription</fullName>
                    <label>Airlines. Magazine Subscription</label>
                </value>
                <value>
                    <fullName>Airline Sustainability Reporting Handbook</fullName>
                </value>
                <value>
                    <fullName>Airport Development Reference Manual</fullName>
                </value>
                <value>
                    <fullName>Airport Handling Manual</fullName>
                </value>
                <value>
                    <fullName>Aviation Charges Intelligence Center (ACIC)</fullName>
                </value>
                <value>
                    <fullName>Aviation Cyber Security Toolkit</fullName>
                </value>
                <value>
                    <fullName>Baggage ID</fullName>
                </value>
                <value>
                    <fullName>Baggage Reference Manual</fullName>
                </value>
                <value>
                    <fullName>Cabin Safety Guide</fullName>
                </value>
                <value>
                    <fullName>Cargo Agency Conference Resolution Manual</fullName>
                </value>
                <value>
                    <fullName>Cargo Claims and Loss Prevention Handbook</fullName>
                </value>
                <value>
                    <fullName>Cargo Country Statistics</fullName>
                </value>
                <value>
                    <fullName>Cargo Interchange Message Procedures (Cargo-IMP)</fullName>
                </value>
                <value>
                    <fullName>Cargo Services Conference Resolution</fullName>
                </value>
                <value>
                    <fullName>Cargo Tariff Coordinating Conference Resolutions Manuals</fullName>
                </value>
                <value>
                    <fullName>Cargo-XML Toolkit</fullName>
                </value>
                <value>
                    <fullName>City Code Directory</fullName>
                </value>
                <value>
                    <fullName>Dangerous Goods Regulations ES</fullName>
                </value>
                <value>
                    <fullName>DGR Compliance Kits - Combos</fullName>
                </value>
                <value>
                    <fullName>DGR Data eList Products</fullName>
                </value>
                <value>
                    <fullName>DGR Handling Labels</fullName>
                </value>
                <value>
                    <fullName>DGR Hazard Labels</fullName>
                </value>
                <value>
                    <fullName>DGR Limited- Excepted Labels</fullName>
                </value>
                <value>
                    <fullName>DGR Posters</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Keywords__c</fullName>
        <label>Keywords</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SFDC_ProductCatalog_Test.cls
@isTest
private class SFDC_ProductCatalog_Test 
{
	
	@isTest /*(SeeAllData=true)*/
	static void test_GET() 
	{
		//-- Generate Products with Prices 
		List<Product2> products = TestDataGenerator.generateProductsWithPrice(10);

		//-- Update Product Properties 
		Integer x =0;
		for(Product2 prod : products)
		{
			prod.Display_Ecom_Topic__c = (Math.mod(x, 2) == 0) ? 'Finance' : 'Economics';
			prod.Keywords__c = '***-xxxx '+x;
			prod.IATA_ORG_Group__c = (Math.mod(x, 2) == 0) ? 'The Financial Times' : 'The Economics';

			x++;
		}

		update products;

		//-- Call the service 
		Date dt = Date.today().addDays(-1);
		RestRequest req = new RestRequest();
			req.httpMethod = 'GET';
			req.requestURI = URL.getSalesforceBaseUrl() . toExternalForm() + '/services/apexrest/ProductCatalog';
			req.addParameter('date', dt.year() + '-' + dt.month() + '-' + dt.day());
			req.addParameter('limit', '2'); // 2 per page
			req.addParameter('page', '1'); // query 1st page

		RestContext.request = req;

		RestResponse res = new RestResponse();	

		RestContext.response = res;

		SFDC_ProductCatalog.ProductCatalog catalog = SFDC_ProductCatalog.getProducts();
	}	
}